'use strict';
var intelligence = require('../../shared/services/intelligence');
var metrics = require('../../shared/services/intelligence/metrics');
var workflow = require('../../shared/services/intelligence/workflow');
var health = require('../../shared/services/intelligence/health');
function boot(ctx){ctx.log.info('intelligence_center booting',{module:'intelligence_center'});} function teardown(ctx){ctx.log.info('intelligence_center tearing down',{module:'intelligence_center'});}
async function listProviders(){return {success:true,providers:intelligence.listProviders()};}
async function runProvider(req){var b=req.body||{}; try{return {success:true,run:await intelligence.runProvider(req.params.id,{from:b.from,to:b.to,comparisonStart:b.comparisonStart,comparisonEnd:b.comparisonEnd,scope:b.scope||{type:'organisation',id:'current'}})};}catch(error){return {success:false,statusCode:400,error:{code:'PROVIDER_RUN_FAILED',message:error.message}};}}
async function listProducts(req){if(req.query.all_scopes==='true')return{success:true,products:intelligence.listAllVisibleProducts(req.user.role)};var type=req.query.scope_type||'organisation';var id=req.query.scope_id||'current';return {success:true,products:intelligence.listVisibleProducts(type,id,req.user.role)};}
async function portfolio(req){var type=req.query.scope_type||'organisation';var id=req.query.scope_id||'current';return {success:true,portfolio:intelligence.getPortfolio(type,id,req.user.role)};}
async function engineHealth(){return {success:true,health:health.evaluate()};}
function canView(product,role){return product&&(!product.audience.length||product.audience.indexOf('all')>=0||product.audience.indexOf(role)>=0);}
async function actOnProduct(req){var action=req.body&&req.body.action;if(!action)return {success:false,statusCode:400,error:{code:'ACTION_REQUIRED',message:'action is required'}};var found=intelligence.getProduct(req.params.id);if(!canView(found,req.user.role))return {success:false,statusCode:404,error:{code:'NOT_FOUND',message:'Insight not found'}};try{intelligence.actOnProduct(req.params.id,action,req.user.id,{rationale:req.body.rationale,metadata:req.body.metadata});return {success:true,product:intelligence.getProduct(req.params.id)};}catch(error){return {success:false,statusCode:400,error:{code:'INVALID_INSIGHT_ACTION',message:error.message}};}}
async function metricSeries(req){return {success:true,points:metrics.series(req.params.id,{type:req.query.scope_type||'organisation',id:req.query.scope_id||'current'},Number(req.query.from)||0,Number(req.query.to)||Date.now())};}
async function decide(req){var found=intelligence.getProduct(req.params.id);if(!canView(found,req.user.role))return {success:false,statusCode:404,error:{code:'NOT_FOUND',message:'Insight not found'}};try{var id=workflow.decide(req.params.id,req.body.action,{id:req.user.id,name:req.body.actorName},{rationale:req.body.rationale,metadata:req.body.metadata});return {success:true,decisionId:id,product:intelligence.getProduct(req.params.id)};}catch(error){return {success:false,statusCode:400,error:{code:'INVALID_DECISION',message:error.message}};}}
async function createAction(req){try{var id=workflow.createAction(req.body,req.user.id);return {success:true,action:workflow.listActions({}).filter(function(a){return a.id===id;})[0]};}catch(error){return {success:false,statusCode:400,error:{code:'INVALID_ACTION',message:error.message}};}}
async function listActions(req){return {success:true,actions:workflow.listActions({ownerId:req.query.owner_id,status:req.query.status,insightId:req.query.insight_id})};}
async function updateAction(req){try{workflow.updateAction(req.params.id,req.body,req.user.id);return {success:true,action:workflow.listActions({}).filter(function(a){return a.id===req.params.id;})[0]};}catch(error){return {success:false,statusCode:400,error:{code:'INVALID_ACTION_UPDATE',message:error.message}};}}
async function generateReminders(req){var ids=workflow.generateReminders(req.body.at,req.body.approachingWindowMs);return {success:true,reminders:ids.map(function(id){return intelligence.getProduct(id);})};}
async function recordOutcome(req){try{var id=workflow.recordOutcome(req.body,req.user.id);return {success:true,outcome:workflow.getOutcome(id)};}catch(error){return {success:false,statusCode:400,error:{code:'INVALID_OUTCOME',message:error.message}};}}
async function assessOutcome(req){try{return {success:true,assessment:workflow.assessOutcome(req.params.id,req.body,req.user.id),outcome:workflow.getOutcome(req.params.id)};}catch(error){return {success:false,statusCode:400,error:{code:'INVALID_ASSESSMENT',message:error.message}};}}
module.exports={boot:boot,teardown:teardown,listProviders:listProviders,runProvider:runProvider,listProducts:listProducts,portfolio:portfolio,engineHealth:engineHealth,actOnProduct:actOnProduct,metricSeries:metricSeries,decide:decide,createAction:createAction,listActions:listActions,updateAction:updateAction,generateReminders:generateReminders,recordOutcome:recordOutcome,assessOutcome:assessOutcome};
