'use strict';

const appScope=require('../../shared/services/appScope'),contract=require('../../contracts/teacherPreferences');
function boot(ctx){ctx.log.info('teacher_preferences booting',{module:'teacher_preferences'});}function teardown(){}
function scope(req){return appScope.fromRequest(req);}function text(v){return String(v==null?'':v).trim();}function num(v,f){const n=Number(v);return Number.isFinite(n)?n:f;}
function bad(message,code,statusCode){return{success:false,statusCode:statusCode||400,error:{code:code||'VALIDATION_ERROR',message}};}
function emit(ctx,channel,record){ctx.events.publish(channel,{entityId:record.id,record,source:'teacher_preferences',__module:'teacher_preferences'});}
function cycle(ctx,id,appId){return ctx.db.query('SELECT * FROM teacher_preference_cycles WHERE id=? AND app_id=?',[id,appId]).rows[0];}
function entry(ctx,id,appId){return ctx.db.query('SELECT * FROM teacher_preference_entries WHERE id=? AND app_id=?',[id,appId]).rows[0];}
function staff(ctx,id,appId){return ctx.db.query('SELECT * FROM staff WHERE staff_id=?',[id]).rows[0];}
function hydrate(ctx,row){if(!row)return row;row.reviews=ctx.db.query('SELECT * FROM teacher_preference_reviews WHERE preference_entry_id=? ORDER BY id',[row.id]).rows;row.advisory_weight=contract.advisoryWeight({...row,staff_id:String(row.staff_id)});return row;}
function page(req){return{page:Math.max(1,num(req.query.page,1)),limit:Math.min(50,Math.max(1,num(req.query.limit,50)))};}
function expected(row,body){if(body.expected_revision!=null&&Number(body.expected_revision)!==Number(row.revision))return bad('Preference was changed by another user; reload before continuing','REVISION_CONFLICT',409);return null;}
function generatedKey(body){return text(body.external_key)||['preference',body.staff_id,body.domain,body.stance,body.target_key].map(text).join(':');}
function stable(value){if(Array.isArray(value))return value.map(stable);if(value&&typeof value==='object')return Object.keys(value).sort().reduce((o,k)=>(o[k]=stable(value[k]),o),{});return value;}
function hash(value){return require('crypto').createHash('sha256').update(JSON.stringify(stable(value))).digest('hex');}

async function getContract(){return{success:true,contract:{provider:'teacher_preferences',authority:'advisory_only',human_confirmation_required:true,domains:contract.DOMAINS,stances:contract.STANCES,review_states:contract.REVIEW_STATES,confidence_levels:contract.CONFIDENCE_LEVELS,qualification_is_preference:false}};}
async function listCycles(req,ctx){const appId=scope(req),pg=page(req),where=['app_id=?'],params=[appId];if(req.query.academic_year_id){where.push('academic_year_id=?');params.push(req.query.academic_year_id);}if(req.query.status){where.push('status=?');params.push(req.query.status);}const clause=' WHERE '+where.join(' AND '),total=ctx.db.query('SELECT COUNT(*) total FROM teacher_preference_cycles'+clause,params).rows[0].total,rows=ctx.db.query('SELECT * FROM teacher_preference_cycles'+clause+' ORDER BY academic_year_id DESC,version DESC,id DESC LIMIT ? OFFSET ?',params.concat([pg.limit,(pg.page-1)*pg.limit])).rows;return{success:true,cycles:rows,total:Number(total),...pg};}
async function createCycle(req,ctx){const appId=scope(req),b=req.body||{};try{contract.validateCycle({...b,academic_year_id:String(b.academic_year_id||'')});}catch(e){return bad(e.message);}if(!ctx.db.query('SELECT id FROM academic_years WHERE id=? AND app_id=?',[b.academic_year_id,appId]).rows[0])return bad('Academic year not found','NOT_FOUND',404);try{const x=ctx.db.query('INSERT INTO teacher_preference_cycles(app_id,external_key,academic_year_id,name,opens_at,closes_at,created_by) VALUES(?,?,?,?,?,?,?)',[appId,text(b.external_key),b.academic_year_id,text(b.name),b.opens_at||null,b.closes_at||null,String(req.user.id)]),row=cycle(ctx,x.lastInsertRowid,appId);emit(ctx,'teacher_preference.cycle_created',row);return{success:true,cycle:row};}catch(e){if(String(e.message).includes('UNIQUE'))return bad('Preference cycle already exists','CYCLE_EXISTS',409);throw e;}}
async function setCycleStatus(req,ctx,next){const appId=scope(req),row=cycle(ctx,req.params.id,appId);if(!row)return bad('Preference cycle not found','NOT_FOUND',404);if(next==='open'&&!['draft','closed'].includes(row.status))return bad('Only draft or closed cycles can open','INVALID_STATE',409);if(next==='closed'&&row.status!=='open')return bad('Only open cycles can close','INVALID_STATE',409);ctx.db.transaction(db=>{if(next==='open')db.query("UPDATE teacher_preference_cycles SET status='closed',updated_at=datetime('now') WHERE app_id=? AND academic_year_id=? AND status='open' AND id<>?",[appId,row.academic_year_id,row.id]);db.query("UPDATE teacher_preference_cycles SET status=?,version=version+1,updated_at=datetime('now') WHERE id=?",[next,row.id]);});const saved=cycle(ctx,row.id,appId);emit(ctx,'teacher_preference.cycle_'+(next==='open'?'opened':'closed'),saved);return{success:true,cycle:saved};}
async function openCycle(req,ctx){return setCycleStatus(req,ctx,'open');}async function closeCycle(req,ctx){return setCycleStatus(req,ctx,'closed');}

async function listEntries(req,ctx){const appId=scope(req),pg=page(req),where=['app_id=?'],params=[appId];for(const field of ['cycle_id','staff_id','domain','stance','status','review_state'])if(req.query[field]){where.push(field+'=?');params.push(req.query[field]);}const clause=' WHERE '+where.join(' AND '),total=ctx.db.query('SELECT COUNT(*) total FROM teacher_preference_entries'+clause,params).rows[0].total,rows=ctx.db.query('SELECT * FROM teacher_preference_entries'+clause+' ORDER BY staff_id,domain,CASE WHEN rank IS NULL THEN 999 ELSE rank END,id DESC LIMIT ? OFFSET ?',params.concat([pg.limit,(pg.page-1)*pg.limit])).rows.map(r=>hydrate(ctx,r));return{success:true,preferences:rows,total:Number(total),...pg};}
function normalized(body,base){const b={...(base||{}),...body};return{...b,external_key:generatedKey(b),staff_id:text(b.staff_id),domain:b.domain,stance:b.stance,target_key:text(b.target_key),target_label:text(b.target_label),rank:b.rank==null?null:Number(b.rank),confidence:b.confidence||'medium',valid_from:b.valid_from||null,valid_to:b.valid_to||null,status:b.status||'draft',review_state:b.stance==='declared_restriction'?'pending':'not_required'};}
async function createEntry(req,ctx){const appId=scope(req),b=normalized(req.body||{});const c=cycle(ctx,b.cycle_id,appId);if(!c)return bad('Preference cycle not found','NOT_FOUND',404);if(c.status!=='open')return bad('Preference cycle is not open','CYCLE_NOT_OPEN',409);if(!staff(ctx,b.staff_id,appId))return bad('Staff member not found','NOT_FOUND',404);try{contract.validateEntry(b);}catch(e){return bad(e.message);}try{const x=ctx.db.query('INSERT INTO teacher_preference_entries(app_id,cycle_id,external_key,staff_id,domain,stance,target_key,target_label,rank,confidence,rationale,valid_from,valid_to,review_state,status,submitted_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',[appId,b.cycle_id,b.external_key,b.staff_id,b.domain,b.stance,b.target_key,b.target_label,b.rank,b.confidence,b.rationale||null,b.valid_from,b.valid_to,b.review_state,'draft',String(req.user.id)]),row=hydrate(ctx,entry(ctx,x.lastInsertRowid,appId));emit(ctx,'teacher_preference.created',row);return{success:true,preference:row};}catch(e){if(String(e.message).includes('UNIQUE'))return bad('Preference identity or rank already exists in this cycle','PREFERENCE_EXISTS',409);throw e;}}
async function reviseEntry(req,ctx){const appId=scope(req),old=entry(ctx,req.params.id,appId),body=req.body||{};if(!old)return bad('Preference not found','NOT_FOUND',404);const conflict=expected(old,body);if(conflict)return conflict;const c=cycle(ctx,old.cycle_id,appId);if(!c||c.status!=='open')return bad('Preference cycle is not open','CYCLE_NOT_OPEN',409);const next=normalized(body,old);try{contract.validateEntry(next);}catch(e){return bad(e.message);}if(old.status==='draft'){try{ctx.db.query("UPDATE teacher_preference_entries SET domain=?,stance=?,target_key=?,target_label=?,rank=?,confidence=?,rationale=?,valid_from=?,valid_to=?,review_state=?,revision=revision+1,updated_at=datetime('now') WHERE id=? AND revision=?",[next.domain,next.stance,next.target_key,next.target_label,next.rank,next.confidence,next.rationale||null,next.valid_from,next.valid_to,next.review_state,old.id,old.revision]);}catch(e){if(String(e.message).includes('UNIQUE'))return bad('Preference rank already exists','PREFERENCE_EXISTS',409);throw e;}const saved=hydrate(ctx,entry(ctx,old.id,appId));emit(ctx,'teacher_preference.revised',saved);return{success:true,preference:saved};}let saved;try{ctx.db.transaction(db=>{db.query("UPDATE teacher_preference_entries SET status='superseded',updated_at=datetime('now') WHERE id=?",[old.id]);const x=db.query('INSERT INTO teacher_preference_entries(app_id,cycle_id,external_key,staff_id,domain,stance,target_key,target_label,rank,confidence,rationale,valid_from,valid_to,review_state,status,revision,submitted_by,supersedes_id) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',[appId,old.cycle_id,old.external_key,old.staff_id,next.domain,next.stance,next.target_key,next.target_label,next.rank,next.confidence,next.rationale||null,next.valid_from,next.valid_to,next.review_state,'draft',Number(old.revision)+1,String(req.user.id),old.id]);saved=entry(ctx,x.lastInsertRowid,appId);});}catch(e){if(String(e.message).includes('UNIQUE'))return bad('Preference rank already exists','PREFERENCE_EXISTS',409);throw e;}saved=hydrate(ctx,saved);emit(ctx,'teacher_preference.revised',saved);return{success:true,preference:saved,superseded:hydrate(ctx,entry(ctx,old.id,appId))};}
async function submitEntry(req,ctx){const appId=scope(req),row=entry(ctx,req.params.id,appId),body=req.body||{};if(!row)return bad('Preference not found','NOT_FOUND',404);const conflict=expected(row,body);if(conflict)return conflict;if(row.status!=='draft')return bad('Only draft preferences can be submitted','INVALID_STATE',409);const c=cycle(ctx,row.cycle_id,appId);if(!c||c.status!=='open')return bad('Preference cycle is not open','CYCLE_NOT_OPEN',409);ctx.db.query("UPDATE teacher_preference_entries SET status='active',revision=revision+1,updated_at=datetime('now') WHERE id=? AND revision=?",[row.id,row.revision]);const saved=hydrate(ctx,entry(ctx,row.id,appId));emit(ctx,'teacher_preference.submitted',saved);emit(ctx,'teacher_preference.provider_ready',saved);return{success:true,preference:saved};}
async function withdrawEntry(req,ctx){const appId=scope(req),row=entry(ctx,req.params.id,appId),b=req.body||{};if(!row)return bad('Preference not found','NOT_FOUND',404);const conflict=expected(row,b);if(conflict)return conflict;if(!['draft','active'].includes(row.status))return bad('Preference cannot be withdrawn from its current state','INVALID_STATE',409);if(!text(b.reason))return bad('Withdrawal reason is required');ctx.db.query("UPDATE teacher_preference_entries SET status='withdrawn',withdrawal_reason=?,withdrawn_by=?,withdrawn_at=datetime('now'),revision=revision+1,updated_at=datetime('now') WHERE id=? AND revision=?",[text(b.reason),String(req.user.id),row.id,row.revision]);const saved=hydrate(ctx,entry(ctx,row.id,appId));emit(ctx,'teacher_preference.withdrawn',saved);emit(ctx,'teacher_preference.provider_ready',saved);return{success:true,preference:saved};}
async function reviewRestriction(req,ctx){const appId=scope(req),row=entry(ctx,req.params.id,appId),b=req.body||{},decision=b.decision;if(!row)return bad('Preference not found','NOT_FOUND',404);const conflict=expected(row,b);if(conflict)return conflict;if(row.stance!=='declared_restriction'||row.status!=='active'||row.review_state!=='pending')return bad('Only pending active restriction declarations can be reviewed','INVALID_REVIEW_STATE',409);if(!['confirmed','declined'].includes(decision))return bad('Decision must be confirmed or declined');if(!text(b.reason))return bad('Review reason is required');ctx.db.transaction(db=>{db.query('INSERT INTO teacher_preference_reviews(app_id,preference_entry_id,decision,reason,decided_by) VALUES(?,?,?,?,?)',[appId,row.id,decision,text(b.reason),String(req.user.id)]);db.query("UPDATE teacher_preference_entries SET review_state=?,reviewed_by=?,reviewed_at=datetime('now'),revision=revision+1,updated_at=datetime('now') WHERE id=? AND revision=?",[decision,String(req.user.id),row.id,row.revision]);});const saved=hydrate(ctx,entry(ctx,row.id,appId));emit(ctx,'teacher_preference.restriction_reviewed',saved);emit(ctx,'teacher_preference.provider_ready',saved);return{success:true,preference:saved};}
async function staffHistory(req,ctx){const appId=scope(req),staffId=text(req.params.staffId),pg=page(req);if(!staff(ctx,staffId,appId))return bad('Staff member not found','NOT_FOUND',404);const total=ctx.db.query('SELECT COUNT(*) total FROM teacher_preference_entries WHERE app_id=? AND staff_id=?',[appId,staffId]).rows[0].total,rows=ctx.db.query('SELECT * FROM teacher_preference_entries WHERE app_id=? AND staff_id=? ORDER BY created_at DESC,id DESC LIMIT ? OFFSET ?',[appId,staffId,pg.limit,(pg.page-1)*pg.limit]).rows.map(r=>hydrate(ctx,r));return{success:true,staff_id:staffId,history:rows,total:Number(total),...pg};}
async function listProviderRecords(req,ctx){const appId=scope(req),pg=page(req),where=["app_id=?","status IN ('active','withdrawn')"],params=[appId];if(req.query.cycle_id){where.push('cycle_id=?');params.push(req.query.cycle_id);}if(req.query.staff_id){where.push('staff_id=?');params.push(String(req.query.staff_id));}const clause=' WHERE '+where.join(' AND '),total=ctx.db.query('SELECT COUNT(*) total FROM teacher_preference_entries'+clause,params).rows[0].total,rows=ctx.db.query('SELECT * FROM teacher_preference_entries'+clause+' ORDER BY staff_id,domain,rank,id LIMIT ? OFFSET ?',params.concat([pg.limit,(pg.page-1)*pg.limit])).rows,records=rows.map(row=>contract.providerRecord({...row,staff_id:String(row.staff_id)},row.revision));return{success:true,provider:'teacher_preferences',authority:'advisory_only',human_confirmation_required:true,records,total:Number(total),...pg};}

async function getInsights(req,ctx){const appId=scope(req),counts={};for(const status of ['draft','active','withdrawn','superseded'])counts[status]=Number(ctx.db.query('SELECT COUNT(*) n FROM teacher_preference_entries WHERE app_id=? AND status=?',[appId,status]).rows[0].n);const openCycles=Number(ctx.db.query("SELECT COUNT(*) n FROM teacher_preference_cycles WHERE app_id=? AND status='open'",[appId]).rows[0].n),pending=Number(ctx.db.query("SELECT COUNT(*) n FROM teacher_preference_entries WHERE app_id=? AND status='active' AND stance='declared_restriction' AND review_state='pending'",[appId]).rows[0].n),staffTotal=Number(ctx.db.query("SELECT COUNT(*) n FROM staff WHERE employment_status='active'").rows[0].n),staffRepresented=Number(ctx.db.query("SELECT COUNT(DISTINCT staff_id) n FROM teacher_preference_entries WHERE app_id=? AND status='active'",[appId]).rows[0].n),distribution=ctx.db.query("SELECT domain,stance,COUNT(*) value FROM teacher_preference_entries WHERE app_id=? AND status='active' GROUP BY domain,stance ORDER BY domain,stance",[appId]).rows.map(x=>({...x,value:Number(x.value)})),coverage=staffTotal?Math.round(staffRepresented*1000/staffTotal)/10:0,alerts=[];if(!openCycles)alerts.push({severity:'info',message:'No preference collection cycle is currently open.'});if(pending)alerts.push({severity:'warning',message:`${pending} declared restriction(s) await human review.`});if(staffTotal&&!staffRepresented)alerts.push({severity:'warning',message:'No active staff preferences have been submitted.'});return{success:true,insights:{readiness:pending?'review_required':counts.active?'operational':'collecting',counts:{...counts,open_cycles:openCycles,pending_restrictions:pending,staff_total:staffTotal,staff_represented:staffRepresented},coverage_percent:coverage,distribution,alerts,narrative:counts.active?`${counts.active} active advisory record(s) represent ${staffRepresented} of ${staffTotal} active staff.`:'Preferences are not yet supplying active advisory records.'}};}

async function syncScheduler(req,ctx){const appId=scope(req),setupId=Number(req.body&&req.body.scheduler_setup_id),target=ctx.db.query('SELECT * FROM scheduler_setups WHERE id=? AND app_id=?',[setupId,appId]).rows[0];if(!target)return bad('Scheduler setup not found','NOT_FOUND',404);const rows=ctx.db.query("SELECT * FROM teacher_preference_entries WHERE app_id=? AND status IN ('active','withdrawn') ORDER BY id",[appId]).rows,records=rows.map(row=>contract.providerRecord({...row,staff_id:String(row.staff_id)},row.revision)),seen=new Set(),now=new Date().toISOString();let changed=0;ctx.db.transaction(db=>{for(const record of records){const key=record.record_type+':'+record.external_key;if(seen.has(key))throw new Error('Duplicate provider record identity: '+key);seen.add(key);const payloadHash=hash(record.payload),old=db.query('SELECT * FROM scheduler_provider_records WHERE app_id=? AND scheduler_setup_id=? AND provider=? AND record_type=? AND external_key=?',[appId,setupId,'teacher_preferences',record.record_type,record.external_key]).rows[0];if(old&&old.provider_version===String(record.provider_version)&&old.payload_hash===payloadHash&&old.status===(record.status||'active'))continue;db.query("INSERT INTO scheduler_provider_records(app_id,scheduler_setup_id,provider,record_type,external_key,provider_version,effective_from,effective_to,payload_json,payload_hash,status) VALUES(?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(app_id,scheduler_setup_id,provider,record_type,external_key) DO UPDATE SET provider_version=excluded.provider_version,effective_from=excluded.effective_from,effective_to=excluded.effective_to,payload_json=excluded.payload_json,payload_hash=excluded.payload_hash,status=excluded.status,updated_at=datetime('now')",[appId,setupId,'teacher_preferences',record.record_type,record.external_key,String(record.provider_version),record.effective_from||null,record.effective_to||null,JSON.stringify(record.payload),payloadHash,record.status||'active']);changed++;}if(changed){db.query("UPDATE scheduler_setups SET input_revision=input_revision+1,updated_at=datetime('now') WHERE id=? AND app_id=?",[setupId,appId]);db.query("UPDATE scheduler_versions SET stale=1,updated_at=datetime('now') WHERE scheduler_setup_id=? AND app_id=? AND status NOT IN ('published','superseded')",[setupId,appId]);}});const saved=ctx.db.query('SELECT input_revision FROM scheduler_setups WHERE id=?',[setupId]).rows[0];ctx.events.publish('teacher_preference.scheduler_synced',{source:'teacher_preferences',__module:'teacher_preferences',app_id:appId,scheduler_setup_id:setupId,received:records.length,changed,input_revision:saved.input_revision,synced_at:now});return{success:true,provider:'teacher_preferences',authority:'advisory_only',human_confirmation_required:true,received:records.length,changed,input_revision:saved.input_revision};}

module.exports={boot,teardown,getContract,listProviderRecords,getInsights,syncScheduler,listCycles,createCycle,openCycle,closeCycle,listEntries,createEntry,reviseEntry,submitEntry,withdrawEntry,reviewRestriction,staffHistory};
