'use strict';
var db=require('../../db'),products=require('../products'),metrics=require('../metrics');
var ID='core.registry-quality',VERSION='2.0.0',STALE_MS=365*86400000;
function parse(value,fallback){try{return JSON.parse(value);}catch(_){return fallback;}}
function title(type){return type.split('_').map(function(p){return p.charAt(0).toUpperCase()+p.slice(1);}).join(' ');}
function evidence(row,issue,fields){return {kind:'data_quality',entityType:row.entity_type,entityId:row.entity_id,issue:issue,fields:fields||[],dataQuality:row.data_quality};}
function stableKey(row){var f=parse(row.facts,{}),keys={student:'student_id',staff:'staff_id',room:'room_number',inventory_item:'item_number'};var key=keys[row.entity_type];return key&&f[key]?String(f[key]).trim().toLowerCase():null;}
function contradictions(row){var f=parse(row.facts,{}),out=[];
 if(row.lifecycle_status==='withdrawn'&&['active','available'].indexOf(f.enrollment_status||f.employment_status||f.status)>=0)out.push('lifecycle_status');
 if(row.entity_type==='inventory_item'&&f.assigned_to_staff_id&&f.assigned_to_student_id)out.push('assigned_to_staff_id','assigned_to_student_id');
 if(row.entity_type==='room_booking'&&f.start_time&&f.end_time&&Date.parse(f.end_time)<=Date.parse(f.start_time))out.push('start_time','end_time');
 return out;
}
function analyse(ctx){
 var rows=db.query('SELECT * FROM world_entities').rows,created=[],summary={},now=ctx.period.end||Date.now(),byType={};
 rows.forEach(function(row){(byType[row.entity_type]||(byType[row.entity_type]=[])).push(row);});
 Object.keys(byType).forEach(function(type){var group=byType[type],average=group.reduce(function(n,r){return n+r.data_quality;},0)/group.length,incomplete=group.filter(function(r){return r.data_quality<1;});summary[type]={records:group.length,averageQuality:average,incomplete:incomplete.length};
  metrics.define({id:type+'.data_quality.average',name:title(type)+' record completeness',description:'Average declared field completeness',unit:'ratio',scopeTypes:['organisation'],providerId:ID,providerVersion:VERSION});
  metrics.record({metricId:type+'.data_quality.average',scope:ctx.scope,period:ctx.period,value:average,evidence:group.map(function(r){return evidence(r,'completeness');}),providerRunId:ctx.runId});
  var ev=(incomplete.length?incomplete:group).map(function(r){return evidence(r,incomplete.length?'incomplete':'complete');});
  if(average>=.95)created.push(products.create({type:'observation',scope:ctx.scope,title:title(type)+' records are highly complete',summary:Math.round(average*100)+'% average declared-field completeness across '+group.length+' records.',explanation:'This positive signal assesses declared required fields, not whether every value is factually correct.',evidence:ev,possibleActions:['Sustain current record-keeping practice'],confidence:Math.min(1,group.length/20),severity:'positive',providerId:ID,providerVersion:VERSION,providerRunId:ctx.runId}));
  else created.push(products.create({type:'data_quality',scope:ctx.scope,title:title(type)+' records need completion',summary:incomplete.length+' of '+group.length+' records are missing declared fields.',explanation:'Incomplete information limits later synthesis and exposes a management blind spot.',evidence:ev,possibleActions:['Review the identified records'],confidence:1,severity:average<.7?'warning':'information',providerId:ID,providerVersion:VERSION,providerRunId:ctx.runId}));
 });
 var stale=rows.filter(function(r){var f=parse(r.facts,{}),stamp=Date.parse(f.updated_at||f.created_at||'');return Number.isFinite(stamp)&&now-stamp>STALE_MS;});
 if(stale.length)created.push(products.create({type:'data_quality',scope:ctx.scope,title:'Some records may be stale',summary:stale.length+' records have not been updated for over one year.',explanation:'Age alone does not mean a record is wrong; it identifies records worth confirming.',evidence:stale.map(function(r){return evidence(r,'stale',['updated_at']);}),possibleActions:['Confirm that stale records remain current'],confidence:.8,severity:'information',providerId:ID,providerVersion:VERSION,providerRunId:ctx.runId}));
 var contradictory=[];rows.forEach(function(r){var fields=contradictions(r);if(fields.length)contradictory.push(evidence(r,'contradictory_state',fields));});
 if(contradictory.length)created.push(products.create({type:'data_quality',scope:ctx.scope,title:'Contradictory record states detected',summary:contradictory.length+' records contain states that cannot safely be interpreted together.',explanation:'These conflicts can lead to incorrect conclusions until the source record is corrected.',evidence:contradictory,possibleActions:['Review the conflicting fields'],confidence:1,severity:'warning',providerId:ID,providerVersion:VERSION,providerRunId:ctx.runId}));
 var broken=db.query("SELECT r.* FROM world_relationships r LEFT JOIN world_entities e ON e.entity_type=r.object_type AND e.entity_id=r.object_id WHERE r.valid_to IS NULL AND e.entity_id IS NULL").rows;
 if(broken.length)created.push(products.create({type:'data_quality',scope:ctx.scope,title:'Broken entity relationships detected',summary:broken.length+' active relationships point to records that are unavailable.',explanation:'Cross-component analysis cannot safely use these links.',evidence:broken.map(function(r){return {kind:'broken_relationship',relationshipId:r.id,entityType:r.subject_type,entityId:r.subject_id,targetType:r.object_type,targetId:r.object_id};}),possibleActions:['Restore or correct the referenced records'],confidence:1,severity:'warning',providerId:ID,providerVersion:VERSION,providerRunId:ctx.runId}));
 var seen={},duplicates=[];rows.forEach(function(r){var key=stableKey(r);if(!key)return;var compound=r.entity_type+'|'+key;if(seen[compound])duplicates.push(evidence(r,'duplicate_identifier',[key]));else seen[compound]=r;});
 if(duplicates.length)created.push(products.create({type:'data_quality',scope:ctx.scope,title:'Duplicate identifiers detected',summary:duplicates.length+' records reuse a canonical business identifier.',explanation:'These may represent duplicate objects and should be resolved before synthesis.',evidence:duplicates,possibleActions:['Compare and merge or correct duplicate records'],confidence:1,severity:'warning',providerId:ID,providerVersion:VERSION,providerRunId:ctx.runId}));
 return {summary:summary,issues:{stale:stale.length,contradictory:contradictory.length,brokenRelationships:broken.length,duplicates:duplicates.length},products:created};
}
module.exports={id:ID,version:VERSION,analyse:analyse,governance:{inputs:['world_entities','world_relationships','component intelligence data-quality declarations'],outputs:['*.data_quality.average','observation','data_quality'],supportedScopes:['organisation'],minimumEvidence:{observation:1,data_quality:1},confidenceMethod:'declared-field coverage plus deterministic integrity checks',failureMode:'fail visibly; never infer missing values',knowledgeDependencies:[],suppression:['no conclusion for an empty entity type','staleness is review advice, not an assertion of inaccuracy','no duplicate claim without a matching canonical identifier']}};
