import sharp from "sharp";
import { FINGERPRINT_ALGORITHM_VERSION, FINGERPRINT_SCHEMA_VERSION, type FieldSuggestion, type ImageMeasurements, type PaletteEntry, type VisualFingerprint } from "../../domain/garment/visual-fingerprint.js";

const clamp=(value:number,min=0,max=1)=>Math.min(Math.max(value,min),max);
const rounded=(value:number,digits=4)=>Number(value.toFixed(digits));

function lab(r:number,g:number,b:number):readonly[number,number,number]{const linear=(v:number)=>{v/=255;return v<=.04045?v/12.92:((v+.055)/1.055)**2.4};const R=linear(r),G=linear(g),B=linear(b);const x=(R*.4124+G*.3576+B*.1805)/.95047,y=(R*.2126+G*.7152+B*.0722),z=(R*.0193+G*.1192+B*.9505)/1.08883;const f=(v:number)=>v>.008856?Math.cbrt(v):7.787*v+16/116;return[rounded(116*f(y)-16,2),rounded(500*(f(x)-f(y)),2),rounded(200*(f(y)-f(z)),2)]}
const colourNames=[{n:"black",v:[20,20,20]},{n:"white",v:[235,235,235]},{n:"grey",v:[128,128,128]},{n:"navy",v:[25,40,80]},{n:"blue",v:[50,105,180]},{n:"brown",v:[105,70,45]},{n:"beige",v:[205,185,145]},{n:"red",v:[175,45,45]},{n:"burgundy",v:[95,25,40]},{n:"green",v:[55,110,65]},{n:"yellow",v:[220,190,55]},{n:"orange",v:[210,115,40]},{n:"purple",v:[105,65,135]},{n:"pink",v:[215,135,155]}] as const;
function label(r:number,g:number,b:number){return colourNames.reduce((best,current)=>{const d=(r-current.v[0])**2+(g-current.v[1])**2+(b-current.v[2])**2;return d<best.d?{n:current.n,d}:best},{n:"unknown",d:Infinity}).n}

export async function measureImage(bytes:Buffer):Promise<ImageMeasurements>{const{data,info}=await sharp(bytes).rotate().resize({width:256,height:256,fit:"inside",withoutEnlargement:true}).removeAlpha().raw().toBuffer({resolveWithObject:true});const{width,height,channels}=info;if(channels<3)throw new Error("image_channels_unsupported");const pixels=width*height;const lum=new Float64Array(pixels);const bins=new Map<string,{count:number;r:number;g:number;b:number}>();let sumL=0,sumC=0;
  const cornerPoints:readonly(readonly[number,number])[]=[[0,0],[width-1,0],[0,height-1],[width-1,height-1]];const corners=cornerPoints.map(([x,y])=>{const i=(y!*width+x!)*channels;return[data[i]!,data[i+1]!,data[i+2]!]});const bg=[0,1,2].map((c)=>corners.reduce((s,p)=>s+p[c]!,0)/4);let minX=width,minY=height,maxX=-1,maxY=-1,foreground=0;
  for(let p=0;p<pixels;p++){const i=p*channels,r=data[i]!,g=data[i+1]!,b=data[i+2]!,y=.2126*r+.7152*g+.0722*b;lum[p]=y;const [L,a,bb]=lab(r,g,b);sumL+=L;sumC+=Math.hypot(a,bb);const key=`${r>>5}-${g>>5}-${b>>5}`,bin=bins.get(key)??{count:0,r:0,g:0,b:0};bin.count++;bin.r+=r;bin.g+=g;bin.b+=b;bins.set(key,bin);if(Math.hypot(r-bg[0]!,g-bg[1]!,b-bg[2]!)>35){const x=p%width,yy=Math.floor(p/width);minX=Math.min(minX,x);maxX=Math.max(maxX,x);minY=Math.min(minY,yy);maxY=Math.max(maxY,yy);foreground++}}
  const mean=lum.reduce((s,v)=>s+v,0)/pixels;let variance=0,edges=0,horizontal=0,vertical=0,neighborDifference=0,neighbors=0;for(let y=1;y<height-1;y++)for(let x=1;x<width-1;x++){const p=y*width+x,gx=lum[p+1]!-lum[p-1]!,gy=lum[p+width]!-lum[p-width]!,m=Math.hypot(gx,gy);if(m>36)edges++;horizontal+=Math.abs(gy);vertical+=Math.abs(gx);neighborDifference+=Math.abs(lum[p]!-lum[p-1]!)+Math.abs(lum[p]!-lum[p-width]!);neighbors+=2}for(const value of lum)variance+=(value-mean)**2;const palette:PaletteEntry[]=[...bins.values()].sort((a,b)=>b.count-a.count).slice(0,5).map((bin)=>{const r=Math.round(bin.r/bin.count),g=Math.round(bin.g/bin.count),b=Math.round(bin.b/bin.count);return{rgb:[r,g,b],lab:lab(r,g,b),proportion:rounded(bin.count/pixels),label:label(r,g,b)}});const edgeDensity=edges/Math.max((width-2)*(height-2),1),contrast=Math.sqrt(variance/pixels)/64,texture=(neighborDifference/Math.max(neighbors,1))/32,paletteComplexity=clamp((bins.size-1)/40),complexity=clamp(.2*paletteComplexity+.4*edgeDensity*4+.15*contrast+.15*texture+.1*(1-palette[0]!.proportion));const boxWidth=maxX>=0?maxX-minX+1:width,boxHeight=maxY>=0?maxY-minY+1:height;
  return Object.freeze({width,height,foregroundCoverage:rounded(foreground/pixels),foregroundAspectRatio:rounded(boxWidth/boxHeight),palette:Object.freeze(palette),averageLightness:rounded(sumL/pixels),averageChroma:rounded(sumC/pixels),luminanceContrast:rounded(clamp(contrast)),edgeDensity:rounded(edgeDensity),horizontalEdgeEnergy:rounded(clamp(horizontal/Math.max(neighbors,1)/32)),verticalEdgeEnergy:rounded(clamp(vertical/Math.max(neighbors,1)/32)),textureStrength:rounded(clamp(texture)),paletteComplexity:rounded(paletteComplexity),visualComplexity:rounded(complexity),solidConfidence:rounded(clamp(1-edgeDensity*3-paletteComplexity*.45))});}

export function combineFingerprint(whole:ImageMeasurements|null,detail:ImageMeasurements|null):VisualFingerprint{if(!whole&&!detail)throw new Error("fingerprint_requires_image");const w=whole?0.65:0,d=detail?(whole?0.35:1):0,total=w+d;const weighted=(key:keyof Pick<ImageMeasurements,"averageLightness"|"averageChroma"|"luminanceContrast"|"edgeDensity"|"textureStrength"|"visualComplexity"|"solidConfidence">)=>rounded(((whole?Number(whole[key])*w:0)+(detail?Number(detail[key])*d:0))/total);const palette=(whole??detail)!.palette;const confidence=rounded(clamp((whole&&detail?.width?0.9:0.62)*((whole??detail)!.foregroundCoverage>.1?1:.75)));return Object.freeze({schemaVersion:FINGERPRINT_SCHEMA_VERSION,algorithmVersion:FINGERPRINT_ALGORITHM_VERSION,whole,detail,combined:{palette,averageLightness:weighted("averageLightness"),averageChroma:weighted("averageChroma"),contrast:weighted("luminanceContrast"),patternDensity:weighted("edgeDensity"),textureStrength:weighted("textureStrength"),visualComplexity:weighted("visualComplexity"),solidConfidence:weighted("solidConfidence")},confidence});}

export function suggestFields(fingerprint:VisualFingerprint):readonly FieldSuggestion[]{const m=fingerprint.combined,shape=(fingerprint.whole??fingerprint.detail)!,suggestions:FieldSuggestion[]=[];const ratio=shape.foregroundAspectRatio;let categories:{slug:string;confidence:number;reason:string}[];if(ratio<.32)categories=[{slug:"ties",confidence:.66,reason:"very narrow vertical foreground"},{slug:"scarves",confidence:.38,reason:"narrow foreground"}];else if(ratio>3)categories=[{slug:"belts",confidence:.62,reason:"very wide narrow foreground"},{slug:"scarves",confidence:.35,reason:"wide foreground"}];else if(ratio<.72)categories=[{slug:"formal-shirts",confidence:.37,reason:"vertical garment silhouette"},{slug:"formal-trousers",confidence:.35,reason:"vertical garment silhouette"},{slug:"coats",confidence:.31,reason:"vertical garment silhouette"}];else categories=[{slug:"casual-shirts",confidence:.3,reason:"broad garment silhouette"},{slug:"sweaters",confidence:.28,reason:"broad garment silhouette"},{slug:"pocket-squares",confidence:.24,reason:"near-square foreground"}];suggestions.push({field:"category",value:categories,confidence:categories[0]!.confidence*fingerprint.confidence,evidence:{foregroundAspectRatio:ratio,foregroundCoverage:shape.foregroundCoverage,limitation:"shape-only semantic estimate"}});const formality=clamp(5-(m.visualComplexity*2.4+m.averageChroma/60));suggestions.push({field:"formality",value:Math.max(1,Math.min(5,Math.round(formality))),confidence:rounded(.34*fingerprint.confidence),evidence:{visualComplexity:m.visualComplexity,averageChroma:m.averageChroma}});const seasons=m.averageLightness<45?["autumn","winter"]:m.averageLightness>70?["spring","summer"]:["all-season"];suggestions.push({field:"seasons",value:seasons,confidence:rounded(.4*fingerprint.confidence),evidence:{averageLightness:m.averageLightness}});return Object.freeze(suggestions);}
