import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    environment: "node",
    include: [
      "tests/unit/token-security.test.ts",
      "tests/unit/momentum.test.ts",
      "tests/unit/position-sizing.test.ts",
      "tests/unit/quote.test.ts",
      "tests/unit/order-state.test.ts",
      "tests/unit/position-exits.test.ts",
      "tests/unit/emergency-exits.test.ts",
      "tests/unit/emergency-execution.test.ts",
      "tests/unit/standard-execution.test.ts",
      "tests/unit/runtime-fact-aggregation.test.ts",
      "tests/integration/execution.test.ts",
      "tests/integration/position-worker.test.ts",
      "tests/integration/persistence.test.ts",
      "tests/integration/restart-recovery.test.ts",
      "tests/integration/reconciliation-locking.test.ts",
      "tests/integration/job-runner.test.ts",
      "tests/integration/supervisor.test.ts",
      "tests/integration/startup-database.test.ts",
      "tests/integration/production-startup.test.ts",
      "tests/integration/production-composition.test.ts",
      "tests/integration/worker-entrypoint.test.ts",
      "tests/integration/runtime-facts.test.ts",
      "tests/integration/migrations.test.ts",
      "tests/integration/observation-ingestion.test.ts",
      "tests/integration/runtime-fact-publishing.test.ts",
      "tests/integration/runtime-fact-publisher-worker.test.ts",
      "tests/contract/dexscreener.test.ts",
      "tests/contract/solana.test.ts",
      "tests/contract/jupiter.test.ts",
      "tests/contract/helius.test.ts",
      "tests/contract/provider-clients.test.ts",
      "tests/security/transaction-inspection.test.ts",
      "tests/security/solana-instruction-parser.test.ts",
      "tests/security/startup-config.test.ts",
      "tests/security/http-transport.test.ts",
      "tests/security/secrets.test.ts",
      "tests/failure/reconciliation.test.ts",
      "tests/failure/reconciliation-retry.test.ts",
      "tests/replay/determinism.test.ts",
    ],
    passWithNoTests: false,
  },
});
