import {randomUUID,createHash} from 'node:crypto';
import {z} from 'zod';
import {MCF,MCF_HASH,decisionInput,validateDecision,valence} from '../domain/mcf.js';
import config from '../../analysis-config/mcf-classification/1.0.json' with {type:'json'};
import {McfRepository} from '../infrastructure/mcf-repository.js';
import {runGroundedAiAnalysis,type AiAnalysisProvider} from './ai-analysis.js';
import {answerQuestions} from './question-analysis.js';

export const proposalResponse=z.object({units:z.array(z.object({unitId:z.uuid(),codes:z.array(z.object({competencyId:z.enum(MCF.competencies.map(c=>c.id) as [string,...string[]]),evidenceStrength:z.enum(['Explicit','Implicit']),valence:valence.nullable(),rationale:z.string().max(5000),evidence:z.string().min(1).max(20000)}).strict()).max(21),valence:valence.nullable(),notes:z.string().max(10000)}).strict()).min(1).max(12)}).strict();
export function validateProposals(value:unknown,units:{id:string;original_text:string}[],mode:string,citations:string[]){
 const parsed=proposalResponse.parse(value);if(parsed.units.length!==units.length||new Set(parsed.units.map(u=>u.unitId)).size!==units.length)throw Error('incomplete_mcf_response');
 return parsed.units.map(p=>{const unit=units.find(u=>u.id===p.unitId);if(!unit)throw Error('unknown_proposal_unit');const decision=decisionInput.parse({previousId:null,codes:p.codes,valence:p.valence,notes:p.notes,reviewedNoCode:p.codes.length===0,actor:'Machine proposal'});validateDecision(decision,unit.original_text,mode);if(p.codes.length&&!citations.includes(unit.id))throw Error('unsupported_mcf_citation');return{unitId:unit.id,codes:decision.codes,valence:decision.valence,notes:decision.notes,reviewedNoCode:decision.reviewedNoCode};});
}
export function codingSnapshot(session:any){return{decisions:session.units.filter((u:any)=>u.decision).map((u:any)=>({unitId:u.id,decisionId:u.decision.id,codes:u.decision.codes,valence:u.decision.valence,reviewedNoCode:u.decision.reviewed_no_code,text:u.original_text})),representations:session.representations,instrumentHash:session.instrument_hash,totalUnits:session.units.length};}
export const snapshotHash=(value:unknown)=>createHash('sha256').update(JSON.stringify(value)).digest('hex');
export class McfAiWorker{
 private timer:ReturnType<typeof setInterval>|null=null;private busy=false;private stopped=false;error:string|null=null;
 constructor(readonly repo:McfRepository,readonly provider:()=>AiAnalysisProvider|null){}
 async start(){await this.repo.db.query("UPDATE researched.mcf_ai_tasks SET status='failed',error='Interrupted by restart; start a new analysis to retry.' WHERE status='running'");await this.settle();this.timer=setInterval(()=>{void this.tick();},1000);this.timer.unref();}
 stop(){this.stopped=true;if(this.timer)clearInterval(this.timer);}
 async enqueue(sessionId:string,kind:'classification'|'interpretation',actor:string,questions:string[]=[]){
  const provider=this.provider();if(!provider)throw Error('ai_provider_not_configured');const session=await this.repo.workspace(sessionId);if(session.instrument_hash!==MCF_HASH)throw Error('instrument_version_mismatch');if(session.blind||session.kind==='validation')throw Error('manual_validation_no_ai');
  const units=session.units.filter((u:any)=>u.original_text.trim());if(!units.length)throw Error('no_readable_evidence');const snapshot=kind==='interpretation'?codingSnapshot(session):null;if(snapshot&&!snapshot.decisions.length&&!snapshot.representations.length)throw Error('review_coding_before_interpretation');
  const id=randomUUID(),batches:string[][]=[];if(kind==='classification'){let batch:string[]=[],size=0;for(const u of units){if(batch.length&&(batch.length>=config.maximumBatchUnits||size+u.original_text.length>config.maximumBatchCharacters)){batches.push(batch);batch=[];size=0;}batch.push(u.id);size+=u.original_text.length;}if(batch.length)batches.push(batch);}else batches.push(snapshot!.decisions.map((d:any)=>d.unitId));
  await this.repo.transaction(async c=>{await this.repo.writable(session.dataset_id,c);await this.repo.active('sessions',sessionId,c);await c.query("INSERT INTO researched.mcf_ai_runs(id,session_id,kind,status,configuration,actor) VALUES($1,$2,$3,'queued',$4,$5)",[id,sessionId,kind,JSON.stringify({provider:{id:provider.id,model:provider.model,connectionId:provider.configurationId??null},classificationConfig:config,instrumentHash:MCF_HASH,unitSets:session.configuration.unitSets,questions:questions.length?questions:['What patterns and limitations are supported by the reviewed MCF findings?'],snapshot,snapshotHash:snapshot?snapshotHash(snapshot):null}),actor]);for(const [i,ids]of batches.entries())await c.query("INSERT INTO researched.mcf_ai_tasks(id,run_id,ordinal,unit_ids,status) VALUES($1,$2,$3,$4,'queued')",[randomUUID(),id,i+1,JSON.stringify(ids)]);await this.repo.audit(c,session.dataset_id,'mcf_ai_requested',id,actor,{sessionId,kind,provider:provider.id,model:provider.model});});return{id};
 }
 async overview(sessionId:string){const session=await this.repo.session(sessionId);if(session.blind||session.kind==='validation')return{runs:[],proposals:[],outputs:[]};const runs=(await this.repo.db.query('SELECT r.*,(SELECT count(*)::int FROM researched.mcf_ai_tasks t WHERE t.run_id=r.id) AS total,(SELECT count(*)::int FROM researched.mcf_ai_tasks t WHERE t.run_id=r.id AND t.status=\'completed\') AS completed,(SELECT jsonb_agg(error) FROM researched.mcf_ai_tasks t WHERE t.run_id=r.id AND t.error IS NOT NULL) AS errors FROM researched.mcf_ai_runs r WHERE session_id=$1 ORDER BY created_at DESC',[sessionId])).rows;
  const proposals=(await this.repo.db.query("SELECT p.*,o.run_id,(SELECT jsonb_build_object('outcome',v.outcome,'actor',v.actor,'reason',v.reason,'decisionId',v.decision_id) FROM researched.mcf_ai_reviews v WHERE v.proposal_id=p.id ORDER BY v.created_at DESC LIMIT 1) AS review FROM researched.mcf_ai_proposals p JOIN researched.mcf_ai_outputs o ON o.id=p.output_id WHERE p.session_id=$1 ORDER BY p.created_at DESC,p.id",[sessionId])).rows;
  const outputs=(await this.repo.db.query('SELECT o.* FROM researched.mcf_ai_outputs o JOIN researched.mcf_ai_runs r ON r.id=o.run_id WHERE r.session_id=$1 AND r.kind=\'interpretation\' ORDER BY o.created_at DESC',[sessionId])).rows;const hash=snapshotHash(codingSnapshot(await this.repo.workspace(sessionId)));return{runs:runs.map(r=>({...r,stale:r.kind==='interpretation'&&r.configuration.snapshotHash!==hash})),proposals,outputs};
 }
 async export(sessionId:string){const result=await this.overview(sessionId);const s=await this.repo.session(sessionId);if(s.blind||s.kind==='validation')return{...result,reviews:[]};const reviews=(await this.repo.db.query('SELECT r.* FROM researched.mcf_ai_reviews r JOIN researched.mcf_ai_proposals p ON p.id=r.proposal_id WHERE p.session_id=$1 ORDER BY r.created_at,r.id',[sessionId])).rows;return{...result,reviews};}
 async reject(sessionId:string,proposalId:string,actor:string,reason:string){return this.repo.transaction(async c=>{const s=await this.repo.session(sessionId,c);await this.repo.writable(s.dataset_id,c);await this.repo.active('sessions',sessionId,c);const p=(await c.query('SELECT id FROM researched.mcf_ai_proposals WHERE id=$1 AND session_id=$2',[proposalId,sessionId])).rows[0];if(!p)throw Error('proposal_not_found');await c.query("INSERT INTO researched.mcf_ai_reviews(id,proposal_id,outcome,actor,reason) VALUES($1,$2,'rejected',$3,$4)",[randomUUID(),proposalId,actor,reason]);return{rejected:true};});}
 async cancel(sessionId:string,id:string){await this.repo.db.query("UPDATE researched.mcf_ai_runs SET status='cancelled',finished_at=now() WHERE id=$1 AND session_id=$2 AND status IN ('queued','running')",[id,sessionId]);await this.repo.db.query("UPDATE researched.mcf_ai_tasks SET status='cancelled' WHERE run_id=$1 AND status IN ('queued','running') AND EXISTS(SELECT 1 FROM researched.mcf_ai_runs r WHERE r.id=$1 AND r.session_id=$2 AND r.status='cancelled')",[id,sessionId]);return{cancelled:true};}
 async settle(){await this.repo.db.query("UPDATE researched.mcf_ai_runs r SET status=CASE WHEN NOT EXISTS(SELECT 1 FROM researched.mcf_ai_tasks t WHERE t.run_id=r.id AND t.status='failed') THEN 'completed' WHEN EXISTS(SELECT 1 FROM researched.mcf_ai_tasks t WHERE t.run_id=r.id AND t.status='completed') THEN 'partial' ELSE 'failed' END,finished_at=now() WHERE r.status IN ('queued','running') AND NOT EXISTS(SELECT 1 FROM researched.mcf_ai_tasks t WHERE t.run_id=r.id AND t.status IN ('queued','running'))");}
 async tick(){if(this.busy||this.stopped)return;this.busy=true;try{await Promise.all([this.process(),this.process()]);await this.settle();this.error=null;}catch(e){this.error=e instanceof Error?e.message:String(e);}finally{this.busy=false;}}
 async process(){if(!this.provider())return;const task=(await this.repo.db.query("WITH next AS(SELECT t.id FROM researched.mcf_ai_tasks t JOIN researched.mcf_ai_runs r ON r.id=t.run_id WHERE t.status='queued' AND r.status IN ('queued','running') ORDER BY r.created_at,t.ordinal FOR UPDATE OF t SKIP LOCKED LIMIT 1) UPDATE researched.mcf_ai_tasks t SET status='running' FROM next WHERE t.id=next.id RETURNING t.*")).rows[0];if(!task)return;
  try{const run=(await this.repo.db.query('SELECT * FROM researched.mcf_ai_runs WHERE id=$1',[task.run_id])).rows[0];const session=await this.repo.session(run.session_id);if(session.instrument_hash!==MCF_HASH||run.configuration.instrumentHash!==MCF_HASH)throw Error('instrument_version_mismatch');if(this.stopped)throw Error('Analysis stopped');await this.repo.transaction(async c=>{await this.repo.writable(session.dataset_id,c);await this.repo.active('sessions',session.id,c);});const provider=this.provider();if(!provider||provider.id!==run.configuration.provider.id||provider.model!==run.configuration.provider.model||(provider.configurationId??null)!==run.configuration.provider.connectionId)throw Error('AI connection changed. Reconnect the original provider/model or start a new analysis.');await this.repo.db.query("UPDATE researched.mcf_ai_runs SET status='running' WHERE id=$1 AND status='queued'",[run.id]);const units=(await this.repo.db.query('SELECT * FROM researched.mcf_units WHERE id=ANY($1::uuid[]) ORDER BY id',[task.unit_ids])).rows;let payload:unknown,proposals:ReturnType<typeof validateProposals>=[];
   if(run.kind==='classification'){if(units.some(u=>u.original_text.length>config.maximumBatchCharacters))throw Error('A section exceeds the AI size limit. Split it in Prepare or code it manually.');const answer=await runGroundedAiAnalysis(provider,{requestId:task.id,analysisType:run.configuration.classificationConfig.promptVersion,instructions:`${run.configuration.classificationConfig.rules}\nMode: ${session.mode}. Return exactly one entry per supplied section. Frozen MCF instrument: ${JSON.stringify(MCF)}`,evidence:units.map(u=>({segmentId:u.id,sourceId:u.unit_set_id,content:u.original_text})),outputSchema:z.toJSONSchema(proposalResponse)});proposals=validateProposals(answer.value,units,session.mode,answer.evidenceSegmentIds);payload={proposals,limitations:answer.limitations,provider:{id:provider.id,model:provider.model,connectionId:provider.configurationId??null},instrumentHash:MCF_HASH};}
   else{const snap=run.configuration.snapshot;payload=await answerQuestions(provider,[...snap.decisions.map((d:any)=>({id:d.unitId,content:JSON.stringify(d)})),...snap.representations.map((r:any)=>({id:r.id,content:JSON.stringify(r)}))],run.configuration.questions,`Interpret only these researcher-approved MCF decisions. This is a documentary coding pattern, not a measurement of an institution's competence. Reviewed ${snap.decisions.length} of ${snap.totalUnits} sections; explicitly describe partial coverage. No domain scores, averages, reliability claims or inferred institutional identities. Documentary observations: ${JSON.stringify(snap.representations)}. Instrument: ${JSON.stringify(MCF)}`);}
   if(this.stopped)throw Error('Analysis stopped');await this.repo.transaction(async c=>{await this.repo.writable(session.dataset_id,c);await this.repo.active('sessions',session.id,c);const current=(await c.query('SELECT status FROM researched.mcf_ai_runs WHERE id=$1 FOR UPDATE',[run.id])).rows[0];const active=(await c.query('SELECT status FROM researched.mcf_ai_tasks WHERE id=$1 FOR UPDATE',[task.id])).rows[0];if(current.status!=='running'||active.status!=='running')return;const output=randomUUID();await c.query('INSERT INTO researched.mcf_ai_outputs(id,run_id,task_id,payload) VALUES($1,$2,$3,$4)',[output,run.id,task.id,JSON.stringify(payload)]);for(const p of proposals)await c.query('INSERT INTO researched.mcf_ai_proposals(id,output_id,session_id,unit_id,payload) VALUES($1,$2,$3,$4,$5)',[randomUUID(),output,session.id,p.unitId,JSON.stringify(p)]);await c.query("UPDATE researched.mcf_ai_tasks SET status='completed' WHERE id=$1",[task.id]);});
  }catch(e){await this.repo.db.query("UPDATE researched.mcf_ai_tasks SET status='failed',error=$2 WHERE id=$1 AND status='running'",[task.id,e instanceof Error?e.message:String(e)]);}
 }
}
