export interface ResearchInsightMetrics{pendingSources:number;unextractedSources:number;failedTasks:number;unreviewedResults:number;lowConfidenceResults:number;potentialContradictions:number;missingExpectedFields:number;confirmedFindings:number;completedResults:number}
export function buildResearchInsights(metrics:ResearchInsightMetrics){
  const items=[] as {id:string;severity:"info"|"warning"|"critical";title:string;message:string;evidence:Record<string,number>;action:{label:string;tab:string}}[];
  if(metrics.pendingSources)items.push({id:"pending-corpus-decisions",severity:"warning",title:"Corpus decisions are waiting",message:`${metrics.pendingSources} source(s) still need an include or exclude decision.`,evidence:{pendingSources:metrics.pendingSources},action:{label:"Review corpus",tab:"corpus"}});
  if(metrics.unextractedSources)items.push({id:"unextracted-sources",severity:"critical",title:"Included evidence is not ready",message:`${metrics.unextractedSources} included source(s) do not have completed text extraction.`,evidence:{unextractedSources:metrics.unextractedSources},action:{label:"Prepare sources",tab:"corpus"}});
  if(metrics.failedTasks)items.push({id:"failed-analysis-tasks",severity:"critical",title:"Analysis tasks need attention",message:`${metrics.failedTasks} analysis task(s) exhausted their retry limit or require corrected configuration.`,evidence:{failedTasks:metrics.failedTasks},action:{label:"Open analysis runs",tab:"analysis"}});
  if(metrics.unreviewedResults)items.push({id:"unreviewed-results",severity:"warning",title:"Generated interpretations await review",message:`${metrics.unreviewedResults} result(s) have not been accepted, amended or rejected by a person.`,evidence:{unreviewedResults:metrics.unreviewedResults},action:{label:"Review results",tab:"analysis"}});
  if(metrics.potentialContradictions)items.push({id:"potential-contradictions",severity:"warning",title:"Potential contradictions were identified",message:`${metrics.potentialContradictions} cross-source contradiction(s) require human interpretation.`,evidence:{potentialContradictions:metrics.potentialContradictions},action:{label:"Inspect comparisons",tab:"analysis"}});
  if(metrics.missingExpectedFields)items.push({id:"missing-information",severity:"warning",title:"Expected information was not found",message:`${metrics.missingExpectedFields} expected field(s) were reported missing. Absence from extracted text is not proof that the information does not exist.`,evidence:{missingExpectedFields:metrics.missingExpectedFields},action:{label:"Inspect completeness results",tab:"analysis"}});
  if(metrics.lowConfidenceResults)items.push({id:"low-confidence-results",severity:"info",title:"Some results have low confidence",message:`${metrics.lowConfidenceResults} result(s) have confidence below 50%. Treat them as prompts for closer evidence review.`,evidence:{lowConfidenceResults:metrics.lowConfidenceResults},action:{label:"Review evidence",tab:"review"}});
  if(metrics.completedResults&&!metrics.confirmedFindings)items.push({id:"results-not-synthesised",severity:"info",title:"Results have not become confirmed findings",message:"Analysis results exist, but no finding has yet been confirmed. Analysis assists the researcher; it does not create conclusions automatically.",evidence:{completedResults:metrics.completedResults,confirmedFindings:metrics.confirmedFindings},action:{label:"Develop findings",tab:"analysis"}});
  return{summary:{attention:items.filter(item=>item.severity==="critical").length,warnings:items.filter(item=>item.severity==="warning").length,information:items.filter(item=>item.severity==="info").length},metrics,items,interpretation:"Insights describe recorded workflow and validated analysis output. They do not establish source truth, causation or research conclusions."};
}
