import type { Pool } from "pg";
import type { CombinationOverride, SlotRequirement, SlottedGarment } from "../../domain/outfit/ensemble-engine.js";
import type { StylingEvaluation } from "../../domain/outfit/styling-engine.js";

export class EnsembleRepository {
  public constructor(private readonly pool: Pool) {}
  public async requirements(contextId: string): Promise<readonly SlotRequirement[]> { const result=await this.pool.query("SELECT slot_id,requirement,minimum_items,maximum_items FROM dressed.context_slot_requirements WHERE context_id=$1 ORDER BY slot_id",[contextId]); return result.rows.map((row)=>({slotId:row.slot_id,requirement:row.requirement,minimumItems:row.minimum_items,maximumItems:row.maximum_items})); }
  public async candidates(useId?: string): Promise<readonly (SlottedGarment&{useIds:readonly string[]})[]> { const values=useId?[useId]:[];const useFilter=useId?" AND EXISTS(SELECT 1 FROM dressed.garment_uses gu WHERE gu.garment_id=g.garment_id AND gu.use_id=$1)":"";const result=await this.pool.query(`SELECT g.garment_id,g.name,g.lifecycle_status,g.formality,c.slug,a.slot_id,COALESCE(array_agg(DISTINCT s.season) FILTER(WHERE s.season IS NOT NULL),'{}') seasons,COALESCE((SELECT array_agg(gu.use_id ORDER BY gu.use_id) FROM dressed.garment_uses gu WHERE gu.garment_id=g.garment_id),'{}') use_ids,f.fingerprint_id,f.measurement_payload,(SELECT i.image_id FROM dressed.garment_images i WHERE i.garment_id=g.garment_id AND i.is_current AND i.role='whole' LIMIT 1) image_id FROM dressed.garments g JOIN dressed.garment_categories c ON c.category_id=g.category_id JOIN dressed.category_slot_assignments a ON a.category_id=g.category_id LEFT JOIN dressed.garment_seasons s ON s.garment_id=g.garment_id JOIN dressed.visual_fingerprints f ON f.garment_id=g.garment_id AND f.is_current WHERE g.lifecycle_status='available'${useFilter} GROUP BY g.garment_id,c.slug,a.slot_id,f.fingerprint_id,f.measurement_payload ORDER BY g.garment_id LIMIT 5000`,values); return result.rows.map((row)=>({id:row.garment_id,name:row.name,categorySlug:row.slug,status:row.lifecycle_status,formality:row.formality,seasons:row.seasons,useIds:row.use_ids,fingerprintId:row.fingerprint_id,fingerprint:row.measurement_payload,slotId:row.slot_id,imageId:row.image_id})); }
  public async overrides(): Promise<readonly CombinationOverride[]> { const result=await this.pool.query<{override_type:"ban"|"favourite";scope:"exact_outfit"|"relationship";garment_ids:string[];score_delta:string}>("SELECT override_type,scope,garment_ids,score_delta FROM dressed.combination_overrides WHERE is_active"); return result.rows.map((row)=>({type:row.override_type,scope:row.scope,garmentIds:row.garment_ids,scoreDelta:Number(row.score_delta)})); }
  public async addOverride(input:{id:string;type:"ban"|"favourite";scope:"exact_outfit"|"relationship";garmentIds:readonly string[];reason:string|null;timestamp:string}) { const ids=[...input.garmentIds].sort(); await this.pool.query("INSERT INTO dressed.combination_overrides(override_id,override_type,scope,garment_ids,score_delta,reason,created_at) VALUES($1,$2,$3,$4::uuid[],$5,$6,$7)",[input.id,input.type,input.scope,ids,input.type==="favourite"?3:0,input.reason,input.timestamp]); return{...input,garmentIds:ids}; }
  public async saveOutfit(input:{id:string;name:string;contextId:string;useId:string;evaluationId:string;garments:readonly SlottedGarment[];evaluation:StylingEvaluation;notes:string|null;timestamp:string}) { const client=await this.pool.connect(); try { await client.query("BEGIN"); await client.query("INSERT INTO dressed.saved_outfits(outfit_id,name,context_id,use_id,styling_evaluation_id,calculated_score,calculated_grade,explanation_snapshot,notes,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8::jsonb,$9,$10,$10)",[input.id,input.name,input.contextId,input.useId,input.evaluationId,input.evaluation.score,input.evaluation.grade,JSON.stringify(input.evaluation),input.notes,input.timestamp]); for(const[index,garment]of input.garments.entries()) await client.query("INSERT INTO dressed.saved_outfit_items(outfit_id,garment_id,slot_id,position) VALUES($1,$2,$3,$4)",[input.id,garment.id,garment.slotId,index]); await client.query("COMMIT"); return{id:input.id,name:input.name,score:input.evaluation.score,grade:input.evaluation.grade}; } catch(error) { await client.query("ROLLBACK"); throw error; } finally { client.release(); } }
  public async saved() { const result=await this.pool.query(`SELECT o.outfit_id,o.name,o.calculated_score,o.calculated_grade,o.user_grade,o.favourite,o.notes,o.created_at,c.name context_name,COALESCE(jsonb_agg(jsonb_build_object('id',g.garment_id,'name',g.name,'slotId',i.slot_id) ORDER BY i.position),'[]'::jsonb) items FROM dressed.saved_outfits o JOIN dressed.outfit_contexts c ON c.context_id=o.context_id JOIN dressed.saved_outfit_items i ON i.outfit_id=o.outfit_id JOIN dressed.garments g ON g.garment_id=i.garment_id GROUP BY o.outfit_id,c.name ORDER BY o.created_at DESC`); return result.rows.map((row)=>({id:row.outfit_id,name:row.name,score:Number(row.calculated_score),calculatedGrade:row.calculated_grade,userGrade:row.user_grade,favourite:row.favourite,notes:row.notes,createdAt:row.created_at,contextName:row.context_name,items:row.items})); }
}
