import type{Pool}from"pg";
export class InsightsRepository{public constructor(private readonly pool:Pool){}
 public async dashboard(){const[summary,utilisation,versatility,care,rotation,preferences]=await Promise.all([
  this.pool.query(`SELECT COUNT(*) FILTER(WHERE lifecycle_status<>'archived')::int garments,COUNT(*) FILTER(WHERE lifecycle_status='available')::int available,COUNT(*) FILTER(WHERE lifecycle_status='unavailable')::int unavailable,COALESCE(SUM(purchase_price_minor) FILTER(WHERE lifecycle_status<>'archived'),0)::bigint purchase_minor,COUNT(*) FILTER(WHERE purchase_price_minor IS NOT NULL)::int priced FROM dressed.garments`),
  this.pool.query(`SELECT g.garment_id id,g.name,c.name category,COUNT(w.wear_event_id)::int wear_count,MAX(e.worn_date) last_worn,g.purchase_price_minor,g.currency,CASE WHEN COUNT(w.wear_event_id)>0 AND g.purchase_price_minor IS NOT NULL THEN ROUND((g.purchase_price_minor::numeric/100)/COUNT(w.wear_event_id),2) END cost_per_wear FROM dressed.garments g JOIN dressed.garment_categories c ON c.category_id=g.category_id LEFT JOIN dressed.wear_event_items w ON w.garment_id=g.garment_id LEFT JOIN dressed.wear_events e ON e.wear_event_id=w.wear_event_id WHERE g.lifecycle_status<>'archived' GROUP BY g.garment_id,c.name ORDER BY wear_count,g.name`),
  this.pool.query(`SELECT g.garment_id id,g.name,COUNT(DISTINCT i.outfit_id)::int outfit_count FROM dressed.garments g LEFT JOIN dressed.saved_outfit_items i ON i.garment_id=g.garment_id WHERE g.lifecycle_status<>'archived' GROUP BY g.garment_id ORDER BY outfit_count,g.name`),
  this.pool.query(`SELECT COUNT(*) FILTER(WHERE status='open')::int open_cases,COUNT(*) FILTER(WHERE status='open' AND blocks_availability)::int blockers,COALESCE(SUM(cost_minor),0)::bigint care_cost_minor,COUNT(*) FILTER(WHERE status='open' AND due_date<CURRENT_DATE)::int overdue FROM dressed.garment_care_cases`),
  this.pool.query(`SELECT COUNT(*)::int wears,COUNT(DISTINCT saved_outfit_id)::int distinct_outfits,COUNT(DISTINCT worn_date)::int wear_days FROM dressed.wear_events`),
  this.pool.query("SELECT preference_key,preference_value FROM dressed.user_preferences ORDER BY preference_key")]);const s=summary.rows[0],r=rotation.rows[0];return{summary:{garments:s.garments,available:s.available,unavailable:s.unavailable,purchaseValue:Number(s.purchase_minor)/100,priced:s.priced,wears:r.wears,distinctOutfits:r.distinct_outfits,rotationDiversity:r.wears?Number((r.distinct_outfits/r.wears).toFixed(3)):null},utilisation:utilisation.rows.map(x=>({...x,cost_per_wear:x.cost_per_wear==null?null:Number(x.cost_per_wear)})),versatility:versatility.rows,care:{...care.rows[0],care_cost:Number(care.rows[0].care_cost_minor)/100},preferences:Object.fromEntries(preferences.rows.map(x=>[x.preference_key,x.preference_value]))}}
 public async preferences(){const result=await this.pool.query("SELECT preference_key,preference_value FROM dressed.user_preferences ORDER BY preference_key");return Object.fromEntries(result.rows.map(x=>[x.preference_key,x.preference_value]))}
 public async setPreference(key:string,value:unknown,timestamp:string){await this.pool.query("INSERT INTO dressed.user_preferences(preference_key,preference_value,updated_at) VALUES($1,$2::jsonb,$3) ON CONFLICT(preference_key) DO UPDATE SET preference_value=EXCLUDED.preference_value,updated_at=EXCLUDED.updated_at",[key,JSON.stringify(value),timestamp]);return{key,value}}
 public async updateOutfit(id:string,input:{userGrade?:"A"|"B"|"C"|null|undefined;favourite?:boolean|undefined;notes?:string|null|undefined},timestamp:string){const result=await this.pool.query("UPDATE dressed.saved_outfits SET user_grade=CASE WHEN $2 THEN $3 ELSE user_grade END,favourite=COALESCE($4,favourite),notes=CASE WHEN $5 THEN $6 ELSE notes END,updated_at=$7 WHERE outfit_id=$1 RETURNING outfit_id id,calculated_grade,user_grade,favourite,notes",[id,Object.hasOwn(input,"userGrade"),input.userGrade??null,input.favourite??null,Object.hasOwn(input,"notes"),input.notes??null,timestamp]);return result.rows[0]??null}
}
