import type {Pool} from "pg";
import type {PlannedCandidate,PriorAssignment,RotationAssignment,RotationPolicy} from "../../domain/planner/rotation-engine.js";

export class PlannerRepository{public constructor(private readonly pool:Pool){}
  public async catalogue(){const[contexts,policies,outfits,plans]=await Promise.all([this.pool.query("SELECT context_id id,name FROM dressed.outfit_contexts ORDER BY name"),this.pool.query("SELECT policy_id id,name,complete_outfit_days,garment_days,maximum_consecutive_jacket_days,allow_grade_c,is_default FROM dressed.rotation_policies ORDER BY is_default DESC,name"),this.pool.query(`SELECT o.outfit_id id,o.name,o.calculated_score score,COALESCE(o.user_grade,o.calculated_grade) grade,o.context_id,"items".garments FROM dressed.saved_outfits o JOIN LATERAL(SELECT jsonb_agg(jsonb_build_object('id',i.garment_id,'name',g.name,'slotId',i.slot_id) ORDER BY i.position) garments FROM dressed.saved_outfit_items i JOIN dressed.garments g ON g.garment_id=i.garment_id WHERE i.outfit_id=o.outfit_id)"items" ON true ORDER BY o.name`),this.plans()]);return{contexts:contexts.rows,policies:policies.rows.map((row)=>({id:row.id,name:row.name,completeOutfitDays:row.complete_outfit_days,garmentDays:row.garment_days,maximumConsecutiveJacketDays:row.maximum_consecutive_jacket_days,allowGradeC:row.allow_grade_c,isDefault:row.is_default})),outfits:outfits.rows.map((row)=>({id:row.id,name:row.name,score:Number(row.score),grade:row.grade,contextId:row.context_id,garments:row.garments})),plans}}
  public async policy(id:string):Promise<RotationPolicy|null>{const result=await this.pool.query("SELECT complete_outfit_days,garment_days,maximum_consecutive_jacket_days,allow_grade_c FROM dressed.rotation_policies WHERE policy_id=$1",[id]),row=result.rows[0];return row?{completeOutfitDays:row.complete_outfit_days,garmentDays:row.garment_days,maximumConsecutiveJacketDays:row.maximum_consecutive_jacket_days,allowGradeC:row.allow_grade_c}:null}
  public async candidates(contextId:string):Promise<readonly PlannedCandidate[]>{const result=await this.pool.query(`SELECT o.outfit_id id,o.calculated_score score,COALESCE(o.user_grade,o.calculated_grade) grade,jsonb_agg(jsonb_build_object('id',i.garment_id,'slotId',i.slot_id) ORDER BY i.position) garments FROM dressed.saved_outfits o JOIN dressed.saved_outfit_items i ON i.outfit_id=o.outfit_id WHERE o.context_id=$1 GROUP BY o.outfit_id`,[contextId]);return result.rows.map((row)=>({id:row.id,score:Number(row.score),grade:row.grade,garments:row.garments}))}
  public async history(before:string):Promise<readonly PriorAssignment[]>{const result=await this.pool.query(`SELECT p.planned_date date,p.saved_outfit_id outfit_id,jsonb_agg(jsonb_build_object('id',i.garment_id,'slotId',i.slot_id) ORDER BY i.position) garments FROM dressed.planned_outfits p JOIN dressed.saved_outfit_items i ON i.outfit_id=p.saved_outfit_id WHERE p.status='worn' AND p.planned_date<$1 GROUP BY p.planned_outfit_id ORDER BY p.planned_date`,[before]);return result.rows.map((row)=>({date:String(row.date).slice(0,10),outfitId:row.outfit_id,garments:row.garments}))}
  public async create(input:{id:string;name:string;startDate:string;endDate:string;contextId:string;policyId:string;weekdays:readonly number[];fixedGarmentIds:readonly string[];excludedGarmentIds:readonly string[];assignments:readonly RotationAssignment[];timestamp:string}){const client=await this.pool.connect();try{await client.query("BEGIN");await client.query("INSERT INTO dressed.outfit_plans(plan_id,name,start_date,end_date,context_id,policy_id,weekdays,fixed_garment_ids,excluded_garment_ids,created_at) VALUES($1,$2,$3,$4,$5,$6,$7::smallint[],$8::uuid[],$9::uuid[],$10)",[input.id,input.name,input.startDate,input.endDate,input.contextId,input.policyId,input.weekdays,input.fixedGarmentIds,input.excludedGarmentIds,input.timestamp]);for(const assignment of input.assignments)await client.query("INSERT INTO dressed.planned_outfits(planned_outfit_id,plan_id,planned_date,saved_outfit_id,rotation_score,rotation_explanation,created_at,updated_at) VALUES(gen_random_uuid(),$1,$2,$3,$4,$5::jsonb,$6,$6)",[input.id,assignment.date,assignment.outfitId,assignment.rotationScore,JSON.stringify(assignment.explanations),input.timestamp]);await client.query("COMMIT");return{id:input.id,entries:input.assignments.length}}catch(error){await client.query("ROLLBACK");throw error}finally{client.release()}}
  public async plans(){const result=await this.pool.query(`SELECT p.plan_id id,p.name,p.start_date,p.end_date,c.name context_name,COUNT(e.planned_outfit_id)::int entry_count,jsonb_agg(jsonb_build_object('id',e.planned_outfit_id,'date',e.planned_date,'status',e.status,'outfitId',o.outfit_id,'outfitName',o.name,'grade',COALESCE(o.user_grade,o.calculated_grade),'rotationScore',e.rotation_score,'explanations',e.rotation_explanation) ORDER BY e.planned_date) FILTER(WHERE e.planned_outfit_id IS NOT NULL) entries FROM dressed.outfit_plans p JOIN dressed.outfit_contexts c ON c.context_id=p.context_id LEFT JOIN dressed.planned_outfits e ON e.plan_id=p.plan_id LEFT JOIN dressed.saved_outfits o ON o.outfit_id=e.saved_outfit_id GROUP BY p.plan_id,c.name ORDER BY p.created_at DESC`);return result.rows.map((row)=>({id:row.id,name:row.name,startDate:String(row.start_date).slice(0,10),endDate:String(row.end_date).slice(0,10),contextName:row.context_name,entryCount:row.entry_count,entries:row.entries??[]}))}
  public async updateEntry(id:string,input:{status?:"planned"|"skipped"|undefined;plannedDate?:string|undefined;notes?:string|null|undefined},timestamp:string){const result=await this.pool.query("UPDATE dressed.planned_outfits SET status=COALESCE($2,status),planned_date=COALESCE($3,planned_date),notes=CASE WHEN $4::boolean THEN $5 ELSE notes END,updated_at=$6 WHERE planned_outfit_id=$1 RETURNING planned_outfit_id id,planned_date,status,notes",[id,input.status??null,input.plannedDate??null,Object.hasOwn(input,"notes"),input.notes??null,timestamp]);return result.rows[0]??null}
}
