import type { Pool } from "pg";
import type { RuleParameters, StylingContext, StylingEvaluation, StylingGarment } from "../../domain/outfit/styling-engine.js";

export class StylingRepository {
  public constructor(private readonly pool:Pool){}
  public async catalogue(){const ruleSet=await this.pool.query("SELECT rule_set_id,name,version,grade_a_threshold,grade_b_threshold,grade_c_threshold FROM dressed.styling_rule_sets WHERE status='active'");const contexts=await this.pool.query("SELECT context_id,slug,name,formality_min,formality_max,configuration FROM dressed.outfit_contexts WHERE is_active ORDER BY formality_min DESC,name");const row=ruleSet.rows[0];if(!row)throw new Error("active_rule_set_missing");return{ruleSet:{id:row.rule_set_id,name:row.name,version:row.version,thresholds:{a:Number(row.grade_a_threshold),b:Number(row.grade_b_threshold),c:Number(row.grade_c_threshold)}},contexts:contexts.rows.map((value)=>({id:value.context_id,slug:value.slug,name:value.name,formalityMin:value.formality_min,formalityMax:value.formality_max,configuration:value.configuration}))};}
  public async parameters(ruleSetId:string):Promise<RuleParameters>{const result=await this.pool.query<{rule_id:string;parameters:Record<string,number>}>("SELECT rule_id,parameters FROM dressed.styling_rules WHERE rule_set_id=$1 AND enabled ORDER BY sort_order",[ruleSetId]);return Object.freeze(Object.fromEntries(result.rows.map((row)=>[row.rule_id,Object.freeze(row.parameters)])));}
  public async garments(ids:readonly string[]):Promise<readonly StylingGarment[]>{const result=await this.pool.query(`SELECT g.garment_id,g.name,g.lifecycle_status,g.formality,c.slug,COALESCE(array_agg(DISTINCT s.season) FILTER(WHERE s.season IS NOT NULL),'{}') AS seasons,f.fingerprint_id,f.measurement_payload
    FROM dressed.garments g JOIN dressed.garment_categories c ON c.category_id=g.category_id LEFT JOIN dressed.garment_seasons s ON s.garment_id=g.garment_id LEFT JOIN dressed.visual_fingerprints f ON f.garment_id=g.garment_id AND f.is_current WHERE g.garment_id=ANY($1::uuid[]) GROUP BY g.garment_id,c.slug,f.fingerprint_id,f.measurement_payload`,[ids]);return result.rows.map((row)=>({id:row.garment_id,name:row.name,categorySlug:row.slug,status:row.lifecycle_status,formality:row.formality,seasons:row.seasons,fingerprintId:row.fingerprint_id,fingerprint:row.measurement_payload}))}
  public async save(input:{id:string;ruleSetId:string;context:StylingContext;season:string|null;garments:readonly StylingGarment[];evaluation:StylingEvaluation;timestamp:string}){const client=await this.pool.connect();try{await client.query("BEGIN");await client.query("INSERT INTO dressed.styling_evaluations(evaluation_id,rule_set_id,context_id,numerical_score,grade,eligible,requested_season,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8)",[input.id,input.ruleSetId,input.context.id,input.evaluation.score,input.evaluation.grade,input.evaluation.eligible,input.season,input.timestamp]);for(const garment of input.garments)if(garment.fingerprintId)await client.query("INSERT INTO dressed.styling_evaluation_items(evaluation_id,garment_id,fingerprint_id) VALUES($1,$2,$3)",[input.id,garment.id,garment.fingerprintId]);for(const[index,value]of input.evaluation.outcomes.entries())await client.query(`INSERT INTO dressed.styling_rule_outcomes(evaluation_id,outcome_index,rule_id,domain,passed,hard_failure,score_delta,explanation_code,explanation,affected_garment_ids,measurements) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10::uuid[],$11::jsonb)`,[input.id,index,value.ruleId,value.domain,value.passed,value.hardFailure,value.scoreDelta,value.explanationCode,value.explanation,value.affectedGarmentIds,JSON.stringify(value.measurements)]);await client.query("COMMIT");}catch(error){await client.query("ROLLBACK");throw error}finally{client.release()}}
}
