'use strict';
const appScope=require('../../shared/services/appScope');
const ALGORITHM_VERSION='ela-rules-1';
const FUNCTIONS={recall:['identify','name','define','recall','list'],comprehension:['describe','explain','summarize','paraphrase'],analysis:['analyze','compare','contrast','infer','interpret','distinguish','evaluate'],application:['apply','use','demonstrate','solve'],creation:['create','compose','develop','design','write'],evidence:['cite','support','justify','evidence','quote']};
const STOP=new Set('a an and are as at be by for from in into is it of on or that the their this to with'.split(' '));
function scope(r){return appScope.fromRequest(r)} function txt(v){return String(v==null?'':v).trim()} function bad(message,code='VALIDATION_ERROR',statusCode=400){return{success:false,statusCode,error:{code,message}}}
function terms(value){return [...new Set(txt(value).toLowerCase().replace(/[^a-z0-9 -]/g,' ').split(/\s+/).filter(x=>x.length>3&&!STOP.has(x)))];}
function functions(value){const lower=txt(value).toLowerCase(),out=[];for(const [key,verbs] of Object.entries(FUNCTIONS))if(verbs.some(v=>new RegExp(`\\b${v}(?:s|ed|ing)?\\b`).test(lower)))out.push(key);return out.length?out:['comprehension'];}
function hydrate(c,row){if(!row)return row;row.nodes=c.db.query('SELECT * FROM standards_ontology_nodes WHERE build_id=? ORDER BY node_type,label',[row.id]).rows;row.relations=c.db.query('SELECT * FROM standards_ontology_relations WHERE build_id=? ORDER BY id',[row.id]).rows;return row}
function boot(c){c.log.info('standards ontology consumable ready',{module:'ontology_engine',algorithm:ALGORITHM_VERSION})} function teardown(){}
function on_standards_repository_framework_verified(payload,c){const row=payload&&payload.record;if(row)c.log.info('verified standards framework is ready for an explicit ontology build',{module:'ontology_engine',frameworkId:row.id});}
async function listBuilds(r,c){const s=scope(r),rows=c.db.query('SELECT b.*,f.code framework_code,f.name framework_name FROM standards_ontology_builds b JOIN standards_repository_frameworks f ON f.id=b.framework_id WHERE b.app_id=? ORDER BY b.id DESC',[s]).rows;return{success:true,builds:rows}}
async function read(r,c){const row=c.db.query('SELECT * FROM standards_ontology_builds WHERE id=? AND app_id=?',[r.params.id,scope(r)]).rows[0];return row?{success:true,build:hydrate(c,row)}:bad('Ontology build not found','NOT_FOUND',404)}
async function build(r,c){const s=scope(r),framework=c.db.query("SELECT * FROM standards_repository_frameworks WHERE id=? AND app_id=? AND status='active'",[r.params.id,s]).rows[0];if(!framework)return bad('Only a verified, active standards framework can be built into the ontology','FRAMEWORK_NOT_ACTIVE',409);const statements=c.db.query("SELECT * FROM standards_repository_statements WHERE framework_id=? AND verification_status='verified' ORDER BY sequence,id",[framework.id]).rows;if(!statements.length)return bad('No verified standards statements are available','NO_VERIFIED_STATEMENTS',409);const version=1+(+c.db.query('SELECT COALESCE(MAX(version),0) n FROM standards_ontology_builds WHERE app_id=? AND framework_id=?',[s,framework.id]).rows[0].n);let buildId;
 c.db.transaction(db=>{db.query("UPDATE standards_ontology_builds SET status='superseded' WHERE app_id=? AND framework_id=? AND status='ready'",[s,framework.id]);buildId=db.query('INSERT INTO standards_ontology_builds(app_id,framework_id,version,algorithm_version,built_by) VALUES(?,?,?,?,?)',[s,framework.id,version,ALGORITHM_VERSION,String(r.user.id)]).lastInsertRowid;const nodeIds=new Map();const add=(type,key,label,description,statementId,aliases=[],provenance={})=>{const mapKey=type+':'+key;if(nodeIds.has(mapKey))return nodeIds.get(mapKey);const id=db.query('INSERT INTO standards_ontology_nodes(build_id,framework_id,statement_id,node_type,canonical_key,label,description,aliases_json,provenance_json) VALUES(?,?,?,?,?,?,?,?,?)',[buildId,framework.id,statementId||null,type,key,label,description||null,JSON.stringify(aliases),JSON.stringify(provenance)]).lastInsertRowid;nodeIds.set(mapKey,id);return id};const relate=(a,b,type,rationale,provenance={})=>db.query('INSERT OR IGNORE INTO standards_ontology_relations(build_id,source_node_id,target_node_id,relation_type,rationale,provenance_json) VALUES(?,?,?,?,?,?)',[buildId,a,b,type,rationale,JSON.stringify(provenance)]);
  for(const st of statements){const std=add('standard',st.code,st.code,st.statement,st.id,[],{statement_id:st.id,source_page:st.source_page});for(const [type,val] of [['domain',st.domain],['strand',st.strand],['grade',st.grade_label]])if(txt(val)){const n=add(type,txt(val).toLowerCase(),txt(val),null,null);relate(n,std,'contains',`${type} groups this standard`,{statement_id:st.id})}for(const fn of functions(st.statement)){const n=add('function',fn,fn[0].toUpperCase()+fn.slice(1),`Cognitive function inferred from explicit standards verbs.`,null,FUNCTIONS[fn]);relate(std,n,'expresses','Explicit verb rule matched the standards statement',{statement_id:st.id,algorithm:ALGORITHM_VERSION})}for(const term of terms([st.domain,st.strand,st.statement].join(' ')).slice(0,12)){const n=add('concept',term,term,null,null);relate(std,n,'requires','Deterministic keyword extraction from the verified statement',{statement_id:st.id,algorithm:ALGORITHM_VERSION})}}
  for(const st of statements)if(st.parent_id){const child=nodeIds.get('standard:'+st.code),parentStatement=statements.find(x=>x.id===st.parent_id),parent=parentStatement&&nodeIds.get('standard:'+parentStatement.code);if(child&&parent){relate(parent,child,'broader_than','Relationship copied from the verified source hierarchy',{statement_id:st.id});relate(child,parent,'narrower_than','Relationship copied from the verified source hierarchy',{statement_id:st.id})}}const n=+db.query('SELECT COUNT(*) n FROM standards_ontology_nodes WHERE build_id=?',[buildId]).rows[0].n,rel=+db.query('SELECT COUNT(*) n FROM standards_ontology_relations WHERE build_id=?',[buildId]).rows[0].n;db.query("UPDATE standards_ontology_builds SET status='ready',statement_count=?,node_count=?,relation_count=?,completed_at=datetime('now') WHERE id=?",[statements.length,n,rel,buildId])});const row=hydrate(c,c.db.query('SELECT * FROM standards_ontology_builds WHERE id=?',[buildId]).rows[0]);c.events.publish('ontology.build_completed',{entityId:row.id,record:row,__module:'ontology_engine'});return{success:true,build:row}}
async function query(r,c){const s=scope(r),b=r.body||{},frameworkIds=(Array.isArray(b.framework_ids)?b.framework_ids:[b.framework_id]).filter(Boolean);if(!frameworkIds.length)return bad('Choose at least one standards framework');const tokens=terms([b.text,b.construct,b.function].join(' '));if(!tokens.length)return bad('Provide text, a construct or a function to query');const marks=frameworkIds.map(()=>'?').join(','),builds=c.db.query(`SELECT * FROM standards_ontology_builds WHERE app_id=? AND status='ready' AND framework_id IN (${marks}) ORDER BY version DESC`,[s].concat(frameworkIds)).rows,latest=[...new Map(builds.map(x=>[x.framework_id,x])).values()];const results=[];for(const build of latest){const nodes=c.db.query("SELECT * FROM standards_ontology_nodes WHERE build_id=? AND node_type IN ('standard','concept','function')",[build.id]).rows;const byId=new Map(nodes.map(n=>[n.id,n]));for(const standard of nodes.filter(n=>n.node_type==='standard')){const linked=c.db.query("SELECT r.*,n.node_type,n.canonical_key,n.label FROM standards_ontology_relations r JOIN standards_ontology_nodes n ON n.id=r.target_node_id WHERE r.build_id=? AND r.source_node_id=?",[build.id,standard.id]).rows;const hay=terms([standard.label,standard.description,...linked.map(x=>x.canonical_key)].join(' ')),matches=tokens.filter(t=>hay.some(h=>h===t||h.includes(t)||t.includes(h)));if(matches.length)results.push({framework_id:build.framework_id,build_id:build.id,statement_id:standard.statement_id,standard_code:standard.canonical_key,standard_text:standard.description,matched_terms:matches,score:+(matches.length/tokens.length).toFixed(3),functions:linked.filter(x=>x.node_type==='function').map(x=>x.canonical_key),concepts:linked.filter(x=>x.node_type==='concept').map(x=>x.canonical_key)})}}
 results.sort((a,b)=>b.score-a.score||a.standard_code.localeCompare(b.standard_code));return{success:true,authority:'advisory_only',method:'deterministic_verified_ontology',human_confirmation_required:true,results:results.slice(0,Math.min(50,+b.limit||10))}}
module.exports={boot,teardown,listBuilds,read,build,query,on_standards_repository_framework_verified,_rules:{terms,functions}};
