'use strict';

const PROGRAMME_STATUSES=Object.freeze(['draft','configured','active','closed','withdrawn','archived']);
const OPERATING_MODES=Object.freeze(['before_school','timetabled','off_timetable','after_school','mixed']);
const RESPONDENT_MODES=Object.freeze(['student','student_parent','student_teacher','student_parent_teacher']);
const SOURCE_CHANNELS=Object.freeze(['native','public_link','google_forms','csv']);
const SETUP_STEPS=Object.freeze(['purpose','timing','location','participation','governance']);
const PARTICIPANT_SCOPES=Object.freeze(['single_class','single_grade','cross_class','cross_grade','open','custom']);
const LOCATION_STRATEGIES=Object.freeze(['scheduler_assigned','select_from_scheduler_availability','mixed']);
const SUBMITTER_ROLES=Object.freeze(['student','parent','teacher']);

function required(value,field){if(typeof value!=='string'||!value.trim())throw new Error(field+' is required');}
function positiveInteger(value,field){if(!Number.isInteger(+value)||+value<1)throw new Error(field+' must be a positive integer');}
function validateProgramme(value){if(!value||typeof value!=='object')throw new Error('programme is required');required(value.external_key,'external_key');required(value.name,'name');required(value.programme_type,'programme_type');positiveInteger(value.academic_year_id,'academic_year_id');if(value.status!=null&&!PROGRAMME_STATUSES.includes(value.status))throw new Error('unsupported programme status');if(value.operating_mode!=null&&!OPERATING_MODES.includes(value.operating_mode))throw new Error('unsupported operating mode');if(value.respondent_mode!=null&&!RESPONDENT_MODES.includes(value.respondent_mode))throw new Error('unsupported respondent mode');return value;}
function canRevise(status){return status==='draft'||status==='configured';}

function object(value,field){if(!value||typeof value!=='object'||Array.isArray(value))throw new Error(field+' must be an object');return value;}
function strings(value,field,{required:must=false,allowed}={}){if(value==null&&!must)return[];if(!Array.isArray(value)||(must&&!value.length)||value.some(x=>typeof x!=='string'||!x.trim()))throw new Error(field+' must be '+(must?'a non-empty ':'an ')+'array of strings');const result=[...new Set(value.map(x=>x.trim()))];if(allowed&&result.some(x=>!allowed.includes(x)))throw new Error(field+' contains an unsupported value');return result;}
function validateSetupStep(step,input){const value=object(input,step);if(step==='purpose'){required(value.summary,'summary');required(value.intended_outcome,'intended_outcome');return{summary:value.summary.trim(),intended_outcome:value.intended_outcome.trim(),programme_categories:strings(value.programme_categories,'programme_categories'),notes:typeof value.notes==='string'?value.notes.trim():''};}if(step==='timing'){positiveInteger(value.scheduler_setup_id,'scheduler_setup_id');const ids=strings(value.scheduler_window_ids,'scheduler_window_ids',{required:true}).map(String);return{scheduler_setup_id:+value.scheduler_setup_id,scheduler_window_ids:ids,delivery_notes:typeof value.delivery_notes==='string'?value.delivery_notes.trim():''};}if(step==='location'){if(!LOCATION_STRATEGIES.includes(value.strategy))throw new Error('unsupported location strategy');return{strategy:value.strategy,requirements:strings(value.requirements,'requirements'),notes:typeof value.notes==='string'?value.notes.trim():''};}if(step==='participation'){if(!PARTICIPANT_SCOPES.includes(value.scope))throw new Error('unsupported participant scope');if(value.respondent_mode!=null&&!RESPONDENT_MODES.includes(value.respondent_mode))throw new Error('unsupported respondent mode');return{participant_type:value.participant_type||'student',scope:value.scope,respondent_mode:value.respondent_mode||'student',scope_notes:typeof value.scope_notes==='string'?value.scope_notes.trim():''};}if(step==='governance'){const submitters=strings(value.submitter_roles,'submitter_roles',{required:true,allowed:SUBMITTER_ROLES}),amenders=strings(value.amendment_roles,'amendment_roles',{allowed:SUBMITTER_ROLES}),editors=strings(value.manual_edit_roles,'manual_edit_roles',{required:true});if(amenders.some(x=>!submitters.includes(x)))throw new Error('amendment roles must also be submitter roles');return{owner_staff_ids:strings(value.owner_staff_ids,'owner_staff_ids'),submitter_roles:submitters,amendment_roles:amenders,manual_edit_roles:editors,human_confirmation_required:true,notes:typeof value.notes==='string'?value.notes.trim():''};}throw new Error('unsupported setup step');}

module.exports={PROGRAMME_STATUSES,OPERATING_MODES,RESPONDENT_MODES,SOURCE_CHANNELS,SETUP_STEPS,PARTICIPANT_SCOPES,LOCATION_STRATEGIES,SUBMITTER_ROLES,validateProgramme,validateSetupStep,canRevise};
