'use strict';

const SCOPE_TYPES=Object.freeze(['school','section','programme','grade','custom']);
const AVAILABILITY_STATES=Object.freeze(['available','unavailable','preferred','discouraged','conditional']);
const CONSTRAINT_LEVELS=Object.freeze(['hard','soft','advisory']);
const REQUIREMENT_STATUSES=Object.freeze(['draft','active','withdrawn']);
const PLACEMENT_STATUSES=Object.freeze(['proposed','locked','validated','published','cancelled','superseded']);
const SCHEDULE_STATUSES=Object.freeze(['draft','generated','validated','submitted','approved','published','rejected','superseded']);
const PROVIDERS=Object.freeze({programme_manager:'programme_manager',teacher_preferences:'teacher_preferences',cover:'cover',calendar:'calendar',rooms:'room_registry',resources:'inventory'});
const EVENTS=Object.freeze(['scheduling_requirement.created','scheduling_requirement.updated','scheduling_requirement.withdrawn','schedule.generated','schedule.validated','schedule.submitted','schedule.approved','schedule.rejected','schedule.published','schedule.superseded','scheduled_lesson.created','scheduled_lesson.updated','scheduled_lesson.cancelled']);

function requiredString(value,field){if(typeof value!=='string'||!value.trim())throw new Error(field+' is required')}
function positive(value,field){if(!Number.isFinite(+value)||+value<=0)throw new Error(field+' must be positive')}
function iso(value,field){requiredString(value,field);if(Number.isNaN(Date.parse(value)))throw new Error(field+' must be an ISO date or instant')}

function validateScope(value){if(!value||typeof value!=='object')throw new Error('scope is required');if(!SCOPE_TYPES.includes(value.type))throw new Error('unsupported scope type');requiredString(value.id,'scope.id');return value}
function validateCycle(value){if(!value||typeof value!=='object')throw new Error('cycle is required');positive(value.week_count,'cycle.week_count');if(+value.week_count>52)throw new Error('cycle.week_count must not exceed 52');if(!Array.isArray(value.week_labels)||value.week_labels.length!==+value.week_count)throw new Error('cycle.week_labels must match week_count');value.week_labels.forEach((x,i)=>requiredString(x,'cycle.week_labels['+i+']'));return value}
function validatePeriodTemplate(value){if(!value||typeof value!=='object')throw new Error('period template is required');requiredString(value.external_key,'external_key');requiredString(value.name,'name');positive(value.duration_minutes,'duration_minutes');if(value.multiplier!=null)positive(value.multiplier,'multiplier');return value}
function validateRequirement(value){if(!value||typeof value!=='object')throw new Error('requirement is required');requiredString(value.external_key,'external_key');requiredString(value.academic_year_id,'academic_year_id');requiredString(value.teaching_group_external_key,'teaching_group_external_key');requiredString(value.name,'name');positive(value.occurrences_per_cycle,'occurrences_per_cycle');positive(value.duration_minutes,'duration_minutes');if(value.status!=null&&!REQUIREMENT_STATUSES.includes(value.status))throw new Error('unsupported requirement status');if(value.valid_from)iso(value.valid_from,'valid_from');if(value.valid_to)iso(value.valid_to,'valid_to');if(value.valid_from&&value.valid_to&&Date.parse(value.valid_from)>Date.parse(value.valid_to))throw new Error('valid_from must not follow valid_to');for(const field of ['eligible_staff_ids','eligible_room_ids','eligible_resource_ids','allowed_period_template_keys'])if(value[field]!=null&&!Array.isArray(value[field]))throw new Error(field+' must be an array');return value}
function validateAvailability(value){if(!value||typeof value!=='object')throw new Error('availability is required');requiredString(value.external_key,'external_key');requiredString(value.entity_type,'entity_type');requiredString(value.entity_id,'entity_id');if(!AVAILABILITY_STATES.includes(value.state))throw new Error('unsupported availability state');if(value.week_index!=null&&(!Number.isInteger(+value.week_index)||+value.week_index<1))throw new Error('week_index must be a positive integer');if(value.starts_at)iso(value.starts_at,'starts_at');if(value.ends_at)iso(value.ends_at,'ends_at');if(value.starts_at&&value.ends_at&&Date.parse(value.starts_at)>=Date.parse(value.ends_at))throw new Error('starts_at must precede ends_at');return value}
function validateConstraint(value){if(!value||typeof value!=='object')throw new Error('constraint is required');requiredString(value.code,'code');requiredString(value.name,'name');if(!CONSTRAINT_LEVELS.includes(value.level))throw new Error('unsupported constraint level');validateScope(value.scope);if(value.weight!=null&&(!Number.isFinite(+value.weight)||+value.weight<0))throw new Error('weight must be non-negative');requiredString(value.explanation_template,'explanation_template');return value}
function validatePlacement(value){if(!value||typeof value!=='object')throw new Error('placement is required');requiredString(value.external_key,'external_key');requiredString(value.schedule_version_id,'schedule_version_id');requiredString(value.requirement_external_key,'requirement_external_key');requiredString(value.teaching_group_external_key,'teaching_group_external_key');if(!Number.isInteger(+value.week_index)||+value.week_index<1)throw new Error('week_index must be a positive integer');if(!Number.isInteger(+value.day_index)||+value.day_index<1||+value.day_index>7)throw new Error('day_index must be between 1 and 7');requiredString(value.start_time,'start_time');requiredString(value.end_time,'end_time');if(value.status!=null&&!PLACEMENT_STATUSES.includes(value.status))throw new Error('unsupported placement status');return value}
function validateEnvelope(channel,payload){if(!EVENTS.includes(channel))throw new Error('unsupported scheduler event');if(!payload||typeof payload!=='object')throw new Error('event payload is required');requiredString(payload.event_id,'event_id');iso(payload.occurred_at,'occurred_at');requiredString(payload.source,'source');requiredString(payload.schedule_version_id,'schedule_version_id');return payload}
function requirementIdentity(value){validateRequirement(value);return[value.academic_year_id,value.external_key].join(':')}
function placementIdentity(value){validatePlacement(value);return[value.schedule_version_id,value.external_key].join(':')}
function rankOutcome(outcome){outcome=outcome||{};const hard=+(outcome.hard_violations||0),soft=+(outcome.soft_penalty||0),advisory=+(outcome.advisory_count||0),unplaced=+(outcome.unplaced_requirements||0);return{feasible:hard===0,score:hard*1e12+unplaced*1e9+soft*1e3+advisory,breakdown:{hard_violations:hard,unplaced_requirements:unplaced,soft_penalty:soft,advisory_count:advisory}}}

module.exports={SCOPE_TYPES,AVAILABILITY_STATES,CONSTRAINT_LEVELS,REQUIREMENT_STATUSES,PLACEMENT_STATUSES,SCHEDULE_STATUSES,PROVIDERS,EVENTS,validateScope,validateCycle,validatePeriodTemplate,validateRequirement,validateAvailability,validateConstraint,validatePlacement,validateEnvelope,requirementIdentity,placementIdentity,rankOutcome};
