'use strict';

const DOMAINS=Object.freeze(['grade_level','subject','elective','activity','role']);
const STANCES=Object.freeze(['prefer','avoid','declared_restriction']);
const REVIEW_STATES=Object.freeze(['not_required','pending','confirmed','declined','expired']);
const STATUSES=Object.freeze(['draft','active','withdrawn','superseded']);
const CONFIDENCE_LEVELS=Object.freeze(['low','medium','high']);

function required(value,field){if(typeof value!=='string'||!value.trim())throw new Error(field+' is required');}
function iso(value,field){required(value,field);if(Number.isNaN(Date.parse(value)))throw new Error(field+' must be an ISO date or instant');}
function validateCycle(value){if(!value||typeof value!=='object')throw new Error('preference cycle is required');required(value.external_key,'external_key');required(value.name,'name');required(String(value.academic_year_id||''),'academic_year_id');if(value.opens_at)iso(value.opens_at,'opens_at');if(value.closes_at)iso(value.closes_at,'closes_at');if(value.opens_at&&value.closes_at&&Date.parse(value.opens_at)>Date.parse(value.closes_at))throw new Error('opens_at must not follow closes_at');return value;}
function validateEntry(value){if(!value||typeof value!=='object')throw new Error('preference entry is required');required(value.external_key,'external_key');required(String(value.staff_id||''),'staff_id');if(!DOMAINS.includes(value.domain))throw new Error('unsupported preference domain');if(!STANCES.includes(value.stance))throw new Error('unsupported preference stance');required(value.target_key,'target_key');required(value.target_label,'target_label');if(value.rank!=null&&(!Number.isInteger(+value.rank)||+value.rank<1||+value.rank>99))throw new Error('rank must be an integer between 1 and 99');if(value.confidence!=null&&!CONFIDENCE_LEVELS.includes(value.confidence))throw new Error('unsupported confidence level');if(value.status!=null&&!STATUSES.includes(value.status))throw new Error('unsupported preference status');if(value.review_state!=null&&!REVIEW_STATES.includes(value.review_state))throw new Error('unsupported review state');if(value.stance!=='declared_restriction'&&value.review_state&&!['not_required'].includes(value.review_state))throw new Error('only declared restrictions may require review');if(value.valid_from)iso(value.valid_from,'valid_from');if(value.valid_to)iso(value.valid_to,'valid_to');if(value.valid_from&&value.valid_to&&Date.parse(value.valid_from)>Date.parse(value.valid_to))throw new Error('valid_from must not follow valid_to');return value;}
function advisoryWeight(value){validateEntry(value);if(value.stance==='declared_restriction')return 0;const rank=Math.max(1,+value.rank||1),confidence={low:.5,medium:.75,high:1}[value.confidence||'medium'];return Math.round((value.stance==='avoid'?-1:1)*(100/rank)*confidence*100)/100;}
function providerRecord(value,version){validateEntry(value);return{record_type:'teacher_preference',external_key:value.external_key,provider_version:String(version||1),effective_from:value.valid_from||null,effective_to:value.valid_to||null,status:value.status==='active'?'active':'withdrawn',payload:{staff_id:String(value.staff_id),domain:value.domain,stance:value.stance,target_key:value.target_key,target_label:value.target_label,rank:value.rank||null,confidence:value.confidence||'medium',review_state:value.review_state||(value.stance==='declared_restriction'?'pending':'not_required'),advisory_weight:advisoryWeight(value)}};}

module.exports={DOMAINS,STANCES,REVIEW_STATES,STATUSES,CONFIDENCE_LEVELS,validateCycle,validateEntry,advisoryWeight,providerRecord};
