import { randomUUID } from "node:crypto";
import type { Pool } from "pg";
import type { ExchangeCandle, ExchangeTicker24h, ExchangeTopOfBook } from "../../domain/exchange/types.js";
import type { AsianRange, SessionBoundaries } from "../../domain/exchange/session-engine.js";
export class ExchangeMarketDataRepository {
  public constructor(private readonly pool: Pick<Pool,"query">, private readonly continuitySegment=randomUUID()) {}
  public async saveCandle(c:ExchangeCandle,source:"websocket"|"rest_backfill"="websocket"):Promise<void>{ await this.pool.query(`INSERT INTO exchange_candles(venue,venue_symbol,interval,open_time,close_time,event_time,received_at,open,high,low,close,base_volume,quote_volume,trade_count,is_closed,source,continuity_segment,fingerprint) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18) ON CONFLICT(venue,venue_symbol,interval,open_time) DO UPDATE SET close_time=EXCLUDED.close_time,event_time=EXCLUDED.event_time,received_at=EXCLUDED.received_at,open=EXCLUDED.open,high=EXCLUDED.high,low=EXCLUDED.low,close=EXCLUDED.close,base_volume=EXCLUDED.base_volume,quote_volume=EXCLUDED.quote_volume,trade_count=EXCLUDED.trade_count,is_closed=EXCLUDED.is_closed,source=EXCLUDED.source,continuity_segment=EXCLUDED.continuity_segment,fingerprint=EXCLUDED.fingerprint WHERE exchange_candles.is_closed=false`,[c.venue,c.venueSymbol,c.interval,c.openTime,c.closeTime,c.eventTime,c.receivedAt,c.open,c.high,c.low,c.close,c.baseVolume,c.quoteVolume,c.trades,c.closed,source,this.continuitySegment,c.fingerprint]); }
  public async saveBook(b:ExchangeTopOfBook):Promise<void>{ await this.pool.query(`INSERT INTO exchange_top_of_book(venue,venue_symbol,event_time,received_at,bid_price,bid_quantity,ask_price,ask_quantity,continuity_segment,fingerprint) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,md5($10)) ON CONFLICT DO NOTHING`,[b.venue,b.venueSymbol,b.eventTime,b.receivedAt,b.bidPrice,b.bidQuantity,b.askPrice,b.askQuantity,this.continuitySegment,JSON.stringify(b)]); }
  public async saveTicker(t:ExchangeTicker24h):Promise<void>{ await this.pool.query(`INSERT INTO exchange_ticker_24h(venue,venue_symbol,event_time,received_at,high,low,base_volume,quote_volume,continuity_segment,fingerprint) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,md5($10)) ON CONFLICT DO NOTHING`,[t.venue,t.venueSymbol,t.eventTime,t.receivedAt,t.high,t.low,t.baseVolume,t.quoteVolume,this.continuitySegment,JSON.stringify(t)]); }
  public async saveAsianRange(venue:string,symbol:string,b:SessionBoundaries,r:AsianRange,verifiedAt:Date):Promise<void>{ const f=`${b.civilDate}:${r.status}:${r.high}:${r.low}:${r.contributingCandles}`; await this.pool.query(`INSERT INTO exchange_session_levels(id,epoch_id,venue,venue_symbol,civil_date,time_zone,level_type,window_start,window_end,status,high,low,contributing_candles,calculation_fingerprint,last_verified_at) VALUES($1,current_paper_validation_epoch_id(),$2,$3,$4,'America/New_York','asian_range',$5,$6,$7,$8,$9,$10,$11,$12) ON CONFLICT(venue,venue_symbol,civil_date,level_type,version) DO UPDATE SET status=EXCLUDED.status,high=EXCLUDED.high,low=EXCLUDED.low,contributing_candles=EXCLUDED.contributing_candles,calculation_fingerprint=EXCLUDED.calculation_fingerprint,last_verified_at=EXCLUDED.last_verified_at`,[randomUUID(),venue,symbol,b.civilDate,b.asianStart,b.asianEnd,r.status,r.high,r.low,r.contributingCandles,f,verifiedAt]); }
}
