import {handoffState} from './selected-context.mjs';
import React,{useEffect,useRef,useState} from 'react';
import {labelPolicy} from './label-policy.mjs';
import {title,encoding} from './model.mjs';
import {visibleEdges,nodeColor} from './semantic-layout.mjs';
export default function Network2D({graph,geography,model,selected,onSelect,onEdge,onGap,cameraMemory,action,colourBy='role',showCompanionLines=false,context=null,familyExpanded=false}) {
  const [callouts,setCallouts]=useState([]),[hovered,setHovered]=useState(''),hoverId=useRef('');
  const canvas=useRef(),drawRef=useRef(),hit=useRef({nodes:[],edges:[],gaps:[]}),drag=useRef(),view=useRef(cameraMemory.current||{x:0,y:0,scale:.55}),[hover,setHover]=useState('');
  useEffect(()=>{const c=canvas.current,ctx=c.getContext('2d');const stop=e=>e.preventDefault();c.addEventListener('wheel',stop,{passive:false});
    const draw=()=>{const start=performance.now(),w=c.clientWidth,h=c.clientHeight,dpr=Math.min(devicePixelRatio,2);if(c.width!==w*dpr||c.height!==h*dpr){c.width=w*dpr;c.height=h*dpr;}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.fillStyle='#0c1522';ctx.fillRect(0,0,w,h);const v=view.current,point=p=>({x:w/2+v.x+p.x*v.scale,y:h/2+v.y-p.y*v.scale}),tn=new Set(graph.trail.nodes),te=new Set(graph.trail.edges),focus=!!selected&&!graph.selectedExcluded;hit.current={nodes:[],edges:[],gaps:[]};

      ctx.lineWidth=1;ctx.strokeStyle='#345361';const ids=new Set(graph.nodes.map(n=>n.id));for(const f of geography.segments){const ps=f.ids.filter(id=>ids.has(id)).map(id=>point(geography.positions2d.get(id)));if(ps.length<2)continue;const xs=ps.map(p=>p.x),ys=ps.map(p=>p.y);ctx.strokeRect(Math.min(...xs)-7,Math.min(...ys)-7,Math.max(...xs)-Math.min(...xs)+14,Math.max(...ys)-Math.min(...ys)+14);}
      const labelStyle=labelPolicy({pixelsPerUnit:v.scale,focused:geography.focused,smallScope:graph.nodes.length<=25});c.parentElement.dataset.labelDetail=labelStyle.detail;ctx.globalAlpha=labelStyle.orientationOpacity;ctx.font=(11*labelStyle.orientationScale)+'px system-ui';for(const level of geography.levels){const members=graph.nodes.filter(n=>geography.meta.get(n.id).level===level.id);if(!members.length)continue;const y=point({x:0,y:geography.focused?Math.max(...members.filter(n=>tn.has(n.id)).map(n=>geography.positions2d.get(n.id).y)):level.band*geography.levelSpacing}).y;if(!Number.isFinite(y))continue;ctx.strokeStyle='#294558';ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke();ctx.fillStyle='#a6bacb';ctx.fillText(level.label,8,y-8);}
      ctx.globalAlpha=1;const batches=new Map();
      const batch=(color,width)=>{const key=color+':'+width;if(!batches.has(key))batches.set(key,{color,width,lines:new Path2D(),arrows:new Path2D()});return batches.get(key);};
      for(const e of visibleEdges(graph,selected,showCompanionLines)){const a=point(geography.positions2d.get(e.data.from_id)),b=point(geography.positions2d.get(e.data.to_id)),style=encoding(e),active=!focus||te.has(e.id);hit.current.edges.push({a,b,id:e.id});
        if((a.x<0&&b.x<0)||(a.x>w&&b.x>w)||(a.y<0&&b.y<0)||(a.y>h&&b.y>h))continue;
        const color=active?(style.companion?(focus?'#79c9df':'#355365'):'#edbd7d'):'#1b2b3a',group=batch(color,focus&&te.has(e.id)?1.7:1),dx=b.x-a.x,dy=b.y-a.y,pieces=style.draft?Math.max(2,Math.min(8,Math.ceil(Math.hypot(dx,dy)/16))):1;
        for(let j=0;j<pieces;j++){group.lines.moveTo(a.x+dx*j/pieces,a.y+dy*j/pieces);group.lines.lineTo(a.x+dx*(j+(style.draft?.45:1))/pieces,a.y+dy*(j+(style.draft?.45:1))/pieces);}
        if(!style.symmetric){const angle=Math.atan2(dy,dx),x=a.x+dx*.76,y=a.y+dy*.76;group.arrows.moveTo(x,y);group.arrows.lineTo(x-6*Math.cos(angle-.5),y-6*Math.sin(angle-.5));group.arrows.lineTo(x-6*Math.cos(angle+.5),y-6*Math.sin(angle+.5));group.arrows.closePath();}
      }
      ctx.setLineDash([]);for(const group of batches.values()){ctx.strokeStyle=group.color;ctx.lineWidth=group.width;ctx.stroke(group.lines);ctx.fillStyle=group.color;ctx.fill(group.arrows);}
      const nodeBatches=new Map(),labels=[];
      for(const n of graph.nodes){const p=point(geography.positions2d.get(n.id)),active=!focus||tn.has(n.id),r=n.id===selected?7:active?3.5:2;hit.current.nodes.push({...p,id:n.id});if(p.x<-10||p.x>w+10||p.y<-10||p.y>h+10)continue;const color=n.id===selected?'#fff':active?nodeColor(model,n,colourBy):'#233343';if(!nodeBatches.has(color))nodeBatches.set(color,new Path2D());const path=nodeBatches.get(color);path.moveTo(p.x+r,p.y);path.arc(p.x,p.y,r,0,Math.PI*2);if(n.id===selected||context?.directIds.has(n.id)||familyExpanded&&context?.familyIds.has(n.id)||!selected&&(graph.nodes.length<=25||v.scale>2)&&labels.length<50)labels.push({n,p});}
      for(const [color,path] of nodeBatches){ctx.fillStyle=color;ctx.fill(path);}ctx.font='12px system-ui';
      graph.gaps.forEach((g,i)=>{const a=point(geography.positions2d.get(g.responsibility_id)),angle=i*2.399963,p={x:a.x+30*Math.cos(angle),y:a.y+30*Math.sin(angle)};ctx.strokeStyle='#f2b8dc';ctx.setLineDash([3,5]);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(p.x,p.y);ctx.stroke();ctx.setLineDash([]);ctx.beginPath();ctx.moveTo(p.x,p.y-7);ctx.lineTo(p.x+7,p.y);ctx.lineTo(p.x,p.y+7);ctx.lineTo(p.x-7,p.y);ctx.closePath();ctx.stroke();hit.current.gaps.push({...p,id:g.id});});
      if(!labelStyle.hideDomains&&!focus&&v.scale<1.3)for(const [id,p] of geography.centers2d){const q=point(p);ctx.globalAlpha=labelStyle.orientationOpacity;ctx.fillStyle='#a6bacb';ctx.font=(12*labelStyle.orientationScale)+'px system-ui';ctx.fillText(model.label(id).slice(0,40),q.x-50,q.y-95*v.scale);}
      const occupied=[],cards=[];const candidates=[...labels.sort((a,b)=>(a.n.id===selected?-1:b.n.id===selected?1:0)).map(({n,p})=>({id:n.id,kind:'node',p,text:(n.id===selected?'SELECTED · ':'')+n.id+' · '+model.label(n.data.role_id)+'\n'+title(n)})),...(graph.selectedGaps||[]).map(g=>({id:g.id,kind:'gap',p:point(geography.positions2d.get(g.responsibility_id)),text:g.target_role_name+'\n'+handoffState(g)+'\n'+g.evidence+' handoff → · '+g.review_status+' · Trail stops here'}))];
      for(const item of candidates){const width=item.kind==='gap'?230:190,height=item.kind==='gap'?116:90;let box;for(let y=35;y<h-height-25;y+=height+8){for(let x=12;x<w-width-8;x+=width+8){if(!occupied.some(b=>x<b.x+b.width+6&&x+width+6>b.x&&y<b.y+b.height+6&&y+height+6>b.y)){box={x,y,width,height};break;}}if(box)break;}if(!box)continue;occupied.push(box);ctx.strokeStyle='#7594a3';ctx.beginPath();ctx.moveTo(item.p.x,item.p.y);ctx.lineTo(box.x+box.width/2,box.y+box.height);ctx.stroke();cards.push({...item,...box});}setCallouts(cards);
      if(hoverId.current){const node=hit.current.nodes.find(n=>n.id===hoverId.current);if(node){ctx.strokeStyle='#ffe1a0';ctx.lineWidth=2;ctx.beginPath();ctx.arc(node.x,node.y,11,0,Math.PI*2);ctx.stroke();}}c.dataset.hoveredNode=hoverId.current;
      ctx.globalAlpha=1;c.dataset.nodes=String(graph.nodes.length);c.dataset.edges=String(graph.edges.length);c.dataset.camera=JSON.stringify(v);c.dataset.updateMs=String(performance.now()-start);cameraMemory.current={...v};
    };drawRef.current=draw;const obs=new ResizeObserver(draw);obs.observe(c);draw();return()=>{obs.disconnect();c.removeEventListener('wheel',stop);};
  },[graph,geography,model,selected,colourBy,showCompanionLines,context,familyExpanded]);
  useEffect(()=>{setHover('');const p=geography.positions2d.get(selected);if(['fit','home','cascade','focus'].includes(action.type)&&graph.nodes.length){const ps=(selected&&['cascade','focus'].includes(action.type)?(geography.focusIds||[selected,...(context?.directIds||[])]):graph.nodes.map(n=>n.id)).map(id=>geography.positions2d.get(id)),xs=ps.map(p=>p.x),ys=ps.map(p=>p.y),cx=(Math.min(...xs)+Math.max(...xs))/2,cy=(Math.min(...ys)+Math.max(...ys))/2,scale=Math.min(canvas.current.clientWidth/(Math.max(...xs)-Math.min(...xs)+80),canvas.current.clientHeight/(Math.max(...ys)-Math.min(...ys)+80));view.current={x:-cx*scale,y:cy*scale,scale};}else if(action.type==='home')view.current={x:0,y:0,scale:.55};else if(action.type==='focus'&&p)view.current={x:-p.x*2,y:-p.y*2,scale:2};else if(action.type==='in'||action.type==='out')view.current.scale=Math.max(.0001,Math.min(40,view.current.scale*(action.type==='in'?1.25:.8)));drawRef.current?.();},[action,geography]);
  const highlight=id=>{if(hoverId.current===id)return;hoverId.current=id;setHovered(id);drawRef.current?.();};
  const local=e=>{const r=canvas.current.getBoundingClientRect();return {x:e.clientX-r.left,y:e.clientY-r.top};};
  const pick=p=>{for(const kind of ['gaps','nodes']){let best=null,d=10;for(const n of hit.current[kind]){const nd=Math.hypot(n.x-p.x,n.y-p.y);if(nd<d){best={kind,id:n.id};d=nd;}}if(best)return best;}for(const e of hit.current.edges){const dx=e.b.x-e.a.x,dy=e.b.y-e.a.y,t=Math.max(0,Math.min(1,((p.x-e.a.x)*dx+(p.y-e.a.y)*dy)/(dx*dx+dy*dy||1)));if(Math.hypot(p.x-e.a.x-t*dx,p.y-e.a.y-t*dy)<4)return{kind:'edges',id:e.id};}return null;};
  return <div className="l1-network-host"><canvas onPointerLeave={()=>{setHover('');highlight('');}} ref={canvas} tabIndex={0} aria-label="2D responsibility network" onContextMenu={e=>e.preventDefault()}
    onWheel={e=>{highlight('');const p=local(e),w=canvas.current.clientWidth,h=canvas.current.clientHeight,v=view.current,s=Math.max(.0001,Math.min(40,v.scale*Math.exp(-e.deltaY*.001)));v.x=p.x-w/2-(p.x-w/2-v.x)*s/v.scale;v.y=p.y-h/2-(p.y-h/2-v.y)*s/v.scale;v.scale=s;drawRef.current();}}
    onPointerDown={e=>{drag.current={...local(e),start:local(e),view:{...view.current}};e.currentTarget.setPointerCapture(e.pointerId);}}
    onPointerMove={e=>{const p=local(e);if(drag.current){view.current.x=drag.current.view.x+p.x-drag.current.x;view.current.y=drag.current.view.y+p.y-drag.current.y;drawRef.current();}else{const h=pick(p),n=model.byId.get(h?.id);highlight(h?.kind==='nodes'?h.id:'');e.currentTarget.style.cursor=h?'pointer':'';setHover(n?`${n.id} · ${title(n)} · ${model.label(n.data.role_id)}`:h?`${h.kind==='gaps'?'Unresolved handoff':'Connection'} ${h.id}`:'');}}}
    onPointerUp={e=>{const p=local(e),d=drag.current;if(d&&Math.hypot(p.x-d.start.x,p.y-d.start.y)<5){const h=pick(p);if(h?.kind==='nodes')onSelect(h.id);if(h?.kind==='edges')onEdge(h.id);if(h?.kind==='gaps')onGap(h.id);}drag.current=null;}} onPointerCancel={()=>{drag.current=null;}}
    onKeyDown={e=>{const moves={ArrowLeft:[30,0],ArrowRight:[-30,0],ArrowUp:[0,30],ArrowDown:[0,-30]};if(moves[e.key]){e.preventDefault();view.current.x+=moves[e.key][0];view.current.y+=moves[e.key][1];drawRef.current();}}}/><div className="l1-spatial-labels">{callouts.map(c=><button key={c.id} className={'l1-spatial-label '+c.kind} data-selected={c.id===selected} data-hovered={c.id===hovered} onPointerEnter={()=>highlight(c.kind==='node'?c.id:'')} onPointerLeave={()=>highlight('')} onFocus={()=>highlight(c.kind==='node'?c.id:'')} onBlur={()=>highlight('')} aria-label={'Inspect '+c.id} style={{transform:`translate(${c.x}px,${c.y}px)`,width:c.width,minHeight:c.height}} onClick={()=>c.kind==='gap'?onGap(c.id):onSelect(c.id)}>{c.text}</button>)}</div>{hover&&<div className="l1-hover" role="status">{hover}</div>}<div className="l1-hint">Drag to pan · scroll to zoom · select node or edge · arrow keys pan</div></div>;
}
