import OrganisationalPosition from './OrganisationalPosition';
import React,{useEffect,useState} from 'react';
import * as api from '../../../api/client';
import {title,groupKey} from './model.mjs';
const checked=r=>{if(!r.data.success)throw Error(r.data.error?.message||'Unable to load record');return r.data;};
export default function Inspector({sourceReveal,context,onCollapse,model,graph,inspection,mode,fixtures,cache,onSelect,onEdge,onGroup,onSource,onGovern,onOriginal,onGap}){
  const [detail,setDetail]=useState(null),[error,setError]=useState(''),[history,setHistory]=useState(null);
  const gap=inspection.kind==='gap'?model.gaps.find(g=>g.id===inspection.id):null,id=gap?.responsibility_id||inspection.id;
  useEffect(()=>{let cancelled=false;setDetail(null);setHistory(null);setError('');if(!id)return;const key=`${model.revision}:${mode}:${id}`;if(cache.current.has(key)){setDetail(cache.current.get(key));return;}
    api.getNervousBreakdownDetail(id,{mode,fixtures}).then(checked).then(r=>{cache.current.set(key,r);if(!cancelled)setDetail(r);}).catch(e=>{if(!cancelled)setError(e.message);});return()=>{cancelled=true;};
  },[id,mode,fixtures,model.revision]);
  useEffect(()=>{if(sourceReveal&&detail?.record.id===id)document.querySelector('.l1-inspector .l1-source-section')?.scrollIntoView({block:'center',behavior:'smooth'});},[sourceReveal,detail]);
  if(!id)return <aside className="l1-inspector"><h2>Inspect the organisation</h2><p>Select a responsibility, connection or unresolved handoff.</p><p>Start with Search, focus a Role or Domain, or use List for precise record access.</p><p className="nb-legend">Spatial proximity is not a governed relationship. Counts describe the mapped sources, not workload or organisational importance.</p></aside>;
  if(error)return <aside className="l1-inspector"><p role="alert">{error}</p></aside>;
  if(!detail)return <aside className="l1-inspector" aria-busy="true">Loading documentary detail…</aside>;
  const {record,statement,source}=detail,d=record.data,edge=record.kind==='connection',type=model.references.get(d.relationship_type_id),symmetric=type?.data.directionality==='symmetric';
  const group=model.groups.get(`${d.statement_id}:${d.statement_revision}`)||[];
  const field=(label,value)=><div><dt>{label}</dt><dd>{value||'Unknown / not classified'}</dd></div>;
  const names=ids=>(ids||[]).map(model.label).join(', ');
  let rationale=d.notes;try{const value=JSON.parse(d.notes);rationale=value.Rationale||d.notes;}catch{/* Plain documentary notes remain exact. */}
  const showHistory=async r=>{try{setHistory({id:r.id,items:checked(await api.getNervousBreakdownHistory(r.id)).history});}catch(e){setError(e.message);}};
  return <aside className="l1-inspector" aria-label="Layer 1 inspector"><header className="l1-inspector-heading"><button className="l1-collapse-detail" onClick={onCollapse}>Collapse detail</button>
    <p className="l1-eyebrow">{gap?'Unresolved Handoff':edge?'Relationship':model.label(d.role_id)}</p><h2>{gap?`${gap.target_role_name} · receiving responsibility unresolved`:edge?title(type):`${record.id} — ${title(record)}`}</h2>{!edge&&!gap&&<p>{model.label(d.role_id)} · {names(d.domain_ids?.filter(id=>!model.references.get(id)?.data.parent_id))} · {d.level_id?model.label(d.level_id):d.level||'Level unknown'}</p>}
    {(edge||gap)&&<p className="nb-id">{gap?gap.id:record.id} · {gap?'analytical gap overlay':`revision ${record.revision}`}</p>}
    <p className="nb-review-badge">Evidence: {gap?.evidence||d.evidence||'unknown'} · Review: {gap?.review_status||d.review_status} · {gap?'Unresolved':`Lifecycle: ${d.status}`}</p>
    {mode==='draft_review'&&<p className="nb-legend">Non-approved analytical structure. Inspection does not approve or activate records.</p>}
    </header>{!edge&&!gap&&context?.responsibility.id===record.id&&<><h3>Organisational consequence</h3><OrganisationalPosition detailsOnly context={context} model={model} onGap={onGap} onEdge={onEdge} onSelect={onSelect}/></>}<div className="l1-inspector-sections">{gap&&<section><h3>Documented direction, unresolved endpoint</h3><button onClick={()=>onSelect(gap.responsibility_id)}>{gap.responsibility_id} · {title(record)}</button><p>Originating role: {model.label(d.role_id)}</p><p>Referenced target role: <strong>{gap.target_role_name}</strong></p><p>{gap.target_has_mapped_responsibilities?'This role has mapped responsibilities, but no defensible receiving responsibility is bound to this handoff.':'Referenced role: its authoritative responsibilities are outside the currently mapped corpus.'}</p><p>{gap.rationale}</p><p>Resolution: {gap.resolution}. No responsibility connection has been created.</p><details><summary>Original analytical artefact fields</summary><pre>{JSON.stringify(gap.original,null,2)}</pre><p>The supplied lifecycle field is preserved as artefact metadata; it does not activate a responsibility connection.</p></details></section>}
    {edge&&<section><h3>{symmetric?'Companion responsibilities':'Directed endpoints'}</h3>{['from_id','to_id'].map((k,i)=>{const n=model.byId.get(d[k]);return <div key={k}><p>{symmetric?`Companion ${i+1}`:i?'To':'From'}</p><button onClick={()=>onSelect(d[k])}>{d[k]} · {title(n)}</button><p>{model.label(n?.data.role_id)}</p></div>;})}<p>Directionality: {symmetric?'symmetric — endpoint order is storage only':'directed — From → To'}</p>{symmetric&&<p>Common source statement; no process order, causality or hierarchy is implied.</p>}<h3>Rationale</h3><p className="l1-verbatim">{rationale||'No rationale supplied.'}</p>{!statement&&<p>No direct source statement is attached. Endpoint provenance does not make this relationship documentary.</p>}</section>}
    {!edge&&!gap&&<section><h3>Responsibility</h3><dl>{field('Role',model.label(d.role_id))}{field('Domain',names(d.domain_ids?.filter(id=>!model.references.get(id)?.data.parent_id)))}{field('Subdomain',names(d.domain_ids?.filter(id=>model.references.get(id)?.data.parent_id)))}{field('Action type',names(d.responsibility_type_ids))}{field('Authority',names(d.authority_type_ids))}{field('Responsibility Level',d.level_id?model.label(d.level_id):d.level)}{field('Current connections',String(model.degree.get(record.id)||0))}</dl></section>}
    {statement&&<section className="l1-source-section"><h3>Source · Documentary trace</h3><p>{statement.id} · pinned revision {statement.revision}</p><blockquote>{statement.data.original_text}</blockquote><p>Location: {statement.data.location}</p><p>{source?.data.name} · {source?.data.version_label}</p><p className="nb-id">Source {source?.id} · document {source?.data.document_id} · immutable version {source?.data.document_version_id}</p><button onClick={()=>onOriginal(source)}>Open original source version</button><button onClick={()=>onSource(source.id)}>Show responsibilities from this source</button></section>}
    {group.length>0&&<section><h3>Source-statement group · {group.length}</h3><p>Co-specified responsibilities, with no sequence. All eligible members are listed independently of stored chain order.</p><button onClick={()=>onGroup(`${d.statement_id}:${d.statement_revision}`)}>Show documentary family</button>{group.map(id=><button className="l1-related" key={id} onClick={()=>onSelect(id)}>{id} · {title(model.byId.get(id))}</button>)}</section>}
    {!edge&&!gap&&<section><h3>Current relationships</h3>{(model.adjacency.get(record.id)||[]).map(e=><button className="l1-related" key={e.id} onClick={()=>onEdge(e.id)}>{model.label(e.data.relationship_type_id)} · {e.data.evidence} · {e.data.review_status}<br/>{title(model.byId.get(e.data.from_id===record.id?e.data.to_id:e.data.from_id))}</button>)}{!model.degree.get(record.id)&&<p>Isolated in the current governed graph. This is not automatically an error.</p>}<h3>Unresolved handoffs</h3>{model.gaps.filter(g=>g.responsibility_id===record.id).map(g=><button key={g.id} className="l1-related" onClick={()=>onGap(g.id)}>◇ {g.target_role_name} · {g.id} · unresolved</button>)}</section>}
    <details className="l1-history-section"><summary>Governance and history</summary><p className="nb-id">{record.id} · revision {record.revision}</p><button onClick={()=>onGovern(record)}>Open governed record</button>{detail.history.map(h=><details key={h.revision}><summary>Revision {h.revision} · {h.reason}</summary><pre>{JSON.stringify(h.snapshot.data,null,2)}</pre></details>)}{detail.related?.filter(r=>['inactive','superseded'].includes(r.data.status)).map(r=><button className="l1-related" key={r.id} onClick={()=>showHistory(r)}>{r.id} · {r.data.status} · inspect historical revisions</button>)}{history&&<section><h3>{history.id} history</h3>{history.items.map(h=><details key={h.revision}><summary>Revision {h.revision} · {h.reason}</summary><pre>{JSON.stringify(h.snapshot.data,null,2)}</pre></details>)}</section>}</details>
  </div></aside>;
}
