import React,{useMemo,useState,useEffect,useRef} from 'react';
import {title} from './model.mjs';
export default function ListView({graph,model,selected,onSelect}){
  const table=useRef();
  const [sort,setSort]=useState('id'),[asc,setAsc]=useState(true),[page,setPage]=useState(0),[all,setAll]=useState(false);
  const columns={id:['ID',n=>n.id],wording:['Responsibility',title],role:['Role',n=>model.label(n.data.role_id)],domain:['Domain',n=>(n.data.domain_ids||[]).filter(id=>!model.references.get(id)?.data.parent_id).map(model.label).join(', ')],subdomain:['Subdomain',n=>(n.data.domain_ids||[]).filter(id=>model.references.get(id)?.data.parent_id).map(model.label).join(', ')],action:['Action type',n=>(n.data.responsibility_type_ids||[]).map(model.label).join(', ')],authority:['Authority',n=>(n.data.authority_type_ids||[]).map(model.label).join(', ')],level:['Responsibility Level',n=>n.data.level_id?model.label(n.data.level_id):n.data.level||'Unknown'],source:['Source',n=>model.label(n.data.source_id)],evidence:['Evidence',n=>n.data.evidence||'Unknown'],review:['Review',n=>n.data.review_status],family:['Documentary family',n=>n.data.statement_id||'Unknown'],relation:['Relation to selected',n=>n.id===selected?'Selected':graph.trail.nodes.includes(n.id)?(model.adjacency.get(n.id).filter(e=>e.data.from_id===selected||e.data.to_id===selected).map(e=>model.label(e.data.relationship_type_id)).join('; ')||'Trail / documentary family'):'Context'],degree:['Current connections',n=>model.degree.get(n.id)]};
  const rows=useMemo(()=>graph.nodes.slice().sort((a,b)=>{const av=columns[sort][1](a),bv=columns[sort][1](b);return (typeof av==='number'?av-bv:String(av).localeCompare(String(bv)))*(asc?1:-1)||a.id.localeCompare(b.id);}),[graph,sort,asc]);
  useEffect(()=>{const i=rows.findIndex(n=>n.id===selected);setPage(i<0?0:Math.floor(i/50));},[rows,selected]);
  useEffect(()=>{const row=table.current?.querySelector('tr[data-selected="true"]');if(row)table.current.scrollTop=Math.max(0,row.offsetTop-table.current.clientHeight/2);},[page,selected]);
  const keys=all?Object.keys(columns):['id','wording','role','level','family','relation','evidence','review'];
  return <section aria-label="Responsibility list"><div className="nb-toolbar"><button onClick={()=>setAll(v=>!v)}>{all?'Core columns':'All classification and source columns'}</button><span>{rows.length} eligible records · {selected?`Selected ${selected}`:'Select a row to inspect'}</span></div><div className="l1-table" ref={table}><table><thead><tr>{keys.map(k=><th key={k}><button onClick={()=>{if(sort===k)setAsc(!asc);else{setSort(k);setAsc(true);}}}>{columns[k][0]} {sort===k?(asc?'↑':'↓'):''}</button></th>)}</tr></thead><tbody>{rows.slice(page*50,page*50+50).map(n=><tr key={n.id} data-selected={n.id===selected} data-trail={graph.trail.nodes.includes(n.id)}>{keys.map(k=><td key={k}>{k==='id'?<button onClick={()=>onSelect(n.id)}>{n.id}</button>:columns[k][1](n)??'Unknown'}</td>)}</tr>)}</tbody></table></div><div className="nb-toolbar"><button disabled={page===0} onClick={()=>setPage(p=>p-1)}>Previous records</button><span>Page {page+1} of {Math.max(1,Math.ceil(rows.length/50))}</span><button disabled={(page+1)*50>=rows.length} onClick={()=>setPage(p=>p+1)}>Next records</button></div></section>;
}
