import React,{useEffect,useRef,useState} from 'react';
import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {title,encoding} from './model.mjs';

export default function Network3D({graph,geography,model,selected,onSelect,onEdge,onGap,cameraMemory,action,flat=false,onUnavailable}) {
  const host=useRef(),live=useRef(),callbacks=useRef();callbacks.current={onSelect,onEdge,onGap};
  const [failed,setFailed]=useState(''),[hover,setHover]=useState('');
  useEffect(()=>{
    const element=host.current;let renderer,controls,scene,observer,frame=null;
    try {
      renderer=new T.WebGLRenderer({antialias:graph.edges.length<=10000,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor('#0c1522');
      renderer.domElement.setAttribute('aria-label',flat?'2D responsibility network':'3D responsibility network');renderer.domElement.tabIndex=0;element.appendChild(renderer.domElement);
      scene=new T.Scene();const camera=flat?new T.OrthographicCamera(-700,700,700,-700,.1,15000):new T.PerspectiveCamera(48,1,.1,15000);camera.position.set(0,flat?0:-950,flat?1500:1050);camera.up.set(0,flat?1:0,flat?0:1);
      controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=false;controls.minDistance=12;controls.maxDistance=4000;controls.screenSpacePanning=true;controls.enableRotate=!flat;if(flat){controls.mouseButtons.LEFT=T.MOUSE.PAN;controls.minZoom=.2;controls.maxZoom=20;}
      if(cameraMemory.current){camera.position.fromArray(cameraMemory.current.position);controls.target.fromArray(cameraMemory.current.target);if(flat)camera.zoom=cameraMemory.current.zoom||1;}controls.update();
      const render=()=>{if(frame!==null)return;frame=requestAnimationFrame(()=>{frame=null;const started=performance.now();renderer.render(scene,camera);renderer.domElement.dataset.renderMs=String(performance.now()-started);renderer.domElement.dataset.camera=camera.position.toArray().map(x=>x.toFixed(2)).join(',')+':'+camera.zoom;});};
      controls.addEventListener('change',()=>{cameraMemory.current={position:camera.position.toArray(),target:controls.target.toArray(),zoom:camera.zoom};render();});
      const resize=()=>{const w=element.clientWidth,h=element.clientHeight;renderer.setSize(w,h);if(flat){camera.left=-700*w/h;camera.right=700*w/h;}else camera.aspect=w/h;camera.updateProjectionMatrix();render();};observer=new ResizeObserver(resize);observer.observe(element);
      const ray=new T.Raycaster();ray.params.Line.threshold=2;let down=null;
      const pick=e=>{const r=renderer.domElement.getBoundingClientRect();ray.setFromCamera(new T.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),camera);const state=live.current;if(!state)return;const hit=(ray.intersectObjects(state.pickable.filter(o=>o.userData.kind!=='edge'),false)[0]||ray.intersectObjects(state.pickable.filter(o=>o.userData.kind==='edge'),false)[0]);if(!hit)return null;return hit.object.userData.kind==='edge'?{kind:'edge',id:hit.object.userData.ids[Math.floor(hit.index/2)]}:{kind:hit.object.userData.kind,id:hit.object.userData.ids[hit.instanceId]};};
      const move=e=>{if(e.buttons)return;const hit=pick(e);const n=hit?.kind==='node'?live.current.model.byId.get(hit.id):null;setHover(n?`${n.id} · ${title(n)} · ${live.current.model.label(n.data.role_id)}`:hit?.kind==='gap'?`Unresolved handoff ${hit.id} · no receiving responsibility`:hit?.kind==='edge'?`Connection ${hit.id} · select to inspect`:'');};
      const pointerDown=e=>{down={x:e.clientX,y:e.clientY};};
      const up=e=>{if(down&&Math.hypot(e.clientX-down.x,e.clientY-down.y)<5){const hit=pick(e);if(hit?.kind==='node')callbacks.current.onSelect(hit.id);if(hit?.kind==='edge')callbacks.current.onEdge(hit.id);if(hit?.kind==='gap')callbacks.current.onGap(hit.id);}down=null;};
      const key=e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();if(flat){const move=new T.Vector3(e.key==='ArrowLeft'?30:e.key==='ArrowRight'?-30:0,e.key==='ArrowUp'?-30:e.key==='ArrowDown'?30:0,0).multiplyScalar(1/camera.zoom);camera.position.add(move);controls.target.add(move);controls.update();render();return;}const delta=camera.position.clone().sub(controls.target);delta.applyAxisAngle(new T.Vector3(0,0,1),e.key==='ArrowLeft'?.12:e.key==='ArrowRight'?-.12:0);if(e.key==='ArrowUp')delta.multiplyScalar(.9);if(e.key==='ArrowDown')delta.multiplyScalar(1.1);camera.position.copy(controls.target).add(delta);controls.update();render();}};
      const lost=e=>{e.preventDefault();onUnavailable?.();setFailed('3D graphics became unavailable. Continue in 2D Network or List.');};
      renderer.domElement.addEventListener('pointerdown',pointerDown);renderer.domElement.addEventListener('pointerup',up);renderer.domElement.addEventListener('pointermove',move);renderer.domElement.addEventListener('keydown',key);renderer.domElement.addEventListener('webglcontextlost',lost);
      live.current={renderer,scene,camera,controls,render,pickable:[],model,content:null};resize();
    }catch{onUnavailable?.();setFailed('3D graphics are unavailable in this browser. Your data remains accessible in 2D Network and List.');}
    return()=>{if(frame!==null)cancelAnimationFrame(frame);observer?.disconnect();controls?.dispose();if(scene)scene.traverse(o=>{o.geometry?.dispose();o.material?.map?.dispose();o.material?.dispose();});renderer?.dispose();renderer?.domElement.remove();live.current=null;};
  },[]);
  useEffect(()=>{
    const s=live.current;if(!s)return;const start=performance.now();s.model=model;const position=id=>{const p=geography.positions.get(id);return flat?{x:p.x,y:p.y,z:0}:p;};
    if(s.content){s.scene.remove(s.content);s.content.traverse(o=>{o.geometry?.dispose();o.material?.map?.dispose();o.material?.dispose();});}
    const content=new T.Group();s.content=content;s.scene.add(content);s.pickable=[];
    const trailNodes=new Set(graph.trail.nodes),trailEdges=new Set(graph.trail.edges),focused=!!selected&&!graph.selectedExcluded;
    const matrix=new T.Matrix4(),color=new T.Color(),dummy=new T.Object3D();
    const nodes=new T.InstancedMesh(new T.IcosahedronGeometry(1,1),new T.MeshBasicMaterial(),Math.max(1,graph.nodes.length));nodes.count=graph.nodes.length;
    nodes.userData={kind:'node',ids:graph.nodes.map(n=>n.id)};
    graph.nodes.forEach((n,i)=>{const p=position(n.id);const active=!focused||trailNodes.has(n.id);const size=n.id===selected?6:active?3.2:2.1;matrix.makeScale(size,size,size);matrix.setPosition(p.x,p.y,p.z);nodes.setMatrixAt(i,matrix);nodes.setColorAt(i,color.set(n.id===selected?'#ffffff':active?'#6cd6c1':'#263748'));});nodes.instanceMatrix.needsUpdate=true;content.add(nodes);s.pickable.push(nodes);
    const vertices=[],colors=[],edgeIds=[],arrows=[];
    function segment(a,b,c,id){vertices.push(a.x,a.y,a.z,b.x,b.y,b.z);color.set(c);colors.push(color.r,color.g,color.b,color.r,color.g,color.b);edgeIds.push(id);}
    for(const e of graph.edges){const a=new T.Vector3(...Object.values(position(e.data.from_id))),b=new T.Vector3(...Object.values(position(e.data.to_id))),style=encoding(e),active=!focused||trailEdges.has(e.id),c=active?(style.companion?(focused?'#79c9df':'#274757'):'#edbd7d'):'#192838';
      const pieces=style.draft?8:1;for(let j=0;j<pieces;j++)segment(a.clone().lerp(b,j/pieces),a.clone().lerp(b,(j+(style.draft?.46:1))/pieces),c,e.id);
      if(!style.symmetric)arrows.push({a,b,c});
    }
    const geometry=new T.BufferGeometry();geometry.setAttribute('position',new T.Float32BufferAttribute(vertices,3));geometry.setAttribute('color',new T.Float32BufferAttribute(colors,3));const lines=new T.LineSegments(geometry,new T.LineBasicMaterial({vertexColors:true}));lines.userData={kind:'edge',ids:edgeIds};content.add(lines);s.pickable.push(lines);
    const arrowMesh=new T.InstancedMesh(new T.ConeGeometry(2.2,6,5),new T.MeshBasicMaterial(),Math.max(1,arrows.length));arrowMesh.count=arrows.length;arrows.forEach(({a,b,c},i)=>{dummy.position.copy(a).lerp(b,.76);dummy.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),b.clone().sub(a).normalize());dummy.scale.set(1,1,1);dummy.updateMatrix();arrowMesh.setMatrixAt(i,dummy.matrix);arrowMesh.setColorAt(i,color.set(c));});content.add(arrowMesh);
    const gapMesh=new T.InstancedMesh(new T.OctahedronGeometry(5),new T.MeshBasicMaterial({color:'#f2b8dc',wireframe:true}),Math.max(1,graph.gaps.length));gapMesh.count=graph.gaps.length;gapMesh.userData={kind:'gap',ids:graph.gaps.map(g=>g.id)};const gapVertices=[];
    graph.gaps.forEach((g,i)=>{const a=position(g.responsibility_id),angle=i*2.399963,b={x:a.x+25*Math.cos(angle),y:a.y+25*Math.sin(angle),z:a.z+25};matrix.identity().setPosition(b.x,b.y,b.z);gapMesh.setMatrixAt(i,matrix);for(let j=0;j<4;j++){const p=new T.Vector3(a.x,a.y,a.z).lerp(new T.Vector3(b.x,b.y,b.z),j/4),q=new T.Vector3(a.x,a.y,a.z).lerp(new T.Vector3(b.x,b.y,b.z),(j+.5)/4);gapVertices.push(...p.toArray(),...q.toArray());}});content.add(gapMesh);s.pickable.unshift(gapMesh);const gg=new T.BufferGeometry();gg.setAttribute('position',new T.Float32BufferAttribute(gapVertices,3));content.add(new T.LineSegments(gg,new T.LineBasicMaterial({color:'#f2b8dc'})));
    // Sparse region labels; full wording belongs in the accessible inspector.
    for(const [id,p] of geography.centers){if(focused)continue;const canvas=document.createElement('canvas');canvas.width=512;canvas.height=64;const c=canvas.getContext('2d');c.fillStyle='#94aabd';c.font='22px system-ui';c.fillText(model.label(id).slice(0,42),8,40);const sprite=new T.Sprite(new T.SpriteMaterial({map:new T.CanvasTexture(canvas),transparent:true,depthTest:false,opacity:focused?.28:.8}));sprite.position.set(p.x,p.y+(flat?125:0),flat?0:p.z+90);sprite.scale.set(180,22.5,1);content.add(sprite);}
    if(selected&&!graph.selectedExcluded){const p=position(selected),n=model.byId.get(selected);const halo=new T.Mesh(new T.IcosahedronGeometry(7,1),new T.MeshBasicMaterial({color:'#ffffff',wireframe:true,depthTest:false}));halo.position.set(p.x,p.y,p.z);halo.renderOrder=10;content.add(halo);const c=document.createElement('canvas');c.width=256;c.height=64;const ctx=c.getContext('2d');ctx.fillStyle='#101720ee';ctx.fillRect(0,0,256,64);ctx.fillStyle='#ffffff';ctx.font='24px system-ui';ctx.fillText(selected,16,40);const label=new T.Sprite(new T.SpriteMaterial({map:new T.CanvasTexture(c),depthTest:false,transparent:true}));label.position.set(p.x,p.y,p.z+14);label.scale.set(26,6.5,1);label.renderOrder=11;content.add(label);}
    s.renderer.domElement.dataset.nodes=String(graph.nodes.length);s.renderer.domElement.dataset.edges=String(graph.edges.length);s.renderer.domElement.dataset.symmetric=String(graph.edges.filter(e=>encoding(e).symmetric).length);s.renderer.domElement.dataset.arrows=String(arrows.length);s.render();s.renderer.domElement.dataset.updateMs=String(performance.now()-start);
  },[graph,geography,model,selected]);
  useEffect(()=>{setHover('');const s=live.current;if(!s)return;const p=geography.positions.get(selected);if(action.type==='fit'&&graph.nodes.length){const ps=graph.nodes.map(n=>geography.positions.get(n.id)),box=new T.Box3().setFromPoints(ps.map(p=>new T.Vector3(p.x,p.y,flat?0:p.z))),center=box.getCenter(new T.Vector3()),size=box.getSize(new T.Vector3()),radius=Math.max(size.x,size.y,size.z,50);s.controls.target.copy(center);if(flat){s.camera.position.set(center.x,center.y,1500);s.camera.zoom=Math.min(12,Math.max(.2,1100/radius));}else{s.camera.position.copy(center).add(new T.Vector3(0,-radius*1.3,radius*1.3));}}else if(action.type==='home'){s.controls.target.set(0,0,0);s.camera.position.set(0,flat?0:-950,flat?1500:1050);if(flat)s.camera.zoom=1;}else if(action.type==='focus'&&p){s.controls.target.set(p.x,p.y,flat?0:p.z);s.camera.position.set(p.x,flat?p.y:p.y-135,flat?1500:p.z+120);if(flat)s.camera.zoom=3;}else if(action.type==='in'||action.type==='out'){if(flat)s.camera.zoom=Math.max(.2,Math.min(20,s.camera.zoom*(action.type==='in'?1.25:.8)));else s.camera.position.sub(s.controls.target).multiplyScalar(action.type==='in'?.8:1.25).add(s.controls.target);}s.camera.updateProjectionMatrix();s.controls.update();s.render();},[action,geography]);
  return <div className="l1-network-host" ref={host}>{failed&&<p role="alert" className="l1-fallback">{failed}</p>}{hover&&<div className="l1-hover" role="status">{hover}</div>}<div className="l1-hint">{flat?'Drag to pan · scroll to zoom · arrow keys pan · select to inspect':'Drag to rotate · right-drag to pan · scroll to zoom · arrow keys rotate/zoom · select to inspect'}</div></div>;
}
