import {selectedContext} from './selected-context.mjs';
import OrganisationalPosition from './OrganisationalPosition';
import React,{useEffect,useMemo,useRef,useState,lazy,Suspense} from 'react';
import * as api from '../../../api/client';
import {adapt,DEFAULTS,layout,selectGraph,searchNodes,title} from './model.mjs';
import Network2D from './Network2D';
import {focusLayout,VERSION,visibleEdges,nodeColor} from './semantic-layout.mjs';
import ListView from './ListView';
import Inspector from './Inspector';
import './workspace.css';
const Network3D=lazy(()=>import('./Network3D'));
class RenderBoundary extends React.Component {state={error:false};static getDerivedStateFromError(){return {error:true};}render(){return this.state.error?<p role="alert">This network renderer could not finish. Switch to List or another representation; your analytical context is preserved.</p>:this.props.children;}}
const checked=r=>{if(!r.data.success)throw Error(r.data.error?.message||'Unable to load network');return r.data;};
export default function Workspace({canDraftReview,fixtures,refresh,onGovern,onOriginal,roleFocus}) {
  const [mode,setMode]=useState('normal'),[view,setView]=useState(()=>{try{return ['3d','2d','list'].includes(localStorage.getItem('nb.view'))?localStorage.getItem('nb.view'):'3d';}catch{return '3d';}});
  const [raw,setRaw]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[filters,setFilters]=useState({...DEFAULTS}),[q,setQ]=useState('');
  const [selected,setSelected]=useState(''),[inspection,setInspection]=useState({id:'',kind:'node'}),[panel,setPanel]=useState(true),[expanded,setExpanded]=useState(false),[action,setAction]=useState({type:'home',tick:0});
  const [familyExpanded,setFamilyExpanded]=useState(false),[sourceReveal,setSourceReveal]=useState(0);
  const [connectionQuery,setConnectionQuery]=useState(''),[cascade,setCascade]=useState(false),[advanced,setAdvanced]=useState(false),[colourBy,setColourBy]=useState('role'),[showCompanionLines,setShowCompanionLines]=useState(false);
  const detailCache=useRef(new Map()),camera3d=useRef(),camera2d=useRef(),performanceRef=useRef({});
  const command=type=>setAction(a=>({type,tick:a.tick+1}));
  useEffect(()=>{if(roleFocus){setFilters({...DEFAULTS,role:roleFocus.id});setSelected('');setInspection({id:'',kind:'node'});command('fit');}},[roleFocus]);
  useEffect(()=>{let cancelled=false;setBusy(true);setError('');setRaw(null);detailCache.current.clear();const t=performance.now();api.getNervousBreakdownTopology({mode,fixtures}).then(checked).then(data=>{if(!cancelled){setRaw(data);performanceRef.current.fetch=performance.now()-t;}}).catch(e=>{if(!cancelled)setError(e.message);}).finally(()=>{if(!cancelled)setBusy(false);});return()=>{cancelled=true;};},[mode,fixtures,refresh]);
  const model=useMemo(()=>{if(!raw)return null;try{return adapt(raw);}catch(e){return {failure:e.message};}},[raw]);
  const [geography,setGeography]=useState(null);
  useEffect(()=>{if(!model||model.failure)return;let cancelled=false;setGeography(null);const cacheKey='nb.semantic.'+VERSION+'.'+mode+'.'+fixtures+'.'+model.revision;try{const saved=localStorage.getItem(cacheKey);if(saved){const cached=JSON.parse(saved,(_,v)=>v?.__map?new Map(v.__map):v);if(cached.version===VERSION){setGeography({...cached,revision:model.revision,basis:model});return;}}}catch{/* Cache is optional. */}const worker=new Worker(new URL('./layout.worker.mjs',import.meta.url),{type:'module'});worker.onmessage=({data})=>{if(cancelled)return;if(data.error)setError(data.error);else {setGeography({...data.result,revision:model.revision,basis:model});try{localStorage.setItem(cacheKey,JSON.stringify(data.result,(_,v)=>v instanceof Map?{__map:[...v]}:v));}catch{/* Storage may be full. */}}worker.terminate();};worker.onerror=()=>{if(!cancelled)setError('The layout could not be calculated. Refresh to retry.');worker.terminate();};worker.postMessage(raw);return()=>{cancelled=true;worker.terminate();};},[model]);
  const graph=useMemo(()=>model&&!model.failure?selectGraph(model,filters,selected,true,familyExpanded):null,[model,filters,selected,familyExpanded]);
  const context=useMemo(()=>model&&!model.failure?selectedContext(model,selected):null,[model,selected]);
  const presentation=useMemo(()=>cascade&&geography?.basis===model&&graph&&!graph.selectedExcluded?focusLayout(model,geography,graph,selected,context,familyExpanded):geography,[model,geography,graph,selected,cascade,context,familyExpanded]);
  const results=useMemo(()=>model&&!model.failure?searchNodes(model,q):[],[model,q]);
  const choose=id=>{setSourceReveal(0);setFamilyExpanded(false);setCascade(false);setSelected(id);setInspection({id,kind:'node'});setPanel(true);setQ('');command('focus');};
  const edge=id=>{setSourceReveal(0);setInspection({id,kind:'edge'});setPanel(true);};
  const gap=id=>{setSourceReveal(0);const g=model?.gaps.find(g=>g.id===id);if(g)setSelected(g.responsibility_id);setInspection({id,kind:'gap'});setPanel(true);command('focus');};
  const change=(k,v)=>{if(!['depth','direction','showGaps'].includes(k))setCascade(false);setFilters(f=>({...f,[k]:v}));};
  const reset=()=>{setFamilyExpanded(false);setCascade(false);setFilters({...DEFAULTS});setSelected('');setInspection({id:'',kind:'node'});setQ('');command('home');};
  const switchView=id=>{setView(id);try{localStorage.setItem('nb.view',id);}catch{/* Local preferences are optional. */}if(selected)command(cascade?'cascade':'focus');};
  const changeMode=value=>{setCascade(false);setMode(value);setSelected('');setInspection({id:'',kind:'node'});setFilters({...DEFAULTS});setQ('');command('home');};
  const options=(kind,category,parent)=>[...model.references.values()].filter(r=>r.kind===kind&&(!category||r.data.category===category)&&(parent===undefined||!!r.data.parent_id===parent)).sort((a,b)=>title(a).localeCompare(title(b)));
  const selector=(key,label,records)=><label>{label}<select aria-label={label} value={filters[key]} onChange={e=>{change(key,e.target.value);if(key==='domain')change('subdomain','');if(key==='role'||key==='domain')command('fit');}}><option value="">All / any</option>{records.map(r=><option key={r.id} value={r.id}>{r.data.parent_id?`${model.label(r.data.parent_id)} / `:''}{title(r)}</option>)}</select></label>;
  const modeControl=<label>Layer 1 mode<select aria-label="Layer 1 mode" value={mode} onChange={e=>changeMode(e.target.value)}><option value="normal">Normal View</option>{canDraftReview&&<option value="draft_review">Governance / Draft Review</option>}</select></label>;
  if(error||model?.failure)return <section>{modeControl}<p role="alert">{error||model.failure}</p><p>Refresh to retry. No organisational data was changed.</p></section>;
  if(!graph||!geography||geography.basis!==model)return <section>{modeControl}<p role="status">{busy?'Loading governed topology…':'Calculating stable organisational geography…'}</p></section>;
  const p=model.byId.get(selected),visibleGaps=graph.gaps;
  const connectionMatches=graph.edges.filter(e=>[e.id,e.data.from_id,e.data.to_id,model.label(e.data.relationship_type_id)].join(' ').toLowerCase().includes(connectionQuery.toLowerCase()));
  const connectionChoices=connectionMatches.slice(0,250);const inspectedEdge=graph.edges.find(e=>e.id===inspection.id);if(inspectedEdge&&!connectionChoices.includes(inspectedEdge))connectionChoices.push(inspectedEdge);
  const renderProps={model,graph,geography:presentation,selected,onSelect:choose,onEdge:edge,onGap:gap,action,colourBy,showCompanionLines,context,familyExpanded,onFamily:key=>showGroup(key)};
  const relatedRoles=new Map();const focusIds=new Set(model.nodes.filter(n=>filters.role?n.data.role_id===filters.role:filters.domain?n.data.domain_ids?.includes(filters.domain):false).map(n=>n.id));
  if(focusIds.size)for(const e of model.edges){const a=model.byId.get(e.data.from_id),b=model.byId.get(e.data.to_id);if(focusIds.has(a.id)!==focusIds.has(b.id)){const role=focusIds.has(a.id)?b.data.role_id:a.data.role_id;relatedRoles.set(role,(relatedRoles.get(role)||0)+1);}}
  const counts=field=>{const m=new Map();for(const id of focusIds){const value=model.byId.get(id).data[field];for(const k of Array.isArray(value)?value:[value].filter(Boolean))m.set(k,(m.get(k)||0)+1);}return [...m].map(([id,n])=>`${model.label(id)}: ${n}`).join(' · ');};
  const trailControls=<><div className="l1-direction" role="group" aria-label="Trail direction"><span>Trail:</span>{[['upstream','↑ Upstream'],['downstream','↓ Downstream'],['both','↕ Both']].map(([value,label])=><button key={value} aria-pressed={filters.direction===value} onClick={()=>change('direction',value)}>{label}</button>)}</div><label>Trail depth<select aria-label="Trail depth" value={filters.depth} onChange={e=>change('depth',e.target.value)}>{[['1','Direct'],['2','2'],['3','3'],['full','Full']].map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label></>;
  const focus=()=>{setFamilyExpanded(false);setCascade(true);command('cascade');};
  const showFamily=()=>{setFamilyExpanded(true);setCascade(true);command('cascade');};
  const showGroup=key=>{if(context&&key===`${context.responsibility.data.statement_id}:${context.responsibility.data.statement_revision}`)showFamily();else{setFilters(f=>({...f,group:key}));command('fit');}};
  const sourceDetail=()=>{setInspection({id:selected,kind:'node'});setPanel(true);setSourceReveal(n=>n+1);};
  return <section className={`l1-workspace l1-semantic ${expanded?'l1-expanded':''}`} data-view={view} data-selected={selected} data-trail={graph.trail.nodes.join(',')} data-layout-version={geography.version} data-focused={cascade} data-direction={filters.direction} data-depth={filters.depth}>
    <div className="l1-mode-row">{modeControl}<span>{raw.corpus.sources} JDs · {raw.corpus.responsibilities.toLocaleString()} responsibilities</span>{mode==='draft_review'&&<strong className="l1-draft-banner" role="note">DRAFT REVIEW · NOT APPROVED</strong>}<span className="l1-axis-key">Territory = domain · Height = classified level · Enclosure = source family</span></div>
    <div className="l1-primary-toolbar">
      <div role="tablist" aria-label="Layer 1 representation">{[['3d','3D Network'],['2d','2D Network'],['list','List']].map(([id,label])=><button role="tab" aria-selected={view===id} onClick={()=>switchView(id)} key={id}>{label}</button>)}</div>
      <div className="l1-search"><label><span className="l1-sr-only">Search responsibilities</span><input aria-label="Search responsibilities" placeholder="Find a responsibility…" value={q} onChange={e=>{const value=e.target.value;setQ(value);const exact=model.nodes.find(n=>n.id.toLowerCase()===value.trim().toLowerCase());if(exact)choose(exact.id);}}/></label>{q&&<div className="l1-search-results" role="list" aria-label="Search results"><p>{results.length} distinct records</p>{results.slice(0,100).map(n=><button key={n.id} onClick={()=>choose(n.id)}>{title(n)}<small>{n.id} · {model.label(n.data.role_id)} · {model.label(geography.meta.get(n.id).domain)} · {model.label(n.data.level_id)}</small></button>)}{results.length>100&&<p>First 100 shown; narrow your search.</p>}</div>}</div>
      {selector('role','Role',options('role'))}{selector('domain','Domain',options('term','domain',false))}
      <button disabled={!selected||graph.selectedExcluded} onClick={focus}>Focus selection</button><button onClick={reset}>Home / Show all</button><button aria-expanded={advanced} onClick={()=>setAdvanced(!advanced)}>Filters / Advanced</button><button disabled={!inspection.id} aria-expanded={panel&&!!inspection.id} onClick={()=>setPanel(!panel)}>{panel&&inspection.id?'Hide inspector':'Show inspector'}</button><button onClick={()=>setExpanded(!expanded)}>{expanded?'Restore workspace':'Expand workspace'}</button>
    </div>
    {selected&&<div className="l1-trail-bar"><strong>{selected} · {familyExpanded?'Documentary family':cascade?'Focused organisational context':'Selected responsibility'}</strong>{trailControls}{cascade&&<button onClick={()=>{setCascade(false);command('focus');}}>Exit focus</button>}<button onClick={()=>{setCascade(false);setSelected('');setInspection({id:'',kind:'node'});}}>Clear selection</button></div>}
    {advanced&&<div className="l1-filter-drawer" role="region" aria-label="Advanced filters"><button className="l1-close-filter" onClick={()=>setAdvanced(false)}>Close filters</button><div className="nb-filters">
      <label>Evidence<select aria-label="Evidence" value={filters.evidence} onChange={e=>change('evidence',e.target.value)}><option value="">All evidence</option>{['documentary','inferred','proposed','approved_operational','unresolved'].map(v=><option key={v}>{v}</option>)}</select></label>
      {selector('relationship','Relationship type',options('term','relationship_type'))}{selector('subdomain','Subdomain',options('term','domain',true).filter(r=>!filters.domain||r.data.parent_id===filters.domain))}{selector('action','Action type',options('term','responsibility_type'))}{selector('authority','Authority',options('term','authority_type'))}{selector('level','Responsibility Level',options('term','responsibility_level'))}{selector('source','Source document',options('source'))}
      <label>Review status<select aria-label="Review status" value={filters.review} onChange={e=>change('review',e.target.value)}><option value="">All review states</option>{['draft','proposed','reviewed'].map(v=><option key={v}>{v}</option>)}</select></label><label>Referenced target role<select aria-label="Referenced target role" value={filters.referenced} onChange={e=>{change('referenced',e.target.value);change('showGaps',true);}}><option value="">All handoff roles</option>{[...new Set(model.gaps.map(g=>g.target_role_name))].sort().map(name=><option key={name}>{name}</option>)}</select></label>
      <label>Colour by<select aria-label="Colour by" value={colourBy} onChange={e=>setColourBy(e.target.value)}><option value="role">Role</option><option value="domain">Domain</option></select></label>
    </div><div className="l1-toggles">{[['companions','Documentary companions'],['inferred','Include inferred'],['showGaps','Show unresolved handoffs'],['context','Role/domain focus with connected context'],['isolates','Isolated responsibilities (current full graph)'],['gapsOnly','Responsibilities with unresolved handoffs']].map(([k,label])=><label key={k}><input type="checkbox" checked={filters[k]} onChange={e=>{change(k,e.target.checked);if(k==='gapsOnly')change('showGaps',true);}}/>{label}</label>)}<label><input type="checkbox" checked={showCompanionLines} onChange={e=>setShowCompanionLines(e.target.checked)}/>Show all companion lines</label><button onClick={()=>{setCascade(false);setFilters({...DEFAULTS});}}>Clear filters</button>{filters.group&&<button onClick={()=>change('group','')}>Clear source-statement group focus</button>}</div></div>}
    <p className="l1-context" role="status">{graph.primary.size} filtered responsibilities · {graph.nodes.length-graph.primary.size} external context · {graph.trail.nodes.length} in selected trail · {graph.selectedGaps.length} selected-context handoffs · {graph.globalGaps.length} global handoffs shown / {model.gaps.length} unresolved · {model.nodes.length.toLocaleString()} eligible responsibilities</p>
    {graph.selectedExcluded&&<p className="nb-notice">Selected responsibility is outside these filters. <button onClick={()=>setFilters({...DEFAULTS})}>Reveal selected responsibility</button></p>}
    {graph.trail.nodes.length>1500&&<p className="nb-notice">This trail includes {graph.trail.nodes.length} responsibilities; none truncated. Reduce depth for a clearer view.</p>}
    {!!raw.diagnostics.length&&<details className="l1-diagnostics"><summary>{raw.diagnostics.length} overlay bindings need governance review</summary><ul>{raw.diagnostics.map(d=><li key={d.id}>{d.id}: {d.message}</li>)}</ul></details>}
    {!graph.nodes.length&&<div className="nb-empty">{!raw.corpus.responsibilities?<><p>No responsibility dataset has been imported into this installation.</p><p>Register sources and validate governed data in Sources &amp; exchange.</p></>:mode==='normal'?<><p>No reviewed/active responsibility network is available in Normal View.</p>{canDraftReview&&<button onClick={()=>changeMode('draft_review')}>Enter Draft Review</button>}</>:<><p>No responsibilities match these filters.</p><button onClick={()=>setFilters({...DEFAULTS})}>Clear all filters</button></>}</div>}
    {context&&<OrganisationalPosition compact context={context} model={model} onGap={gap} onEdge={edge} onSelect={choose} onFamily={showFamily} onSource={sourceDetail}/>}
    {familyExpanded&&<button onClick={focus}>Show organisational context</button>}
    <div className={`l1-stage ${panel?'':'l1-stage-wide'}`}><div className="l1-renderer"><div className="l1-view-tools"><span>{cascade?'Focused organisational context · global positions ghosted':'Stable semantic geography'}</span>{view==='3d'&&['top','side','front'].map(type=><button key={type} onClick={()=>command(type)}>{type[0].toUpperCase()+type.slice(1)} view</button>)}<button onClick={()=>command('fit')}>Fit visible</button><button onClick={()=>command('home')}>Reset camera</button><button aria-label="Zoom in" onClick={()=>command('in')}>+</button><button aria-label="Zoom out" onClick={()=>command('out')}>−</button></div>
      <RenderBoundary key={view}><Suspense fallback={<p role="status">Preparing renderer…</p>}>{view==='3d'?<Network3D {...renderProps} cameraMemory={camera3d}/>:view==='2d'?<Network2D {...renderProps} cameraMemory={camera2d}/>:<ListView {...renderProps}/>}</Suspense></RenderBoundary>
      <details className="l1-legend"><summary>Spatial grammar, colours and navigation</summary><p>Territory = governed domain. Height = classified responsibility level, not a judgement of rank or importance. Unknown classifications have an explicit region. Focus arranges the selected trail temporarily; Home restores geography. Proximity creates no relationship.</p><p>Enclosures = source-statement families, never process sequence. Families become explicit on focus; use Show all companion lines to reveal stored companion edges. Dashed pathways = draft / inferred, not approved structure. Amber: support/accountability; blue: collaboration/information; lilac: referral. Arrowheads follow recorded direction; companion edges have none.</p><p>Upstream/downstream follow graph direction, not necessarily management hierarchy. ◇ is an unresolved handoff; its receiving responsibility and classification are unknown. Layout guides are not graph entities.</p><div className="l1-colour-key">{options(colourBy==='role'?'role':'term',colourBy==='domain'?'domain':undefined,colourBy==='domain'?false:undefined).map(r=>{const n=model.nodes.find(n=>colourBy==='role'?n.data.role_id===r.id:geography.meta.get(n.id).domain===r.id);return n&&<span key={r.id}><i style={{background:nodeColor(model,n,colourBy)}}/>{title(r)}</span>;})}</div><p>{geography.levels.map(l=>l.label).join(' · ')}</p></details>
      <details className="l1-more"><summary>Find a connection or unresolved handoff</summary><label>Find connection<input value={connectionQuery} onChange={e=>setConnectionQuery(e.target.value)} placeholder="Connection ID, responsibility ID or relationship…"/></label><p>{connectionMatches.length} matching connections; first 250 shown. Narrow search to locate any connection.</p><label>Inspect connection<select aria-label="Inspect connection" value={graph.edges.some(e=>e.id===inspection.id)?inspection.id:''} onChange={e=>edge(e.target.value)}><option value="">Select a current connection…</option>{connectionChoices.map(e=><option key={e.id} value={e.id}>{e.id} · {model.label(e.data.relationship_type_id)} · {e.data.evidence} / {e.data.review_status} · {e.data.from_id} {e.semantics.directionality==='symmetric'?'—':'→'} {e.data.to_id}</option>)}</select></label>{filters.showGaps&&<label>Inspect unresolved handoff<select aria-label="Inspect unresolved handoff" value={visibleGaps.some(g=>g.id===inspection.id)?inspection.id:''} onChange={e=>gap(e.target.value)}><option value="">Select documentary gap…</option>{visibleGaps.map(g=><option key={g.id} value={g.id}>{g.id} · {g.responsibility_id} → {g.target_role_name} · unresolved</option>)}</select></label>}</details>
      {focusIds.size>0&&<details className="l1-more"><summary>Focused scope · {focusIds.size} responsibilities</summary><p>Domain distribution: {counts('domain_ids')}</p><p>Authority distribution: {counts('authority_type_ids')}</p><p>Boundary role relationships: {[...relatedRoles].map(([id,n])=>model.label(id)+': '+n).join(' · ')||'None'}</p><p>Unresolved outgoing handoffs: {model.gaps.filter(g=>focusIds.has(g.responsibility_id)).length}. Counts do not measure workload.</p></details>}
    </div>{panel&&inspection.id&&<Inspector sourceReveal={sourceReveal} context={context} onCollapse={()=>setPanel(false)} model={model} graph={graph} inspection={inspection} mode={mode} fixtures={fixtures} cache={detailCache} onSelect={choose} onEdge={edge} onGap={gap} onGroup={showGroup} onSource={id=>{setCascade(false);setFilters({...DEFAULTS,source:id});command('fit');}} onGovern={onGovern} onOriginal={onOriginal}/>}</div>
    {!inspection.id&&<p className="l1-inspection-guidance">Select a responsibility, connection or unresolved handoff to inspect its detail below the workspace.</p>}
  </section>;
}
