import React,{useEffect,useMemo,useRef,useState,lazy,Suspense} from 'react';
import * as api from '../../../api/client';
import {adapt,DEFAULTS,layout,selectGraph,searchNodes,title} from './model.mjs';
import Network2D from './Network2D';
import ListView from './ListView';
import Inspector from './Inspector';
import './workspace.css';
const Network3D=lazy(()=>import('./Network3D'));
class RenderBoundary extends React.Component {state={error:false};static getDerivedStateFromError(){return {error:true};}render(){return this.state.error?<p role="alert">This network renderer could not finish. Switch to List or another representation; your analytical context is preserved.</p>:this.props.children;}}
const checked=r=>{if(!r.data.success)throw Error(r.data.error?.message||'Unable to load network');return r.data;};
export default function Workspace({canDraftReview,fixtures,refresh,onGovern,onOriginal,roleFocus}) {
  const [mode,setMode]=useState('normal'),[view,setView]=useState(()=>{try{return ['3d','2d','list'].includes(localStorage.getItem('nb.view'))?localStorage.getItem('nb.view'):'3d';}catch{return '3d';}});
  const [raw,setRaw]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[filters,setFilters]=useState({...DEFAULTS}),[q,setQ]=useState('');
  const [selected,setSelected]=useState(''),[inspection,setInspection]=useState({id:'',kind:'node'}),[panel,setPanel]=useState(true),[expanded,setExpanded]=useState(false),[action,setAction]=useState({type:'home',tick:0});
  const [connectionQuery,setConnectionQuery]=useState('');
  const detailCache=useRef(new Map()),camera3d=useRef(),camera2d=useRef(),performanceRef=useRef({});
  const command=type=>setAction(a=>({type,tick:a.tick+1}));
  useEffect(()=>{if(roleFocus){setFilters({...DEFAULTS,role:roleFocus.id});setSelected('');setInspection({id:'',kind:'node'});command('fit');}},[roleFocus]);
  useEffect(()=>{let cancelled=false;setBusy(true);setError('');setRaw(null);detailCache.current.clear();const t=performance.now();api.getNervousBreakdownTopology({mode,fixtures}).then(checked).then(data=>{if(!cancelled){setRaw(data);performanceRef.current.fetch=performance.now()-t;}}).catch(e=>{if(!cancelled)setError(e.message);}).finally(()=>{if(!cancelled)setBusy(false);});return()=>{cancelled=true;};},[mode,fixtures,refresh]);
  const model=useMemo(()=>{if(!raw)return null;try{return adapt(raw);}catch(e){return {failure:e.message};}},[raw]);
  const [geography,setGeography]=useState(null);
  useEffect(()=>{if(!model||model.failure)return;let cancelled=false;setGeography(null);const worker=new Worker(new URL('./layout.worker.mjs',import.meta.url),{type:'module'});worker.onmessage=({data})=>{if(cancelled)return;if(data.error)setError(data.error);else setGeography({...data.result,revision:model.revision,basis:model});worker.terminate();};worker.onerror=()=>{if(!cancelled)setError('The layout could not be calculated. Refresh to retry.');worker.terminate();};worker.postMessage(raw);return()=>{cancelled=true;worker.terminate();};},[model]);
  const graph=useMemo(()=>model&&!model.failure?selectGraph(model,filters,selected):null,[model,filters,selected]);
  const results=useMemo(()=>model&&!model.failure?searchNodes(model,q):[],[model,q]);
  const choose=id=>{setSelected(id);setInspection({id,kind:'node'});setPanel(true);setQ('');command('focus');};
  const edge=id=>{setInspection({id,kind:'edge'});setPanel(true);};
  const gap=id=>{const g=model?.gaps.find(g=>g.id===id);if(g)setSelected(g.responsibility_id);setInspection({id,kind:'gap'});setPanel(true);command('focus');};
  const change=(k,v)=>setFilters(f=>({...f,[k]:v}));
  const reset=()=>{setFilters({...DEFAULTS});setSelected('');setInspection({id:'',kind:'node'});setQ('');command('home');};
  const switchView=id=>{setView(id);try{localStorage.setItem('nb.view',id);}catch{/* Local preferences are optional. */}if(selected)command('focus');};
  const changeMode=value=>{setMode(value);setSelected('');setInspection({id:'',kind:'node'});setFilters({...DEFAULTS});setQ('');command('home');};
  const options=(kind,category,parent)=>[...model.references.values()].filter(r=>r.kind===kind&&(!category||r.data.category===category)&&(parent===undefined||!!r.data.parent_id===parent)).sort((a,b)=>title(a).localeCompare(title(b)));
  const selector=(key,label,records)=><label>{label}<select aria-label={label} value={filters[key]} onChange={e=>{change(key,e.target.value);if(key==='domain')change('subdomain','');if(key==='role'||key==='domain')command('fit');}}><option value="">All / any</option>{records.map(r=><option key={r.id} value={r.id}>{r.data.parent_id?`${model.label(r.data.parent_id)} / `:''}{title(r)}</option>)}</select></label>;
  const modeControl=<label>Layer 1 mode<select aria-label="Layer 1 mode" value={mode} onChange={e=>changeMode(e.target.value)}><option value="normal">Normal View</option>{canDraftReview&&<option value="draft_review">Governance / Draft Review</option>}</select></label>;
  if(error||model?.failure)return <section>{modeControl}<p role="alert">{error||model.failure}</p><p>Refresh to retry. No organisational data was changed.</p></section>;
  if(!graph||!geography||geography.basis!==model)return <section>{modeControl}<p role="status">{busy?'Loading governed topology…':'Calculating stable organisational geography…'}</p></section>;
  const p=model.byId.get(selected),visibleGaps=graph.gaps;
  const connectionMatches=graph.edges.filter(e=>[e.id,e.data.from_id,e.data.to_id,model.label(e.data.relationship_type_id)].join(' ').toLowerCase().includes(connectionQuery.toLowerCase()));
  const connectionChoices=connectionMatches.slice(0,250);const inspectedEdge=graph.edges.find(e=>e.id===inspection.id);if(inspectedEdge&&!connectionChoices.includes(inspectedEdge))connectionChoices.push(inspectedEdge);
  const renderProps={model,graph,geography,selected,onSelect:choose,onEdge:edge,onGap:gap,action};
  const relatedRoles=new Map();const focusIds=new Set(model.nodes.filter(n=>filters.role?n.data.role_id===filters.role:filters.domain?n.data.domain_ids?.includes(filters.domain):false).map(n=>n.id));
  if(focusIds.size)for(const e of model.edges){const a=model.byId.get(e.data.from_id),b=model.byId.get(e.data.to_id);if(focusIds.has(a.id)!==focusIds.has(b.id)){const role=focusIds.has(a.id)?b.data.role_id:a.data.role_id;relatedRoles.set(role,(relatedRoles.get(role)||0)+1);}}
  const counts=field=>{const m=new Map();for(const id of focusIds){const value=model.byId.get(id).data[field];for(const k of Array.isArray(value)?value:[value].filter(Boolean))m.set(k,(m.get(k)||0)+1);}return [...m].map(([id,n])=>`${model.label(id)}: ${n}`).join(' · ');};
  return <section className={`l1-workspace ${expanded?'l1-expanded':''}`} data-view={view} data-selected={selected} data-trail={graph.trail.nodes.join(',')} data-layout-version={geography.version}>
    <div className="l1-mode-row">{modeControl}<div><strong>Mapped corpus: {raw.corpus.sources} source documents</strong><span> · {raw.corpus.responsibilities.toLocaleString()} responsibilities</span><p>Currently mapped sources describe formal responsibility, not the absolute limits of reasonable work allocation.</p></div></div>
    {mode==='draft_review'&&<div className="l1-draft-banner" role="note"><strong>DRAFT REVIEW · NOT APPROVED ORGANISATIONAL STRUCTURE</strong><span> Documentary ≠ reviewed. Inferred ≠ approved. Exploration is read-only.</span></div>}
    <div className="l1-command-row"><div role="tablist" aria-label="Layer 1 representation">{[['3d','3D Network'],['2d','2D Network'],['list','List']].map(([id,label])=><button role="tab" aria-selected={view===id} onClick={()=>switchView(id)} key={id}>{label}</button>)}</div><div className="nb-toolbar"><button onClick={reset}>Home / Show all</button><button onClick={()=>command('home')}>Reset camera</button><button disabled={!selected||graph.selectedExcluded} onClick={()=>command('focus')}>Focus selection</button><button onClick={()=>command('in')}>Zoom in</button><button onClick={()=>command('out')}>Zoom out</button><button onClick={()=>setPanel(!panel)}>{panel?'Hide inspector':'Show inspector'}</button><button onClick={()=>setExpanded(!expanded)}>{expanded?'Restore workspace':'Expand workspace'}</button></div></div>
    <div className="l1-search"><label>Search responsibilities<input placeholder="Find wording, ID, role, domain or source…" value={q} onChange={e=>setQ(e.target.value)}/></label>{q&&<div className="l1-search-results" role="list" aria-label="Search results"><p>{results.length} distinct records · IDs preserve same-wording provenance</p>{results.slice(0,100).map(n=><button key={n.id} onClick={()=>choose(n.id)}>{n.id} · {title(n)}<small>{model.label(n.data.role_id)} · {model.label(n.data.source_id)} · {n.data.statement_id}</small></button>)}{results.length>100&&<p>First 100 shown; narrow your search to locate a specific record.</p>}</div>}</div>
    <div className="nb-filters">{selector('role','Role',options('role'))}{selector('domain','Domain',options('term','domain',false))}
      <label>Evidence<select aria-label="Evidence" value={filters.evidence} onChange={e=>change('evidence',e.target.value)}><option value="">All evidence</option>{['documentary','inferred','proposed','approved_operational','unresolved'].map(v=><option key={v}>{v}</option>)}</select></label>
      {selector('relationship','Relationship type',options('term','relationship_type'))}
      <label>Trail direction<select aria-label="Trail direction" value={filters.direction} onChange={e=>change('direction',e.target.value)}>{['both','upstream','downstream'].map(x=><option key={x}>{x}</option>)}</select></label>
      <label>Trail depth<select aria-label="Trail depth" value={filters.depth} onChange={e=>change('depth',e.target.value)}>{[['1','Direct'],['2','2'],['3','3'],['full','Full relevant trail']].map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label>
    </div>
    <div className="l1-toggles">{[['companions','Documentary companions'],['inferred','Include inferred'],['showGaps','Show unresolved handoffs'],['context','Role/domain focus with connected context']].map(([k,label])=><label key={k}><input type="checkbox" checked={filters[k]} onChange={e=>change(k,e.target.checked)}/>{label}</label>)}<button onClick={()=>{setFilters({...DEFAULTS});}}>Clear filters</button><button disabled={!selected} onClick={()=>{setSelected('');setInspection({id:'',kind:'node'});}}>Clear selection</button></div>
    <details className="l1-more"><summary>More filters and scope</summary><div className="nb-filters">{selector('subdomain','Subdomain',options('term','domain',true).filter(r=>!filters.domain||r.data.parent_id===filters.domain))}{selector('action','Action type',options('term','responsibility_type'))}{selector('authority','Authority',options('term','authority_type'))}{selector('level','Responsibility Level',options('term','responsibility_level'))}{selector('source','Source document',options('source'))}<label>Review status<select aria-label="Review status" value={filters.review} onChange={e=>change('review',e.target.value)}><option value="">All review states</option>{['draft','proposed','reviewed'].map(v=><option key={v}>{v}</option>)}</select></label><label>Referenced target role<select aria-label="Referenced target role" value={filters.referenced} onChange={e=>{change('referenced',e.target.value);change('showGaps',true);}}><option value="">All handoff roles</option>{[...new Set(model.gaps.map(g=>g.target_role_name))].sort().map(name=><option key={name}>{name}</option>)}</select></label></div><div className="l1-toggles"><label><input type="checkbox" checked={filters.isolates} onChange={e=>change('isolates',e.target.checked)}/>Isolated responsibilities (current full graph)</label><label><input type="checkbox" checked={filters.gapsOnly} onChange={e=>{change('gapsOnly',e.target.checked);change('showGaps',true);}}/>Responsibilities with unresolved handoffs</label>{filters.group&&<button onClick={()=>change('group','')}>Clear source-statement group focus</button>}</div></details>
    <p className="l1-context" role="status">{graph.nodes.length.toLocaleString()} visible / {model.nodes.length.toLocaleString()} eligible responsibilities · {graph.edges.length.toLocaleString()} visible / {model.edges.length.toLocaleString()} current connections · {graph.trail.nodes.length} in trail · {visibleGaps.length} shown / {model.gaps.length} unresolved handoffs {p&&<> · Selected: {p.id} / {model.label(p.data.role_id)}</>}</p>
    {graph.selectedExcluded&&<p className="nb-notice">Selected responsibility {selected} is outside the current filters. Its inspector is retained for context. <button onClick={()=>setFilters({...DEFAULTS})}>Reveal selected responsibility</button></p>}
    {graph.trail.nodes.length>1500&&<p className="nb-notice">This trail includes {graph.trail.nodes.length} responsibilities. No records were truncated; reduce depth or evidence scope for a clearer view.</p>}
    {!!raw.diagnostics.length&&<details className="l1-diagnostics"><summary>{raw.diagnostics.length} overlay bindings need governance review</summary><ul>{raw.diagnostics.map(d=><li key={d.id}>{d.id}: {d.message}</li>)}</ul></details>}
    {focusIds.size>0&&<details className="l1-more"><summary>Focused scope · {focusIds.size} responsibilities · role/domain relationships</summary><p>Domain distribution: {counts('domain_ids')}</p><p>Authority distribution: {counts('authority_type_ids')}</p><p>Boundary role relationships: {[...relatedRoles].map(([id,n])=>`${model.label(id)}: ${n}`).join(' · ')||'None in current graph'}</p><p>Mapped source: {[...new Set([...focusIds].map(id=>model.label(model.byId.get(id).data.source_id)))].join(', ')}</p><p>Unresolved outgoing handoffs: {model.gaps.filter(g=>focusIds.has(g.responsibility_id)).length} · Incoming role references: {model.gaps.filter(g=>g.target_role_id===filters.role).length}. Counts do not measure workload.</p></details>}
    {!graph.nodes.length&&<div className="nb-empty">{!raw.corpus.responsibilities?<><p>No responsibility dataset has been imported into this installation.</p><p>Use Sources &amp; exchange to register documents and validate a governed dataset. Uploading a JD alone does not generate responsibilities or connections.</p></>:mode==='normal'?<><p>No reviewed/active responsibility network is currently available in Normal View.</p>{canDraftReview&&<button onClick={()=>changeMode('draft_review')}>Enter Draft Review</button>}</>:<><p>No currently mapped responsibility matches the active filters.</p><button onClick={()=>setFilters({...DEFAULTS})}>Clear all filters</button></>}</div>}
    <div className={`l1-stage ${panel?'':'l1-stage-wide'}`}><div className="l1-renderer"><RenderBoundary key={view}><Suspense fallback={<p role="status">Preparing 3D renderer…</p>}>{view==='3d'?<Network3D {...renderProps} cameraMemory={camera3d}/>:view==='2d'?<Network2D {...renderProps} cameraMemory={camera2d}/>:<ListView {...renderProps}/>}</Suspense></RenderBoundary>
      <details className="l1-legend"><summary>Legend and navigation</summary><p>● Responsibility · white selected node · bright trail · faded context. Node size marks selection, not importance. Domain regions guide geography; categorical level/authority and topology influence local placement. Height is not seniority, proximity is not a relationship.</p><p>··· Documentary companion: subtle, symmetric, no arrowhead. ··▶ Inferred/draft relationship: dotted arrow, non-approved. ◇ Unresolved handoff: incomplete documentary pathway, never a responsibility node. Mapped role has source-derived responsibilities; referenced role has no receiving responsibility bound here.</p><p>Documentary groups provide zero-hop context; directed trail depth counts organisational relationships, not stored companion-chain distance. Full trail is never silently truncated.</p></details>
      <label>Find connection<input value={connectionQuery} onChange={e=>setConnectionQuery(e.target.value)} placeholder="Connection ID, responsibility ID or relationship…"/></label><p className="nb-legend">{connectionMatches.length} matching connections; selector shows up to 250. Narrow the search to find any current connection.</p><label>Inspect connection<select aria-label="Inspect connection" value={graph.edges.some(e=>e.id===inspection.id)?inspection.id:''} onChange={e=>edge(e.target.value)}><option value="">Select a current connection…</option>{connectionChoices.map(e=><option key={e.id} value={e.id}>{e.id} · {model.label(e.data.relationship_type_id)} · {e.data.evidence} / {e.data.review_status} · {e.data.from_id} {e.semantics.directionality==='symmetric'?'—':'→'} {e.data.to_id}</option>)}</select></label>
      {filters.showGaps&&<label>Inspect unresolved handoff<select aria-label="Inspect unresolved handoff" value={visibleGaps.some(g=>g.id===inspection.id)?inspection.id:''} onChange={e=>gap(e.target.value)}><option value="">Select documentary gap…</option>{visibleGaps.map(g=><option key={g.id} value={g.id}>{g.id} · {g.responsibility_id} → {g.target_role_name} · unresolved</option>)}</select></label>}
    </div>{panel&&<Inspector model={model} graph={graph} inspection={inspection} mode={mode} fixtures={fixtures} cache={detailCache} onSelect={choose} onEdge={edge} onGap={gap} onGroup={key=>{setFilters({...DEFAULTS,group:key});command('fit');}} onSource={id=>{setFilters({...DEFAULTS,source:id});command('fit');}} onGovern={onGovern} onOriginal={onOriginal}/>}</div>
  </section>;
}
