import {readFile,unlink} from 'node:fs/promises';
import {resolve,relative,isAbsolute} from 'node:path';
import {inspectCompiledDocx,mapCompiledRecords} from '../application/compiled-review.js';
import {randomUUID,createHash} from 'node:crypto';
import type {Pool,PoolClient} from 'pg';
import type {z} from 'zod';
import {MCF,MCF_HASH,MCF_ANALYSIS_CONFIG,MANUAL_ENGINE,SOFTWARE_VERSION,SEGMENTER_VERSION,initialSpans,editSpans,seededSample,validateDecision} from '../domain/mcf.js';
import type {datasetInput,mappingInput,sessionInput,decisionInput,representationInput,segmentInput,Span} from '../domain/mcf.js';
import {mapMcfRecords,MCF_EXTRACTOR} from '../application/mcf-import.js';
import type {RawImport} from '../application/mcf-import.js';
import {preserveSource} from '../application/source-acquisition.js';

type Query=Pick<PoolClient,'query'>;
export class McfRepository {
 constructor(readonly db:Pick<Pool,'query'|'connect'>,readonly storageRoot:string){}
 async transaction<T>(fn:(c:PoolClient)=>Promise<T>){const c=await this.db.connect();try{await c.query('BEGIN');const value=await fn(c);await c.query('COMMIT');return value;}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
 async audit(c:Query,dataset:string,action:string,id:string,actor:string,value:unknown){await c.query("INSERT INTO researched.audit_events(id,study_id,entity_kind,entity_id,action,actor,occurred_at,after_value) VALUES($1,$2,'mcf',$3,$4,$5,clock_timestamp(),$6)",[randomUUID(),dataset,id,action,actor,JSON.stringify(value)]);}
 async list(showArchived=false){return(await this.db.query(`SELECT d.*,s.title,researched.mcf_label('datasets',d.id,s.title) AS display_title,researched.mcf_archived('datasets',d.id) AS archived,
 (SELECT count(*)::int FROM researched.mcf_imports i WHERE i.dataset_id=d.id AND NOT researched.mcf_archived('imports',i.id)) AS source_count,
 (SELECT count(*)::int FROM researched.mcf_sessions x WHERE x.dataset_id=d.id AND NOT researched.mcf_archived('sessions',x.id)) AS session_count,
 (SELECT count(*)::int FROM researched.mcf_decisions c JOIN researched.mcf_sessions x ON x.id=c.session_id WHERE x.dataset_id=d.id AND NOT researched.mcf_archived('sessions',x.id)) AS decision_count
 FROM researched.mcf_datasets d JOIN researched.studies s ON s.id=d.id WHERE $1 OR NOT researched.mcf_archived('datasets',d.id) ORDER BY d.created_at DESC`,[showArchived])).rows;}
 async writable(id:string,c:Query){const row=(await c.query("SELECT id,researched.mcf_archived('datasets',id) AS archived FROM researched.mcf_datasets WHERE id=$1 FOR UPDATE",[id])).rows[0];if(!row)throw Error('dataset_not_found');if(row.archived)throw Error('archived_work_restore_first');}
 async active(kind:string,id:string,c:Query){if((await c.query('SELECT researched.mcf_archived($1,$2) AS archived',[kind,id])).rows[0].archived)throw Error('archived_work_restore_first');}

 async dataset(id:string,c:Query=this.db){const row=(await c.query("SELECT d.*,s.title,researched.mcf_label('datasets',d.id,s.title) AS display_title,researched.mcf_archived('datasets',d.id) AS archived FROM researched.mcf_datasets d JOIN researched.studies s ON s.id=d.id WHERE d.id=$1",[id])).rows[0];if(!row)throw Error('dataset_not_found');return row;}
 async create(v:z.infer<typeof datasetInput>){const id=randomUUID();await this.transaction(async c=>{
  await c.query('INSERT INTO researched.mcf_instruments(version,hash,payload) VALUES($1,$2,$3) ON CONFLICT DO NOTHING',[MCF.version,MCF_HASH,JSON.stringify(MCF)]);
  const stored=(await c.query('SELECT hash FROM researched.mcf_instruments WHERE version=$1',[MCF.version])).rows[0];if(stored.hash!==MCF_HASH)throw Error('instrument_version_hash_conflict');
  await c.query("INSERT INTO researched.studies(id,title,research_question,methodology,created_at,updated_at) VALUES($1,$2,'Manual MCF research','MCF v1.0; human coding; no classifier',now(),now())",[id,v.title]);
  await c.query('INSERT INTO researched.mcf_datasets(id,mode,review_category) VALUES($1,$2,$3)',[id,v.mode,v.reviewCategory]);await this.audit(c,id,'dataset_created',id,v.actor,v);
 });return this.dataset(id);}
 async overview(id:string){const dataset=await this.dataset(id);const [imports,records,sessions]=await Promise.all([
  this.db.query(`SELECT i.id,i.filename,researched.mcf_label('imports',i.id,i.filename) AS display_label,researched.mcf_archived('imports',i.id) AS archived,i.created_at,i.snapshot_id,(SELECT count(*)::int FROM researched.mcf_records r WHERE r.import_id=i.id) AS record_count FROM researched.mcf_imports i WHERE dataset_id=$1 ORDER BY created_at DESC`,[id]),
  this.db.query(`SELECT r.id,r.import_id,(SELECT filename FROM researched.mcf_imports WHERE id=r.import_id) AS filename,researched.mcf_archived('imports',r.import_id) AS source_archived,researched.mcf_archived('mappings',r.mapping_id) AS mapping_archived,r.review_identifier,r.institution,r.review_category,r.source_type,r.locator,r.mapping_id,(SELECT version FROM researched.mcf_import_mappings WHERE id=r.mapping_id) AS mapping_version,NOT EXISTS(SELECT 1 FROM researched.mcf_import_mappings m JOIN researched.mcf_import_mappings current ON current.id=r.mapping_id WHERE m.import_id=r.import_id AND m.version>current.version AND NOT researched.mcf_archived('mappings',m.id)) AS active_mapping,length(r.original_text) AS characters,(SELECT max(version) FROM researched.mcf_unit_sets u WHERE u.record_id=r.id) AS segmentation_version,(SELECT count(*)::int FROM researched.mcf_units u WHERE u.unit_set_id=(SELECT id FROM researched.mcf_unit_sets WHERE record_id=r.id AND NOT researched.mcf_archived('unit-sets',id) ORDER BY version DESC LIMIT 1)) AS section_count FROM researched.mcf_records r WHERE dataset_id=$1 ORDER BY created_at,id`,[id]),
  this.db.query("SELECT x.*,researched.mcf_label('sessions',x.id,x.title) AS display_title,researched.mcf_archived('sessions',x.id) AS archived,(SELECT count(*)::int FROM researched.mcf_session_units u WHERE u.session_id=x.id) AS section_count,(SELECT count(DISTINCT unit_id)::int FROM researched.mcf_decisions d WHERE d.session_id=x.id) AS coded_count FROM researched.mcf_sessions x WHERE dataset_id=$1 ORDER BY created_at DESC",[id])]);return{...dataset,imports:imports.rows,records:records.rows,sessions:sessions.rows};}
 async storeImport(dataset:string,filename:string,bytes:Buffer,raw:RawImport,actor:string){await this.dataset(dataset);const id=randomUUID(),source=randomUUID(),snapshot=randomUUID();
  const media=raw.format==='pdf'?'application/pdf':raw.format==='txt'?'text/plain':raw.format==='csv'?'text/csv':'application/octet-stream';
  let path:string|undefined;const hash=createHash('sha256').update(bytes).digest('hex');
  try{await this.transaction(async c=>{await this.writable(dataset,c);path=await preserveSource(this.storageRoot,source,snapshot,bytes,media);await c.query("INSERT INTO researched.sources(id,study_id,label,original_url,source_type,created_at,updated_at) VALUES($1,$2,$3,$4,'document',now(),now())",[source,dataset,filename,`upload://${source}/${encodeURIComponent(filename)}`]);
   await c.query('INSERT INTO researched.source_snapshots(id,source_id,sequence,retrieved_at,content_hash,media_type,byte_length,storage_path,retrieval_metadata) VALUES($1,$2,1,now(),$3,$4,$5,$6,$7)',[snapshot,source,hash,media,bytes.length,path,JSON.stringify({filename,mcf:true})]);
   await c.query('INSERT INTO researched.mcf_imports(id,dataset_id,snapshot_id,filename,extracted,extraction_version) VALUES($1,$2,$3,$4,$5,$6)',[id,dataset,snapshot,filename,JSON.stringify(raw),MCF_EXTRACTOR]);await this.audit(c,dataset,'original_import_preserved',id,actor,{filename,hash,snapshot});});}catch(error){if(path)await unlink(resolve(this.storageRoot,path)).catch(()=>{});throw error;}return this.import(id);}
 async import(id:string){const row=(await this.db.query('SELECT i.*,s.content_hash,s.storage_path,s.byte_length FROM researched.mcf_imports i JOIN researched.source_snapshots s ON s.id=i.snapshot_id WHERE i.id=$1',[id])).rows[0];if(!row)throw Error('import_not_found');return {...row,latestMappingId:(await this.db.query('SELECT id FROM researched.mcf_import_mappings WHERE import_id=$1 ORDER BY version DESC LIMIT 1',[id])).rows[0]?.id??null};}
 async structuralPreview(id:string){const source=await this.import(id);if(source.extracted.format!=='docx')throw Error('docx_required');
  const target=resolve(this.storageRoot,source.storage_path),route=relative(resolve(this.storageRoot),target);if(isAbsolute(route)||route.startsWith('..'))throw Error('invalid_archive_path');
  const data=await readFile(target);if(createHash('sha256').update(data).digest('hex')!==source.content_hash)throw Error('original_hash_mismatch');
  const preview=await inspectCompiledDocx(data);const latest=(await this.db.query('SELECT id,version,configuration FROM researched.mcf_import_mappings WHERE import_id=$1 ORDER BY version DESC LIMIT 1',[id])).rows[0];
  return{...preview,previousRecords:latest?.configuration?.structural?.hash===preview.hash?latest.configuration.structural.records:null,previousMappingId:latest?.id??null,nextVersion:(latest?.version??0)+1};
 }
 async units(c:Query,set:string,text:string,spans:Span[]){for(const [i,s] of spans.entries())await c.query('INSERT INTO researched.mcf_units(id,unit_set_id,ordinal,start_offset,end_offset,original_text) VALUES($1,$2,$3,$4,$5,$6)',[randomUUID(),set,i+1,s.start,s.end,text.slice(s.start,s.end)]);}
 async map(id:string,v:z.infer<typeof mappingInput>){const source=await this.import(id),dataset=await this.dataset(source.dataset_id),preview=v.structural?await this.structuralPreview(id):null,rows=v.structural&&preview?mapCompiledRecords(preview,v.structural,dataset.review_category):mapMcfRecords(source.extracted,v,dataset.review_category),mapping=randomUUID();
  await this.transaction(async c=>{
   await this.writable(source.dataset_id,c);await this.active('imports',id,c);await c.query('SELECT id FROM researched.mcf_imports WHERE id=$1 FOR UPDATE',[id]);
   const previous=(await c.query('SELECT id,version FROM researched.mcf_import_mappings WHERE import_id=$1 ORDER BY version DESC LIMIT 1',[id])).rows[0];
   if(v.structural?(previous?.id??null)!==v.structural.previousMappingId:previous?previous.id!==v.previousMappingId:!!v.previousMappingId)throw Error('stale_mapping');
   await c.query('INSERT INTO researched.mcf_import_mappings(id,import_id,configuration,actor,version,previous_id) VALUES($1,$2,$3,$4,$5,$6)',[mapping,id,JSON.stringify({...v,...(preview?{structuralExtraction:preview}: {})}),v.actor,(previous?.version??0)+1,previous?.id??null]);
   for(const r of rows){const record=randomUUID(),set=randomUUID();await c.query('INSERT INTO researched.mcf_records(id,dataset_id,import_id,mapping_id,review_identifier,institution,review_category,source_type,original_text,working_text,locator,preprocessing) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)',[record,source.dataset_id,id,mapping,r.reviewIdentifier,r.institution,r.reviewCategory,source.extracted.format,r.text,r.text.replace(/\r\n?/g,'\n'),JSON.stringify(r.locator),JSON.stringify({...(v.structural?{source:'Selected structural components; full extraction preserved in mapping configuration',joining:'Two LF characters between nonempty selected source blocks'}:{}),version:'mcf-working-text.v1',normalisation:'CRLF/CR to LF only; units use original text',offsetEncoding:'UTF-16 code units'})]);
    await c.query('INSERT INTO researched.mcf_unit_sets(id,record_id,version,reason,actor,segmenter_version) VALUES($1,$2,1,$3,$4,$5)',[set,record,'Initial sentence segmentation',v.actor,SEGMENTER_VERSION]);await this.units(c,set,r.text,initialSpans(r.text));}
   await this.audit(c,source.dataset_id,'records_derived',mapping,v.actor,{records:rows.length,configuration:v});});return{records:rows.length,mappingId:mapping};}
 async record(id:string,setId?:string){const row=(await this.db.query('SELECT r.*,i.filename,i.snapshot_id FROM researched.mcf_records r JOIN researched.mcf_imports i ON i.id=r.import_id WHERE r.id=$1',[id])).rows[0];if(!row)throw Error('record_not_found');if(row.locator.profile){const mapping=(await this.db.query('SELECT configuration FROM researched.mcf_import_mappings WHERE id=$1',[row.mapping_id])).rows[0];row.sourceComponents=mapping.configuration.structuralExtraction.blocks.slice(row.locator.blockStart,row.locator.blockEnd);}row.sets=(await this.db.query("SELECT *,researched.mcf_archived('unit-sets',id) AS archived FROM researched.mcf_unit_sets WHERE record_id=$1 ORDER BY version DESC",[id])).rows;row.selectedSetId=setId??row.sets.find((s:any)=>!s.archived)?.id??row.sets[0]?.id;if(!row.sets.some((s:any)=>s.id===row.selectedSetId))throw Error('unit_set_not_found');row.units=(await this.db.query('SELECT * FROM researched.mcf_units WHERE unit_set_id=$1 ORDER BY ordinal',[row.selectedSetId])).rows;return row;}
 async segment(recordId:string,v:z.infer<typeof segmentInput>){return this.transaction(async c=>{
  const r=(await c.query('SELECT * FROM researched.mcf_records WHERE id=$1',[recordId])).rows[0];if(!r)throw Error('record_not_found');await this.writable(r.dataset_id,c);await this.active('imports',r.import_id,c);await this.active('mappings',r.mapping_id,c);await this.active('unit-sets',v.baseSetId,c);const set=(await c.query("SELECT * FROM researched.mcf_unit_sets WHERE record_id=$1 AND NOT researched.mcf_archived('unit-sets',id) ORDER BY version DESC LIMIT 1",[recordId])).rows[0];if(set.id!==v.baseSetId)throw Error('stale_segmentation');
  const rows=(await c.query('SELECT * FROM researched.mcf_units WHERE unit_set_id=$1 ORDER BY ordinal',[set.id])).rows;const spans=editSpans(r.original_text,rows.map(u=>({start:u.start_offset,end:u.end_offset})),v.operation,v.ordinal,v.offset),id=randomUUID();
  const version=Number((await c.query('SELECT max(version) AS v FROM researched.mcf_unit_sets WHERE record_id=$1',[recordId])).rows[0].v)+1;
  await c.query('INSERT INTO researched.mcf_unit_sets(id,record_id,parent_id,version,reason,actor,segmenter_version) VALUES($1,$2,$3,$4,$5,$6,$7)',[id,recordId,set.id,version,v.reason,v.actor,'manual-boundaries.v1']);await this.units(c,id,r.original_text,spans);await this.audit(c,r.dataset_id,'segmentation_version_created',id,v.actor,v);return{id,version};});}
 async createSession(datasetId:string,v:z.infer<typeof sessionInput>){await this.dataset(datasetId);return this.transaction(async c=>{
  await this.writable(datasetId,c);const sets=(await c.query(`SELECT DISTINCT ON (r.id) u.id,u.record_id,u.version FROM researched.mcf_records r JOIN researched.mcf_unit_sets u ON u.record_id=r.id WHERE r.dataset_id=$1 AND NOT researched.mcf_archived('imports',r.import_id) AND NOT researched.mcf_archived('mappings',r.mapping_id) AND NOT researched.mcf_archived('unit-sets',u.id) AND NOT EXISTS(SELECT 1 FROM researched.mcf_import_mappings m JOIN researched.mcf_import_mappings current ON current.id=r.mapping_id WHERE m.import_id=r.import_id AND m.version>current.version AND NOT researched.mcf_archived('mappings',m.id)) ORDER BY r.id,u.version DESC`,[datasetId])).rows;
  if(!sets.length)throw Error('import_records_first');const population=(await c.query('SELECT u.id FROM researched.mcf_units u JOIN researched.mcf_unit_sets us ON us.id=u.unit_set_id JOIN researched.mcf_records r ON r.id=us.record_id WHERE u.unit_set_id=ANY($1::uuid[]) ORDER BY r.created_at,r.id,u.ordinal',[sets.map(s=>s.id)])).rows.map(r=>r.id as string);
  if(v.kind==='validation'&&(!population.length||v.sampleSize>population.length))throw Error('sample_size_exceeds_population');if(population.length>25000)throw Error('session_unit_limit');
  if(v.includedUnitIds?.some(id=>!population.includes(id)))throw Error('selection_not_in_prepared_source');
  const selected=v.kind==='validation'?seededSample(population,v.seed,v.sampleSize):v.includedUnitIds??population,id=randomUUID();
  const selectedSets=v.includedUnitIds?[]:sets;
  if(v.includedUnitIds){const ids=(await c.query('SELECT DISTINCT unit_set_id FROM researched.mcf_units WHERE id=ANY($1::uuid[])',[selected])).rows.map(r=>r.unit_set_id);selectedSets.push(...sets.filter(s=>ids.includes(s.id)));}
  const config={analysisConfiguration:MCF_ANALYSIS_CONFIG,unitSets:selectedSets,populationUnitIds:population,selectedUnitIds:selected,seed:v.kind==='validation'?v.seed:null,samplingAlgorithm:v.kind==='validation'?'sha256-json-seed-unit-id-rank.v1':null,populationHash:createHash('sha256').update(JSON.stringify(population)).digest('hex'),preprocessing:'Original UTF-16 offsets; immutable imported record text',machineComparison:null,thresholds:null,blindScope:'Session-local decisions; other sessions are not exposed by this workspace'};
  await c.query('INSERT INTO researched.mcf_sessions(id,dataset_id,title,kind,blind,instrument_version,instrument_hash,engine_version,software_version,configuration,actor) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)',[id,datasetId,v.title,v.kind,v.blind,MCF.version,MCF_HASH,MANUAL_ENGINE,SOFTWARE_VERSION,JSON.stringify(config),v.actor]);
  for(const [i,unit] of selected.entries())await c.query('INSERT INTO researched.mcf_session_units VALUES($1,$2,$3)',[id,unit,i+1]);await this.audit(c,datasetId,'manual_session_created',id,v.actor,{...v,unitCount:selected.length});return{id};});}
 async session(id:string,c:Query=this.db){const s=(await c.query('SELECT s.*,d.mode,d.review_category FROM researched.mcf_sessions s JOIN researched.mcf_datasets d ON d.id=s.dataset_id WHERE s.id=$1',[id])).rows[0];if(!s)throw Error('session_not_found');return s;}
 async workspace(id:string){const s=await this.session(id);
  const units=(await this.db.query(`SELECT u.*,su.ordinal AS session_ordinal,r.id AS record_id,r.review_identifier,r.institution,r.review_category,r.locator,i.filename,
   left(right(left(r.original_text,u.start_offset),150),150) AS context_before,substring(r.original_text FROM u.end_offset+1 FOR 150) AS context_after,
   (SELECT row_to_json(d) FROM researched.mcf_decisions d WHERE d.session_id=su.session_id AND d.unit_id=u.id ORDER BY d.revision DESC LIMIT 1) AS decision
   FROM researched.mcf_session_units su JOIN researched.mcf_units u ON u.id=su.unit_id JOIN researched.mcf_unit_sets us ON us.id=u.unit_set_id JOIN researched.mcf_records r ON r.id=us.record_id JOIN researched.mcf_imports i ON i.id=r.import_id WHERE su.session_id=$1 ORDER BY su.ordinal`,[id])).rows;
  // PostgreSQL substring counts Unicode code points, whereas JS offsets count UTF-16.
  // Compute contexts in JS against original text to keep astral characters traceable.
  const records=(await this.db.query('SELECT r.*,i.filename,i.snapshot_id FROM researched.mcf_records r JOIN researched.mcf_imports i ON i.id=r.import_id WHERE r.id=ANY($1::uuid[])',[s.configuration.unitSets.map((x:any)=>x.record_id)])).rows;
  for(const u of units){const text=records.find(r=>r.id===u.record_id)?.original_text??'';u.context_before=text.slice(Math.max(0,u.start_offset-150),u.start_offset);u.context_after=text.slice(u.end_offset,u.end_offset+150);}
  const representations=(await this.db.query('SELECT DISTINCT ON(record_id,competency_id) * FROM researched.mcf_representation_decisions WHERE session_id=$1 ORDER BY record_id,competency_id,revision DESC',[id])).rows;
  const presentation=(await this.db.query("SELECT researched.mcf_label('sessions',$1,$2) AS display_title,researched.mcf_archived('sessions',$1) AS archived,researched.mcf_archived('datasets',$3) AS dataset_archived",[id,s.title,s.dataset_id])).rows[0];
  const currentSets=(await this.db.query("SELECT DISTINCT ON(record_id) id,record_id FROM researched.mcf_unit_sets WHERE record_id=ANY($1::uuid[]) AND NOT researched.mcf_archived('unit-sets',id) ORDER BY record_id,version DESC",[records.map(r=>r.id)])).rows;
  const currentMappings=(await this.db.query("SELECT DISTINCT ON(import_id) id,import_id FROM researched.mcf_import_mappings WHERE import_id=ANY($1::uuid[]) AND NOT researched.mcf_archived('mappings',id) ORDER BY import_id,version DESC",[records.map(r=>r.import_id)])).rows;
  return{...s,units,records,representations,presentation:{...presentation,historicalText:s.configuration.unitSets.some((u:any)=>currentSets.find(x=>x.record_id===u.record_id)?.id!==u.id)||records.some(r=>currentMappings.find(m=>m.import_id===r.import_id)?.id!==r.mapping_id)}};
 }
 async decide(sessionId:string,unitId:string,v:z.infer<typeof decisionInput>){return this.transaction(async c=>{
  const s=await this.session(sessionId,c);await this.writable(s.dataset_id,c);await this.active('sessions',sessionId,c);const u=(await c.query('SELECT u.* FROM researched.mcf_session_units su JOIN researched.mcf_units u ON u.id=su.unit_id WHERE su.session_id=$1 AND su.unit_id=$2 FOR UPDATE OF su',[sessionId,unitId])).rows[0];if(!u)throw Error('session_unit_not_found');validateDecision(v,u.original_text,s.mode);
  const proposal=v.proposalId?(await c.query('SELECT * FROM researched.mcf_ai_proposals WHERE id=$1 AND session_id=$2 AND unit_id=$3',[v.proposalId,sessionId,unitId])).rows[0]:null;if(v.proposalId&&(!proposal||s.blind||s.kind==='validation'))throw Error('proposal_not_found');
  const previous=(await c.query('SELECT * FROM researched.mcf_decisions WHERE session_id=$1 AND unit_id=$2 ORDER BY revision DESC LIMIT 1',[sessionId,unitId])).rows[0];if((previous?.id??null)!==v.previousId)throw Error('stale_decision');const id=randomUUID();
  await c.query('INSERT INTO researched.mcf_decisions(id,session_id,unit_id,previous_id,revision,codes,valence,reviewed_no_code,notes,actor) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)',[id,sessionId,unitId,v.previousId,(previous?.revision??0)+1,JSON.stringify(v.codes),v.valence,v.reviewedNoCode,v.notes,v.actor]);if(proposal){const original=proposal.payload;const same=v.codes.length===original.codes.length&&v.valence===original.valence&&v.codes.every(code=>original.codes.some((p:any)=>['competencyId','evidenceStrength','valence','rationale','evidence'].every(k=>(code as any)[k]===p[k])));await c.query('INSERT INTO researched.mcf_ai_reviews(id,proposal_id,decision_id,outcome,actor,reason) VALUES($1,$2,$3,$4,$5,$6)',[randomUUID(),proposal.id,id,same?'accepted':'modified',v.actor,v.notes]);}await this.audit(c,s.dataset_id,'manual_coding_appended',id,v.actor,{sessionId,unitId,previousId:v.previousId,...(proposal?{proposalId:proposal.id}:{})});return{id};});}
 async decisionHistory(sessionId:string,unitId:string){await this.session(sessionId);return(await this.db.query('SELECT * FROM researched.mcf_decisions WHERE session_id=$1 AND unit_id=$2 ORDER BY revision DESC',[sessionId,unitId])).rows;}
 async represent(sessionId:string,recordId:string,v:z.infer<typeof representationInput>){return this.transaction(async c=>{
  const s=await this.session(sessionId,c);await this.writable(s.dataset_id,c);await this.active('sessions',sessionId,c);await c.query('SELECT id FROM researched.mcf_sessions WHERE id=$1 FOR UPDATE',[sessionId]);if(s.mode!=='documentary')throw Error('documentary_session_required');if(!s.configuration.unitSets.some((r:any)=>r.record_id===recordId))throw Error('session_record_not_found');
  const evidence=(await c.query('SELECT u.id,r.id AS record_id FROM researched.mcf_session_units su JOIN researched.mcf_units u ON u.id=su.unit_id JOIN researched.mcf_unit_sets us ON us.id=u.unit_set_id JOIN researched.mcf_records r ON r.id=us.record_id WHERE su.session_id=$1 AND u.id=ANY($2::uuid[])',[sessionId,v.evidenceUnitIds])).rows;
  const original=(await c.query('SELECT original_text FROM researched.mcf_records WHERE id=$1',[recordId])).rows[0];if(v.state==='assessed'&&!original?.original_text.trim())throw Error('source_has_no_readable_text_use_unavailable');
  if(evidence.length!==v.evidenceUnitIds.length||evidence.some(e=>e.record_id!==recordId))throw Error('evidence_must_belong_to_session_document');
  const previous=(await c.query('SELECT * FROM researched.mcf_representation_decisions WHERE session_id=$1 AND record_id=$2 AND competency_id=$3 ORDER BY revision DESC LIMIT 1',[sessionId,recordId,v.competencyId])).rows[0];if((previous?.id??null)!==v.previousId)throw Error('stale_decision');const id=randomUUID();
  await c.query('INSERT INTO researched.mcf_representation_decisions(id,session_id,record_id,competency_id,previous_id,revision,state,score,evidence_unit_ids,notes,actor) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)',[id,sessionId,recordId,v.competencyId,v.previousId,(previous?.revision??0)+1,v.state,v.score,JSON.stringify(v.evidenceUnitIds),v.notes,v.actor]);await this.audit(c,s.dataset_id,'documentary_observation_appended',id,v.actor,{sessionId,recordId,competencyId:v.competencyId});return{id};});}
 async representationHistory(session:string,record:string){return(await this.db.query('SELECT * FROM researched.mcf_representation_decisions WHERE session_id=$1 AND record_id=$2 ORDER BY competency_id,revision DESC',[session,record])).rows;}
 async archive(sessionId:string){const {presentation,...session}=await this.workspace(sessionId);const imports=(await this.db.query('SELECT i.*,x.content_hash FROM researched.mcf_imports i JOIN researched.source_snapshots x ON x.id=i.snapshot_id WHERE i.id=ANY($1::uuid[])',[session.records.map((r:any)=>r.import_id)])).rows;const mappings=(await this.db.query('SELECT * FROM researched.mcf_import_mappings WHERE import_id=ANY($1::uuid[])',[imports.map(i=>i.id)])).rows;const decisions=(await this.db.query('SELECT * FROM researched.mcf_decisions WHERE session_id=$1 ORDER BY unit_id,revision',[sessionId])).rows;const representations=(await this.db.query('SELECT * FROM researched.mcf_representation_decisions WHERE session_id=$1 ORDER BY record_id,competency_id,revision',[sessionId])).rows;const unitSets=(await this.db.query('SELECT * FROM researched.mcf_unit_sets WHERE id=ANY($1::uuid[])',[session.configuration.unitSets.map((s:any)=>s.id)])).rows;const populationUnits=(await this.db.query('SELECT * FROM researched.mcf_units WHERE unit_set_id=ANY($1::uuid[]) ORDER BY unit_set_id,ordinal',[unitSets.map(s=>s.id)])).rows;const preservedImports=session.blind?imports.map(({extracted,...metadata})=>({...metadata,extractionOmittedForBlindReview:true})):imports;return{contract:'researched.mcf-manual-export.v1',instrument:MCF,instrumentHash:MCF_HASH,session,imports:preservedImports,mappings,unitSets,populationUnits,decisions,representations,exportedAt:new Date().toISOString(),machineOutputs:[],notice:'Manual research only; no machine classifier or reliability thresholds. Original file downloads remain linked by import ID.'};}
}
