import React,{useState} from 'react';
export default function ContentStart({busy,catalog,connect,start}){
 const [method,setMethod]=useState('document'),[file,setFile]=useState(null),[urls,setUrls]=useState(''),[title,setTitle]=useState('Course and professional development analysis'),[goal,setGoal]=useState('Explain what each course offers, with evidence.'),[questions,setQuestions]=useState('What curriculum and modules are included?\nHow is learning assessed?\nWhat professional development does the course provide?'),[followWebpages,setWeb]=useState(true),[followDocuments,setDocs]=useState(true),[maxDepth,setDepth]=useState(2),[maxPages,setPages]=useState(8),[hosts,setHosts]=useState('');
 const lines=value=>value.split('\n').map(s=>s.trim()).filter(Boolean);
 return <section className="card"><h2>Content analysis</h2><p>Choose your sources and questions. Research’Ed navigates within your rules, then AI analyses the preserved content and answers with source evidence.</p><label>Research title<input value={title} onChange={e=>setTitle(e.target.value)}/></label><h3>1. Add your links</h3><div className="toolbar"><label className="checkbox"><input type="radio" checked={method==='document'} onChange={()=>setMethod('document')}/>Upload a document containing links</label><label className="checkbox"><input type="radio" checked={method==='manual'} onChange={()=>setMethod('manual')}/>Enter links manually</label></div>{method==='document'?<label>Link document<input type="file" accept=".docx,.pdf" onChange={e=>setFile(e.target.files?.[0]??null)}/></label>:<label>Links (one per line)<textarea aria-label="Links (one per line)" value={urls} onChange={e=>setUrls(e.target.value)} placeholder="https://university.example/course"/></label>}
 <h3>2. Choose what to read</h3><label className="checkbox"><input type="checkbox" checked={followWebpages} onChange={e=>setWeb(e.target.checked)}/>Follow relevant links to other webpages</label><label className="checkbox"><input type="checkbox" checked={followDocuments} onChange={e=>setDocs(e.target.checked)}/>Read linked PDFs and documents</label><p>These choices control supporting links found on the supplied pages. Links you enter directly are always treated as requested sources.</p><details><summary>Navigation limits and trusted hosts</summary><div className="form-grid"><label>Supporting link depth<select value={maxDepth} onChange={e=>setDepth(Number(e.target.value))}>{[0,1,2].map(n=><option key={n} value={n}>{n}</option>)}</select></label><label>Maximum pages per source<input type="number" min={1} max={15} value={maxPages} onChange={e=>setPages(Number(e.target.value))}/></label></div><label>Additional trusted hosts<input value={hosts} onChange={e=>setHosts(e.target.value)} placeholder="documents.university.edu"/></label><p>Relevant pages on the source host and its subdomains are allowed. Other hosts require your explicit inclusion here. Navigation is bounded and never delegated to AI.</p></details>
 <h3>3. Set the analysis</h3><label>What do you want to understand?<textarea aria-label="Analysis objective" value={goal} onChange={e=>setGoal(e.target.value)}/></label><label>Questions for AI (one per line)<textarea aria-label="Questions for AI" rows={5} value={questions} onChange={e=>setQuestions(e.target.value)}/></label><p>Content analysis examines what the source says in relation to your questions. Answers distinguish cited findings, missing information and inaccessible sources.</p>{catalog?.provider?<p>AI connection: {catalog.provider.id} / {catalog.provider.model}. Captured passages and your questions will be sent to this connection.</p>:<p>Connect an AI provider to answer your questions. The advanced extraction workflow remains available without AI.</p>}{!catalog?.aiAvailable&&<button onClick={connect}>Connect AI for content analysis</button>}<button className="primary" disabled={busy||!catalog?.aiAvailable||!goal.trim()||!title.trim()||!lines(questions).length||lines(questions).length>20||(method==='document'?!file:!lines(urls).length)} onClick={()=>start({title,goal,questions:lines(questions),followWebpages,followDocuments,maxDepth,maxPages,allowedHosts:hosts.split(',').map(h=>h.trim()).filter(Boolean),file:method==='document'?file:null,urls:method==='manual'?lines(urls):[]})}>Go — analyse content</button>
 </section>;
}
