'use strict';
var crypto=require('crypto');var db=require('../db');var products=require('./products');
var DECISION_ACTIONS=['accepted','rejected','deferred','dismissed'];
function parse(value,fallback){try{return JSON.parse(value);}catch(_){return fallback;}}
function formatAction(row){return Object.assign({},row);}
function decide(insightId,action,actor,options){options=options||{};if(DECISION_ACTIONS.indexOf(action)<0)throw new Error('Decision must be accepted, rejected, deferred or dismissed');
 return db.transaction(function(tx){var insight=tx.query('SELECT * FROM insight_products WHERE id=?',[insightId]).rows[0];if(!insight)throw new Error('Insight not found');products.act(insightId,action,actor.id,{rationale:options.rationale,metadata:options.metadata});var result=tx.query('INSERT INTO decision_log (actor_id,actor_name,action,entity_type,entity_id,context,rationale,related_insight_id) VALUES (?,?,?,?,?,?,?,?)',[actor.id,actor.name||null,action,insight.scope_type,insight.scope_id,JSON.stringify({productType:insight.product_type,title:insight.title,evidence:parse(insight.evidence,[])}),options.rationale||null,insightId]);return result.lastInsertRowid;});}
function createAction(input,actorId){if(!input.title||!input.ownerId)throw new Error('Action title and owner are required');if(input.insightId&&!db.query('SELECT id FROM insight_products WHERE id=?',[input.insightId]).rows.length)throw new Error('Insight not found');var id=crypto.randomUUID(),now=Date.now();db.query('INSERT INTO action_items (id,insight_id,decision_id,title,description,owner_id,created_by,due_at,review_at,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)',[id,input.insightId||null,input.decisionId||null,input.title,input.description||null,input.ownerId,actorId,input.dueAt||null,input.reviewAt||null,now,now]);return id;}
function updateAction(id,input,actorId){var found=db.query('SELECT * FROM action_items WHERE id=?',[id]).rows[0];if(!found)throw new Error('Action not found');var status=input.status||found.status;if(['open','in_progress','completed','cancelled'].indexOf(status)<0)throw new Error('Invalid action status');var now=Date.now();db.query('UPDATE action_items SET status=?,owner_id=?,due_at=?,review_at=?,completed_at=?,completion_note=?,updated_at=? WHERE id=?',[status,input.ownerId||found.owner_id,input.dueAt===undefined?found.due_at:input.dueAt,input.reviewAt===undefined?found.review_at:input.reviewAt,status==='completed'?(found.completed_at||now):null,input.completionNote===undefined?found.completion_note:input.completionNote,now,id]);db.query('INSERT INTO decision_log (actor_id,action,entity_type,entity_id,context,rationale,related_insight_id) VALUES (?,?,?,?,?,?,?)',[actorId,'action.'+status,'action_item',id,JSON.stringify({previousStatus:found.status,newStatus:status}),input.completionNote||null,found.insight_id]);return true;}
function listActions(filter){filter=filter||{};var where=[],params=[];if(filter.ownerId){where.push('owner_id=?');params.push(filter.ownerId);}if(filter.status){where.push('status=?');params.push(filter.status);}if(filter.insightId){where.push('insight_id=?');params.push(filter.insightId);}return db.query('SELECT * FROM action_items'+(where.length?' WHERE '+where.join(' AND '):'')+' ORDER BY CASE WHEN due_at IS NULL THEN 1 ELSE 0 END,due_at,created_at DESC',params).rows.map(formatAction);}
function generateReminders(at,approachingWindowMs){at=at||Date.now();approachingWindowMs=approachingWindowMs||7*86400000;var actions=db.query("SELECT * FROM action_items WHERE status IN ('open','in_progress')").rows;var ids=[];actions.forEach(function(action){var kind=null,target=null;if(action.due_at&&action.due_at<at){kind='overdue';target=action.due_at;}else if(action.due_at&&action.due_at<=at+approachingWindowMs){kind='approaching';target=action.due_at;}else if(action.review_at&&action.review_at<=at){kind='review_due';target=action.review_at;}if(!kind)return;var evidence=[{kind:'action_item',actionId:action.id,status:action.status,dueAt:action.due_at,reviewAt:action.review_at}];var insightId=products.create({type:'reminder',scope:{type:'action_item',id:action.id},title:kind==='overdue'?'Action is overdue':kind==='approaching'?'Action due soon':'Action review is due',summary:action.title,explanation:'This reminder is based on the recorded action date and status.',evidence:evidence,possibleActions:['Open the action','Update its status'],confidence:1,severity:kind==='overdue'?'warning':'information',providerId:'core.action-reminders',providerVersion:'1.0.0',fingerprint:'action-reminder|'+action.id+'|'+kind});try{db.query('INSERT INTO reminder_dispatches (id,action_id,reminder_kind,insight_id,generated_at) VALUES (?,?,?,?,?)',[crypto.randomUUID(),action.id,kind,insightId,at]);}catch(_){}ids.push(insightId);});return ids;}
function recordOutcome(input,actorId){if(!input.description)throw new Error('Outcome description is required');var id=crypto.randomUUID(),now=Date.now();db.query('INSERT INTO outcome_records (id,decision_id,insight_id,entity_type,entity_id,description,measures,recorded_by,occurred_at,recorded_at,action_id) VALUES (?,?,?,?,?,?,?,?,?,?,?)',[id,input.decisionId||null,input.insightId||null,input.entityType||null,input.entityId==null?null:String(input.entityId),input.description,JSON.stringify(input.measures||{}),actorId,input.occurredAt||now,now,input.actionId||null]);db.query('INSERT INTO decision_log (actor_id,action,entity_type,entity_id,context,rationale,related_insight_id) VALUES (?,?,?,?,?,?,?)',[actorId,'outcome.recorded',input.entityType||'outcome',input.entityId==null?id:String(input.entityId),JSON.stringify({outcomeId:id,measures:input.measures||{},actionId:input.actionId||null}),input.description,input.insightId||null]);return id;}
function assessOutcome(outcomeId,input,actorId){var outcome=db.query('SELECT * FROM outcome_records WHERE id=?',[outcomeId]).rows[0];if(!outcome)throw new Error('Outcome not found');if(!input.metricId||!input.scope)throw new Error('Metric and scope are required');var points=db.query('SELECT * FROM metric_points WHERE metric_id=? AND scope_type=? AND scope_id=? ORDER BY period_end',[input.metricId,input.scope.type,String(input.scope.id)]).rows;var baseline=points.filter(function(p){return p.period_start===input.baseline.start&&p.period_end===input.baseline.end;})[0];var followup=points.filter(function(p){return p.period_start===input.followup.start&&p.period_end===input.followup.end;})[0];var assessment='insufficient_evidence',explanation='Comparable baseline and follow-up metric points are not both available.';
 if(baseline&&followup){var difference=followup.value-baseline.value;var tolerance=input.tolerance==null?0:Number(input.tolerance);if(Math.abs(difference)<=tolerance){assessment='unchanged';explanation='The follow-up value ('+followup.value+') is within the stated tolerance of the baseline ('+baseline.value+').';}else{var improved=input.lowerIsBetter!==false?difference<0:difference>0;assessment=improved?'improved':'worsened';explanation='The metric changed from '+baseline.value+' to '+followup.value+'. This describes what followed the action; it does not prove that the action caused the change.';}}
 db.query('UPDATE outcome_records SET assessment=?,assessment_explanation=?,baseline_metric_point_id=?,followup_metric_point_id=? WHERE id=?',[assessment,explanation,baseline?baseline.id:null,followup?followup.id:null,outcomeId]);db.query('INSERT INTO decision_log (actor_id,action,entity_type,entity_id,context,rationale,related_insight_id) VALUES (?,?,?,?,?,?,?)',[actorId,'outcome.assessed','outcome',outcomeId,JSON.stringify({assessment:assessment,metricId:input.metricId,baselinePointId:baseline&&baseline.id,followupPointId:followup&&followup.id}),explanation,outcome.insight_id]);return {assessment:assessment,explanation:explanation,baseline:baseline||null,followup:followup||null};}
function getOutcome(id){var rows=db.query('SELECT * FROM outcome_records WHERE id=?',[id]).rows;if(!rows.length)return null;rows[0].measures=parse(rows[0].measures,{});return rows[0];}
module.exports={decide:decide,createAction:createAction,updateAction:updateAction,listActions:listActions,generateReminders:generateReminders,recordOutcome:recordOutcome,assessOutcome:assessOutcome,getOutcome:getOutcome};
