import React,{useEffect,useState}from"react";
import * as api from"../../api/client";

const message=e=>e?.response?.data?.error?.message||e.message||"The request could not be completed.";
const Field=({label,...props})=><label className="field"><span>{label}</span><input {...props}/></label>;

export default function GradebookSetupPanel({onError,onChanged}){
 const[tab,setTab]=useState("structure"),[data,setData]=useState({years:[],programmes:[],subjects:[],periods:[],groups:[],scales:[],policies:[],standards:[],behaviours:[],categories:[]}),[form,setForm]=useState({});
 const load=async()=>{try{const responses=await Promise.all([api.listAcademicYears(),api.listAcademicProgrammes(),api.listAcademicSubjects(),api.listReportingPeriods(),api.listTeachingGroups(),api.listAssessmentScales(),api.listEvaluationPolicies(),api.listStandardsFrameworks(),api.listBehaviourFrameworks(),api.listAssessmentCategories()]);setData({years:responses[0].data.years||[],programmes:responses[1].data.programmes||[],subjects:responses[2].data.subjects||[],periods:responses[3].data.reporting_periods||[],groups:responses[4].data.teaching_groups||[],scales:responses[5].data.scales||[],policies:responses[6].data.policies||[],standards:responses[7].data.frameworks||[],behaviours:responses[8].data.frameworks||[],categories:responses[9].data.categories||[]});}catch(e){onError(message(e))}};
 useEffect(()=>{load()},[]);
 const set=(key,value)=>setForm(x=>({...x,[key]:value}));
 const run=async(fn)=>{try{await fn();setForm({});await load();onChanged?.()}catch(e){onError(message(e))}};
 return <section className="academic-setup">
  <div className="section-heading"><div><h2>Academic setup</h2><p>Organisation-wide definitions. Published versions remain immutable so historic grades stay auditable.</p></div></div>
  <div className="subtabs">{[["structure","Structure"],["scales","Grading scales"],["policies","Evaluation policies"],["standards","Standards"],["behaviours","Learning behaviours"]].map(([id,label])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}>{label}</button>)}</div>
  {tab==="structure"&&<div className="setup-grid">
   <form className="form-card" onSubmit={e=>{e.preventDefault();run(()=>api.createAcademicProgramme({code:form.code,name:form.name}))}}><h3>New programme</h3><Field label="Code" value={form.code||""} onChange={e=>set("code",e.target.value)} required/><Field label="Name" value={form.name||""} onChange={e=>set("name",e.target.value)} required/><button className="primary">Create programme</button><small>{data.programmes.length} configured</small></form>
   <form className="form-card" onSubmit={e=>{e.preventDefault();run(()=>api.createAcademicSubject({code:form.subject_code,name:form.subject_name,programme_id:form.programme_id||null}))}}><h3>New subject</h3><Field label="Code" value={form.subject_code||""} onChange={e=>set("subject_code",e.target.value)} required/><Field label="Name" value={form.subject_name||""} onChange={e=>set("subject_name",e.target.value)} required/><label className="field"><span>Programme (optional)</span><select value={form.programme_id||""} onChange={e=>set("programme_id",e.target.value)}><option value="">Whole school</option>{data.programmes.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><button className="primary">Create subject</button><small>{data.subjects.length} configured</small></form>
   <form className="form-card" onSubmit={e=>{e.preventDefault();run(()=>api.createReportingPeriod({academic_year_id:+form.year_id,code:form.period_code,name:form.period_name,starts_on:form.starts_on,ends_on:form.ends_on,scope_type:"school",scope_id:"default"}))}}><h3>New reporting period</h3><label className="field"><span>Academic year</span><select required value={form.year_id||""} onChange={e=>set("year_id",e.target.value)}><option value="">Select…</option>{data.years.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><Field label="Code" value={form.period_code||""} onChange={e=>set("period_code",e.target.value)} required/><Field label="Name" value={form.period_name||""} onChange={e=>set("period_name",e.target.value)} required/><Field label="Starts" type="date" value={form.starts_on||""} onChange={e=>set("starts_on",e.target.value)} required/><Field label="Ends" type="date" value={form.ends_on||""} onChange={e=>set("ends_on",e.target.value)} required/><button className="primary">Create period</button></form>
  </div>}
  {tab==="scales"&&<><form className="inline-create" onSubmit={e=>{e.preventDefault();run(()=>api.createAssessmentScale({code:form.scale_code,name:form.scale_name,scale_type:form.scale_type||"percentage",minimum_value:0,maximum_value:form.scale_type==="points"?null:100}))}}><Field label="Code" value={form.scale_code||""} onChange={e=>set("scale_code",e.target.value)} required/><Field label="Name" value={form.scale_name||""} onChange={e=>set("scale_name",e.target.value)} required/><label className="field"><span>Type</span><select value={form.scale_type||"percentage"} onChange={e=>set("scale_type",e.target.value)}>{["percentage","points","letter","proficiency","pass_fail","custom"].map(x=><option key={x}>{x.replaceAll("_"," ")}</option>)}</select></label><button className="primary">Create draft</button></form><RecordList rows={data.scales} extra={x=><>{x.scale_type} · v{x.version} · {x.status}{x.status==="draft"&&<button onClick={()=>run(()=>api.activateAssessmentScale(x.id))}>Activate</button>}</>}/></>}
  {tab==="policies"&&<><form className="inline-create" onSubmit={e=>{e.preventDefault();run(()=>api.createEvaluationPolicy({code:form.policy_code,name:form.policy_name,model:form.model||"percentage",aggregation:form.aggregation||"mean",minimum_evidence:+form.minimum_evidence||1}))}}><Field label="Code" value={form.policy_code||""} onChange={e=>set("policy_code",e.target.value)} required/><Field label="Name" value={form.policy_name||""} onChange={e=>set("policy_name",e.target.value)} required/><label className="field"><span>Model</span><select value={form.model||"percentage"} onChange={e=>set("model",e.target.value)}>{["percentage","points","traditional","standards","hybrid"].map(x=><option key={x}>{x}</option>)}</select></label><label className="field"><span>Aggregation</span><select value={form.aggregation||"mean"} onChange={e=>set("aggregation",e.target.value)}>{["mean","weighted_mean","total_points","latest","highest"].map(x=><option key={x}>{x.replaceAll("_"," ")}</option>)}</select></label><button className="primary">Create draft</button></form><RecordList rows={data.policies} extra={x=><>{x.model} · {x.aggregation} · {x.status}{x.status==="draft"&&<button onClick={()=>run(()=>api.activateEvaluationPolicy(x.id))}>Activate</button>}</>}/></>}
  {tab==="standards"&&<><form className="inline-create" onSubmit={e=>{e.preventDefault();run(()=>api.createStandardsFramework({code:form.standard_code,name:form.standard_name,subject_id:form.standard_subject||null,grade_band:form.grade_band||null}))}}><Field label="Code" value={form.standard_code||""} onChange={e=>set("standard_code",e.target.value)} required/><Field label="Framework name" value={form.standard_name||""} onChange={e=>set("standard_name",e.target.value)} required/><Field label="Grade band" value={form.grade_band||""} onChange={e=>set("grade_band",e.target.value)}/><button className="primary">Create draft</button></form><RecordList rows={data.standards} extra={x=><>{x.grade_band||"All grades"} · v{x.version} · {x.status}{x.status==="draft"&&<button onClick={()=>run(()=>api.activateStandardsFramework(x.id))}>Activate</button>}</>}/></>}
  {tab==="behaviours"&&<><form className="inline-create" onSubmit={e=>{e.preventDefault();run(()=>api.createBehaviourFramework({code:form.behaviour_code,name:form.behaviour_name,description:form.behaviour_description}))}}><Field label="Code" value={form.behaviour_code||""} onChange={e=>set("behaviour_code",e.target.value)} required/><Field label="Framework name" value={form.behaviour_name||""} onChange={e=>set("behaviour_name",e.target.value)} required/><Field label="Description" value={form.behaviour_description||""} onChange={e=>set("behaviour_description",e.target.value)}/><button className="primary">Create draft</button></form><RecordList rows={data.behaviours} extra={x=><>{x.status}{x.status==="draft"&&<button onClick={()=>run(()=>api.activateBehaviourFramework(x.id))}>Activate</button>}</>}/></>}
 </section>;
}

function RecordList({rows,extra}){return <div className="record-list">{rows.length?rows.map(x=><div key={x.id}><span><strong>{x.name}</strong><small>{x.code}</small></span><span>{extra(x)}</span></div>):<p className="empty-state">Nothing configured yet.</p>}</div>}
