import React,{useEffect,useState}from"react";
import * as api from"../../api/client";

const msg=e=>e?.response?.data?.error?.message||e.message||"The request could not be completed.";
const label=x=>String(x||"").replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());
const Field=({label:caption,...props})=><label className="field"><span>{caption}</span><input {...props}/></label>;

export default function ScheduleReviewPanel({setup,version,askConfirmation,onError,onChanged}){
 const[tab,setTab]=useState("placements"),[validation,setValidation]=useState(null),[windows,setWindows]=useState([]),[provider,setProvider]=useState("teacher_preferences"),[records,setRecords]=useState([]),[selected,setSelected]=useState(null),[form,setForm]=useState({});
 const load=async()=>{try{const calls=[api.listSchedulerProgrammeWindows({scheduler_setup_id:setup.id,limit:50}),api.listSchedulerProviderRecords(provider,{scheduler_setup_id:setup.id,limit:50})];if(version.validation_run_id)calls.push(api.getSchedulerValidationRun(version.validation_run_id));const values=await Promise.all(calls);setWindows(values[0].data.windows||[]);setRecords(values[1].data.records||[]);setValidation(values[2]?.data.validation_run||null)}catch(e){onError(msg(e))}};
 useEffect(()=>{load()},[version.id,provider]);
 const lock=async p=>{try{const accepted=!askConfirmation||await askConfirmation({title:p.locked?"Unlock placement?":"Lock placement?",message:`${p.teaching_group_external_key} · week ${p.week_index}, day ${p.day_index}`,confirmLabel:p.locked?"Unlock":"Lock"});if(!accepted)return;await api.setSchedulePlacementLock(version.id,p.id,{locked:!p.locked,expected_revision:version.revision});await onChanged()}catch(e){onError(msg(e))}};
 const override=async e=>{e.preventDefault();try{const accepted=!askConfirmation||await askConfirmation({title:"Apply manual placement override?",message:"The complete timetable will be revalidated and the reason retained permanently.",confirmLabel:"Apply override"});if(!accepted)return;await api.overrideSchedulePlacement(version.id,selected.id,{week_index:+form.week_index,day_index:+form.day_index,start_time:form.start_time,end_time:form.end_time,staff_ids:split(form.staff_ids),room_ids:split(form.room_ids),resource_ids:split(form.resource_ids),reason:form.reason,expected_revision:version.revision});setSelected(null);setForm({});await onChanged()}catch(e){onError(msg(e))}};
 const choose=p=>{setSelected(p);setForm({week_index:p.week_index,day_index:p.day_index,start_time:p.start_time,end_time:p.end_time,staff_ids:(p.staff_ids||[]).join(", "),room_ids:(p.room_ids||[]).join(", "),resource_ids:(p.resource_ids||[]).join(", "),reason:""})};
 return <section className="schedule-review"><div className="subtabs">{[["placements","Placements"],["validation","Validation"],["providers","Input provenance"],["windows","Programme windows"]].map(([id,name])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}>{name}</button>)}</div>
 {tab==="placements"&&<div className="split-workspace"><div className="record-list schedule-placement-list">{version.placements.map((p,i)=><div key={p.id}><span><strong>{i+1}. {p.teaching_group_external_key}</strong><small>Week {p.week_index} · day {p.day_index} · {p.start_time}–{p.end_time}</small><small>{(p.staff_ids||[]).join(", ")||"No staff"} · {(p.room_ids||[]).join(", ")||"No room"}</small></span><span className="header-actions"><button disabled={version.status!=="draft"} onClick={()=>lock(p)}>{p.locked?"Unlock":"Lock"}</button><button disabled={version.status!=="draft"||p.locked} onClick={()=>choose(p)}>Override</button></span></div>)}</div>{selected?<form className="form-card" onSubmit={override}><h3>Manual override</h3><Field label="Week" type="number" min="1" value={form.week_index} onChange={e=>setForm({...form,week_index:e.target.value})} required/><Field label="Day" type="number" min="1" max="7" value={form.day_index} onChange={e=>setForm({...form,day_index:e.target.value})} required/><Field label="Starts" type="time" value={form.start_time} onChange={e=>setForm({...form,start_time:e.target.value})} required/><Field label="Ends" type="time" value={form.end_time} onChange={e=>setForm({...form,end_time:e.target.value})} required/><Field label="Staff IDs" value={form.staff_ids} onChange={e=>setForm({...form,staff_ids:e.target.value})}/><Field label="Room IDs" value={form.room_ids} onChange={e=>setForm({...form,room_ids:e.target.value})}/><Field label="Resource IDs" value={form.resource_ids} onChange={e=>setForm({...form,resource_ids:e.target.value})}/><Field label="Reason" value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})} required/><div className="header-actions"><button className="primary">Validate and apply</button><button type="button" onClick={()=>setSelected(null)}>Cancel</button></div></form>:<p className="empty-state">Select Override to manually adjust an unlocked placement.</p>}</div>}
 {tab==="validation"&&<>{validation?<><section className="metric-grid"><article><strong>{validation.feasible?"Feasible":"Blocked"}</strong><span>Outcome</span></article><article><strong>{validation.score}</strong><span>Penalty score</span></article><article><strong>{validation.findings?.length||0}</strong><span>Explained findings</span></article></section><div className="record-list">{(validation.findings||[]).map((x,i)=><div key={x.id||i}><span><strong>{label(x.constraint_code||x.severity)}</strong><small>{x.message||x.explanation}</small></span><span className="status-pill">{label(x.severity)}</span></div>)}</div></>:<p className="empty-state">This alternative has not been checked yet.</p>}</>}
 {tab==="providers"&&<><label className="field compact"><span>Connected input</span><select value={provider} onChange={e=>setProvider(e.target.value)}>{["teacher_preferences","programme_manager","staff_registry","room_registry","inventory"].map(x=><option key={x} value={x}>{label(x)}</option>)}</select></label><div className="record-list">{records.map((x,i)=><div key={x.id}><span><strong>{i+1}. {x.record_type}</strong><small>{x.external_key} · provider version {x.provider_version||"—"}</small></span><span className="status-pill">{x.status}</span></div>)}{!records.length&&<p className="empty-state">No records have been supplied by this component.</p>}</div></>}
 {tab==="windows"&&<div className="record-list">{windows.map((x,i)=><div key={x.id}><span><strong>{i+1}. {x.name||x.teaching_group_external_key}</strong><small>Week {x.week_index} · day {x.day_index} · {x.start_time}–{x.end_time}</small></span><span>Published Scheduler authority</span></div>)}{!windows.length&&<p className="empty-state">No published programme windows. Programme Manager can only operate inside windows published here.</p>}</div>}
 </section>;
}
function split(value){return String(value||"").split(",").map(x=>x.trim()).filter(Boolean)}
