import React,{useEffect,useState}from"react";
import * as api from"../../api/client";

const msg=e=>e?.response?.data?.error?.message||e.message||"The request could not be completed.";
const Field=({label,...props})=><label className="field"><span>{label}</span><input {...props}/></label>;
const minutes=t=>{const[h,m]=t.split(":").map(Number);return h*60+m};
const clock=n=>`${String(Math.floor(n/60)%24).padStart(2,"0")}:${String(n%60).padStart(2,"0")}`;

export default function SchedulerConfigurationPanel({setup,askConfirmation,onError,onChanged}){
 const[tab,setTab]=useState("shape"),[scopes,setScopes]=useState([]),[structures,setStructures]=useState(null),[rules,setRules]=useState(null),[requirements,setRequirements]=useState([]),[form,setForm]=useState({weeks:1,days:5,periods:7,start:"08:00",duration:50,break_after:3,break_minutes:25,scope_type:"section",level:"soft",occurrences:3});
 const load=async()=>{try{const[s,st,r,q]=await Promise.all([api.listSchedulerScopes(setup.id),api.getSchedulerStructures(setup.id),api.getSchedulerRules(setup.id),api.getSchedulerRequirements(setup.id)]);setScopes(s.data.scopes||[]);setStructures(st.data.structures);setRules(r.data.rules);setRequirements(q.data.requirements||[])}catch(e){onError(msg(e))}};
 useEffect(()=>{load()},[setup.id]);
 const set=(k,v)=>setForm(x=>({...x,[k]:v}));
 const run=async fn=>{try{await fn();await load();onChanged?.()}catch(e){onError(msg(e))}};
 const buildStructure=()=>{const scope=scopes.find(x=>x.status==="active");if(!scope)return onError("Create or reinstate a scheduling scope first.");const weeks=+form.weeks,dayCount=+form.days,count=+form.periods,duration=+form.duration,breakAfter=+form.break_after,breakLength=+form.break_minutes,templates=[{external_key:`single-${duration}`,name:`Single (${duration} minutes)`,duration_minutes:duration}],patterns=[];for(let w=1;w<=weeks;w++)for(let d=1;d<=dayCount;d++){let cursor=minutes(form.start),periods=[];for(let p=1;p<=count;p++){if(p===breakAfter+1){periods.push({external_key:`w${w}d${d}-break`,name:"Break",sequence:periods.length+1,starts_at:clock(cursor),ends_at:clock(cursor+breakLength),kind:"break",counts_as_instruction:false});cursor+=breakLength}periods.push({external_key:`w${w}d${d}-p${p}`,name:`Period ${p}`,sequence:periods.length+1,starts_at:clock(cursor),ends_at:clock(cursor+duration),kind:"instruction",period_template_key:`single-${duration}`,counts_as_instruction:true});cursor+=duration}patterns.push({scheduler_scope_id:scope.id,cycle_week:w,day_index:d,name:["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"][d%7],is_operating_day:true,periods})}return run(()=>api.saveSchedulerStructures({scheduler_setup_id:setup.id,cycle:{name:weeks===2?"A/B rotation":"Standard week",week_count:weeks,week_labels:weeks===2?["A Week","B Week"]:["Week"]},period_templates:templates,day_patterns:patterns}))};
 const addScope=e=>{e.preventDefault();return run(()=>api.createSchedulerScope({scheduler_setup_id:setup.id,external_key:`${form.scope_type}:${form.scope_ref}`,scope_type:form.scope_type,scope_ref:form.scope_ref,name:form.scope_name,configuration:{}}))};
 const addRule=e=>{e.preventDefault();const next=[...(rules?.constraints||[]),{code:form.rule_code,name:form.rule_name,level:form.level,scope_type:"school",scope_ref:"school",rule_type:"preference",parameters:{instruction:form.rule_instruction},explanation_template:form.rule_instruction}];return run(()=>api.saveSchedulerRules({scheduler_setup_id:setup.id,availability:rules?.availability||[],constraints:next,travel_times:rules?.travel_times||[]}))};
 const addRequirement=e=>{e.preventDefault();const item={external_key:`req:${form.group_key}`,academic_year_id:String(setup.academic_year_id),teaching_group_external_key:form.group_key,name:form.group_name,occurrences_per_cycle:+form.occurrences,duration_minutes:+form.req_duration,eligible_staff_ids:split(form.staff_ids),eligible_room_ids:split(form.room_ids),eligible_resource_ids:split(form.resource_ids),allowed_period_template_keys:split(form.template_keys),attributes:{kind:form.kind||"academic",subject_category:form.subject_category||"core",default_gradebook_mode:"graded"},status:"active"};return run(()=>api.saveSchedulerRequirements({scheduler_setup_id:setup.id,requirements:[...requirements,item]}))};
 return <section className="scheduler-config"><div className="section-heading"><div><h2>Timetable configuration</h2><p>Define the timetable before generating alternatives. All philosophy rules remain visible in validation explanations.</p></div></div><div className="subtabs">{[["shape","Day structure"],["scopes","School sections"],["rules","Rules & philosophy"],["requirements","Classes to place"]].map(([id,label])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}>{label}</button>)}</div>
 {tab==="shape"&&<div className="split-workspace"><form className="form-card" onSubmit={e=>{e.preventDefault();buildStructure()}}><h3>Build the operating pattern</h3><label className="field"><span>Rotation</span><select value={form.weeks} onChange={e=>set("weeks",e.target.value)}><option value="1">One week</option><option value="2">A/B two-week rotation</option></select></label><Field label="Operating days per week" type="number" min="1" max="7" value={form.days} onChange={e=>set("days",e.target.value)} required/><Field label="Teaching periods per day" type="number" min="1" max="20" value={form.periods} onChange={e=>set("periods",e.target.value)} required/><Field label="Day starts" type="time" value={form.start} onChange={e=>set("start",e.target.value)} required/><Field label="Standard period length (minutes)" type="number" min="10" value={form.duration} onChange={e=>set("duration",e.target.value)} required/><Field label="Break after period" type="number" min="0" value={form.break_after} onChange={e=>set("break_after",e.target.value)}/><Field label="Break length (minutes)" type="number" min="0" value={form.break_minutes} onChange={e=>set("break_minutes",e.target.value)}/><button className="primary">Save day structure</button></form><Snapshot title="Current structure" lines={[`${structures?.cycle?.week_count||0} week rotation`,`${structures?.day_patterns?.filter(x=>x.is_operating_day).length||0} operating day patterns`,`${structures?.period_templates?.length||0} period templates`]}/></div>}
 {tab==="scopes"&&<div className="split-workspace"><form className="form-card" onSubmit={addScope}><h3>Add a schedulable section</h3><label className="field"><span>Type</span><select value={form.scope_type} onChange={e=>set("scope_type",e.target.value)}>{["section","campus","division","programme"].map(x=><option key={x}>{x}</option>)}</select></label><Field label="Reference" placeholder="secondary" value={form.scope_ref||""} onChange={e=>set("scope_ref",e.target.value)} required/><Field label="Display name" placeholder="Secondary School" value={form.scope_name||""} onChange={e=>set("scope_name",e.target.value)} required/><button className="primary">Add section</button></form><div className="record-list">{scopes.map(x=><div key={x.id}><span><strong>{x.name}</strong><small>{x.scope_type} · {x.status}</small></span>{x.scope_type!=="school"&&(x.status==="active"?<button onClick={()=>confirm(askConfirmation,"Withdraw this scheduling section?",()=>run(()=>api.withdrawSchedulerScope(x.id)))}>Withdraw</button>:<button onClick={()=>run(()=>api.reinstateSchedulerScope(x.id))}>Reinstate</button>)}</div>)}</div></div>}
 {tab==="rules"&&<div className="split-workspace"><form className="form-card" onSubmit={addRule}><h3>Add an explainable rule</h3><Field label="Rule code" placeholder="CORE_BEFORE_LUNCH" value={form.rule_code||""} onChange={e=>set("rule_code",e.target.value)} required/><Field label="Rule name" value={form.rule_name||""} onChange={e=>set("rule_name",e.target.value)} required/><label className="field"><span>Strength</span><select value={form.level} onChange={e=>set("level",e.target.value)}><option value="hard">Hard — never breach</option><option value="soft">Soft — optimise where possible</option><option value="advisory">Advisory — explain only</option></select></label><Field label="Plain-language instruction" value={form.rule_instruction||""} onChange={e=>set("rule_instruction",e.target.value)} required/><button className="primary">Add rule</button></form><Snapshot title="Current rules" lines={[`${rules?.constraints?.filter(x=>x.level==="hard").length||0} hard constraints`,`${rules?.constraints?.filter(x=>x.level==="soft").length||0} soft preferences`,`${rules?.availability?.length||0} availability blocks`,`${rules?.travel_times?.length||0} travel-time rules`]}/></div>}
 {tab==="requirements"&&<div className="split-workspace"><form className="form-card" onSubmit={addRequirement}><h3>Add a class requirement</h3><Field label="Class key" placeholder="grade-7-maths-a" value={form.group_key||""} onChange={e=>set("group_key",e.target.value)} required/><Field label="Class name" value={form.group_name||""} onChange={e=>set("group_name",e.target.value)} required/><Field label="Times per rotation" type="number" min="1" value={form.occurrences} onChange={e=>set("occurrences",e.target.value)} required/><Field label="Duration (minutes)" type="number" min="10" value={form.req_duration||form.duration} onChange={e=>set("req_duration",e.target.value)} required/><Field label="Eligible staff IDs (comma separated)" value={form.staff_ids||""} onChange={e=>set("staff_ids",e.target.value)}/><Field label="Eligible room IDs (comma separated)" value={form.room_ids||""} onChange={e=>set("room_ids",e.target.value)}/><Field label="Eligible resource IDs (comma separated)" value={form.resource_ids||""} onChange={e=>set("resource_ids",e.target.value)}/><Field label="Period template keys" placeholder={`single-${form.duration}`} value={form.template_keys||""} onChange={e=>set("template_keys",e.target.value)}/><button className="primary">Add requirement</button></form><div className="record-list">{requirements.map((x,i)=><div key={x.id||x.external_key}><span><strong>{i+1}. {x.name}</strong><small>{x.occurrences_per_cycle} × {x.duration_minutes} minutes</small></span><span>{x.status}</span></div>)}</div></div>}
 </section>;
}
function Snapshot({title,lines}){return <section className="snapshot-card"><h3>{title}</h3>{lines.map(x=><p key={x}>✓ {x}</p>)}</section>}
function split(value){return String(value||"").split(",").map(x=>x.trim()).filter(Boolean)}
async function confirm(askConfirmation,text,action){const accepted=await askConfirmation?.({title:"Please confirm",message:text,confirmLabel:"Continue",destructive:true});if(accepted)await action()}
