import React,{useEffect,useState}from"react";
import * as api from"../../api/client";

const split=value=>String(value||"").split(",").map(x=>x.trim().toLowerCase()).filter(Boolean);
const label=value=>String(value||"").replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());
const errorText=error=>error.response?.data?.error?.message||error.message;

export default function StudentExitGovernancePanel(){
 const[policy,setPolicy]=useState({}),[studentId,setStudentId]=useState(""),[rules,setRules]=useState([]),[rule,setRule]=useState({rule_kind:"restrict",exit_type_code:"",reason_visibility:"restricted",details:""}),[analytics,setAnalytics]=useState(null),[insights,setInsights]=useState([]),[error,setError]=useState(""),[notice,setNotice]=useState("");
 const load=async()=>{try{const[p,a,i]=await Promise.all([api.getStudentExitPolicy(),api.getStudentExitsAnalytics(),api.getStudentExitsInsights()]);setPolicy(p.data.policy||{});setAnalytics(a.data.analytics||a.data);setInsights(i.data.insights?.issues||i.data.insights||[]);setError("")}catch(e){setError(errorText(e))}};
 useEffect(()=>{void load()},[]);
 const savePolicy=async(action,roles)=>{try{const r=await api.saveStudentExitPolicy({action,roles:split(roles)});setPolicy(r.data.policy||{});setNotice(`${label(action)} permissions updated.`)}catch(e){setError(errorText(e))}};
 const findRules=async event=>{event.preventDefault();try{const r=await api.listStudentExitStudentRules(studentId.trim());setRules(r.data.rules||[]);setError("")}catch(e){setError(errorText(e))}};
 const saveRule=async event=>{event.preventDefault();try{const r=await api.saveStudentExitStudentRule(studentId.trim(),{rule_kind:rule.rule_kind,exit_type_code:rule.exit_type_code||null,reason_visibility:rule.reason_visibility,rule:{details:rule.details},active:true});setRules(r.data.rules||[]);setNotice("Student movement rule recorded with an audit owner.")}catch(e){setError(errorText(e))}};
 return <div className="space-y-5">{error&&<div className="workspace-error">{error}</div>}{notice&&<div className="callout"><strong>Saved</strong><p>{notice}</p></div>}<section className="scheduler-summary"><Summary title="Recorded movements" value={analytics?.summary?.total??analytics?.total??"—"}/><Summary title="Students represented" value={analytics?.summary?.students??analytics?.students??"—"}/><Summary title="Human-review insights" value={Array.isArray(insights)?insights.length:"—"}/></section><section className="split-workspace"><div className="form-card"><h2>Who may perform each action?</h2><p>Comma-separated roles. Superuser access remains protected by the backend.</p>{Object.entries(policy).map(([action,roles])=><PolicyRow key={action} action={action} roles={roles} onSave={savePolicy}/>)}</div><div className="form-card"><h2>Individual movement rules</h2><p>Record restrictions, permissions or accommodations without exposing restricted reasons in the live movement list.</p><form onSubmit={findRules} className="header-actions"><input required placeholder="Student ID" value={studentId} onChange={e=>setStudentId(e.target.value)}/><button>Load rules</button></form>{studentId&&<form onSubmit={saveRule} className="people-form"><label className="field"><span>Rule</span><select value={rule.rule_kind} onChange={e=>setRule({...rule,rule_kind:e.target.value})}>{["allow","restrict","accommodation"].map(x=><option key={x}>{x}</option>)}</select></label><label className="field"><span>Exit type (optional)</span><input value={rule.exit_type_code} onChange={e=>setRule({...rule,exit_type_code:e.target.value})}/></label><label className="field"><span>Reason visibility</span><select value={rule.reason_visibility} onChange={e=>setRule({...rule,reason_visibility:e.target.value})}><option>restricted</option><option>standard</option></select></label><label className="field"><span>Operational instruction</span><input required value={rule.details} onChange={e=>setRule({...rule,details:e.target.value})}/></label><button className="primary">Save rule</button></form>}<div className="stack-list">{rules.map(x=><article key={x.id}><strong>{label(x.rule_kind)} · {x.exit_type_code||"All exit types"}</strong><p>{x.rule?.details||"No operational instruction"}</p><small>{label(x.reason_visibility)} visibility</small></article>)}</div></div></section>{Array.isArray(insights)&&insights.length>0&&<section className="form-card"><h2>Movement insights</h2>{insights.map((x,i)=><div className="callout" key={i}><strong>{label(x.severity||"information")}</strong><p>{x.message||String(x)}</p></div>)}</section>}</div>;
}
function PolicyRow({action,roles,onSave}){const[value,setValue]=useState((roles||[]).join(", "));return <div className="decision-panel"><div><strong>{label(action)}</strong><p>{(roles||[]).length} authorised role(s)</p></div><input value={value} onChange={e=>setValue(e.target.value)}/><button type="button" onClick={()=>onSave(action,value)}>Save</button></div>}
function Summary({title,value}){return <article><strong>{value}</strong><span>{title}</span></article>}
