'use strict';const appScope=require('../../shared/services/appScope'),PARTIES=['user','staff','student','guardian','external'],TYPES=['allergy','intolerance','religious','ethical','texture','other'],SEVERITY=['preference','required','critical'];function scope(r){return appScope.fromRequest(r)}function bad(m,c,s){return{success:false,statusCode:s||400,error:{code:c||'VALIDATION_ERROR',message:m}}}function pg(r){return{page:Math.max(1,+r.query.page||1),limit:Math.min(50,Math.max(1,+r.query.limit||50))}}function audit(c,a,r,t,id,o,n){c.db.query('INSERT INTO audit_log(timestamp,user_id,action,entity_type,entity_id,old_value,new_value,ip_address) VALUES(?,?,?,?,?,?,?,?)',[Date.now(),String(r.user.id),a,t,String(id),o?JSON.stringify(o):null,n?JSON.stringify(n):null,null])}function emit(c,n,id,row){c.events.publish(n,{entityId:id,record:row,__module:'catering'})}function one(c,t,id,s){return c.db.query('SELECT * FROM '+t+' WHERE id=? AND app_id=?',[id,s]).rows[0]}function boot(c){c.log.info('catering booting',{module:'catering'})}function teardown(){}
async function listProviders(r,c){return listing(r,c,'catering_providers','providers','name ASC')}
async function createProvider(r,c){var b=r.body||{},s=scope(r);if(!b.name)return bad('Provider name is required');var x=c.db.query('INSERT INTO catering_providers(app_id,name,contact_name,contact_phone,food_safety_reference,food_safety_expiry,created_by) VALUES(?,?,?,?,?,?,?)',[s,b.name,b.contact_name||null,b.contact_phone||null,b.food_safety_reference||null,b.food_safety_expiry||null,String(r.user.id)]),row=one(c,'catering_providers',x.lastInsertRowid,s);changed(c,r,'provider','create',null,row);return{success:true,provider:row}}
async function updateProvider(r,c){var s=scope(r),old=one(c,'catering_providers',r.params.id,s),b=Object.assign({},old,r.body||{});if(!old)return bad('Provider not found','NOT_FOUND',404);if(!b.name)return bad('Provider name is required');c.db.query("UPDATE catering_providers SET name=?,contact_name=?,contact_phone=?,food_safety_reference=?,food_safety_expiry=?,updated_at=datetime('now') WHERE id=?",[b.name,b.contact_name||null,b.contact_phone||null,b.food_safety_reference||null,b.food_safety_expiry||null,old.id]);var row=one(c,'catering_providers',old.id,s);changed(c,r,'provider','update',old,row);return{success:true,provider:row}}
async function providerStatus(r,c){return status(r,c,'catering_providers','provider',['active','withdrawn'])}
async function listPlans(r,c){var s=scope(r),p=pg(r),w=['x.app_id=?'],v=[s];if(r.query.status){w.push('x.status=?');v.push(r.query.status)}if(r.query.subject_id){w.push('x.subject_id=?');v.push(r.query.subject_id)}var cl=' WHERE '+w.join(' AND '),total=c.db.query('SELECT COUNT(*) total FROM catering_plans x'+cl,v).rows[0].total,rows=c.db.query('SELECT x.*,p.name provider_name,a.name audience_name FROM catering_plans x LEFT JOIN catering_providers p ON p.id=x.provider_id LEFT JOIN audiences a ON a.id=x.audience_id'+cl+' ORDER BY x.service_at DESC,x.id DESC LIMIT ? OFFSET ?',v.concat([p.limit,(p.page-1)*p.limit])).rows.map(hydrate);return{success:true,plans:rows,total:+total,...p}}
function hydrate(x){try{x.declared_allergens=JSON.parse(x.declared_allergens||'[]')}catch(_){x.declared_allergens=[]}return x}
function validatePlan(c,b,s){if(!b.title||!b.subject_component||!b.subject_type||!b.subject_id||!b.delivery_location||!b.service_at||isNaN(Date.parse(b.service_at))||!Number.isInteger(+b.headcount)||+b.headcount<1)return'Title, subject, service time, location and positive headcount are required';if(b.delivery_at&&isNaN(Date.parse(b.delivery_at)))return'Delivery time is invalid';if(b.delivery_at&&Date.parse(b.delivery_at)>Date.parse(b.service_at))return'Delivery must not be after service time';if(b.provider_id&&!c.db.query("SELECT id FROM catering_providers WHERE id=? AND app_id=? AND status='active'",[b.provider_id,s]).rows[0])return'Active catering provider not found';if(b.audience_id&&!c.db.query("SELECT id FROM audiences WHERE id=? AND app_id=? AND status='active'",[b.audience_id,s]).rows[0])return'Active audience not found';return null}
async function createPlan(r,c){var b=r.body||{},s=scope(r),e=validatePlan(c,b,s);if(e)return bad(e);var allergens=Array.isArray(b.declared_allergens)?b.declared_allergens:String(b.declared_allergens||'').split(',').map(x=>x.trim()).filter(Boolean),x=c.db.query('INSERT INTO catering_plans(app_id,subject_component,subject_type,subject_id,title,service_type,provider_id,audience_id,service_at,delivery_at,delivery_location,headcount,menu_summary,declared_allergens,notes,status,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',[s,b.subject_component,b.subject_type,String(b.subject_id),b.title,b.service_type||'meal',b.provider_id||null,b.audience_id||null,b.service_at,b.delivery_at||null,b.delivery_location,+b.headcount,b.menu_summary||null,JSON.stringify(allergens),b.notes||null,b.status==='requested'?'requested':'draft',String(r.user.id)]),row=hydrate(one(c,'catering_plans',x.lastInsertRowid,s));changed(c,r,'plan','create',null,row);return{success:true,plan:row}}
async function updatePlan(r,c){var s=scope(r),old=hydrate(one(c,'catering_plans',r.params.id,s)||{});if(!old.id)return bad('Catering plan not found','NOT_FOUND',404);if(['delivered','cancelled','withdrawn'].includes(old.status))return bad('Catering plan is not editable','INVALID_STATE',409);var b=Object.assign({},old,r.body||{}),e=validatePlan(c,b,s);if(e)return bad(e);var allergens=Array.isArray(b.declared_allergens)?b.declared_allergens:String(b.declared_allergens||'').split(',').map(x=>x.trim()).filter(Boolean);c.db.query("UPDATE catering_plans SET title=?,service_type=?,provider_id=?,audience_id=?,service_at=?,delivery_at=?,delivery_location=?,headcount=?,menu_summary=?,declared_allergens=?,notes=?,updated_at=datetime('now') WHERE id=?",[b.title,b.service_type,b.provider_id||null,b.audience_id||null,b.service_at,b.delivery_at||null,b.delivery_location,+b.headcount,b.menu_summary||null,JSON.stringify(allergens),b.notes||null,old.id]);var row=hydrate(one(c,'catering_plans',old.id,s));changed(c,r,'plan','update',old,row);return{success:true,plan:row}}
async function planStatus(r,c){var result=await status(r,c,'catering_plans','plan',['draft','requested','approved','confirmed','delivered','cancelled','withdrawn'],'delivered');if(result.success)result.plan=hydrate(result.plan);return result}
async function listRequirements(r,c){var s=scope(r),p=pg(r),w=['app_id=?'],v=[s];if(r.query.party_type){w.push('party_type=?');v.push(r.query.party_type)}if(r.query.party_id){w.push('party_id=?');v.push(String(r.query.party_id))}var cl=' WHERE '+w.join(' AND '),total=c.db.query('SELECT COUNT(*) total FROM dietary_requirements'+cl,v).rows[0].total,rows=c.db.query('SELECT * FROM dietary_requirements'+cl+' ORDER BY severity DESC,id DESC LIMIT ? OFFSET ?',v.concat([p.limit,(p.page-1)*p.limit])).rows;return{success:true,requirements:rows,total:+total,...p}}
async function createRequirement(r,c){var b=r.body||{},s=scope(r);if(!PARTIES.includes(b.party_type)||!b.party_id||!TYPES.includes(b.requirement_type)||!b.requirement||!SEVERITY.includes(b.severity||'preference'))return bad('Valid party, requirement type, requirement and severity are required');var x=c.db.query('INSERT INTO dietary_requirements(app_id,party_type,party_id,requirement_type,requirement,severity,handling_notes,created_by) VALUES(?,?,?,?,?,?,?,?)',[s,b.party_type,String(b.party_id),b.requirement_type,b.requirement,b.severity||'preference',b.handling_notes||null,String(r.user.id)]),row=one(c,'dietary_requirements',x.lastInsertRowid,s);changed(c,r,'requirement','create',null,row);return{success:true,requirement:row}}
async function updateRequirement(r,c){var s=scope(r),old=one(c,'dietary_requirements',r.params.id,s),b=Object.assign({},old,r.body||{});if(!old)return bad('Dietary requirement not found','NOT_FOUND',404);if(!TYPES.includes(b.requirement_type)||!b.requirement||!SEVERITY.includes(b.severity))return bad('Valid requirement type, requirement and severity are required');c.db.query("UPDATE dietary_requirements SET requirement_type=?,requirement=?,severity=?,handling_notes=?,updated_at=datetime('now') WHERE id=?",[b.requirement_type,b.requirement,b.severity,b.handling_notes||null,old.id]);var row=one(c,'dietary_requirements',old.id,s);changed(c,r,'requirement','update',old,row);return{success:true,requirement:row}}
async function requirementStatus(r,c){return status(r,c,'dietary_requirements','requirement',['active','withdrawn'])}
async function listing(r,c,table,key,order){var s=scope(r),p=pg(r),total=c.db.query('SELECT COUNT(*) total FROM '+table+' WHERE app_id=?',[s]).rows[0].total,rows=c.db.query('SELECT * FROM '+table+' WHERE app_id=? ORDER BY '+order+' LIMIT ? OFFSET ?',[s,p.limit,(p.page-1)*p.limit]).rows;return{success:true,[key]:rows,total:+total,...p}}
function changed(c,r,type,verb,old,row){audit(c,'catering.'+type+'_'+verb,r,'catering_'+type,row.id,old,row);emit(c,'catering.'+type+'_'+(verb==='create'?'created':'updated'),row.id,row)}
async function status(r,c,table,type,allowed,terminal){var s=scope(r),old=one(c,table,r.params.id,s),to=r.body&&r.body.status;if(!old)return bad('Record not found','NOT_FOUND',404);if(!allowed.includes(to))return bad('Invalid status');if(terminal&&old.status===terminal&&to!==terminal)return bad('Completed catering records are immutable','INVALID_STATE',409);c.db.query("UPDATE "+table+" SET status=?,updated_at=datetime('now') WHERE id=?",[to,old.id]);var row=one(c,table,old.id,s);audit(c,'catering.'+type+'_status',r,'catering_'+type,old.id,old,row);emit(c,'catering.'+type+'_status',row.id,row);return{success:true,[type]:row}}
module.exports={boot,teardown,listProviders,createProvider,updateProvider,providerStatus,listPlans,createPlan,updatePlan,planStatus,listRequirements,createRequirement,updateRequirement,requirementStatus};
