'use strict';

const appScope = require('../../shared/services/appScope');
const gradebookContract = require('../../contracts/gradebook');

function boot(ctx) { ctx.log.info('academic_structure booting', { module: 'academic_structure' }); }
function teardown() {}
function bad(message, code, statusCode) { return { success:false, statusCode:statusCode || 400, error:{ code:code || 'VALIDATION_ERROR', message } }; }
function scope(req) { return appScope.fromRequest(req); }
function text(value) { return String(value == null ? '' : value).trim(); }
function page(req) { return { page:Math.max(1, Number(req.query.page) || 1), limit:Math.min(50, Math.max(1, Number(req.query.limit) || 50)) }; }
function emit(ctx, channel, record) { ctx.events.publish(channel, { entityId:record.id, record, source:'academic_structure', __module:'academic_structure' }); }
function exists(ctx, table, id, appId) { return ctx.db.query('SELECT id FROM ' + table + ' WHERE id=? AND app_id=?', [id, appId]).rows[0]; }

function paged(ctx, req, table, where, params, order) {
  const pg=page(req), clause=' WHERE '+where, total=ctx.db.query('SELECT COUNT(*) total FROM '+table+clause,params).rows[0].total;
  const rows=ctx.db.query('SELECT * FROM '+table+clause+' ORDER BY '+(order||'id DESC')+' LIMIT ? OFFSET ?',params.concat([pg.limit,(pg.page-1)*pg.limit])).rows;
  return { rows, total:Number(total), page:pg.page, limit:pg.limit };
}

async function listYears(req,ctx){ const s=scope(req),r=paged(ctx,req,'academic_years','app_id=?',[s],'starts_on DESC'); return {success:true,years:r.rows,total:r.total,page:r.page,limit:r.limit}; }
async function createYear(req,ctx){ const b=req.body||{},s=scope(req); if(!text(b.code)||!text(b.name)||!text(b.starts_on)||!text(b.ends_on))return bad('Code, name, start date and end date are required'); if(b.starts_on>=b.ends_on)return bad('Academic year end date must follow its start date'); try{const x=ctx.db.query('INSERT INTO academic_years(app_id,code,name,starts_on,ends_on,status) VALUES(?,?,?,?,?,?)',[s,text(b.code),text(b.name),b.starts_on,b.ends_on,b.status||'active']),row=ctx.db.query('SELECT * FROM academic_years WHERE id=?',[x.lastInsertRowid]).rows[0];emit(ctx,'academic_year.created',row);return{success:true,year:row};}catch(e){if(String(e.message).includes('UNIQUE'))return bad('Academic year code already exists','ACADEMIC_YEAR_EXISTS',409);throw e;} }

async function listProgrammes(req,ctx){const s=scope(req),r=paged(ctx,req,'academic_programmes','app_id=?',[s],'name');return{success:true,programmes:r.rows,total:r.total,page:r.page,limit:r.limit};}
async function createProgramme(req,ctx){const b=req.body||{},s=scope(req);if(!text(b.code)||!text(b.name))return bad('Programme code and name are required');try{const x=ctx.db.query('INSERT INTO academic_programmes(app_id,code,name) VALUES(?,?,?)',[s,text(b.code),text(b.name)]);return{success:true,programme:ctx.db.query('SELECT * FROM academic_programmes WHERE id=?',[x.lastInsertRowid]).rows[0]};}catch(e){if(String(e.message).includes('UNIQUE'))return bad('Programme code already exists','PROGRAMME_EXISTS',409);throw e;}}

async function listSubjects(req,ctx){const s=scope(req),r=paged(ctx,req,'academic_subjects','app_id=?',[s],'name');return{success:true,subjects:r.rows,total:r.total,page:r.page,limit:r.limit};}
async function createSubject(req,ctx){const b=req.body||{},s=scope(req);if(!text(b.code)||!text(b.name))return bad('Subject code and name are required');if(b.programme_id&&!exists(ctx,'academic_programmes',b.programme_id,s))return bad('Programme not found','NOT_FOUND',404);try{const x=ctx.db.query('INSERT INTO academic_subjects(app_id,code,name,programme_id) VALUES(?,?,?,?)',[s,text(b.code),text(b.name),b.programme_id||null]);return{success:true,subject:ctx.db.query('SELECT * FROM academic_subjects WHERE id=?',[x.lastInsertRowid]).rows[0]};}catch(e){if(String(e.message).includes('UNIQUE'))return bad('Subject code already exists','SUBJECT_EXISTS',409);throw e;}}

async function listReportingPeriods(req,ctx){const s=scope(req),where=['app_id=?'],p=[s];if(req.query.academic_year_id){where.push('academic_year_id=?');p.push(req.query.academic_year_id)}const r=paged(ctx,req,'reporting_periods',where.join(' AND '),p,'starts_on,sequence,id');return{success:true,reporting_periods:r.rows,total:r.total,page:r.page,limit:r.limit};}
async function createReportingPeriod(req,ctx){const b=req.body||{},s=scope(req);if(!b.academic_year_id||!text(b.code)||!text(b.name)||!text(b.starts_on)||!text(b.ends_on))return bad('Academic year, code, name, start date and end date are required');const year=ctx.db.query('SELECT * FROM academic_years WHERE id=? AND app_id=?',[b.academic_year_id,s]).rows[0];if(!year)return bad('Academic year not found','NOT_FOUND',404);if(b.starts_on<year.starts_on||b.ends_on>year.ends_on||b.starts_on>b.ends_on)return bad('Reporting period must fall within its academic year');const st=b.scope_type||'school',sid=text(b.scope_id)||'default';if(!['school','programme','course','gradebook'].includes(st))return bad('Invalid reporting period scope');try{const x=ctx.db.query('INSERT INTO reporting_periods(app_id,academic_year_id,scope_type,scope_id,code,name,starts_on,ends_on,sequence,credit_fraction) VALUES(?,?,?,?,?,?,?,?,?,?)',[s,b.academic_year_id,st,sid,text(b.code),text(b.name),b.starts_on,b.ends_on,Number(b.sequence)||1,b.credit_fraction==null?null:Number(b.credit_fraction)]),row=ctx.db.query('SELECT * FROM reporting_periods WHERE id=?',[x.lastInsertRowid]).rows[0];emit(ctx,'reporting_period.created',row);return{success:true,reporting_period:row};}catch(e){if(String(e.message).includes('UNIQUE'))return bad('Reporting period code already exists in this scope','REPORTING_PERIOD_EXISTS',409);throw e;}}

function hydrateGroup(ctx,row){row.teachers=ctx.db.query('SELECT * FROM teaching_group_teachers WHERE teaching_group_id=? ORDER BY id',[row.id]).rows;row.students=ctx.db.query('SELECT * FROM teaching_group_enrolments WHERE teaching_group_id=? ORDER BY id',[row.id]).rows;return row;}
async function listTeachingGroups(req,ctx){const s=scope(req),where=['app_id=?'],p=[s];if(req.query.academic_year_id){where.push('academic_year_id=?');p.push(req.query.academic_year_id)}if(req.query.status){where.push('status=?');p.push(req.query.status)}const r=paged(ctx,req,'teaching_groups',where.join(' AND '),p,'name,id');return{success:true,teaching_groups:r.rows.map(x=>hydrateGroup(ctx,x)),total:r.total,page:r.page,limit:r.limit};}
async function createTeachingGroup(req,ctx){const b=req.body||{},s=scope(req);let normalized;try{normalized=gradebookContract.validateTeachingGroup({external_key:text(b.external_key),academic_year_id:String(b.academic_year_id||''),subject_id:b.subject_id==null?null:String(b.subject_id),name:text(b.name),kind:b.kind,status:b.status||'active'});}catch(e){return bad(e.message)}if(!exists(ctx,'academic_years',b.academic_year_id,s))return bad('Academic year not found','NOT_FOUND',404);if(b.subject_id&&!exists(ctx,'academic_subjects',b.subject_id,s))return bad('Subject not found','NOT_FOUND',404);if(b.programme_id&&!exists(ctx,'academic_programmes',b.programme_id,s))return bad('Programme not found','NOT_FOUND',404);const mode=b.default_gradebook_mode||'graded';if(!gradebookContract.GRADEBOOK_MODES.includes(mode))return bad('Invalid gradebook mode');try{const x=ctx.db.query('INSERT INTO teaching_groups(app_id,external_key,source,academic_year_id,subject_id,programme_id,name,kind,default_gradebook_mode,status) VALUES(?,?,?,?,?,?,?,?,?,?)',[s,normalized.external_key,b.source||'manual',b.academic_year_id,b.subject_id||null,b.programme_id||null,normalized.name,normalized.kind,mode,normalized.status]),row=hydrateGroup(ctx,ctx.db.query('SELECT * FROM teaching_groups WHERE id=?',[x.lastInsertRowid]).rows[0]);emit(ctx,'teaching_group.created',row);return{success:true,teaching_group:row};}catch(e){if(String(e.message).includes('UNIQUE'))return bad('Teaching group external key already exists','TEACHING_GROUP_EXISTS',409);throw e;}}

function findGroup(ctx,req){return ctx.db.query('SELECT * FROM teaching_groups WHERE id=? AND app_id=?',[req.params.id,scope(req)]).rows[0];}
async function assignTeacher(req,ctx){const g=findGroup(ctx,req),staff=text((req.body||{}).staff_id);if(!g)return bad('Teaching group not found','NOT_FOUND',404);if(!staff)return bad('Staff ID is required');ctx.db.query("INSERT INTO teaching_group_teachers(teaching_group_id,staff_id,status,withdrawn_at) VALUES(?,?,'active',NULL) ON CONFLICT(teaching_group_id,staff_id) DO UPDATE SET status='active',withdrawn_at=NULL",[g.id,staff]);const row=ctx.db.query('SELECT * FROM teaching_group_teachers WHERE teaching_group_id=? AND staff_id=?',[g.id,staff]).rows[0];emit(ctx,'teaching_group.teacher_assigned',row);return{success:true,assignment:row,teaching_group:hydrateGroup(ctx,g)};}
async function enrolStudent(req,ctx){const g=findGroup(ctx,req),student=text((req.body||{}).student_id);if(!g)return bad('Teaching group not found','NOT_FOUND',404);if(!student)return bad('Student ID is required');ctx.db.query("INSERT INTO teaching_group_enrolments(teaching_group_id,student_id,status,withdrawn_at,withdrawal_reason) VALUES(?,?,'active',NULL,NULL) ON CONFLICT(teaching_group_id,student_id) DO UPDATE SET status='active',withdrawn_at=NULL,withdrawal_reason=NULL",[g.id,student]);const row=ctx.db.query('SELECT * FROM teaching_group_enrolments WHERE teaching_group_id=? AND student_id=?',[g.id,student]).rows[0];emit(ctx,'teaching_group.student_enrolled',row);return{success:true,enrolment:row,teaching_group:hydrateGroup(ctx,g)};}
async function withdrawStudent(req,ctx){const g=findGroup(ctx,req),student=text(req.params.studentId);if(!g)return bad('Teaching group not found','NOT_FOUND',404);const row=ctx.db.query('SELECT * FROM teaching_group_enrolments WHERE teaching_group_id=? AND student_id=?',[g.id,student]).rows[0];if(!row)return bad('Enrolment not found','NOT_FOUND',404);ctx.db.query("UPDATE teaching_group_enrolments SET status='withdrawn',withdrawn_at=datetime('now'),withdrawal_reason=? WHERE id=?",[text((req.body||{}).reason)||null,row.id]);const next=ctx.db.query('SELECT * FROM teaching_group_enrolments WHERE id=?',[row.id]).rows[0];emit(ctx,'teaching_group.student_withdrawn',next);return{success:true,enrolment:next,teaching_group:hydrateGroup(ctx,g)};}

function receive(channel,payload,ctx){if(!payload||payload.source==='academic_structure'||!payload.event_id)return;gradebookContract.validateTeachingGroupEvent(channel,payload);const seen=ctx.db.query('SELECT event_id FROM academic_structure_event_receipts WHERE event_id=?',[payload.event_id]).rows[0];if(seen)return;ctx.db.query('INSERT INTO academic_structure_event_receipts(event_id,channel) VALUES(?,?)',[payload.event_id,channel]);}
function subscriber(channel){return function(payload,ctx){receive(channel,payload,ctx);};}

module.exports={boot,teardown,listYears,createYear,listProgrammes,createProgramme,listSubjects,createSubject,listReportingPeriods,createReportingPeriod,listTeachingGroups,createTeachingGroup,assignTeacher,enrolStudent,withdrawStudent,
  on_teaching_group_created:subscriber('teaching_group.created'),on_teaching_group_updated:subscriber('teaching_group.updated'),on_teaching_group_teacher_assigned:subscriber('teaching_group.teacher_assigned'),on_teaching_group_teacher_unassigned:subscriber('teaching_group.teacher_unassigned'),on_teaching_group_student_enrolled:subscriber('teaching_group.student_enrolled'),on_teaching_group_student_withdrawn:subscriber('teaching_group.student_withdrawn'),on_teaching_group_closed:subscriber('teaching_group.closed')};
