'use strict';
const appScope=require('../../shared/services/appScope'),contract=require('../../contracts/gradebook');
function bad(m,c,s){return{success:false,statusCode:s||400,error:{code:c||'VALIDATION_ERROR',message:m}}}function scope(r){return appScope.fromRequest(r)}
function identity(g){return contract.gradebookIdentity({external_key:g.external_key,academic_year_id:String(g.academic_year_id),subject_id:g.subject_id==null?null:String(g.subject_id),name:g.name,kind:g.kind,status:g.status});}
function provisionGroup(ctx,g){if(!g)return null;const key=identity(g),status=g.status==='closed'?'closed':g.status==='withdrawn'?'withdrawn':'active';ctx.db.query("INSERT INTO gradebook_instances(app_id,teaching_group_id,identity_key,academic_year_id,subject_id,name,mode,status,closed_at) VALUES(?,?,?,?,?,?,?,?,CASE WHEN ?='closed' THEN datetime('now') ELSE NULL END) ON CONFLICT(app_id,teaching_group_id) DO UPDATE SET identity_key=excluded.identity_key,academic_year_id=excluded.academic_year_id,subject_id=excluded.subject_id,name=excluded.name,status=excluded.status,updated_at=datetime('now'),closed_at=CASE WHEN excluded.status='closed' THEN COALESCE(gradebook_instances.closed_at,datetime('now')) ELSE gradebook_instances.closed_at END",[g.app_id,g.id,key,g.academic_year_id,g.subject_id,g.name,g.default_gradebook_mode,status,status]);return ctx.db.query('SELECT * FROM gradebook_instances WHERE app_id=? AND teaching_group_id=?',[g.app_id,g.id]).rows[0];}
function reconcileAll(ctx,appId){const groups=ctx.db.query('SELECT * FROM teaching_groups'+(appId?' WHERE app_id=?':''),appId?[appId]:[]).rows;let created=0,updated=0;groups.forEach(g=>{const before=ctx.db.query('SELECT id FROM gradebook_instances WHERE app_id=? AND teaching_group_id=?',[g.app_id,g.id]).rows[0],row=provisionGroup(ctx,g);if(before)updated++;else{created++;ctx.events.publish('gradebook.instance.provisioned',{entityId:row.id,record:row,source:'gradebook_core',__module:'gradebook_core'});}});return{created,updated,total:groups.length};}
function boot(ctx){const result=reconcileAll(ctx);ctx.log.info('gradebook_core booting',{module:'gradebook_core',reconciled:result.total});}function teardown(){}
async function list(req,ctx){const s=scope(req),w=['g.app_id=?'],p=[s];if(req.query.status){w.push('g.status=?');p.push(req.query.status)}if(req.query.mode){w.push('g.mode=?');p.push(req.query.mode)}if(req.query.academic_year_id){w.push('g.academic_year_id=?');p.push(req.query.academic_year_id)}const pg=Math.max(1,+req.query.page||1),limit=Math.min(50,Math.max(1,+req.query.limit||50)),cl=' WHERE '+w.join(' AND '),total=ctx.db.query('SELECT COUNT(*) total FROM gradebook_instances g'+cl,p).rows[0].total,rows=ctx.db.query('SELECT g.*,t.kind,t.external_key FROM gradebook_instances g JOIN teaching_groups t ON t.id=g.teaching_group_id'+cl+' ORDER BY g.name,g.id LIMIT ? OFFSET ?',p.concat([limit,(pg-1)*limit])).rows;return{success:true,gradebooks:rows,total:+total,page:pg,limit};}
function hydrate(ctx,row){if(!row)return row;row.teachers=ctx.db.query("SELECT * FROM teaching_group_teachers WHERE teaching_group_id=? AND status='active' ORDER BY id",[row.teaching_group_id]).rows;row.students=ctx.db.query('SELECT * FROM teaching_group_enrolments WHERE teaching_group_id=? ORDER BY id',[row.teaching_group_id]).rows;row.reporting_periods=ctx.db.query("SELECT * FROM reporting_periods WHERE app_id=? AND academic_year_id=? AND status='active' ORDER BY CASE scope_type WHEN 'gradebook' THEN 1 WHEN 'course' THEN 2 WHEN 'programme' THEN 3 ELSE 4 END,sequence,starts_on",[row.app_id,row.academic_year_id]).rows;return row;}
async function read(req,ctx){const row=ctx.db.query('SELECT * FROM gradebook_instances WHERE id=? AND app_id=?',[req.params.id,scope(req)]).rows[0];return row?{success:true,gradebook:hydrate(ctx,row)}:bad('Gradebook not found','NOT_FOUND',404);}
async function setMode(req,ctx){const s=scope(req),mode=req.body&&req.body.mode;if(!contract.GRADEBOOK_MODES.includes(mode))return bad('Invalid gradebook mode');const row=ctx.db.query('SELECT * FROM gradebook_instances WHERE id=? AND app_id=?',[req.params.id,s]).rows[0];if(!row)return bad('Gradebook not found','NOT_FOUND',404);ctx.db.query("UPDATE gradebook_instances SET mode=?,updated_at=datetime('now') WHERE id=?",[mode,row.id]);const next=ctx.db.query('SELECT * FROM gradebook_instances WHERE id=?',[row.id]).rows[0];ctx.events.publish('gradebook.instance.updated',{entityId:row.id,record:next,source:'gradebook_core',__module:'gradebook_core'});return{success:true,gradebook:next};}
async function reconcile(req,ctx){return{success:true,reconciliation:reconcileAll(ctx,scope(req))};}
function syncPayload(payload,ctx){if(!payload||payload.source==='gradebook_core')return;const record=payload.record||payload.teaching_group;if(!record||!record.id)return;const row=provisionGroup(ctx,record);ctx.events.publish(row.status==='closed'?'gradebook.instance.closed':'gradebook.instance.updated',{entityId:row.id,record:row,source:'gradebook_core',__module:'gradebook_core'});}
function on_teaching_group_created(p,c){syncPayload(p,c)}function on_teaching_group_updated(p,c){syncPayload(p,c)}function on_teaching_group_closed(p,c){syncPayload(p,c)}
module.exports={boot,teardown,list,read,setMode,reconcile,on_teaching_group_created,on_teaching_group_updated,on_teaching_group_closed};
