export type PlannedCandidate=Readonly<{id:string;grade:"A"|"B"|"C";score:number;garments:readonly Readonly<{id:string;slotId:string}>[]}>;
export type PriorAssignment=Readonly<{date:string;outfitId:string;garments:readonly Readonly<{id:string;slotId:string}>[]}>;
export type RotationPolicy=Readonly<{completeOutfitDays:number;garmentDays:Readonly<Record<string,number>>;maximumConsecutiveJacketDays:number;allowGradeC:boolean}>;
export type RotationAssignment=Readonly<{date:string;outfitId:string;rotationScore:number;explanations:readonly string[]}>;

const daysBetween=(later:string,earlier:string)=>Math.round((Date.parse(`${later}T00:00:00Z`)-Date.parse(`${earlier}T00:00:00Z`))/86400000);
const dateRange=(start:string,end:string,weekdays:readonly number[])=>{const values:string[]=[];for(let date=new Date(`${start}T00:00:00Z`);date<=new Date(`${end}T00:00:00Z`);date.setUTCDate(date.getUTCDate()+1)){const iso=date.toISOString().slice(0,10);if(weekdays.includes(date.getUTCDay()))values.push(iso)}return values};

export function planRotation(input:{startDate:string;endDate:string;weekdays:readonly number[];candidates:readonly PlannedCandidate[];history?:readonly PriorAssignment[];fixedGarmentIds?:readonly string[];excludedGarmentIds?:readonly string[];policy:RotationPolicy}):readonly RotationAssignment[]{const history=[...(input.history??[])],fixed=new Set(input.fixedGarmentIds??[]),excluded=new Set(input.excludedGarmentIds??[]);const eligible=input.candidates.filter((candidate)=>(input.policy.allowGradeC||candidate.grade!=="C")&&[...fixed].every((id)=>candidate.garments.some((garment)=>garment.id===id))&&!candidate.garments.some((garment)=>excluded.has(garment.id))).sort((a,b)=>b.score-a.score||a.id.localeCompare(b.id));if(!eligible.length)throw new Error("no_eligible_saved_outfits");const assignments:RotationAssignment[]=[];for(const date of dateRange(input.startDate,input.endDate,input.weekdays)){const ranked=eligible.map((candidate)=>{let rotationScore=candidate.grade==="A"?100:candidate.grade==="B"?85:70;const explanations=[`Grade ${candidate.grade} styling score ${candidate.score}.`];const lastOutfit=[...history].reverse().find((entry)=>entry.outfitId===candidate.id);if(lastOutfit){const elapsed=daysBetween(date,lastOutfit.date),minimum=input.policy.completeOutfitDays;if(elapsed<minimum){const penalty=(minimum-elapsed)*2;rotationScore-=penalty;explanations.push(`Complete outfit used ${elapsed} day(s) ago; ${minimum} preferred.`)}}for(const garment of candidate.garments){const previous=[...history].reverse().find((entry)=>entry.garments.some((item)=>item.id===garment.id));if(!previous)continue;const elapsed=daysBetween(date,previous.date),minimum=input.policy.garmentDays[garment.slotId]??input.policy.garmentDays.default??0;if(elapsed<minimum){rotationScore-=minimum-elapsed;explanations.push(`${garment.slotId} repeats after ${elapsed} day(s); ${minimum} preferred.`)}}return{candidate,rotationScore,explanations}}).sort((a,b)=>b.rotationScore-a.rotationScore||b.candidate.score-a.candidate.score||a.candidate.id.localeCompare(b.candidate.id));const selected=ranked[0]!;const assignment={date,outfitId:selected.candidate.id,rotationScore:selected.rotationScore,explanations:Object.freeze(selected.explanations)};assignments.push(assignment);history.push({date,outfitId:selected.candidate.id,garments:selected.candidate.garments})}return Object.freeze(assignments)}
