import React,{useEffect,useState}from"react";
import * as api from"../../api/client";
import Pagination from"../components/Pagination";

const stage=()=>({name:"",approver_type:"role",approver_id:"",required_decisions:1});
const empty=()=>({title:"",description:"",subject_component:"",subject_type:"",subject_id:"",stages:[stage()]});
export default function ApprovalsWidget({askConfirmation}){
 const [rows,setRows]=useState([]),[form,setForm]=useState(empty()),[editing,setEditing]=useState(null),[page,setPage]=useState(1),[total,setTotal]=useState(0),[search,setSearch]=useState(""),[status,setStatus]=useState(""),[error,setError]=useState(""),[message,setMessage]=useState("");
 const [decision,setDecision]=useState(null),[decisionForm,setDecisionForm]=useState({outcome:"approved",comments:""});
 const load=async()=>{try{const r=await api.listApprovalRequests({page,limit:50,q:search,status:status||undefined});setRows(r.data.requests||[]);setTotal(r.data.total||0);setError("");}catch(e){setError(e.response?.data?.error?.message||e.message);}};
 useEffect(()=>{void load();},[page,search,status]);
 useEffect(()=>{window.dispatchEvent(new CustomEvent("principaled:dirty-state",{detail:Boolean(form.title||editing||decision)}));return()=>window.dispatchEvent(new CustomEvent("principaled:dirty-state",{detail:false}));},[form.title,editing,decision]);
 const patchStage=(i,key,value)=>setForm({...form,stages:form.stages.map((s,n)=>n===i?{...s,[key]:value}:s)});
 const save=async e=>{e.preventDefault();try{if(editing)await api.updateApprovalRequest(editing,form);else await api.createApprovalRequest(form);setForm(empty());setEditing(null);setMessage(editing?"Approval request updated":"Approval request created as draft");await load();}catch(err){setError(err.response?.data?.error?.message||err.message);}};
 const edit=row=>{setEditing(row.id);setForm({title:row.title,description:row.description||"",subject_component:row.subject_component,subject_type:row.subject_type,subject_id:row.subject_id,stages:row.stages.map(s=>({name:s.name,approver_type:s.approver_type,approver_id:s.approver_id,required_decisions:s.required_decisions}))});window.scrollTo({top:0,behavior:"smooth"});};
 const submit=async row=>{if(await askConfirmation({title:"Submit approval request?",message:"Stages and subject details become locked while this decision cycle is active.",confirmLabel:"Submit"})){try{await api.submitApprovalRequest(row.id);await load();}catch(err){setError(err.response?.data?.error?.message||err.message);}}};
 const lifecycle=async(row,next)=>{if(await askConfirmation({title:`${next==="withdrawn"?"Withdraw":"Reinstate"} approval request?`,message:next==="withdrawn"?"The request and its history will be retained.":"The request will return to draft and require submission.",confirmLabel:next==="withdrawn"?"Withdraw":"Reinstate",destructive:next==="withdrawn"})){try{await api.setApprovalRequestStatus(row.id,next);await load();}catch(err){setError(err.response?.data?.error?.message||err.message);}}};
 const recordDecision=async e=>{e.preventDefault();const label=decisionForm.outcome==="approved"?"Approve":"Reject";if(!await askConfirmation({title:`${label} this stage?`,message:"Decisions are immutable once recorded.",confirmLabel:label,destructive:decisionForm.outcome==="rejected"}))return;try{await api.decideApprovalStage(decision.row.id,decision.stage.id,decisionForm);setDecision(null);setDecisionForm({outcome:"approved",comments:""});await load();}catch(err){setError(err.response?.data?.error?.message||err.message);}};
 return <div className="space-y-5"><header><span className="text-xs uppercase tracking-widest text-purple-400">Reusable workflow component</span><h1 className="text-3xl font-semibold">Approvals</h1><p className="text-gray-400">Apply auditable, ordered decisions to records owned anywhere on the platform.</p></header>{error&&<p className="rounded border border-red-700 bg-red-950/40 p-3 text-red-200">{error}</p>}{message&&<p className="text-emerald-400">{message}</p>}
 <form onSubmit={save} className="rounded border border-gray-800 bg-gray-900/60 p-4"><h2 className="mb-3 font-semibold">{editing?"Edit draft request":"Create approval request"}</h2><div className="grid gap-3 md:grid-cols-3"><input required className="rounded bg-gray-950 p-2" placeholder="Request title" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><input required className="rounded bg-gray-950 p-2" placeholder="Subject component" value={form.subject_component} onChange={e=>setForm({...form,subject_component:e.target.value})}/><input required className="rounded bg-gray-950 p-2" placeholder="Subject type" value={form.subject_type} onChange={e=>setForm({...form,subject_type:e.target.value})}/><input required className="rounded bg-gray-950 p-2" placeholder="Subject identifier" value={form.subject_id} onChange={e=>setForm({...form,subject_id:e.target.value})}/><textarea className="rounded bg-gray-950 p-2 md:col-span-2" placeholder="Description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></div><h3 className="mt-4 text-sm font-semibold">Ordered stages</h3>{form.stages.map((s,i)=><div key={i} className="mt-2 grid gap-2 rounded border border-gray-800 p-3 md:grid-cols-5"><span className="self-center text-gray-400">{i+1}</span><input required className="rounded bg-gray-950 p-2" placeholder="Stage name" value={s.name} onChange={e=>patchStage(i,"name",e.target.value)}/><select className="rounded bg-gray-950 p-2" value={s.approver_type} onChange={e=>patchStage(i,"approver_type",e.target.value)}><option value="role">Role</option><option value="team">Team</option><option value="staff">Staff</option><option value="user">User</option></select><input required className="rounded bg-gray-950 p-2" placeholder="Approver identifier" value={s.approver_id} onChange={e=>patchStage(i,"approver_id",e.target.value)}/><div className="flex gap-2"><input required type="number" min="1" className="w-20 rounded bg-gray-950 p-2" aria-label="Required decisions" value={s.required_decisions} onChange={e=>patchStage(i,"required_decisions",Number(e.target.value))}/>{form.stages.length>1&&<button type="button" className="text-red-300" onClick={()=>setForm({...form,stages:form.stages.filter((_,n)=>n!==i)})}>Remove</button>}</div></div>)}<div className="mt-3 flex flex-wrap gap-2"><button type="button" className="rounded bg-gray-700 px-3 py-2" onClick={()=>setForm({...form,stages:[...form.stages,stage()]})}>Add stage</button><button className="rounded bg-purple-600 px-4 py-2">{editing?"Save changes":"Create draft"}</button>{(editing||form.title)&&<button type="button" className="rounded bg-gray-700 px-4 py-2" onClick={()=>{setEditing(null);setForm(empty());}}>Cancel</button>}</div></form>
 {decision&&<form onSubmit={recordDecision} className="rounded border border-purple-700 bg-purple-950/20 p-4"><h2 className="font-semibold">Decision: {decision.stage.name}</h2><div className="mt-3 flex flex-wrap gap-3"><select className="rounded bg-gray-950 p-2" value={decisionForm.outcome} onChange={e=>setDecisionForm({...decisionForm,outcome:e.target.value})}><option value="approved">Approve</option><option value="rejected">Reject</option></select><input className="min-w-72 flex-1 rounded bg-gray-950 p-2" placeholder="Decision comments" value={decisionForm.comments} onChange={e=>setDecisionForm({...decisionForm,comments:e.target.value})}/><button className="rounded bg-purple-600 px-4 py-2">Record decision</button><button type="button" className="rounded bg-gray-700 px-4 py-2" onClick={()=>setDecision(null)}>Cancel</button></div></form>}
 <section><div className="grid gap-3 sm:grid-cols-2"><input className="rounded bg-gray-900 p-2" placeholder="Search approval requests" value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}}/><select className="rounded bg-gray-900 p-2" value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="">All statuses</option><option value="draft">Draft</option><option value="pending">Pending</option><option value="approved">Approved</option><option value="rejected">Rejected</option><option value="withdrawn">Withdrawn</option></select></div><div className="mt-3 overflow-x-auto"><table className="w-full min-w-[1050px] text-sm"><thead><tr className="border-b border-gray-700 text-left text-gray-400"><th className="p-2">#</th><th>Request</th><th>Subject</th><th>Status</th><th>Stages</th><th>Actions</th></tr></thead><tbody>{rows.map((row,i)=>{const active=row.stages.find(s=>s.status==="pending");return <tr key={row.id} className={`border-b border-gray-800 ${row.status==="rejected"?"bg-red-950/30":""}`}><td className="p-2">{(page-1)*50+i+1}</td><td>{row.title}</td><td>{row.subject_component}/{row.subject_type}/{row.subject_id}</td><td>{row.status}</td><td>{row.stages.map(s=><div key={s.id} className="text-xs">{s.sequence}. {s.name}: {s.status} ({s.decisions.length}/{s.required_decisions})</div>)}</td><td><div className="flex flex-wrap gap-2 text-xs">{row.status==="draft"&&<><button className="text-blue-300" onClick={()=>edit(row)}>Edit</button><button className="text-purple-300" onClick={()=>submit(row)}>Submit</button></>}{active&&<button className="text-emerald-300" onClick={()=>setDecision({row,stage:active})}>Decide</button>}{['draft','pending'].includes(row.status)&&<button className="text-red-300" onClick={()=>lifecycle(row,"withdrawn")}>Withdraw</button>}{row.status==="withdrawn"&&<button className="text-emerald-300" onClick={()=>lifecycle(row,"draft")}>Reinstate</button>}</div></td></tr>;})}</tbody></table>{!rows.length&&<p className="p-8 text-center text-gray-500">No approval requests found.</p>}</div><Pagination page={page} pageSize={50} total={total} onPageChange={setPage}/></section></div>;
}
