import React, { useEffect, useMemo, useState } from "react";
import * as api from "../../api/client";

const MONTHS=["January","February","March","April","May","June","July","August","September","October","November","December"];
const VIEWS=["month","week","day","year","agenda"];
const blank={title:"",description:"",primary_layer:"academic",start_at:"",end_at:"",all_day:false,status:"planned",priority:"normal",visibility_roles:["superuser","principal"],recurrence:null,rollover_strategy:"manual_review"};
const isoInput=value=>value?new Date(value).toISOString().slice(0,16):"";
const dayKey=value=>new Date(value).toISOString().slice(0,10);
const startDay=date=>new Date(Date.UTC(date.getUTCFullYear(),date.getUTCMonth(),date.getUTCDate()));
const addDays=(date,n)=>new Date(date.getTime()+n*86400000);
const periodParts=value=>String(value||"01-01").split("-").map(Number);

function PeriodField({label,value,onChange}){const [month,day]=periodParts(value);return <fieldset><legend className="text-sm text-gray-300">{label}</legend><div className="mt-1 flex gap-2"><select className="min-w-0 flex-1 rounded bg-gray-950 p-2" value={month} onChange={e=>onChange(`${String(e.target.value).padStart(2,"0")}-${String(day).padStart(2,"0")}`)}>{MONTHS.map((name,i)=><option value={i+1} key={name}>{name}</option>)}</select><input aria-label={`${label} day`} className="w-20 rounded bg-gray-950 p-2" type="number" min="1" max="31" value={day} onChange={e=>onChange(`${String(month).padStart(2,"0")}-${String(e.target.value).padStart(2,"0")}`)}/></div></fieldset>}

export default function CalendarWidget({askConfirmation}){
  const [entries,setEntries]=useState([]),[layers,setLayers]=useState([]),[settings,setSettings]=useState(null);
  const [form,setForm]=useState(blank),[editing,setEditing]=useState(null),[message,setMessage]=useState(""),[error,setError]=useState("");
  const [mode,setMode]=useState("internal"),[view,setView]=useState("month"),[focus,setFocus]=useState(()=>new Date()),[layer,setLayer]=useState(""),[status,setStatus]=useState("");
  const [conflicts,setConflicts]=useState([]);
  const range=useMemo(()=>{const d=startDay(focus);if(view==="day")return{from:d.toISOString(),to:addDays(d,1).toISOString()};if(view==="week"){const from=addDays(d,-((d.getUTCDay()+6)%7));return{from:from.toISOString(),to:addDays(from,7).toISOString()};}if(view==="year")return{from:new Date(Date.UTC(d.getUTCFullYear(),0,1)).toISOString(),to:new Date(Date.UTC(d.getUTCFullYear()+1,0,1)).toISOString()};if(view==="agenda")return{from:d.toISOString(),to:addDays(d,90).toISOString()};return{from:new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),1)).toISOString(),to:new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+1,1)).toISOString()};},[focus,view]);
  const load=async()=>{try{setError("");const [e,l,s]=await Promise.all([api.listCalendarEntries({...range,layer,status}),api.listCalendarLayers(),api.getCalendarSettings()]);setEntries(e.data.entries||[]);setLayers(l.data.layers||[]);setSettings(s.data.settings);}catch(err){setError(err.response?.data?.error?.message||err.message);}};
  useEffect(()=>{void load();},[range.from,range.to,layer,status]);
  useEffect(()=>{window.dispatchEvent(new CustomEvent("principaled:dirty-state",{detail:Boolean(form.title||editing)}));return()=>window.dispatchEvent(new CustomEvent("principaled:dirty-state",{detail:false}));},[form,editing]);
  useEffect(()=>{if(!form.start_at||!form.end_at){setConflicts([]);return;}const timer=setTimeout(()=>api.findCalendarConflicts({from:new Date(form.start_at).toISOString(),to:new Date(form.end_at).toISOString(),exclude_entry_id:editing||undefined}).then(r=>setConflicts(r.data.conflicts||[])).catch(()=>setConflicts([])),250);return()=>clearTimeout(timer);},[form.start_at,form.end_at,editing]);
  const visible=entries.filter(entry=>mode==="internal"||entry.public_enabled);
  const display=value=>new Intl.DateTimeFormat(settings?.locale||"en-GB",{dateStyle:"medium",timeStyle:"short",timeZone:settings?.timezone||"UTC"}).format(new Date(value));
  const reset=()=>{setForm(blank);setEditing(null);setConflicts([]);};
  const save=async event=>{event.preventDefault();try{const payload={...form,start_at:new Date(form.start_at).toISOString(),end_at:new Date(form.end_at).toISOString()};if(editing)await api.updateCalendarEntry(editing,payload);else await api.createCalendarEntry(payload);reset();setMessage("Calendar entry saved");await load();}catch(err){setError(err.response?.data?.error?.message||err.message);}};
  const edit=entry=>{setEditing(entry.id);setForm({...blank,...entry,start_at:isoInput(entry.series_start_at||entry.start_at),end_at:isoInput(entry.series_end_at||entry.end_at)});};
  const confirm=options=>askConfirmation(options);
  const remove=async entry=>{if(await confirm({title:"Delete calendar entry?",message:"This permanently removes the entry, occurrences and outward projection.",confirmLabel:"Delete entry",destructive:true})){await api.deleteCalendarEntry(entry.id);await load();}};
  const changeStatus=async(entry,next)=>{if(await confirm({title:`${next==="cancelled"?"Cancel":"Reinstate"} calendar entry?`,message:`This changes every occurrence of ${entry.title}.`,confirmLabel:next==="cancelled"?"Cancel entry":"Reinstate entry",destructive:next==="cancelled"})){await api.setCalendarEntryStatus(entry.id,next);await load();}};
  const cancelOccurrence=async entry=>{if(await confirm({title:"Cancel this occurrence?",message:"The recurring series remains active; only this occurrence is removed.",confirmLabel:"Cancel occurrence",destructive:true})){await api.setCalendarException(entry.id,{original_start_at:entry.start_at,action:"cancelled",reason:"Cancelled by user"});await load();}};
  const publication=async entry=>{if(entry.public_enabled){if(await confirm({title:"Withdraw outward entry?",message:"External stakeholders will no longer see this entry.",confirmLabel:"Withdraw",destructive:true}))await api.withdrawCalendarPublication(entry.id);}else if(await confirm({title:"Publish outward?",message:"The outward projection will become publicly available.",confirmLabel:"Publish",destructive:false}))await api.publishCalendarEntry(entry.id);await load();};
  const move=direction=>{const d=new Date(focus);if(view==="year")d.setUTCFullYear(d.getUTCFullYear()+direction);else if(view==="month")d.setUTCMonth(d.getUTCMonth()+direction);else d.setUTCDate(d.getUTCDate()+direction*(view==="week"?7:view==="agenda"?30:1));setFocus(d);};
  const entryCard=(entry,index)=><article key={`${entry.id}-${entry.instance_id}`} className={`rounded border p-2 text-sm ${entry.status==="cancelled"?"border-red-700 bg-red-950/30 opacity-70":"border-gray-700 bg-gray-900/80"}`}><div className="flex gap-2"><span className="text-gray-500">{index+1}</span><div className="min-w-0 flex-1"><strong className="block truncate">{mode==="external"?(entry.public_title||entry.title):entry.title}</strong><span className="text-xs text-gray-400">{display(entry.start_at)}</span><div className="mt-1 flex flex-wrap gap-1"><span className="rounded px-1.5 text-xs" style={{background:layers.find(x=>x.code===entry.primary_layer)?.colour}}>{entry.primary_layer}</span><span className="text-xs text-gray-400">{entry.status}</span>{entry.source_component&&<span className="text-xs text-gray-400">From {entry.source_component}</span>}</div></div></div>{mode==="internal"&&<div className="mt-2 flex flex-wrap gap-2 text-xs"><button onClick={()=>edit(entry)} className="text-blue-300">Edit</button>{entry.recurrence&&<button onClick={()=>cancelOccurrence(entry)} className="text-amber-300">Cancel occurrence</button>}<button onClick={()=>changeStatus(entry,entry.status==="cancelled"?"planned":"cancelled")} className="text-amber-300">{entry.status==="cancelled"?"Reinstate":"Cancel"}</button><button onClick={()=>publication(entry)} className="text-emerald-300">{entry.public_enabled?"Withdraw public":"Publish"}</button><button onClick={()=>remove(entry)} className="text-red-300">Delete</button></div>}</article>;
  const calendarBody=()=>{if(view==="agenda"||view==="day")return <div className="space-y-2">{visible.map(entryCard)}</div>;if(view==="year")return <div className="grid gap-3 sm:grid-cols-3 lg:grid-cols-4">{MONTHS.map((name,m)=>{const items=visible.filter(e=>new Date(e.start_at).getUTCMonth()===m);return <section className="min-h-28 rounded border border-gray-800 p-3" key={name}><h3 className="font-medium">{name}</h3><p className="text-sm text-gray-500">{items.length} entries</p>{items.slice(0,3).map(entryCard)}</section>;})}</div>;const from=new Date(range.from),days=view==="week"?7:new Date(Date.UTC(from.getUTCFullYear(),from.getUTCMonth()+1,0)).getUTCDate();return <div className={`grid gap-px overflow-hidden rounded border border-gray-800 bg-gray-800 ${view==="week"?"grid-cols-7":"grid-cols-7"}`}>{Array.from({length:days},(_,i)=>{const date=addDays(from,i),items=visible.filter(e=>dayKey(e.start_at)===dayKey(date));return <section key={date.toISOString()} className="min-h-32 bg-gray-950 p-2"><h3 className="mb-2 text-xs text-gray-400">{date.getUTCDate()} {MONTHS[date.getUTCMonth()].slice(0,3)}</h3><div className="space-y-1">{items.map(entryCard)}</div></section>;})}</div>;};
  if(!settings)return <div className="text-gray-400">Loading Calendar...</div>;
  return <div className="space-y-5"><header className="flex flex-wrap items-end justify-between gap-4"><div><span className="text-xs uppercase tracking-widest text-purple-400">Shared scheduling component</span><h1 className="text-3xl font-semibold">Calendar</h1><p className="text-gray-400">Direct entries and schedules supplied by other components.</p></div><div className="flex gap-2"><button className={`rounded px-3 py-2 ${mode==="internal"?"bg-purple-600":"bg-gray-800"}`} onClick={()=>setMode("internal")}>Internal</button><button className={`rounded px-3 py-2 ${mode==="external"?"bg-purple-600":"bg-gray-800"}`} onClick={()=>setMode("external")}>Outward</button></div></header>
  {error&&<p className="rounded border border-red-700 bg-red-950/40 p-3 text-red-200">{error}</p>}{message&&<p className="text-emerald-400">{message}</p>}
  <details className="rounded border border-gray-800 bg-gray-900/60 p-4"><summary className="cursor-pointer font-semibold">Initial Calendar setup</summary><div className="mt-4 grid gap-3 md:grid-cols-2 lg:grid-cols-3"><PeriodField label="Calendar year starts" value={settings.calendar_start} onChange={value=>setSettings({...settings,calendar_start:value})}/><PeriodField label="Calendar year ends" value={settings.calendar_end} onChange={value=>setSettings({...settings,calendar_end:value})}/><PeriodField label="Academic year starts" value={settings.academic_start} onChange={value=>setSettings({...settings,academic_start:value})}/><PeriodField label="Academic year ends" value={settings.academic_end} onChange={value=>setSettings({...settings,academic_end:value})}/><label className="text-sm text-gray-300">Timezone<input className="mt-1 w-full rounded bg-gray-950 p-2" value={settings.timezone} onChange={e=>setSettings({...settings,timezone:e.target.value})}/></label><button className="self-end rounded bg-gray-700 p-2" onClick={async()=>{await api.updateCalendarSettings(settings);setMessage("Calendar setup saved");}}>Save setup</button></div></details>
  {mode==="internal"&&<form onSubmit={save} className="rounded border border-gray-800 bg-gray-900/60 p-4"><h2 className="mb-3 font-semibold">{editing?"Edit calendar entry":"Create calendar entry"}</h2><div className="grid gap-3 md:grid-cols-3"><input required className="rounded bg-gray-950 p-2" placeholder="Entry title" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><select className="rounded bg-gray-950 p-2" value={form.primary_layer} onChange={e=>setForm({...form,primary_layer:e.target.value})}>{layers.map(x=><option key={x.code} value={x.code}>{x.name}{x.sensitive?" (controlled)":""}</option>)}</select><select className="rounded bg-gray-950 p-2" value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="draft">Draft</option><option value="planned">Provisional</option><option value="confirmed">Confirmed</option></select><input required type="datetime-local" className="rounded bg-gray-950 p-2" value={form.start_at} onChange={e=>setForm({...form,start_at:e.target.value})}/><input required type="datetime-local" className="rounded bg-gray-950 p-2" value={form.end_at} onChange={e=>setForm({...form,end_at:e.target.value})}/><select className="rounded bg-gray-950 p-2" value={form.recurrence?.frequency||""} onChange={e=>setForm({...form,recurrence:e.target.value?{frequency:e.target.value,interval:1}:null})}><option value="">Does not repeat</option><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option><option value="yearly">Yearly</option></select><textarea className="rounded bg-gray-950 p-2 md:col-span-2" placeholder="Calendar description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.visibility_roles.includes("staff")} onChange={e=>setForm({...form,visibility_roles:e.target.checked?[...form.visibility_roles,"staff"]:form.visibility_roles.filter(x=>x!=="staff")})}/>Visible to staff</label></div>{conflicts.length>0&&<div className="mt-3 rounded border border-amber-700 bg-amber-950/30 p-3 text-sm text-amber-200">{conflicts.length} overlapping visible calendar {conflicts.length===1?"entry":"entries"}: {conflicts.map(x=>x.title).join(", ")}</div>}<div className="mt-3 flex gap-2"><button className="rounded bg-purple-600 px-4 py-2">{editing?"Save changes":"Add entry"}</button>{(editing||form.title)&&<button type="button" className="rounded bg-gray-700 px-4 py-2" onClick={reset}>Cancel</button>}</div></form>}
  <section><div className="mb-3 flex flex-wrap items-center justify-between gap-3"><div className="flex gap-2"><button onClick={()=>move(-1)} className="rounded bg-gray-800 px-3 py-2" aria-label="Previous period">Previous</button><button onClick={()=>setFocus(new Date())} className="rounded bg-gray-800 px-3 py-2">Today</button><button onClick={()=>move(1)} className="rounded bg-gray-800 px-3 py-2" aria-label="Next period">Next</button></div><div className="flex flex-wrap gap-2">{VIEWS.map(x=><button key={x} onClick={()=>setView(x)} className={`rounded px-3 py-2 capitalize ${view===x?"bg-purple-600":"bg-gray-800"}`}>{x}</button>)}</div><div className="flex gap-2"><select aria-label="Filter by layer" className="rounded bg-gray-900 p-2" value={layer} onChange={e=>setLayer(e.target.value)}><option value="">All layers</option>{layers.map(x=><option key={x.code} value={x.code}>{x.name}</option>)}</select><select aria-label="Filter by status" className="rounded bg-gray-900 p-2" value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option><option value="draft">Draft</option><option value="planned">Provisional</option><option value="confirmed">Confirmed</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select></div></div>{calendarBody()}{visible.length===0&&<div className="rounded border border-dashed border-gray-700 p-8 text-center text-gray-500">No calendar entries in this period.</div>}</section>
  <section className="rounded border border-gray-800 p-4"><h2 className="font-semibold">Rollover review preparation</h2><p className="my-2 text-sm text-gray-400">Creates draft entries for individual review. Nothing is published automatically.</p><button className="rounded bg-amber-700 px-3 py-2" onClick={async()=>{const year=focus.getUTCFullYear()+1;if(await confirm({title:`Prepare ${year} rollover?`,message:"Eligible entries will become reviewable drafts.",confirmLabel:"Create drafts",destructive:false})){const result=await api.rolloverCalendar(year);setMessage(`${result.data.total} rollover drafts created`);await load();}}}>Prepare next year</button></section></div>;
}
