import React,{useEffect,useMemo,useState} from "react";
import * as api from "../../api/client";
import Pagination from "../components/Pagination";

const message=e=>e.response?.data?.error?.message||e.message;
const label=x=>String(x||"").replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());
const stamp=x=>x?new Date(x).toLocaleString():"Open ended";
const emptyAbsence={staff_id:"",absence_type:"full_day",starts_at:"",ends_at:"",category:"unspecified",operational_note:""};
export default function CoverWidget({askConfirmation}){
 const[tab,setTab]=useState("queue"),[demands,setDemands]=useState([]),[demandPage,setDemandPage]=useState(1),[demandTotal,setDemandTotal]=useState(0),[status,setStatus]=useState("open"),[selected,setSelected]=useState(null),[run,setRun]=useState(null),[assignmentData,setAssignmentData]=useState({assignments:[],decisions:[]}),[absences,setAbsences]=useState([]),[absencePage,setAbsencePage]=useState(1),[absenceTotal,setAbsenceTotal]=useState(0),[insights,setInsights]=useState(null),[analytics,setAnalytics]=useState(null),[analyticsDays,setAnalyticsDays]=useState(30),[policy,setPolicy]=useState(null),[policyDraft,setPolicyDraft]=useState(null),[absenceDraft,setAbsenceDraft]=useState(emptyAbsence),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 const activeAssignment=assignmentData.assignments.find(x=>x.status==="active");
 const eligible=run?.recommendations?.filter(x=>x.eligible)||[];
 const loadDetail=async d=>{if(!d){setRun(null);setAssignmentData({assignments:[],decisions:[]});return}const[r,a]=await Promise.all([api.listCoverRecommendationRuns(d.id,{page:1,limit:1}),api.listCoverAssignments(d.id)]);setRun(r.data.runs?.[0]||null);setAssignmentData(a.data)};
 const load=async()=>{try{const to=new Date(),from=new Date(to.getTime()-analyticsDays*86400000),[d,a,i,p,n]=await Promise.all([api.listCoverDemands({page:demandPage,limit:50,...(status?{status}:{})}),api.listCoverAbsences({page:absencePage,limit:50}),api.getCoverInsights(),api.getCoverPolicy(),api.getCoverAnalytics({limit:50,from:from.toISOString(),to:to.toISOString()})]);setDemands(d.data.demands);setDemandTotal(d.data.total);setAbsences(a.data.absences);setAbsenceTotal(a.data.total);setInsights(i.data.insights);setAnalytics(n.data.analytics);setPolicy(p.data.policy);setPolicyDraft(p.data.policy.policy);const current=d.data.demands.find(x=>x.id===selected?.id)||d.data.demands[0]||null;setSelected(current);await loadDetail(current);setError("")}catch(e){setError(message(e))}};
 useEffect(()=>{void load()},[demandPage,absencePage,status,analyticsDays]);
 const runAction=async fn=>{setBusy(true);try{await fn();await load()}catch(e){setError(message(e))}finally{setBusy(false)}};
 const confirm=async options=>!askConfirmation||await askConfirmation(options);
 const choose=async rec=>{let reason="";if(rec.rank!==1){reason=window.prompt("Reason for selecting a lower-ranked candidate")||"";if(!reason)return}if(!await confirm({title:`Assign ${rec.candidate_name}?`,message:`This human decision will fill ${selected.title}. Live availability will be checked again.`,confirmLabel:"Confirm assignment"}))return;runAction(()=>activeAssignment?api.reassignCover(activeAssignment.id,{recommendation_id:rec.id,reason:reason||"Human reassignment after operational review",expected_revision:activeAssignment.revision}):api.confirmCoverAssignment(selected.id,{recommendation_id:rec.id,reason:reason||undefined}))};
 const reject=rec=>{const reason=window.prompt("Why is this recommendation being rejected?");if(reason)runAction(()=>api.rejectCoverRecommendation(rec.id,{reason}))};
 const cancelAssignment=async()=>{const reason=window.prompt("Reason for cancelling this assignment");if(!reason||!await confirm({title:"Cancel cover assignment?",message:"The demand will return to the open queue.",confirmLabel:"Cancel assignment",destructive:true}))return;runAction(()=>api.cancelCoverAssignment(activeAssignment.id,{reason,expected_revision:activeAssignment.revision}))};
 const completeAssignment=async()=>{if(!await confirm({title:"Complete cover assignment?",message:"This closes the fulfilled demand and preserves its decision history.",confirmLabel:"Mark complete"}))return;runAction(()=>api.completeCoverAssignment(activeAssignment.id,{expected_revision:activeAssignment.revision}))};
 const generate=async emergency=>{const manual=[];if(emergency){const name=window.prompt("Optional external/non-registered candidate name (leave blank for none)")||"";if(name)manual.push({external_key:`manual:${Date.now()}`,name,candidate_type:"external_manual",within_working_window:null})}if(!await confirm({title:emergency?"Generate emergency recommendations?":"Generate recommendations?",message:`The system will ${emergency?"expand only the pools allowed by emergency policy and ":""}rank and explain candidates. It will not assign anyone.`,confirmLabel:"Generate"}))return;runAction(()=>api.generateCoverRecommendations(selected.id,{emergency,manual_candidates:manual}))};
 const submitAbsence=e=>{e.preventDefault();runAction(async()=>{const b={...absenceDraft,starts_at:new Date(absenceDraft.starts_at).toISOString(),ends_at:absenceDraft.ends_at?new Date(absenceDraft.ends_at).toISOString():null};await api.createCoverAbsence(b);setAbsenceDraft(emptyAbsence)})};
 const absenceAction=async(a,kind)=>{const reason=kind==="cancel"?window.prompt("Reason for cancelling this absence"):"Reinstated after review";if(!reason)return;if(!await confirm({title:`${label(kind)} absence?`,message:`${a.staff_id} Â· ${stamp(a.starts_at)}`,confirmLabel:label(kind),destructive:kind==="cancel"}))return;runAction(()=>kind==="cancel"?api.cancelCoverAbsence(a.id,{reason,expected_revision:a.revision}):api.reinstateCoverAbsence(a.id,{reason,expected_revision:a.revision}))};
 const savePolicy=()=>{const reason=window.prompt("Reason for this policy change");if(reason)runAction(()=>api.saveCoverPolicy({name:policy.name,policy:policyDraft,expected_revision:policy.revision,change_reason:reason}))};
 const setPolicyValue=(group,key,value)=>setPolicyDraft(p=>({...p,[group]:{...p[group],[key]:value}}));
 const summary=insights?.counts||{};
 return <div className="cover-workspace space-y-5"><header className="workspace-hero"><div><span className="eyebrow">Explainable recommendations Â· authorised humans allocate</span><h1>Cover Operations</h1><p>Report absence, identify timetable demand, review every candidate explanation and make a deliberate, auditable cover decision.</p></div><button disabled={busy} onClick={load}>Refresh</button></header>{error&&<div className="workspace-error">{error}</div>}{insights&&<><div className="scheduler-summary"><Summary title="Readiness" value={label(insights.readiness)}/><Summary title="Active absences" value={summary.active_absences}/><Summary title="Open demands" value={summary.open_demands}/><Summary title="Awaiting recommendations" value={summary.unranked_demands}/></div><p className="cover-narrative">{insights.narrative}</p></>}
 <nav className="cover-tabs" aria-label="Cover workspace"><button className={tab==="queue"?"active":""} onClick={()=>setTab("queue")}>Cover queue</button><button className={tab==="absences"?"active":""} onClick={()=>setTab("absences")}>Absences</button><button className={tab==="analytics"?"active":""} onClick={()=>setTab("analytics")}>Analytics</button><button className={tab==="policy"?"active":""} onClick={()=>setTab("policy")}>Policy</button></nav>
 {tab==="queue"&&<div className="cover-split"><section className="cover-panel"><div className="cover-panel-head"><h2>Demand queue</h2><select value={status} onChange={e=>{setDemandPage(1);setStatus(e.target.value)}}><option value="">All statuses</option>{["open","filled","cancelled","closed"].map(x=><option key={x} value={x}>{label(x)}</option>)}</select></div><div className="cover-scroll"><table><thead><tr><th>#</th><th>When</th><th>Demand</th><th>Status</th></tr></thead><tbody>{demands.map((d,i)=><tr key={d.id} className={selected?.id===d.id?"selected":""} onClick={()=>{setSelected(d);loadDetail(d).catch(e=>setError(message(e)))}}><td>{(demandPage-1)*50+i+1}</td><td>{stamp(d.starts_at)}</td><td><strong>{d.title}</strong><small>{d.subject_ref||d.location_ref||label(d.source_type)}</small></td><td><Status value={d.status}/></td></tr>)}</tbody></table>{!demands.length&&<p className="workspace-empty">No demands match this view.</p>}</div><Pagination page={demandPage} pageSize={50} total={demandTotal} onPageChange={setDemandPage}/></section>
 <section className="cover-panel cover-detail">{!selected?<p className="workspace-empty">Select a demand to review.</p>:<><div className="cover-panel-head"><div><span className="eyebrow">{label(selected.source_type)}</span><h2>{selected.title}</h2><p>{stamp(selected.starts_at)} â€“ {stamp(selected.ends_at)}</p></div><Status value={selected.status}/></div>{activeAssignment&&<article className="cover-assignment"><div><small>Confirmed cover</small><strong>{activeAssignment.candidate_name}</strong><span>{label(activeAssignment.decision_type)} Â· by {activeAssignment.assigned_by}</span></div><div className="cover-actions">{Date.parse(selected.ends_at)<=Date.now()&&<button disabled={busy} onClick={completeAssignment}>Mark complete</button>}<button disabled={busy} onClick={cancelAssignment}>Cancel assignment</button></div></article>}{selected.status==="open"&&<div className="cover-recommend-head"><div><h3>Candidate evidence</h3><p>{run?`${run.eligible_count} eligible of ${run.candidate_count}`:"Generate recommendations before assigning cover."}</p></div><div className="cover-actions"><button disabled={busy} onClick={()=>generate(false)}>{run?"Refresh evidence":"Generate recommendations"}</button><button disabled={busy} onClick={()=>generate(true)}>Emergency pools</button></div></div>}{run&&<div className="cover-candidates">{run.recommendations.map(rec=><article key={rec.id} className={rec.eligible?"eligible":"excluded"}><div className="cover-candidate-head"><div><strong>{rec.rank?`#${rec.rank} `:""}{rec.candidate_name}</strong><span>{label(rec.candidate_type)} Â· score {rec.score}</span></div><Status value={rec.eligible?"eligible":"excluded"}/></div><ul>{rec.evidence.evaluation.score_breakdown.map(x=><li key={x.criterion}><span>{label(x.criterion)}</span><strong>{x.contribution>=0?"+":""}{x.contribution}</strong><small>{x.evidence}</small></li>)}</ul>{rec.evidence.evaluation.hard_gates.map(x=><p className="cover-gate" key={x.code}><strong>{label(x.code)}:</strong> {x.message}</p>)}<div className="cover-actions">{rec.eligible&&selected.status!=="cancelled"&&(!activeAssignment||activeAssignment.candidate_ref!==rec.candidate_ref)&&<button disabled={busy} onClick={()=>choose(rec)}>{activeAssignment?"Reassign":"Assign"}</button>}<button disabled={busy} onClick={()=>reject(rec)}>Reject with reason</button></div></article>)}</div>} {assignmentData.decisions.length>0&&<details className="cover-history"><summary>Decision history ({assignmentData.decisions.length})</summary><ol>{assignmentData.decisions.map(x=><li key={x.id}><strong>{label(x.action)}</strong> Â· {stamp(x.created_at)} Â· {x.reason||"No reason required"}</li>)}</ol></details>}</>}</section></div>}
 {tab==="absences"&&<><form className="cover-form" onSubmit={submitAbsence}><h2>Report absence</h2><label>Staff ID<input required value={absenceDraft.staff_id} onChange={e=>setAbsenceDraft({...absenceDraft,staff_id:e.target.value})}/></label><label>Form<select value={absenceDraft.absence_type} onChange={e=>setAbsenceDraft({...absenceDraft,absence_type:e.target.value})}>{["full_day","partial_day","multi_day","open_ended"].map(x=><option key={x} value={x}>{label(x)}</option>)}</select></label><label>Starts<input required type="datetime-local" value={absenceDraft.starts_at} onChange={e=>setAbsenceDraft({...absenceDraft,starts_at:e.target.value})}/></label><label>Ends<input type="datetime-local" disabled={absenceDraft.absence_type==="open_ended"} value={absenceDraft.ends_at} onChange={e=>setAbsenceDraft({...absenceDraft,ends_at:e.target.value})}/></label><label className="wide">Operational note<input value={absenceDraft.operational_note} onChange={e=>setAbsenceDraft({...absenceDraft,operational_note:e.target.value})}/></label><button disabled={busy}>Report absence</button></form><section className="cover-panel"><div className="cover-scroll"><table><thead><tr>{["#","Staff","Form","Starts","Ends","Status","Actions"].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{absences.map((a,i)=><tr key={a.id}><td>{(absencePage-1)*50+i+1}</td><td>{a.staff_id}</td><td>{label(a.absence_type)}</td><td>{stamp(a.starts_at)}</td><td>{stamp(a.ends_at)}</td><td><Status value={a.status}/></td><td className="cover-actions">{a.status==="cancelled"?<button onClick={()=>absenceAction(a,"reinstate")}>Reinstate</button>:<><button onClick={()=>runAction(()=>api.reconcileCoverAbsence(a.id,a.ends_at?{}:{window_end:new Date(Date.now()+7*86400000).toISOString()}))}>Find lessons</button><button onClick={()=>absenceAction(a,"cancel")}>Cancel</button></>}</td></tr>)}</tbody></table></div><Pagination page={absencePage} pageSize={50} total={absenceTotal} onPageChange={setAbsencePage}/></section></>}
 {tab==="analytics"&&analytics&&<Analytics data={analytics} days={analyticsDays} onDays={setAnalyticsDays}/>}
 {tab==="policy"&&policyDraft&&<section className="cover-policy"><div><span className="eyebrow">Revision {policy.revision}</span><h2>School cover philosophy</h2><p>Teachers are the default pool. Preferences guide ranking; confirmed restrictions and live availability remain hard boundaries.</p></div><fieldset><legend>Normal candidate pools</legend>{Object.entries(policyDraft.candidate_types).map(([k,v])=><label key={k}><input type="checkbox" checked={v} onChange={e=>setPolicyValue("candidate_types",k,e.target.checked)}/>{label(k)}</label>)}</fieldset><fieldset><legend>Recommendation priorities</legend>{Object.entries(policyDraft.priorities).map(([k,v])=><label key={k}>{label(k)}<input type="number" min="0" max="100" value={v} onChange={e=>setPolicyValue("priorities",k,+e.target.value)}/></label>)}</fieldset><fieldset><legend>Workload caps</legend>{Object.entries(policyDraft.limits).map(([k,v])=><label key={k}>{label(k)}<input type="number" min="0" value={v} onChange={e=>setPolicyValue("limits",k,+e.target.value)}/></label>)}</fieldset><fieldset><legend>Emergency expansion</legend>{Object.entries(policyDraft.emergency).map(([k,v])=><label key={k}><input type="checkbox" checked={v} onChange={e=>setPolicyValue("emergency",k,e.target.checked)}/>{label(k)}</label>)}</fieldset><button disabled={busy} onClick={savePolicy}>Save policy with reason</button></section>}</div>;
}
function Summary({value,title}){return <article><strong>{value??0}</strong><span>{title}</span></article>}
function Status({value}){return <span className={`cover-status cover-${value}`}>{label(value)}</span>}
function Analytics({data,days,onDays}){const s=data.summary,max=Math.max(1,...data.series.map(x=>x.demands),...data.cover_provided.map(x=>x.count),...data.cover_needed.map(x=>x.count),...data.class_disruption.map(x=>x.count));return <section className="cover-analytics"><div className="cover-analytics-head"><div><span className="eyebrow">Recorded operations, not inferred causes</span><h2>Cover analytics</h2></div><label>Period <select value={days} onChange={e=>onDays(+e.target.value)}>{[7,30,90,180,365].map(x=><option key={x} value={x}>Last {x} days</option>)}</select></label></div><div className="scheduler-summary"><Summary title="Recorded coverage" value={s.coverage_rate==null?"No demand":`${s.coverage_rate}%`}/><Summary title="Assignments" value={s.assignments}/><Summary title="Cover hours" value={Math.round(s.assignment_minutes/6)/10}/><Summary title="Overrides" value={s.overrides}/><Summary title="Reassignments" value={s.reassignments}/><Summary title="Elapsed unresolved" value={s.overdue_unfilled}/></div>{data.alerts.length>0&&<div className="cover-alerts">{data.alerts.map(x=><article key={x.code} className={`cover-alert-${x.severity}`}><strong>{label(x.code)}</strong><p>{x.message}</p><small>{x.possible_action}</small></article>)}</div>}<div className="cover-chart-grid"><BarPanel title="Demand by day" rows={data.series.map(x=>({key:x.date,name:x.date,count:x.demands,detail:`${x.filled} filled Â· ${x.cancelled} cancelled`}))} max={max}/><BarPanel title="Who provided cover" rows={data.cover_provided} max={max}/><BarPanel title="Who needed cover" rows={data.cover_needed} max={max}/><BarPanel title="Classes and lessons affected" rows={data.class_disruption} max={max}/></div><p className="cover-interpretation">{data.interpretation}</p></section>}
function BarPanel({title,rows,max}){return <article className="cover-chart"><h3>{title}</h3>{rows.length?rows.map((x,i)=><div className="cover-bar" key={x.key}><span>{i+1}. {x.name}</span><strong>{x.count}</strong><i><b style={{width:`${Math.max(3,x.count/max*100)}%`}}/></i><small>{x.detail||`${Math.round(x.minutes/6)/10} hours`}</small></div>):<p className="workspace-empty">No recorded activity in this period.</p>}</article>}
