import React,{useEffect,useState}from"react";
import * as api from"../../api/client";
import Pagination from"../components/Pagination";

const empty={title:"",description:"",category:"general"};
const readFile=file=>new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(",")[1]);reader.onerror=reject;reader.readAsDataURL(file);});
export default function DocumentsWidget({askConfirmation}){
 const [rows,setRows]=useState([]),[form,setForm]=useState(empty),[file,setFile]=useState(null),[editing,setEditing]=useState(null),[page,setPage]=useState(1),[total,setTotal]=useState(0),[search,setSearch]=useState(""),[status,setStatus]=useState(""),[action,setAction]=useState(null),[actionFile,setActionFile]=useState(null),[link,setLink]=useState({subject_component:"",subject_type:"",subject_id:"",link_role:"attachment"}),[error,setError]=useState(""),[message,setMessage]=useState("");
 const load=async()=>{try{const r=await api.listDocuments({page,limit:50,q:search,status:status||undefined});setRows(r.data.documents||[]);setTotal(r.data.total||0);setError("");}catch(e){setError(e.response?.data?.error?.message||e.message);}};
 useEffect(()=>{void load();},[page,search,status]);useEffect(()=>{window.dispatchEvent(new CustomEvent("principaled:dirty-state",{detail:Boolean(form.title||editing||action)}));return()=>window.dispatchEvent(new CustomEvent("principaled:dirty-state",{detail:false}));},[form.title,editing,action]);
 const upload=async(id,selected)=>api.addDocumentVersion(id,{filename:selected.name,mime_type:selected.type||"application/octet-stream",content_base64:await readFile(selected)});
 const save=async e=>{e.preventDefault();try{if(file&&file.size>10*1024*1024)throw new Error("File exceeds the 10 MiB limit");if(editing)await api.updateDocument(editing,form);else{const created=await api.createDocument(form);if(file)await upload(created.data.document.id,file);}setForm(empty);setFile(null);setEditing(null);setMessage(editing?"Document updated":"Document created");await load();}catch(err){setError(err.response?.data?.error?.message||err.message);}};
 const edit=row=>{setEditing(row.id);setForm({title:row.title,description:row.description||"",category:row.category});window.scrollTo({top:0,behavior:"smooth"});};
 const lifecycle=async(row,next)=>{if(await askConfirmation({title:`${next==="withdrawn"?"Withdraw":"Reinstate"} document?`,message:"Files, versions, links, and history will be retained.",confirmLabel:next==="withdrawn"?"Withdraw":"Reinstate",destructive:next==="withdrawn"})){await api.setDocumentStatus(row.id,next);await load();}};
 const performAction=async e=>{e.preventDefault();try{if(action.type==="version"){if(!actionFile)throw new Error("Select a file");if(actionFile.size>10*1024*1024)throw new Error("File exceeds the 10 MiB limit");await upload(action.row.id,actionFile);}else await api.addDocumentLink(action.row.id,link);setAction(null);setActionFile(null);setLink({subject_component:"",subject_type:"",subject_id:"",link_role:"attachment"});await load();}catch(err){setError(err.response?.data?.error?.message||err.message);}};
 const download=async(row,version)=>{try{const r=await api.getDocumentContent(row.id,version.id),binary=atob(r.data.contentBase64),bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);const url=URL.createObjectURL(new Blob([bytes],{type:r.data.mimeType})),a=document.createElement("a");a.href=url;a.download=r.data.filename;a.click();URL.revokeObjectURL(url);}catch(err){setError(err.response?.data?.error?.message||err.message);}};
 return <div className="space-y-5"><header><span className="text-xs uppercase tracking-widest text-purple-400">Reusable content component</span><h1 className="text-3xl font-semibold">Documents</h1><p className="text-gray-400">Versioned, integrity-checked files linked to records across the platform.</p></header>{error&&<p className="rounded border border-red-700 bg-red-950/40 p-3 text-red-200">{error}</p>}{message&&<p className="text-emerald-400">{message}</p>}
 <form onSubmit={save} className="rounded border border-gray-800 bg-gray-900/60 p-4"><h2 className="mb-3 font-semibold">{editing?"Edit document":"Create document"}</h2><div className="grid gap-3 md:grid-cols-3"><input required className="rounded bg-gray-950 p-2" placeholder="Document title" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><input required className="rounded bg-gray-950 p-2" placeholder="Category" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/>{!editing&&<input type="file" className="rounded bg-gray-950 p-2" onChange={e=>setFile(e.target.files?.[0]||null)}/>}<textarea className="rounded bg-gray-950 p-2 md:col-span-3" placeholder="Description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></div><p className="mt-2 text-xs text-gray-500">Optional initial file; maximum 10 MiB. Executables and active web content are rejected.</p><div className="mt-3 flex gap-2"><button className="rounded bg-purple-600 px-4 py-2">{editing?"Save changes":"Create"}</button>{(editing||form.title)&&<button type="button" className="rounded bg-gray-700 px-4 py-2" onClick={()=>{setEditing(null);setForm(empty);setFile(null);}}>Cancel</button>}</div></form>
 {action&&<form onSubmit={performAction} className="rounded border border-purple-700 bg-purple-950/20 p-4"><h2 className="font-semibold">{action.type==="version"?"Add file version":"Link document"}: {action.row.title}</h2>{action.type==="version"?<input required type="file" className="mt-3 rounded bg-gray-950 p-2" onChange={e=>setActionFile(e.target.files?.[0]||null)}/>:<div className="mt-3 grid gap-3 md:grid-cols-4"><input required className="rounded bg-gray-950 p-2" placeholder="Subject component" value={link.subject_component} onChange={e=>setLink({...link,subject_component:e.target.value})}/><input required className="rounded bg-gray-950 p-2" placeholder="Subject type" value={link.subject_type} onChange={e=>setLink({...link,subject_type:e.target.value})}/><input required className="rounded bg-gray-950 p-2" placeholder="Subject identifier" value={link.subject_id} onChange={e=>setLink({...link,subject_id:e.target.value})}/><input required className="rounded bg-gray-950 p-2" placeholder="Link role" value={link.link_role} onChange={e=>setLink({...link,link_role:e.target.value})}/></div>}<div className="mt-3 flex gap-2"><button className="rounded bg-purple-600 px-4 py-2">Save</button><button type="button" className="rounded bg-gray-700 px-4 py-2" onClick={()=>setAction(null)}>Cancel</button></div></form>}
 <section><div className="grid gap-3 sm:grid-cols-2"><input className="rounded bg-gray-900 p-2" placeholder="Search documents" value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}}/><select className="rounded bg-gray-900 p-2" value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="">All statuses</option><option value="active">Active</option><option value="withdrawn">Withdrawn</option></select></div><div className="mt-3 overflow-x-auto"><table className="w-full min-w-[1050px] text-sm"><thead><tr className="border-b border-gray-700 text-left text-gray-400"><th className="p-2">#</th><th>Document</th><th>Status</th><th>Versions</th><th>Links</th><th>Actions</th></tr></thead><tbody>{rows.map((row,i)=><tr key={row.id} className="border-b border-gray-800"><td className="p-2">{(page-1)*50+i+1}</td><td>{row.title}<div className="text-xs text-gray-500">{row.category}</div></td><td>{row.status}</td><td>{row.versions.map(v=><div key={v.id} className="text-xs"><button className="text-blue-300" onClick={()=>download(row,v)}>v{v.version_number} {v.original_filename}</button> ({Math.ceil(v.byte_size/1024)} KiB)</div>)}</td><td>{row.links.map(l=><div key={l.id} className="text-xs">{l.link_role}: {l.subject_component}/{l.subject_type}/{l.subject_id} <button className="text-red-300" onClick={async()=>{if(await askConfirmation({title:"Remove document link?",message:"The file and its versions remain available.",confirmLabel:"Remove",destructive:true})){await api.removeDocumentLink(row.id,l.id);await load();}}}>Remove</button></div>)}</td><td><div className="flex flex-wrap gap-2 text-xs"><button className="text-blue-300" onClick={()=>edit(row)}>Edit</button><button className="text-purple-300" onClick={()=>setAction({type:"version",row})}>New version</button><button className="text-amber-300" onClick={()=>setAction({type:"link",row})}>Link</button><button className={row.status==="withdrawn"?"text-emerald-300":"text-red-300"} onClick={()=>lifecycle(row,row.status==="withdrawn"?"active":"withdrawn")}>{row.status==="withdrawn"?"Reinstate":"Withdraw"}</button></div></td></tr>)}</tbody></table>{!rows.length&&<p className="p-8 text-center text-gray-500">No documents found.</p>}</div><Pagination page={page} pageSize={50} total={total} onPageChange={setPage}/></section></div>;
}
