import React,{useCallback,useEffect,useRef,useState} from 'react';
import * as api from '../../api/client';
import Timeline from './execution/Timeline';
import useUnsavedChanges from '../components/useUnsavedChanges';
import './execution/execution.css';

const label=s=>String(s||'').replaceAll('_',' ').replace(/^./,c=>c.toUpperCase());
const key=()=>crypto.randomUUID();
const failure=e=>e.response?.data?.error?.message||e.message||'Unable to load work';
const response=r=>{if(r.data.success===false)throw new Error(r.data.error?.message);return r.data;};
const initial=()=>{const p=new URLSearchParams(location.search);if(!p.has('execution_view')){try{const saved=JSON.parse(sessionStorage.getItem('execution_selection'));if(saved)return saved;}catch{/* Start at Portfolio if cached selection is invalid. */}}return {instance:p.get('execution_instance')||'',task:p.get('execution_task')||'',tab:p.get('execution_view')||'My Work'};};
const tabs=['Tasks','Timeline','Overview','Planning','History'];
const viewNames={Portfolio:'Projects',Overview:'Progress',Planning:'Project settings',Dependencies:'Handoffs',History:'Activity'};
const names={planning:'Draft',ready:'Ready to start',waiting:'Waiting on another task',upcoming:'Scheduled',blocked:'Needs help',unassigned:'Needs an owner',in_progress:'In progress',completed:'Done',cancelled:'Cancelled'};
const stateName=s=>names[s]||label(s);
const dialogNames={'instance.delete':'Delete project','task.delete':'Delete task','task.add':'Add a task','task.update':'Edit task','create':'Create a project','instance.activate':'Start this project','instance.update':'Project settings','task.complete':'Complete task','decision.approve':'Approve decision','blocker.add':'What is stopping this task?','dependency.add':'What needs to finish first?'};
const taskDefaults={title:'',description:'',responsible_role:'',assignee_staff_id:'',available_on:'',due_on:'',kind:'ordinary',phase_id:'',required_evidence:false};

function Dialog({title,children,onClose,busy}) {
 const ref=useRef(null);
 useEffect(()=>{const previous=document.activeElement;ref.current?.querySelector('input,select,textarea,button')?.focus();return ()=>previous?.focus?.();},[]);
 function keys(e){if(e.key==='Escape'&&!busy)onClose();if(e.key==='Tab'){const nodes=[...ref.current.querySelectorAll('button:not(:disabled),input,select,textarea,a[href]')];const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}}
 return <div className="ex-overlay" onKeyDown={keys}><section ref={ref} className="ex-dialog" role="dialog" aria-modal="true" aria-labelledby="ex-dialog-title"><h2 id="ex-dialog-title">{title}</h2>{children}<button type="button" disabled={busy} onClick={onClose}>Cancel</button></section></div>;
}
function Field({title,children}){return <label>{title}{children}</label>;}
export default function ExecutionWidget(){
 useEffect(()=>{document.documentElement.classList.add('execution-active');return()=>document.documentElement.classList.remove('execution-active');},[]);
 const [nav,setNav]=useState(initial),[workspace,setWorkspace]=useState(null),[instance,setInstance]=useState(null),[history,setHistory]=useState([]),[cursor,setCursor]=useState(null),[preview,setPreview]=useState([]),[references,setReferences]=useState({documents:[],responsibilities:[]});
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[modal,setModal]=useState(null),[form,setForm]=useState({}),[search,setSearch]=useState(''),[filter,setFilter]=useState('all');
 const [page,setPage]=useState(1);
 useEffect(()=>setPage(1),[search,filter,nav.tab,nav.instance]);
 useUnsavedChanges(Boolean(modal&&modal.type!=='context'));
 const navRef=useRef(nav),request=useRef(0),trail=useRef([]),pending=useRef(null);navRef.current=nav;
 const navigate=(next,push=true)=>{if(push)trail.current.push(nav);setNav({...nav,...next});setError('');};
 useEffect(()=>{sessionStorage.setItem('execution_selection',JSON.stringify(nav));const u=new URL(location.href);for(const [k,v] of Object.entries({execution_instance:nav.instance,execution_task:nav.task,execution_view:nav.tab}))v?u.searchParams.set(k,v):u.searchParams.delete(k);window.history.replaceState(window.history.state,'',u);},[nav]);
 const refresh=useCallback(async()=>{const n=navRef.current,token=++request.current;try{const [w,s]=await Promise.all([api.executionWorkspace().then(response),n.instance?api.executionInstance(n.instance).then(response).catch(e=>{if(e.response?.status===404)return{missing:true};throw e;}):null]);if(token!==request.current)return;setWorkspace(w);setInstance(s?.instance||null);setError('');if(s?.missing){setNav(current=>({...current,instance:'',task:'',tab:'Portfolio'}));setNotice('That project no longer exists. Choose a project or create a new one.');}}catch(e){if(token===request.current)setError(failure(e)+' — displayed data may be stale.');}},[]);
 useEffect(()=>{setInstance(null);setPreview([]);refresh();},[nav.instance,refresh]);
 useEffect(()=>{let timer;const tick=()=>{if(!document.hidden&&!pending.current)refresh();timer=setTimeout(tick,30000);};timer=setTimeout(tick,30000);const focus=()=>{if(!pending.current)refresh();};window.addEventListener('focus',focus);return()=>{clearTimeout(timer);window.removeEventListener('focus',focus);};},[refresh]);
 useEffect(()=>{let live=true;if(instance&&nav.task){api.executionPreview(instance.id,nav.task).then(response).then(r=>{if(live&&r.revision===instance.revision)setPreview(r.consequences);}).catch(()=>{if(live)setPreview([]);});}else setPreview([]);return()=>{live=false;};},[instance?.id,instance?.revision,nav.task]);
 useEffect(()=>{let live=true;if(instance?.id&&nav.tab==='History')api.executionHistory(instance.id).then(response).then(r=>{if(live){setHistory(r.history);setCursor(r.next_before);}}).catch(e=>setError(failure(e)));return()=>{live=false;};},[instance?.id,instance?.revision,nav.tab]);
 async function moreHistory(){try{const r=response(await api.executionHistory(instance.id,cursor));setHistory(h=>[...h,...r.history]);setCursor(r.next_before);}catch(e){setError(failure(e));}}
 function open(type,data={}){setError('');pending.current=null;setForm(data);setModal({type,revision:instance?.revision});}
 async function send(type,data={},close=true){if(busy)return;setBusy(true);setError('');try{
   const body={type,data,expected_revision:modal?.revision??instance.revision};const signature=JSON.stringify(body);
   if(!pending.current||pending.current.signature!==signature)pending.current={signature,id:key()};
   const r=response(await api.executionCommand(instance.id,{...body,command_id:pending.current.id}));
   pending.current=null;request.current++;if(type==='instance.delete'){setModal(null);setInstance(null);setNotice('Project deleted.');trail.current=[];navigate({instance:'',task:'',tab:'Portfolio'},false);return;}setInstance(r.instance);setNotice(r.newly_ready?.length?`${r.newly_ready.map(t=>t.title).join(', ')} became Ready.`:'Saved.');if(close)setModal(null);if(type==='task.delete'){setNav(n=>({...n,task:''}));setNotice('Task deleted. Its history is retained in Activity.');}await refresh();
 }catch(e){setError(failure(e));if(e.response?.status===409){pending.current=null;setModal(null);await refresh();setError(failure(e));}}finally{setBusy(false);}}
 function editProject(){open('instance.update',{title:instance.title,academic_year_id:instance.academic_year_id,description:instance.description,lead_staff_id:instance.lead_staff_id||'',target_on:instance.target_on||'',timezone:instance.timezone,retrospective:instance.retrospective});}
 async function create(e){e.preventDefault();if(busy)return;setBusy(true);setError('');try{const signature=JSON.stringify(form);if(!pending.current||pending.current.signature!==signature)pending.current={signature,id:key()};const r=response(await api.createExecutionInstance({...form,command_id:pending.current.id}));pending.current=null;setModal(null);navigate({instance:r.instance.id,task:'',tab:'Tasks'});setNotice('Project created. Add tasks and owners, then start the project.');}catch(e){setError(failure(e));}finally{setBusy(false);}}
 async function saveIdentity(){setBusy(true);setError('');try{response(await api.bindExecutionIdentity(form));setModal(null);setNotice('Your account is now linked to the selected staff record.');await refresh();}catch(e){setError(failure(e));}finally{setBusy(false);}}
 const workRank=t=>['ready','in_progress'].includes(t.state)?0:['blocked','unassigned'].includes(t.state)?1:2;
 const personalWork=[...(workspace?.my_work||[])].sort((a,b)=>workRank(a)-workRank(b)||String(a.due_on||'9999').localeCompare(String(b.due_on||'9999')));
 const selected=instance?.tasks.find(t=>t.id===nav.task),byId=id=>instance?.tasks.find(t=>t.id===id),people=workspace?.people||[],canPlan=instance?.can_plan;
 const select=id=>navigate({task:id});
 useEffect(()=>{if(nav.task&&instance?.id)document.getElementById('ex-detail')?.focus();},[nav.task,instance?.id]);
 const ownerField=(field='assignee_staff_id')=><Field title={field==='lead_staff_id'?'Work lead':'Assigned person'}><select value={form[field]||''} onChange={e=>setForm({...form,[field]:e.target.value})}><option value="">Unassigned</option>{people.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field>;
 const input=(name,title,type='text',required=false)=><Field title={title}><input type={type} required={required} value={form[name]??''} onChange={e=>setForm({...form,[name]:e.target.value})}/></Field>;
 const pageRows=rows=>rows.slice((page-1)*50,page*50);
 const pagination=total=>total>50?<div className="ex-toolbar" aria-label="Result pages"><span>{total?`Showing ${(page-1)*50+1}–${Math.min(page*50,total)} of ${total}`:'No results'}</span><button disabled={page===1} onClick={()=>setPage(p=>p-1)}>Previous page</button><span aria-current="page">Page {page}</span><button disabled={page*50>=total} onClick={()=>setPage(p=>p+1)}>Next page</button></div>:null;
 function card(t,extra,instanceId){const r=t.ready_context;return <button className="ex-card" key={t.id} onClick={()=>instanceId?navigate({instance:instanceId,task:t.id,tab:'Tasks'}):select(t.id)}><strong>{t.title}</strong><small>{t.person_name||'Unassigned'}{t.responsible_role?` · ${t.responsible_role}`:''}</small><span className="ex-badge">{stateName(t.state)}</span>{t.decision_required&&<span className="ex-badge">Decision required</span>}{t.overdue&&<span className="ex-badge">Overdue</span>}<small>{t.due_on?`Due ${t.due_on}`:'No due date'}</small>{extra&&<p>{extra}</p>}{r&&['task.complete','decision.approve'].includes(r.cause)&&<p>{r.actor_name} {r.cause==='decision.approve'?'approved':'completed'} {r.cause_task_title}. Ready since {r.at} UTC.</p>}</button>;}
 const consequence=c=>c.newly_ready?'Will become Ready':c.after==='completed'?'Remains completed':c.after==='in_progress'?'Remains in progress':`${label(c.after)}${c.reasons.length?` — ${c.reasons.map(r=>r.message).join('; ')}`:''}`;
 function wheel(){if(!selected)return <p className="ex-panel">Choose a task to inspect its handoffs.</p>;const incoming=instance.dependencies.filter(e=>e.to_id===selected.id&&e.state!=='removed'),outgoing=instance.dependencies.filter(e=>e.from_id===selected.id&&e.state!=='removed');return <><p className="ex-muted">What enabled this → work in focus → what this enables. Completion consequences are previews, not state changes.</p><div className="ex-wheel"><section className="ex-panel"><h2>← Prerequisites ({incoming.length})</h2>{incoming.map(e=><div key={e.id}>{card(byId(e.from_id),e.state==='waived'?`Waived: ${e.reason}`:byId(e.from_id).reasons.map(r=>r.message).join('; '))}</div>)}{!incoming.length&&<p>No prerequisite work.</p>}</section><section className="ex-panel ex-hub"><h2>{selected.title}</h2><p>{selected.person_name||'Unassigned'} · {selected.responsible_role||'Role unspecified'}</p><span className="ex-badge">{stateName(selected.state)}</span><p>{selected.reasons.map(r=>r.message).join('; ')||'Prerequisites satisfied'}</p><button onClick={()=>document.getElementById('ex-detail')?.scrollIntoView({behavior:'auto'})}>Task details and actions</button><button onClick={()=>navigate({tab:'Timeline'})}>View in Timeline</button></section><section className="ex-panel"><h2>Successors → ({outgoing.length})</h2>{outgoing.map(e=><div key={e.id}>{card(byId(e.to_id),e.state==='waived'?'This dependency is waived':preview.find(c=>c.task_id===e.to_id)?consequence(preview.find(c=>c.task_id===e.to_id)):'Loading consequences…')}</div>)}{!outgoing.length&&<p>No direct successors.</p>}</section></div></>;}
 async function evidence(kind){try{setReferences(response(await api.executionReferences()));open('link.add',{task_id:selected.id,kind,note:'',reference:''});}catch(e){setError(failure(e));}}
 async function inspectContext(link){try{const r=response(await api.get(`/execution/instances/${instance.id}/context?link_id=${encodeURIComponent(link.id)}`));open('context',r);}catch(e){setError(failure(e));}}
 function detail(){if(!selected)return null;return <section className="ex-panel ex-detail" id="ex-detail" tabIndex={-1} aria-label="Task details"><button className="ex-close" onClick={()=>navigate({task:''})}>Close details ×</button><p className="ex-eyebrow">Task details</p><h2>{selected.title}</h2><p>{selected.description||'No description added.'}</p><dl className="ex-task-properties"><dt>Owner</dt><dd>{selected.person_name||'Unassigned'}</dd><dt>Status</dt><dd><span className="ex-badge">{stateName(selected.state)}</span></dd><dt>Due</dt><dd>{selected.due_on||'No due date'}</dd>{selected.responsible_role&&<><dt>Role</dt><dd>{selected.responsible_role}</dd></>}</dl>{selected.reasons.length>0&&<ul>{selected.reasons.map((r,i)=><li key={i}>{r.message}</li>)}</ul>}
 <div className="ex-toolbar">{canPlan&&<button onClick={()=>open('task.update',{...taskDefaults,...selected,task_id:selected.id})} disabled={['completed','cancelled'].includes(selected.lifecycle)}>Edit task</button>}{selected.can_act&&<>
 {selected.actionable&&selected.kind==='ordinary'&&selected.lifecycle==='open'&&<button disabled={busy} onClick={()=>send('task.start',{task_id:selected.id})}>Start</button>}
 {selected.actionable&&<button className="ex-primary" onClick={()=>open(selected.kind==='decision'?'decision.approve':'task.complete',{task_id:selected.id,reason:''})}>{selected.kind==='decision'?'Approve decision':'Complete task'}</button>}
 {selected.actionable&&selected.kind==='decision'&&<button onClick={()=>open('decision.return',{task_id:selected.id,reason:'',revision_task_ids:[]})}>Return for revision</button>}
 {!['completed','cancelled'].includes(selected.lifecycle)&&<><button onClick={()=>open('blocker.add',{task_id:selected.id,reason:''})}>Record blocker</button><button onClick={()=>evidence('evidence')}>Add evidence</button></>}
 </>}{canPlan&&<details className="ex-task-more"><summary>More actions</summary>{selected.lifecycle==='completed'?<button onClick={()=>open('task.reopen',{task_id:selected.id,reason:''})}>Reopen</button>:selected.lifecycle==='cancelled'?<button onClick={()=>open('task.reinstate',{task_id:selected.id,reason:''})}>Reinstate</button>:<button onClick={()=>open('task.cancel',{task_id:selected.id,reason:''})}>Cancel task</button>}</details>}{instance.can_manage&&<button className="ex-danger" onClick={()=>open('task.delete',{task_id:selected.id,confirm_delete:true})}>Delete task</button>}</div>
 {instance.blockers.filter(b=>b.task_id===selected.id&&b.state==='open').map(b=><div className="ex-warning" key={b.id}>⚑ {b.reason} {selected.can_act&&<button onClick={()=>open('blocker.resolve',{task_id:selected.id,blocker_id:b.id,reason:''})}>Resolve blocker</button>}</div>)}
 <details><summary>What needs to happen before and after this task?</summary><button onClick={()=>navigate({tab:'Dependencies'})}>Show handoff diagram</button>{instance.dependencies.filter(e=>(e.to_id===selected.id||e.from_id===selected.id)&&e.state!=='removed').map(e=><div className="ex-panel" key={e.id}><button onClick={()=>select(e.from_id)}>{byId(e.from_id).title}</button> → <button onClick={()=>select(e.to_id)}>{byId(e.to_id).title}</button><p>{label(e.state)} · {e.reason||e.rationale||'No rationale recorded'}</p>{canPlan&&<div className="ex-toolbar"><button onClick={()=>open(e.state==='waived'?'dependency.reinstate':'dependency.waive',{dependency_id:e.id,reason:''})}>{e.state==='waived'?'Reinstate requirement':'Waive requirement'}</button><button onClick={()=>open('dependency.remove',{dependency_id:e.id,reason:''})}>Remove as planning correction</button></div>}</div>)}{canPlan&&<button onClick={()=>open('dependency.add',{from_id:'',to_id:selected.id,reason:''})}>Add prerequisite</button>}</details>
 <details><summary>Evidence and responsibility links</summary>{selected.can_act&&!['completed','cancelled'].includes(selected.lifecycle)&&<button onClick={()=>evidence('responsibility')}>Link responsibility</button>}{instance.links.filter(l=>l.task_id===selected.id).map(l=><div className="ex-panel" key={l.id}>{l.restricted?<p>Restricted {l.kind} reference</p>:l.kind==='responsibility'?<><strong>{l.title}</strong><p>{l.wording}</p><button onClick={()=>inspectContext(l)}>Inspect formal source context</button><span className="ex-badge">Evidence: {l.evidence||'unknown'}</span><span className="ex-badge">Review: {l.review_status}</span><p>Revision {l.revision} · {l.status}. Context only; no authority granted.</p>{l.review_status!=='reviewed'&&<p className="ex-warning">Provisional organisational context — not approved structure.</p>}</>:l.note?<p>{l.note}</p>:<><strong>{l.title}</strong><p>Document version {l.version_number} · {l.sha256?.slice(0,12)}</p></>}</div>)}<p className="ex-muted">Links pin an exact source version. Execution does not update Layer 1.</p></details>
 </section>;}
 function milestones(){return <section className="ex-panel"><h2>Milestones</h2>{instance.milestones.map(m=><div key={m.id} className="ex-panel"><strong>◆ {m.title}</strong><p>{m.target_on||'Date unspecified'} · {label(m.status)}</p>{m.review_reason&&<p className="ex-warning">{m.review_reason}</p>}{m.contributions.map(c=><div key={c.task_id}><button onClick={()=>select(c.task_id)}>{byId(c.task_id).title}</button> · {label(c.state)}{canPlan&&c.state==='required'&&<button onClick={()=>open('milestone.waive',{milestone_id:m.id,task_id:c.task_id,reason:''})}>Waive contribution</button>}</div>)}{canPlan&&<div className="ex-toolbar">{m.status==='pending'?<><button onClick={()=>open('milestone.achieve',{milestone_id:m.id,reason:''})}>Record achievement</button><button onClick={()=>open('milestone.cancel',{milestone_id:m.id,reason:''})}>Cancel milestone</button></>:<button onClick={()=>open('milestone.reopen',{milestone_id:m.id,reason:''})}>Reopen milestone</button>}</div>}</div>)}{!instance.milestones.length&&<p>No milestones yet.</p>}{canPlan&&<button onClick={()=>open('milestone.add',{title:'',target_on:'',task_ids:[]})}>Add milestone</button>}</section>;}
 function taskTable(){const tasks=instance.tasks.filter(t=>(filter==='all'||t.state===filter)&&`${t.title} ${t.person_name||''} ${t.responsible_role}`.toLowerCase().includes(search.toLowerCase()));return <><div className="ex-toolbar ex-list-tools"><input aria-label="Search tasks" placeholder="Find a task or person…" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Filter task state" value={filter} onChange={e=>setFilter(e.target.value)}>{['all',...Object.keys(names)].map(s=><option key={s} value={s}>{s==='all'?'All tasks':stateName(s)}</option>)}</select>{canPlan&&<button className="ex-primary" onClick={()=>open('task.add',taskDefaults)}>Add task</button>}</div><div className="ex-table-wrap"><table className="ex-table"><thead><tr><th>Task</th><th>Owner</th><th>Status</th><th>Due</th></tr></thead><tbody>{pageRows(tasks).map(t=><tr key={t.id} className={selected?.id===t.id?'ex-selected':''}><td><button aria-current={selected?.id===t.id?'true':undefined} onClick={()=>select(t.id)}>{t.title}</button><small className="ex-mobile-owner">{t.person_name||'Choose an owner'}</small>{t.kind==='decision'&&<small>Approval task</small>}</td><td>{t.person_name||'Choose an owner'}</td><td><span className={'ex-state ex-state-'+t.state}>{stateName(t.state)}</span></td><td>{t.due_on||'No date'}{t.overdue&&<small className="ex-overdue">Overdue</small>}</td></tr>)}</tbody></table>{tasks.length>50&&pagination(tasks.length)}{!tasks.length&&<div className="ex-empty"><h3>{instance.tasks.length?'No matching tasks':'What needs to get done?'}</h3><p>{instance.tasks.length?'Try another search or status.':'Add one clear action at a time. Give it an owner and a due date if known.'}</p></div>}</div></>;}
 function modalContents(){const type=modal.type,isTask=['task.add','task.update'].includes(type),editInstance=type==='instance.update',isCreate=type==='create';
 if(type==='identity.bind')return <Dialog title="Link my account to my staff record" onClose={()=>setModal(null)} busy={busy}><form onSubmit={e=>{e.preventDefault();saveIdentity();}}><p>This links your authenticated account to the selected canonical staff record. Existing bindings are not overwritten.</p><div className="ex-form">{ownerField('staff_id')}{input('reason','Reason','text',true)}</div>{error&&<p className="ex-error" role="alert">{error}</p>}<div className="ex-toolbar"><button disabled={busy||!form.staff_id} className="ex-primary">Confirm my identity</button></div></form></Dialog>;
 if(type==='context')return <Dialog title="Formal responsibility — pinned context" onClose={()=>setModal(null)} busy={false}><strong>{form.record.data.name}</strong><p>{form.record.data.normalized_statement}</p><p>Revision {form.record.revision} · {form.record.data.evidence||'Evidence unknown'} · Review: {form.record.data.review_status}</p>{form.record.data.review_status!=='reviewed'&&<p className="ex-warning">Provisional context. This does not approve the responsibility or confer authority.</p>}{form.statement&&<section className="ex-panel"><h3>Exact source statement</h3><blockquote>{form.statement.data.original_text}</blockquote><p>{form.statement.data.location} · statement revision {form.statement.revision}</p></section>}{form.source&&<p>Source: {form.source.data.name} · {form.source.data.version_label} · document version {form.source.data.document_version_id}</p>}<button onClick={()=>setModal(null)}>Back to task</button></Dialog>;
 const submit=e=>{e.preventDefault();if(isCreate)return create(e);let data={...form};if(type==='link.add'){if(form.kind==='responsibility'){const r=references.responsibilities.find(r=>r.id===form.reference);if(!r){setError('Select a responsibility');return;}data={task_id:form.task_id,kind:'responsibility',responsibility_id:r.id,revision:r.revision};}else if(form.reference)data={task_id:form.task_id,kind:'evidence',document_version_id:Number(form.reference)};else data={task_id:form.task_id,kind:'evidence',note:form.note};}send(type,data);};
 return <Dialog title={dialogNames[type]||label(type.replace('.',' '))} onClose={()=>{setModal(null);pending.current=null;}} busy={busy}><form onSubmit={submit}><fieldset disabled={busy} className="ex-form">
 {(isTask||isCreate||editInstance||['phase.add','milestone.add'].includes(type))&&input('title','Title','text',true)}
 {(isTask||isCreate||editInstance)&&<Field title="Description"><textarea value={form.description||''} onChange={e=>setForm({...form,description:e.target.value})}/></Field>}
 {(isCreate||editInstance)&&<>{ownerField('lead_staff_id')}{input('target_on','Target date','date')}<details className="ex-wide"><summary>School context and project notes</summary><div className="ex-form"><Field title="Academic year (optional)"><select value={form.academic_year_id||''} onChange={e=>setForm({...form,academic_year_id:e.target.value})}><option value="">Unspecified</option>{(workspace?.years||[]).map(y=><option key={y.id} value={y.id}>{y.name}</option>)}</select></Field>{input('timezone','School timezone (IANA)','text',true)}{editInstance&&<Field title="Retrospective and continuity notes"><textarea value={form.retrospective||''} onChange={e=>setForm({...form,retrospective:e.target.value})}/></Field>}</div></details></>}
 {isTask&&<>{ownerField()}{input('due_on','Due date','date')}<details className="ex-wide"><summary>More options: approval, scheduling and evidence</summary><div className="ex-form">{input('responsible_role','Responsible role (optional)')}{input('available_on','Available from','date')}<Field title="Kind"><select value={form.kind} onChange={e=>setForm({...form,kind:e.target.value})}><option value="ordinary">Task</option><option value="decision">Decision</option></select></Field><Field title="Phase"><select value={form.phase_id||''} onChange={e=>setForm({...form,phase_id:e.target.value})}><option value="">No phase</option>{instance.phases.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></Field><label className="ex-check"><input type="checkbox" checked={form.required_evidence} onChange={e=>setForm({...form,required_evidence:e.target.checked})}/>Require completion evidence</label></div></details></>}
 {type==='dependency.add'&&<><Field title="Prerequisite"><select required value={form.from_id} onChange={e=>setForm({...form,from_id:e.target.value})}><option value="">Choose work</option>{instance.tasks.filter(t=>t.id!==form.to_id).map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select></Field><p>Must finish before: {byId(form.to_id)?.title}</p></>}
 {type==='milestone.add'&&<>{input('target_on','Target date','date')}<fieldset className="ex-wide"><legend>Required contributions (optional)</legend>{instance.tasks.map(t=><label key={t.id} className="ex-check"><input type="checkbox" checked={form.task_ids.includes(t.id)} onChange={e=>setForm({...form,task_ids:e.target.checked?[...form.task_ids,t.id]:form.task_ids.filter(id=>id!==t.id)})}/>{t.title}</label>)}</fieldset></>}
 {type==='decision.return'&&<fieldset className="ex-wide"><legend>Deliverables to revise</legend>{instance.dependencies.filter(e=>e.to_id===form.task_id&&e.state==='active').map(e=>byId(e.from_id)).filter(t=>t.lifecycle==='completed').map(t=><label className="ex-check" key={t.id}><input type="checkbox" checked={form.revision_task_ids.includes(t.id)} onChange={e=>setForm({...form,revision_task_ids:e.target.checked?[...form.revision_task_ids,t.id]:form.revision_task_ids.filter(id=>id!==t.id)})}/>{t.title}</label>)}<p>No selected deliverable: the reason becomes a revision blocker.</p></fieldset>}
 {type==='link.add'&&<><Field title={form.kind==='responsibility'?'Formal responsibility (exact current revision)':'Document version (optional)'}><select value={form.reference} onChange={e=>setForm({...form,reference:e.target.value})}><option value="">Choose reference</option>{form.kind==='responsibility'?references.responsibilities.map(r=><option key={r.id} value={r.id}>{r.title} — {r.review_status} · r{r.revision}</option>):references.documents.map(d=><option key={d.id} value={d.id}>{d.title} · v{d.version_number}</option>)}</select></Field>{form.kind==='evidence'&&<Field title="Or a concise evidence note"><textarea value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/></Field>}</>}
 {'reason' in form&&<Field title={type==='dependency.add'?'Rationale (optional)':'Reason / rationale'}><textarea required={!['task.complete','decision.approve','dependency.add','blocker.resolve','milestone.achieve','instance.activate','instance.close'].includes(type)} value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})}/></Field>}
 {['task.complete','decision.approve','task.reopen','task.cancel','decision.return'].includes(type)&&<div className="ex-wide ex-warning"><h3>What happens next</h3>{type==='task.complete'||type==='decision.approve'?preview.map(c=><p key={c.task_id}>{byId(c.task_id)?.title}: {consequence(c)}</p>):<p>Unfinished dependants will wait. In-progress and completed dependants retain their work with a review exception where necessary. No implicit waivers.</p>}{!preview.length&&<p>No active direct successors.</p>}</div>}
 {type==='instance.delete'&&<div className="ex-wide ex-warning"><h3>Delete “{instance.title}”?</h3><p>This removes the whole project, including its {instance.tasks.length} tasks, dependencies, milestones and evidence links, from Projects and My Work.</p><p>There is no undo button. An audit record is retained. Source documents and formal responsibilities are not deleted.</p></div>}
 {type==='task.delete'&&<div className="ex-wide ex-warning"><h3>Delete “{selected?.title}”?</h3><p>This removes the task from this project and My Work. There is no undo button. Its previous state remains in Activity history.</p><ul><li>{instance.dependencies.filter(e=>e.from_id===form.task_id||e.to_id===form.task_id).length} dependency links will be removed. Tasks waiting on this one may become ready; no other task will be completed or approved.</li><li>{instance.milestones.filter(m=>m.contributions.some(c=>c.task_id===form.task_id)).length} milestones will lose this task as a contribution. Their achievement status will not change automatically.</li><li>This task’s blockers, decisions and evidence links will be removed from the working project. Source documents and responsibilities will not be deleted.</li></ul></div>}
 {type==='instance.cancel'&&<p className="ex-wide ex-warning">Cancel all unfinished work in this project. Completed work and its history are preserved. This cannot be resumed in this version.</p>}
 {type==='instance.activate'&&<p className="ex-wide">Starting makes assigned tasks available when their requirements are met. Tasks without a named owner stay unassigned.</p>}
 {type==='instance.close'&&<p className="ex-wide">All work must be completed or explicitly cancelled, with blockers, exceptions and milestones resolved.</p>}
 </fieldset>{error&&<p role="alert" className="ex-error">{error}</p>}<div className="ex-toolbar"><button className="ex-primary" disabled={busy}>{busy?'Saving…':isCreate?'Create project':type==='instance.delete'?'Delete project permanently':type==='task.delete'?'Delete task permanently':isTask?(type==='task.add'?'Add task':'Save task'):editInstance?'Save project':type==='instance.activate'?'Start project':type==='task.complete'?'Complete task':type==='decision.approve'?'Approve decision':'Confirm and save'}</button></div></form></Dialog>;
 }
 return <div className="execution"><div className="ex-topnav"><h1>Projects &amp; tasks</h1><div className="ex-page-actions"><button disabled={busy} onClick={refresh}>Refresh</button>{workspace?.identity.can_create&&<button className="ex-primary" onClick={()=>open('create',{title:'',description:'',lead_staff_id:'',timezone:Intl.DateTimeFormat().resolvedOptions().timeZone,target_on:''})}>New project</button>}</div></div>
 <nav className="ex-switcher" aria-label="Work navigation"><button aria-current={nav.tab==='My Work'?'page':undefined} onClick={()=>navigate({instance:'',task:'',tab:'My Work'})}>My Work</button><button aria-current={nav.tab==='Portfolio'||nav.instance?'page':undefined} onClick={()=>navigate({instance:'',task:'',tab:'Portfolio'})}>Projects</button></nav>
 <details className="ex-help"><summary>How work moves forward</summary><ol><li>Create a project, add tasks and choose their owners.</li><li>Start the project when the team is ready.</li><li>Open My Work, choose a task and start or complete it. Record a blocker if you need help.</li><li>Review progress, then close the finished project in Project settings.</li></ol></details>
 {!modal&&error&&<p role="alert" className="ex-error">{error}</p>}<p role="status" className="ex-status">{notice}</p>{!workspace&&!error&&<p>Loading work…</p>}
 {nav.tab==='Portfolio'&&workspace&&<><input aria-label="Search Work Instances" placeholder="Find a project…" value={search} onChange={e=>setSearch(e.target.value)}/><div className="ex-grid">{pageRows(workspace.instances.filter(s=>s.title.toLowerCase().includes(search.toLowerCase()))).map(s=><button key={s.id} className="ex-panel ex-card" onClick={()=>navigate({instance:s.id,task:'',tab:'Tasks'})}><strong>{s.title}</strong><p>{s.lifecycle==='planning'?'Draft':label(s.lifecycle)} · {s.lead_name||'No lead yet'}</p><p>{s.attention?`${s.attention} issues need attention`:'No current attention flags'}</p><small>{s.completed_count} of {s.task_count} complete · {s.target_on||'No target date'}</small></button>)}</div>{pagination(workspace.instances.filter(s=>s.title.toLowerCase().includes(search.toLowerCase())).length)}{!workspace.instances.length&&<p className="ex-panel">No projects yet. Create a project, add a few tasks, and choose who will do them.</p>}</>}
 {nav.tab==='My Work'&&workspace&&<><h2>My Work</h2>{workspace.identity.can_bind&&!workspace.identity.staff_id&&<button onClick={()=>open('identity.bind',{staff_id:'',reason:''})}>Link my staff record</button>}{!workspace.identity.staff_id&&<p className="ex-warning">{workspace.identity.ambiguous?'Your account is linked to multiple staff records. Resolve that mapping before personal actions.':'Your account is not linked to one active staff record. A staff administrator must bind your account before personal work appears.'}</p>}<p className="ex-muted">Start with work you can move forward. Waiting tasks stay here until their requirements are met.</p>{[['Next up',t=>['ready','in_progress'].includes(t.state)],['Needs attention',t=>['blocked','unassigned'].includes(t.state)],['Waiting and scheduled',t=>!['ready','in_progress','blocked','unassigned'].includes(t.state)]].map(([title,match])=>{const rows=personalWork.filter(match);return pageRows(personalWork).some(match)&&<section className="ex-queue" key={title}><h3>{title} <span>{rows.length}</span></h3>{pageRows(personalWork).filter(match).map(t=><div key={t.id}><small>{t.instance_title}</small>{card(t,t.reasons.map(r=>r.message).join('; '),t.instance_id)}</div>)}</section>;})}{workspace.my_work.length>50&&pagination(workspace.my_work.length)}{workspace.identity.staff_id&&!workspace.my_work.length&&<div className="ex-empty"><h3>You’re up to date</h3><p>No open tasks are assigned to you. You can browse your team’s projects above.</p></div>}</>}
 {nav.instance&&!instance&&!error&&<p>Loading project…</p>}
 {instance&&<><section className="ex-project-header"><p className="ex-eyebrow">Project · {instance.lifecycle==='planning'?'Draft':label(instance.lifecycle)}</p><h2>{instance.title}</h2><p>{instance.description}</p><div className="ex-project-meta"><span>{people.find(p=>p.id===instance.lead_staff_id)?.name||'No lead assigned'}</span><span>{instance.completed_count} of {instance.tasks.length} tasks done</span>{instance.target_on&&<span>Target {instance.target_on}</span>}</div><progress aria-label="Project progress" value={instance.completed_count} max={Math.max(1,instance.tasks.length)}/>{instance.lifecycle==='planning'&&<div className="ex-guide"><strong>Set up your project</strong><ol><li>Add the tasks</li><li>Choose a lead and task owners</li><li>Start when the team is ready</li></ol>{canPlan&&<>{!instance.lead_staff_id&&<button onClick={editProject}>Choose project lead</button>}<button disabled={!instance.tasks.length||!instance.lead_staff_id} className="ex-primary" onClick={()=>open('instance.activate',{reason:''})}>Start project</button></>}</div>}<nav className="ex-toolbar" aria-label="Execution views">{tabs.map(t=><button key={t} aria-current={nav.tab===t?'page':undefined} onClick={()=>navigate({tab:t,task:t==='Dependencies'?nav.task:''})}>{viewNames[t]||t}</button>)}<button aria-current={nav.tab==='Dependencies'?'page':undefined} onClick={()=>navigate({tab:'Dependencies'})}>Handoffs</button></nav></section><div className={selected?'ex-workspace ex-with-detail'+(nav.tab==='Dependencies'?' ex-handoffs':''):'ex-workspace'}><main className="ex-content">
 {nav.tab==='Overview'&&<><div className="ex-grid"><section className="ex-panel"><h2>Needs attention</h2>{instance.tasks.filter(t=>!['completed','cancelled'].includes(t.lifecycle)&&(t.overdue||['blocked','unassigned'].includes(t.state)||t.decision_required)).map(t=>card(t,t.reasons.map(r=>r.message).join('; ')))}{!instance.attention&&<p>No current attention flags.</p>}{instance.exceptions.filter(x=>x.state==='open').map(x=><p key={x.id} className="ex-warning"><button onClick={()=>select(x.task_id)}>{byId(x.task_id)?.title}</button>: prerequisite changed; explicit review required.</p>)}</section><section className="ex-panel"><h2>Progress and continuity</h2><p>{instance.completed_count} of {instance.tasks.length} tasks complete</p><p>{instance.target_on?`Event / target: ${instance.target_on}`:'No target date'}</p><p>{instance.retrospective||'No retrospective recorded yet.'}</p><button onClick={()=>navigate({tab:'Timeline'})}>Open Timeline</button></section></div>{milestones()}</>}
 {nav.tab==='Planning'&&<><h2>Project settings</h2>{instance.can_manage&&<button className="ex-danger" onClick={()=>open('instance.delete',{confirm_delete:true})}>Delete project</button>}{canPlan?<div className="ex-toolbar"><button onClick={editProject}>Edit project</button><button onClick={()=>open('phase.add',{title:''})}>Add phase</button>{instance.lifecycle==='planning'?<button className="ex-primary" onClick={()=>open('instance.activate',{reason:''})}>Start project</button>:<button onClick={()=>open('instance.close',{reason:''})}>Close completed work</button>}<button onClick={()=>open('instance.cancel',{reason:''})}>Cancel project</button></div>:<p>Planning is available to the active lead or Execution manager.</p>}{instance.can_manage&&instance.lifecycle==='completed'&&<button onClick={()=>open('instance.reopen',{reason:''})}>Reopen project</button>}{instance.schedule_warnings.map(w=><p key={w.edge_id} className="ex-warning">{w.message}. Review dates; no automatic rescheduling.</p>)}{milestones()}</>}
 {nav.tab==='Tasks'&&taskTable()}{nav.tab==='Timeline'&&<Timeline instance={instance} selected={nav.task} onSelect={id=>navigate({task:id})}/>}{nav.tab==='Dependencies'&&wheel()}
 {nav.tab==='History'&&<section className="ex-panel"><h2>Project activity</h2>{history.map(h=><div className="ex-panel" key={h.id}><strong>{label(h.type.replace('.',' '))}{h.title?` · ${h.title}`:''}</strong><p>{h.at} UTC · {h.actor_name} · revision {h.revision}</p>{h.reason&&<p>{h.reason}</p>}</div>)}{cursor&&<button onClick={moreHistory}>Earlier history</button>}</section>}
 </main>{detail()}</div></>}{modal&&modalContents()}</div>;
}
