import React,{useEffect,useState}from"react";
import * as api from"../../api/client";
import Pagination from"../components/Pagination";

const tone={high:"border-red-800 bg-red-950/20 text-red-200",medium:"border-amber-800 bg-amber-950/20 text-amber-200",low:"border-blue-800 bg-blue-950/20 text-blue-200"};

export default function GradebookWidget(){
 const[gradebooks,setGradebooks]=useState([]),[page,setPage]=useState(1),[total,setTotal]=useState(0),[selected,setSelected]=useState(null),[periods,setPeriods]=useState([]),[period,setPeriod]=useState(""),[workspace,setWorkspace]=useState(null),[insights,setInsights]=useState([]),[error,setError]=useState("");
 const load=()=>Promise.all([api.listGradebooks({page,limit:50,status:"active"}),api.getGradebookInsights()]).then(([books,signals])=>{setGradebooks(books.data.gradebooks);setTotal(books.data.total);setInsights(signals.data.insights);setError("")}).catch(e=>setError(e.response?.data?.error?.message||e.message));
 useEffect(()=>{load()},[page]);
 const open=async book=>{try{const response=await api.getGradebookReportingPeriods(book.id);setSelected(book);setPeriods(response.data.periods);const first=response.data.periods[0]?.id||"";setPeriod(first);const view=await api.getGradebookWorkspace(book.id,first?{reporting_period_id:first}:{});setWorkspace(view.data.workspace);setError("")}catch(e){setError(e.response?.data?.error?.message||e.message)}};
 const changePeriod=async value=>{setPeriod(value);try{const view=await api.getGradebookWorkspace(selected.id,value?{reporting_period_id:value}:{});setWorkspace(view.data.workspace)}catch(e){setError(e.response?.data?.error?.message||e.message)}};
 return <div className="space-y-5">
  <header><span className="text-xs uppercase tracking-widest text-purple-400">Academic operations</span><h1 className="text-3xl font-semibold">Gradebook</h1><p className="text-gray-400">Academic evidence, learning behaviours, classroom attendance, commentary and reporting remain distinct but connected.</p></header>
  {error&&<p className="rounded border border-red-700 p-3 text-red-200">{error}</p>}
  {insights.length>0&&<section><h2 className="mb-2 text-lg font-semibold">Attention</h2><div className="grid gap-2 md:grid-cols-2">{insights.map((x,i)=><div key={`${x.type}-${i}`} className={`rounded border p-3 ${tone[x.severity]||tone.low}`}><div className="flex justify-between gap-3"><strong>{x.title}</strong><span>{x.count}</span></div><p className="mt-1 text-xs opacity-75">Advisory · {x.type}</p></div>)}</div></section>}
  {selected&&workspace&&<section className="rounded border border-purple-800 p-4"><div className="mb-4 flex flex-wrap items-start justify-between gap-3"><div><button className="mb-2 text-sm text-blue-300" onClick={()=>{setSelected(null);setWorkspace(null)}}>← Back to Gradebooks</button><h2 className="text-xl font-semibold">{workspace.gradebook.name}</h2><p className="text-sm text-gray-400">{workspace.pagination.total} roster entries · {workspace.assessments.length} assessments</p></div><label className="text-sm text-gray-300">Reporting period<select className="ml-2 rounded bg-gray-900 p-2" value={period} onChange={e=>changePeriod(e.target.value)}><option value="">All dates</option>{periods.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label></div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead><tr className="border-b border-gray-700 text-left text-gray-400"><th className="p-2">#</th><th className="p-2">Student</th><th className="p-2">Enrolment</th>{workspace.assessments.map(x=><th className="p-2" key={x.id}>{x.title}</th>)}<th className="p-2">Current result</th></tr></thead><tbody>{workspace.students.map((student,i)=><tr key={student.id} className="border-b border-gray-800"><td className="p-2">{(workspace.pagination.page-1)*workspace.pagination.limit+i+1}</td><td className="p-2 font-mono">{student.student_id}</td><td className={student.status==="withdrawn"?"p-2 text-amber-300":"p-2 text-emerald-300"}>{student.status}</td>{student.evidence.map(cell=><td className="p-2" key={cell.assessment_id}>{cell.evidence?.raw_numeric??cell.evidence?.raw_text??cell.evidence?.state??"—"}</td>)}<td className="p-2">{student.result?.overridden_value??student.result?.text_result??student.result?.numeric_result??"—"}<span className="block text-xs text-gray-500">{student.result?.confidence||"not evaluated"}</span></td></tr>)}</tbody></table></div></section>}
  {!selected&&<><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead><tr className="border-b border-gray-700 text-left text-gray-400">{["#","Gradebook","Type","Mode","Status","Action"].map(x=><th key={x} className="p-2">{x}</th>)}</tr></thead><tbody>{gradebooks.map((book,i)=><tr key={book.id} className="border-b border-gray-800"><td className="p-2">{(page-1)*50+i+1}</td><td className="p-2">{book.name}</td><td className="p-2">{book.kind}</td><td className="p-2">{book.mode.replaceAll("_"," ")}</td><td className="p-2">{book.status}</td><td className="p-2"><button className="text-blue-300" onClick={()=>open(book)}>Open workspace</button></td></tr>)}</tbody></table></div><Pagination page={page} pageSize={50} total={total} onPageChange={setPage}/></>}
 </div>;
}
