import React,{useEffect,useState}from"react";
import * as api from"../../api/client";
import Pagination from"../components/Pagination";
import LateEntryReviewPanel from"../components/LateEntryReviewPanel";
const label=v=>String(v||"").replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());
const errorMessage=e=>e.response?.data?.error?.message||e.message;
const freshId=()=>globalThis.crypto?.randomUUID?.()||`late-${Date.now()}-${Math.random()}`;
export default function LateEntriesWidget({askConfirmation,askText}){
 const[tab,setTab]=useState("arrivals"),[entries,setEntries]=useState([]),[reasons,setReasons]=useState([]),[policies,setPolicies]=useState([]),[summary,setSummary]=useState({}),[page,setPage]=useState(1),[total,setTotal]=useState(0),[filter,setFilter]=useState("today"),[search,setSearch]=useState(""),[students,setStudents]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState(""),[proposal,setProposal]=useState(null),[thresholdCases,setThresholdCases]=useState([]);
 const[form,setForm]=useState({student_id:"",occurrence_type:"school_arrival",reason_code:"transport_delay",operational_note:"",evidence_reference:""}),[policyForm,setPolicyForm]=useState({effective_from:new Date().toISOString().slice(0,10),school_day_grace_minutes:0,class_grace_minutes:0,school_tardies_per_absence:3,class_tardies_per_absence:3,count_excused:false});
 const load=async()=>{try{const params={page,limit:50,...(filter==="today"?{date:new Date().toISOString().slice(0,10)}:filter==="unresolved"?{unresolved:true}:{})},[list,dash,reasonData,policyData,cases]=await Promise.all([api.listLateEntries(params),api.getLateEntriesDashboard(),api.listLateEntryReasons(),api.listLateEntryPolicies(),api.listLateEntryThresholdCases({status:"recommended"})]);setEntries(list.data.entries);setTotal(list.data.total);setSummary(dash.data.summary);setReasons(reasonData.data.reasons.filter(x=>x.enabled));setPolicies(policyData.data.policies);setThresholdCases(cases.data.cases);setError("")}catch(e){setError(errorMessage(e))}};
 useEffect(()=>{void load()},[page,filter]);
 useEffect(()=>{const timer=setTimeout(async()=>{if(search.trim().length<2)return setStudents([]);try{const r=await api.listStudents({page:1,limit:10,search:search.trim()});setStudents(r.data.students||[])}catch(e){setError(errorMessage(e))}},250);return()=>clearTimeout(timer)},[search]);
 const run=async fn=>{setBusy(true);try{await fn();await load()}catch(e){setError(errorMessage(e))}finally{setBusy(false)}};
 const choose=s=>{setForm({...form,student_id:s.student_id});setSearch(`${s.first_name} ${s.last_name} (${s.student_id})`);setStudents([])};
 const submit=e=>{e.preventDefault();if(!form.student_id)return setError("Select or scan a student.");run(async()=>{const body={...Object.fromEntries(Object.entries(form).filter(([,v])=>v!=="")),arrival_at:new Date().toISOString(),client_request_id:freshId()},created=await api.createLateEntry(body);if(created.data.entry.status==="context_resolved"){const proposed=await api.proposeLateEntryReconciliation(created.data.entry.id);if(proposed.data.run.status==="proposed")setProposal({entry:created.data.entry,run:proposed.data.run});else setError(proposed.data.run.blockers?.map(x=>x.message).join(" · ")||"Attendance reconciliation is blocked.")}else setError("Arrival saved. Schedule context requires human reconciliation; nothing was discarded.");setForm({...form,student_id:"",operational_note:"",evidence_reference:""});setSearch("")})};
 const applyProposal=async()=>{const ok=!askConfirmation||await askConfirmation({title:"Apply attendance changes?",message:`Apply ${proposal.run.proposal.changes.length} proposed school/class attendance change(s). The arrival and before/after history will remain auditable.`,confirmLabel:"Confirm attendance changes"});if(!ok)return;run(async()=>{await api.applyLateEntryReconciliation(proposal.entry.id,proposal.run.id,{confirmed_by_human:true,reason:"Front office confirmed physical arrival and attendance proposal"});setProposal(null)})};
 const rejectProposal=async()=>{const reason=await askText({title:"Reject attendance proposal",label:"Reason",description:"Explain why this proposed attendance change should not be applied."});if(!reason)return;run(async()=>{await api.rejectLateEntryReconciliation(proposal.entry.id,proposal.run.id,{reason});setProposal(null)})};
 const createPolicy=e=>{e.preventDefault();run(()=>api.createLateEntryPolicy({...policyForm,school_day_grace_minutes:Number(policyForm.school_day_grace_minutes),class_grace_minutes:Number(policyForm.class_grace_minutes),school_tardies_per_absence:Number(policyForm.school_tardies_per_absence)||null,class_tardies_per_absence:Number(policyForm.class_tardies_per_absence)||null}))};
 const activate=async policy=>{const ok=!askConfirmation||await askConfirmation({title:`Activate policy version ${policy.version}?`,message:"This retires the current policy for future effective dates. Historical attendance retains its original policy version.",confirmLabel:"Activate policy"});if(ok)run(()=>api.activateLateEntryPolicy(policy.id))};
 return <div className="space-y-5"><header className="workspace-hero"><div><span className="eyebrow">Attendance arrival and reconciliation</span><h1>Late Entries</h1><p>Record the arrival fact first. Review every proposed attendance change before confirming it.</p></div><button type="button" disabled={busy} onClick={load}>Refresh</button></header><nav className="flex gap-2">{[["arrivals","Front office"],["setup","Policy setup"],["actions","Threshold actions"],["review","Review and governance"]].map(([id,name])=><button type="button" key={id} onClick={()=>setTab(id)} className={`rounded px-3 py-2 ${tab===id?"bg-purple-600":"bg-gray-800"}`}>{name}</button>)}</nav>{error&&<div className="workspace-error">{error}</div>}{tab==="review"&&<LateEntryReviewPanel askConfirmation={askConfirmation}/>} {tab==="arrivals"&&<><section className="scheduler-summary"><Summary title="Arrivals today" value={summary.total||0}/><Summary title="Unresolved" value={summary.unresolved||0}/><Summary title="Awaiting confirmation" value={summary.pending_confirmation||0}/><Summary title="Threshold actions" value={summary.threshold_actions||0}/></section>
 <form onSubmit={submit} className="rounded-xl border border-gray-800 bg-gray-900/50 p-4"><h2 className="mb-3 text-lg font-semibold">Record an arrival</h2><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-6"><label className="relative xl:col-span-2">Student<input autoFocus autoComplete="off" value={search} placeholder="Scan ID or search name" onChange={e=>{setSearch(e.target.value);setForm({...form,student_id:e.target.value.trim()})}} className="mt-1 w-full rounded bg-gray-950 p-2"/>{students.length>0&&<div className="absolute z-20 mt-1 max-h-52 w-full overflow-y-auto rounded border border-gray-700 bg-gray-950">{students.map(s=><button type="button" key={s.id} onClick={()=>choose(s)} className="block w-full px-3 py-2 text-left hover:bg-gray-800">{s.first_name} {s.last_name} <small>{s.student_id}</small></button>)}</div>}</label><label>Arrival type<select value={form.occurrence_type} onChange={e=>setForm({...form,occurrence_type:e.target.value})} className="mt-1 w-full rounded bg-gray-950 p-2"><option value="school_arrival">Late to school</option><option value="class_arrival">Late to class</option></select></label><label>Reason<select value={form.reason_code} onChange={e=>setForm({...form,reason_code:e.target.value})} className="mt-1 w-full rounded bg-gray-950 p-2">{reasons.map(x=><option key={x.code} value={x.code}>{x.label}</option>)}</select></label><label>Evidence reference<input value={form.evidence_reference} onChange={e=>setForm({...form,evidence_reference:e.target.value})} className="mt-1 w-full rounded bg-gray-950 p-2" placeholder="When required"/></label><button disabled={busy||!form.student_id} className="self-end rounded bg-purple-600 px-4 py-2 disabled:opacity-40">Record arrival</button></div></form>
 {proposal&&<section className="rounded-xl border border-amber-600 bg-amber-950/20 p-4"><h2 className="text-lg font-semibold">Review attendance proposal</h2><p className="text-sm text-gray-300">Student {proposal.entry.student_id} arrived {new Date(proposal.entry.arrival_at).toLocaleTimeString()}. No attendance record has changed yet.</p><ul className="my-3 list-disc pl-5">{proposal.run.proposal.changes.map((x,i)=><li key={i}>{label(x.authority)} · {x.teaching_group_ref||x.date} → {label(x.proposed.attendance_status)}</li>)}</ul><div className="flex gap-2"><button type="button" onClick={applyProposal} className="rounded bg-green-700 px-3 py-2">Confirm changes</button><button type="button" onClick={rejectProposal} className="rounded bg-gray-800 px-3 py-2">Reject proposal</button></div></section>}
 <section><div className="mb-3 flex justify-between"><h2 className="text-lg font-semibold">Arrival records</h2><select value={filter} onChange={e=>{setPage(1);setFilter(e.target.value)}} className="rounded bg-gray-950 p-2"><option value="today">Today</option><option value="unresolved">Unresolved</option><option value="all">All</option></select></div><div className="overflow-x-auto"><table className="w-full min-w-[1000px] text-sm"><thead><tr className="border-b border-gray-700 text-left text-gray-400">{["#","Student","Arrival","Type","Reason","Minutes","Status","Action"].map(x=><th key={x} className="p-2">{x}</th>)}</tr></thead><tbody>{entries.map((x,i)=><tr key={x.id} className={x.status==="exception"?"border-b border-red-700 bg-red-950/30":"border-b border-gray-800"}><td className="p-2">{(page-1)*50+i+1}</td><td>{x.student_id}</td><td>{new Date(x.arrival_at).toLocaleString()}</td><td>{label(x.occurrence_type)}</td><td>{x.reason_label}</td><td>{x.minutes_late??"—"}</td><td>{label(x.status)}</td><td>{x.status==="exception"?<button type="button" disabled={busy} onClick={()=>run(()=>api.retryLateEntryContext(x.id))} className="text-red-300">Retry context</button>:x.status==="context_resolved"?<button type="button" disabled={busy} onClick={()=>run(async()=>{const p=await api.proposeLateEntryReconciliation(x.id);if(p.data.run.status==="proposed")setProposal({entry:x,run:p.data.run})})}>Review changes</button>:"—"}</td></tr>)}</tbody></table></div><Pagination page={page} pageSize={50} total={total} onPageChange={setPage}/></section></>}
 {tab==="setup"&&<div className="grid gap-5 xl:grid-cols-2"><form onSubmit={createPolicy} className="rounded-xl border border-gray-800 p-4"><h2 className="mb-3 text-lg font-semibold">New policy version</h2><div className="grid gap-3 md:grid-cols-2">{[["effective_from","Effective from","date"],["school_day_grace_minutes","School grace minutes","number"],["class_grace_minutes","Class grace minutes","number"],["school_tardies_per_absence","School tardies per absence","number"],["class_tardies_per_absence","Class tardies per absence","number"]].map(([key,name,type])=><label key={key}>{name}<input type={type} min={type==="number"?0:undefined} value={policyForm[key]} onChange={e=>setPolicyForm({...policyForm,[key]:e.target.value})} className="mt-1 w-full rounded bg-gray-950 p-2"/></label>)}<label className="flex items-center gap-2"><input type="checkbox" checked={policyForm.count_excused} onChange={e=>setPolicyForm({...policyForm,count_excused:e.target.checked})}/>Count excused tardies</label><button disabled={busy} className="rounded bg-purple-600 px-3 py-2">Save draft version</button></div></form><section className="rounded-xl border border-gray-800 p-4"><h2 className="mb-3 text-lg font-semibold">Policy versions</h2>{policies.map(x=><div key={x.id} className="mb-2 flex items-center justify-between rounded bg-gray-900 p-3"><span>Version {x.version} · {x.effective_from} · {label(x.status)}</span>{x.status==="draft"&&<button type="button" onClick={()=>activate(x)}>Activate</button>}</div>)}</section></div>}
 {tab==="actions"&&<section><h2 className="mb-3 text-lg font-semibold">Thresholds awaiting a human decision</h2>{thresholdCases.length===0?<p className="text-gray-400">No threshold recommendations are waiting.</p>:thresholdCases.map(x=><article key={x.id} className="mb-3 rounded-xl border border-gray-800 p-4"><strong>{x.student_id} · {x.recommendation.label}</strong><p>{x.observed_count} recorded tardies · {label(x.scope_type)}</p><ul className="list-disc pl-5 text-sm text-gray-300">{x.recommendation.actions.map((a,i)=><li key={i}>{label(a.type)}</li>)}</ul><small>Open the full attendance workflow to approve, modify, dismiss or communicate.</small></article>)}</section>}</div>;
}
function Summary({title,value}){return <article><strong>{value}</strong><span>{title}</span></article>}
