import React, { useEffect, useMemo, useRef, useState } from 'react';
import * as api from '../../api/client';
import useUnsavedChanges from '../components/useUnsavedChanges';
import './nervous-breakdown.css';
import Layer1Workspace from './layer1/Workspace';

const TITLES = { role: 'Roles', source: 'Source documents', statement: 'Source statements', term: 'Ontology', responsibility: 'Responsibilities', connection: 'Connections', role_assignment: 'People in roles' };
const LABELS = { level_id: 'Governed responsibility level', level: 'Level (legacy text)', name: 'Name', normalized_statement: 'Atomic responsibility', original_text: 'Exact source wording', role_id: 'Formal role', source_id: 'Source document version', statement_id: 'Source statement', statement_revision: 'Exact statement revision', domain_ids: 'Domains (first is primary)', responsibility_type_ids: 'Responsibility types', authority_type_ids: 'Authority types', relationship_type_id: 'Relationship type', from_id: 'From responsibility', to_id: 'To responsibility', document_id: 'Document number', document_version_id: 'Document version number', document_sha256: 'Source SHA-256', source_type: 'Source type', version_label: 'Version / academic year', review_status: 'Review state', mapping_state: 'Mapping state', effective_from: 'Effective from', effective_to: 'Effective to', superseded_by: 'Successor record', is_fixture: 'Synthetic test data', parent_id: 'Parent ontology term', operational_ownership_id: 'Linked operational ownership number', staff_id: 'Canonical staff ID', aliases: 'Aliases (comma separated)' };
const ENUMS = { directionality: ['directed', 'symmetric'], grouping: ['source_statement'], direction: ['from_to'], status: ['draft', 'active', 'inactive', 'superseded'], review_status: ['draft', 'proposed', 'reviewed'], mapping_state: ['mapped', 'referenced', 'placeholder'], source_type: ['job_description'], category: ['domain', 'responsibility_type', 'authority_type', 'relationship_type', 'responsibility_level'], evidence: ['documentary', 'inferred', 'proposed', 'approved_operational', 'unresolved'] };
const REFS = { level_id: 'term', role_id: 'role', source_id: 'source', statement_id: 'statement', from_id: 'responsibility', to_id: 'responsibility', parent_id: 'term', relationship_type_id: 'term', domain_ids: 'term', responsibility_type_ids: 'term', authority_type_ids: 'term' };
const CATEGORY = { level_id: 'responsibility_level', domain_ids: 'domain', responsibility_type_ids: 'responsibility_type', authority_type_ids: 'authority_type', relationship_type_id: 'relationship_type' };
const label = key => LABELS[key] || key.replaceAll('_', ' ').replace(/^./, c => c.toUpperCase());
const name = r => r?.data.name || r?.data.original_text?.slice(0, 90) || (r?.kind === 'connection' ? `${r.data.from_id} / ${r.data.to_id}` : r?.id) || 'Unknown';
function connectionNotes(notes) {
  try { const value = JSON.parse(notes); if (value && typeof value === 'object') return { rationale: typeof value.Rationale === 'string' ? value.Rationale : notes, direction: typeof value['Direction Review'] === 'string' ? value['Direction Review'] : null }; } catch { /* Ordinary notes remain verbatim. */ }
  return { rationale: notes, direction: null };
}
function checked(response) { if (!response.data.success) throw new Error(response.data.error?.message || 'Request failed'); return response.data; }
function download(data, filename, type = 'application/json') {
  const url = URL.createObjectURL(new Blob([data], { type })); const a = document.createElement('a'); a.href = url; a.download = filename; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000);
}

export default function NervousBreakdownWidget({ askConfirmation }) {
  const [refreshToken, setRefreshToken] = useState(0);
  const [roleFocus,setRoleFocus] = useState(null);
  const [canDraftReview, setCanDraftReview] = useState(false);
  const [records, setRecords] = useState([]), [schema, setSchema] = useState(null), [tab, setTab] = useState('explore');
  const [kind, setKind] = useState('role'), [draft, setDraft] = useState(null), [reason, setReason] = useState(''), [reviewed, setReviewed] = useState(false);
  const [error, setError] = useState(''), [notice, setNotice] = useState(''), [busy, setBusy] = useState(false), [loaded, setLoaded] = useState(false);
  const [filters, setFilters] = useState({ mode: 'normal', q: '', role_id: '', source_id: '', term_id: '', evidence: '', relationship_type_id: '', status: 'active', fixtures: 'false', direction: 'both', depth: 2 });
  const [selected, setSelected] = useState(''), [inspected, setInspected] = useState(''), [network, setNetwork] = useState({ nodes: [], edges: [], trail: { nodes: [], edges: [] } });
  const [history, setHistory] = useState([]), [query, setQuery] = useState(''), [page, setPage] = useState(1), [importText, setImportText] = useState('');
  const [upload, setUpload] = useState(null), [uploadTitle, setUploadTitle] = useState(''), [uploadResult, setUploadResult] = useState(null), [extraction, setExtraction] = useState(null);
  const [validationReport, setValidationReport] = useState(null);
  const [exchangeContract, setExchangeContract] = useState(null);
  const [graphBusy, setGraphBusy] = useState(false);
  const [selectionQuery, setSelectionQuery] = useState('');
  useUnsavedChanges(Boolean(draft || importText));
  const byId = useMemo(() => new Map(records.map(r => [r.id, r])), [records]);
  const current = byId.get(inspected || selected);
  const load = async () => { const result = checked(await api.getNervousBreakdownWorkspace({ compact: String(tab === 'explore') })); setRecords(result.records.filter(record => !record.data.is_fixture)); setCanDraftReview(result.can_draft_review === true); setSchema(result.schema); setExchangeContract({ schema: result.import_schema, ontology: result.ontology }); setLoaded(true); setRefreshToken(n => n + 1); };
  const run = async (fn, message) => { setBusy(true); setError(''); setNotice(''); try { await fn(); if (message) setNotice(message); } catch (e) { if (e.response?.data?.report) setValidationReport(e.response.data.report); setError(e.response?.data?.error?.message || e.message); } finally { setBusy(false); } };
  useEffect(() => { run(load); }, []);
  useEffect(() => { if (tab !== 'explore') run(load); }, [tab]);
  useEffect(() => { let cancelled = false; setHistory([]); if (current) api.getNervousBreakdownHistory(current.id).then(r => { if (!cancelled) setHistory(checked(r).history); }).catch(e => { if (!cancelled) setError(e.response?.data?.error?.message || e.message); }); return () => { cancelled = true; }; }, [current]);
  const select = id => { setSelected(id); setInspected(id); };
  const discard = async () => { if (!draft || await askConfirmation({ title: 'Discard this draft?', message: 'Your unsaved record changes will be discarded.', confirmLabel: 'Discard draft' })) { setDraft(null); return true; } return false; };
  const edit = async record => { if (!(await discard())) return; setTab('govern'); setKind(record.kind); setDraft(JSON.parse(JSON.stringify(record))); setReason(''); setReviewed(false); };
  const create = async () => { if (!(await discard())) return; const data = { status: 'draft', notes: '', is_fixture: false }; if (kind === 'role') data.mapping_state = 'placeholder'; if (kind === 'source') { data.source_type = 'job_description'; if (uploadResult) { data.document_id = uploadResult.id; data.document_version_id = uploadResult.versions[0].id; data.name = uploadResult.title; } } if (['statement', 'responsibility', 'connection'].includes(kind)) data.review_status = 'draft'; if (kind === 'responsibility') Object.assign(data, { domain_ids: [], responsibility_type_ids: [], authority_type_ids: [] }); if (kind === 'connection') data.evidence = 'proposed'; setDraft({ kind, data, revision: 0 }); setReason(''); setReviewed(false); };
  const change = (key, value) => setDraft(d => ({ ...d, data: { ...d.data, [key]: value } }));
  const save = e => { e.preventDefault(); run(async () => { await api.saveNervousBreakdownRecord({ record: { id: draft.id, kind: draft.kind, expected_revision: draft.revision, data: draft.data }, reason, confirm_review: reviewed }).then(checked); setDraft(null); await load(); }, 'Record saved with a new historical revision.'); };
  const options = (recordKind, field) => records.filter(r => r.kind === recordKind && (!CATEGORY[field] || r.data.category === CATEGORY[field])).map(r => <option value={r.id} key={r.id}>{name(r)}{r.kind === 'term' ? ` · ${r.data.parent_id ? name(byId.get(r.data.parent_id)) + ' / ' : ''}${r.id}` : ''} · {r.data.status}{r.data.is_fixture ? ' · TEST' : ''}</option>);
  const field = key => {
    const value = draft.data[key];
    const refKind = key === 'superseded_by' ? draft.kind : REFS[key];
    if (key === 'is_fixture') return null;
    if (refKind || ENUMS[key]) return <label key={key}>{label(key)}<select multiple={key.endsWith('_ids')} value={value || (key.endsWith('_ids') ? [] : '')} onChange={e => { const v = key.endsWith('_ids') ? [...e.target.selectedOptions].map(o => o.value).filter(Boolean) : (e.target.value || null); change(key, v); if (key === 'statement_id' && !v) change('statement_revision', null); if (key === 'statement_id' && v) change('statement_revision', byId.get(v).revision); }}><option value="">Select…</option>{refKind ? options(refKind, key) : ENUMS[key].map(v => <option key={v} value={v}>{v.replaceAll('_', ' ')}</option>)}</select></label>;
    const numeric = ['document_id', 'document_version_id', 'statement_revision', 'operational_ownership_id'].includes(key);
    return <label key={key}>{label(key)}{['notes', 'normalized_statement', 'original_text', 'definition'].includes(key) ? <textarea rows={key === 'original_text' ? 7 : 3} value={value || ''} onChange={e => change(key, e.target.value)} /> : <input type={key.startsWith('effective_') ? 'date' : numeric ? 'number' : 'text'} min={numeric ? 1 : undefined} readOnly={key === 'document_sha256'} value={Array.isArray(value) ? value.join(', ') : value ?? ''} onChange={e => change(key, key === 'aliases' ? e.target.value.split(',').map(x => x.trim()).filter(Boolean) : numeric ? (e.target.value ? Number(e.target.value) : null) : key.startsWith('effective_') ? (e.target.value || null) : e.target.value)} />}</label>;
  };
  const rows = records.filter(r => r.kind === kind && r.data.is_fixture === (filters.fixtures === 'true') && JSON.stringify(r.data).toLowerCase().includes(query.toLowerCase())).sort((a, b) => name(a).localeCompare(name(b)));
  const getSource = record => { if (!record) return null; if (record.kind === 'source') return record; if (record.kind === 'statement') return byId.get(record.data.source_id); const s = byId.get(record.data.statement_id); return byId.get(s?.data.source_id); };
  const original = async record => { const s = getSource(record); if (!s) throw new Error('No source document is linked'); const file = checked(await api.getDocumentContent(s.data.document_id, s.data.document_version_id)); download(Uint8Array.from(atob(file.contentBase64), c => c.charCodeAt(0)), file.filename, file.mimeType); };
  const inputFile = async file => { if (!file || file.size > 10 * 1024 * 1024) throw new Error('Select a file up to 10 MiB'); return new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result).split(',')[1]); reader.onerror = reject; reader.readAsDataURL(file); }); };
  return <div className={`nb-workspace ${tab==='explore'?'nb-exploring':''}`}>
    <header className="nb-header"><div><p>ORGANISATION / LAYER 1</p><h1>Nervous Breakdown</h1><p>Formal responsibilities, source evidence and the connections between them.</p></div><button disabled={busy} onClick={() => run(load, 'Workspace refreshed; your draft is preserved.')}>Refresh</button></header>
    <div className="nb-toolbar" role="tablist">{[['explore', 'Explore'], ['govern', 'Govern'], ['exchange', 'Sources & exchange']].map(([id, title]) => <button key={id} role="tab" aria-selected={tab === id} onClick={() => setTab(id)}>{title}</button>)}</div>
    {busy && <p role="status">Working…</p>}{error && <p role="alert" className="nb-error">{error} Your input is preserved. Correct the issue or refresh before retrying.</p>}{notice && <p role="status" className="nb-notice">{notice}</p>}
    {!loaded && !error && <p>Loading responsibility workspace…</p>}
    {loaded && <div hidden={tab !== 'explore'}><Layer1Workspace roleFocus={roleFocus} canDraftReview={canDraftReview} fixtures={filters.fixtures} refresh={refreshToken} onGovern={edit} onOriginal={record => run(() => original(record), 'Original source version downloaded.')} /></div>}
    {tab === 'govern' && <div className="nb-govern"><section><div className="nb-toolbar"><label>Records<select value={kind} onChange={e => { setKind(e.target.value); setPage(1); }}>{Object.entries(TITLES).map(([k, v]) => <option value={k} key={k}>{v}</option>)}</select></label><button disabled={busy || !schema} onClick={create}>Create record</button></div><label>Search records<input value={query} onChange={e => { setQuery(e.target.value); setPage(1); }} /></label><p>{rows.length} records · sorted by name</p>
      <table><thead><tr><th>#</th><th>Record</th><th>Status</th><th>Revision</th></tr></thead><tbody>{rows.slice((page - 1) * 50, page * 50).map((r, i) => <tr key={r.id}><td>{(page - 1) * 50 + i + 1}</td><td><button onClick={() => setInspected(r.id)}>{name(r)}</button></td><td>{r.data.status}</td><td>{r.revision}</td></tr>)}</tbody></table>{!rows.length && <p>No records yet. Start with a role, upload its JD, then create a source and source statements.</p>}<div className="nb-toolbar"><button disabled={page <= 1} onClick={() => setPage(p => p - 1)}>Previous</button><span>Page {page}</span><button disabled={page * 50 >= rows.length} onClick={() => setPage(p => p + 1)}>Next</button></div>
      {draft && <form className="nb-form" onSubmit={save}><h2>{draft.id ? 'Edit' : 'Create'} {TITLES[draft.kind]}</h2><p>Changes create a new revision. Exact source wording and history remain recoverable.</p><div className="nb-fields">{[...(schema?.fields[draft.kind] || []), 'status', 'effective_from', 'effective_to', 'superseded_by', 'notes'].map(field)}</div><label>Reason for change (required)<textarea required value={reason} onChange={e => setReason(e.target.value)} /></label><label><input type="checkbox" checked={reviewed} onChange={e => setReviewed(e.target.checked)} /> I have reviewed the wording, provenance and classifications of records marked reviewed.</label><div className="nb-toolbar"><button disabled={busy} type="submit">Save revision</button><button type="button" disabled={busy} onClick={discard}>Discard draft</button></div></form>}
    </section>{inspector()}</div>}
    {tab === 'exchange' && <div className="nb-exchange"><section><h2>Source documents</h2><p>Upload the original JD to TimSyS Documents. Link an exact file version to a formal role in Govern → Source documents. Text extraction is a parsing aid only.</p><label>Document title<input value={uploadTitle} onChange={e => setUploadTitle(e.target.value)} /></label><label>Original PDF or Word file<input type="file" accept=".pdf,.docx" onChange={e => { setUpload(e.target.files[0]); setUploadResult(null); }} /></label><button disabled={busy || !upload || !uploadTitle.trim()} onClick={() => run(async () => { const content = await inputFile(upload); const doc = checked(await api.createDocument({ title: uploadTitle, category: 'job_description' })).document; setUploadResult(doc); const uploaded = checked(await api.addDocumentVersion(doc.id, { filename: upload.name, mime_type: upload.type || (upload.name.endsWith('.pdf') ? 'application/pdf' : 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'), content_base64: content })).document; setUploadResult(uploaded); }, 'Original document stored. Create its source record in Govern.')}>Store original JD</button>
      {uploadResult && <div><p>Document {uploadResult.id} · version {uploadResult.versions?.[0]?.id || 'not uploaded'} · {uploadResult.title}</p><button disabled={busy || !uploadResult.versions?.length} onClick={() => run(async () => { setExtraction(checked(await api.extractDocumentContent(uploadResult.id, { version_id: uploadResult.versions[0].id, ocr: false }))); }, 'Text extracted for review; no responsibilities were created.')}>Extract text for review</button></div>}
      {extraction && <div><h3>Unreviewed extracted text</h3><p>Compare against the original document before creating reviewed source statements.</p><textarea rows="16" readOnly value={extraction.text || extraction.run?.segments?.map(s => s.content).join('\n\n') || ''} /></div>}
    </section><section><h2>Structured import and export</h2><p>Import format: timsys.nervous-breakdown.v1. Use stable IDs and expected_revision (0 for new records). References must resolve; the entire batch is rejected if any record is invalid. Export includes historical revisions; document files remain in the shared Documents store.</p><button disabled={busy} onClick={() => run(async () => { const result = checked(await api.exportNervousBreakdown()); download(JSON.stringify(result, null, 2), 'nervous-breakdown-export.json'); }, 'Organisational records and history exported.')}>Export records and history</button>
      <div className="nb-toolbar"><button disabled={!exchangeContract} onClick={() => download(JSON.stringify(exchangeContract.schema, null, 2), 'nervous-breakdown-import.schema.json')}>Download import schema</button><button disabled={!exchangeContract} onClick={() => download(JSON.stringify(exchangeContract.ontology, null, 2), 'nervous-breakdown-ontology.json')}>Export current ontology</button></div><label>Load JSON<input type="file" accept=".json" onChange={e => { const file = e.target.files[0]; if (file) run(async () => { setImportText(await file.text()); setValidationReport(null); }); }} /></label><label>Review import JSON<textarea rows="16" value={importText} onChange={e => { setImportText(e.target.value); setValidationReport(null); }} /></label><label>Import reason<input value={reason} onChange={e => setReason(e.target.value)} /></label><label><input type="checkbox" checked={reviewed} onChange={e => setReviewed(e.target.checked)} /> I have reviewed records that this import marks reviewed.</label><button disabled={busy || !importText} onClick={() => run(async () => { setValidationReport(null); const result = checked(await api.importNervousBreakdown({ ...JSON.parse(importText), reason: reason || 'Import preflight', dry_run: true })); setValidationReport(result.report); }, 'Validation finished; no records saved.')}>Validate without saving</button><button disabled={busy || !importText || !reason.trim()} onClick={() => run(async () => { const payload = JSON.parse(importText); if (!await askConfirmation({ title: 'Import organisational records?', message: `This will save ${payload.records?.length || 0} records with the supplied statuses and provenance. Existing records require matching revisions.`, confirmLabel: 'Import records' })) return; const result = checked(await api.importNervousBreakdown({ ...payload, reason, confirm_review: reviewed, dry_run: false })); setValidationReport(result.report); setImportText(''); await load(); setNotice(`${result.report.counts.changes} records changed; ${result.report.counts.unchanged} unchanged; ${result.report.warnings.length} review warnings.`); })}>Validate and import</button>
    {validationReport && <section aria-label="Import validation report"><h3>{validationReport.valid ? 'Valid for import' : 'Invalid data — nothing saved'}</h3><p>{validationReport.errors.length} blocking errors · {validationReport.warnings.length} review warnings. Warnings do not imply invalid organisational data. Report includes the projected network. Showing up to 100 issues; download for the complete report.</p><button onClick={() => download(JSON.stringify(validationReport, null, 2), 'nervous-breakdown-validation.json')}>Download full report</button><div style={{maxHeight: 360, overflow: 'auto'}}>{[...validationReport.errors, ...validationReport.warnings].slice(0, 100).map((item, i) => <p key={i}><strong>{item.severity}: {item.code}</strong> · {item.record_id || 'batch'} {item.field && '· ' + item.field}<br />{item.message}</p>)}</div></section>}</section></div>}
  </div>;

  function inspector() {
    if (!current) return <aside className="nb-inspector"><h2>Inspect a responsibility</h2><p>Select a node or record to see its role, source evidence, connections and historical revisions.</p><p>Formal responsibility describes the source documents. It does not prohibit additional operational assignments.</p></aside>;
    const d = current.data, source = getSource(current), statement = byId.get(d.statement_id);
    return <aside className="nb-inspector"><p>{TITLES[current.kind]} · {d.status}{d.is_fixture ? ' · TEST' : ''}</p><h2>{name(current)}</h2><p className="nb-id">{current.id} · revision {current.revision}</p>{!(tab === 'explore' && filters.mode === 'draft_review') && <button disabled={busy} onClick={() => edit(current)}>Edit governed record</button>}
      {current.kind === 'connection' && <section aria-label="Connection review details">
        <p className="nb-review-badge">Evidence: {d.evidence} · Review: {d.review_status} · Lifecycle: {d.status}</p>
        {(d.evidence === 'inferred' || d.evidence === 'proposed' || d.review_status !== 'reviewed' || d.status !== 'active') && <p><strong>Analytical / non-approved structure. Display is not approval.</strong></p>}
        <p>Connection ID: {current.id}</p><p>Relationship: {name(byId.get(d.relationship_type_id))} · {d.relationship_type_id || 'Unclassified'}</p>
        {['from_id', 'to_id'].map(key => { const endpoint = byId.get(d[key]), statement = byId.get(endpoint?.data.statement_id), source = byId.get(statement?.data.source_id); return <section key={key}><h3>{key === 'from_id' ? 'Source responsibility' : 'Target responsibility'}</h3><button onClick={() => select(d[key])}>{d[key]} · {name(endpoint)}</button><p>Role: {name(byId.get(endpoint?.data.role_id))} · {endpoint?.data.role_id}</p><p>Endpoint provenance: {statement?.id || 'Unknown'} · pinned revision {endpoint?.data.statement_revision ?? 'Unknown'} · {source?.data.name || 'Unknown source'}</p><p>Document {source?.data.document_id ?? 'Unknown'} · immutable version {source?.data.document_version_id ?? 'Unknown'}</p>{statement && <button onClick={() => setInspected(statement.id)}>Inspect source statement and exact revision history</button>}</section>; })}
        <p>Directionality: {byId.get(d.relationship_type_id)?.data.directionality || 'directed'}</p>
        {byId.get(d.relationship_type_id)?.data.directionality === 'symmetric' && <p><strong>Symmetric relationship — endpoint order is storage only. Excluded from process-order inference.</strong></p>}
        {byId.get(d.relationship_type_id)?.data.grouping === 'source_statement' && <section><h3>Co-specified source-statement group</h3><p>{d.statement_id} · revision {d.statement_revision}. Chain distance is not organisational distance or process order.</p>{records.filter(r => r.kind === 'responsibility' && r.data.statement_id === d.statement_id && r.data.statement_revision === d.statement_revision).map(r => <p key={r.id}><button onClick={() => select(r.id)}>{r.id} · {name(r)}</button></p>)}</section>}
        <h3>Connection rationale</h3><p style={{ whiteSpace: 'pre-wrap' }}>{connectionNotes(d.notes).rationale || 'No rationale supplied.'}</p>{connectionNotes(d.notes).direction && <p>Direction review: {connectionNotes(d.notes).direction}. Supplied endpoint order is not approval of process order.</p>}
        {!d.statement_id && <p>No direct documentary statement is attached to this connection. Endpoint provenance does not make this relationship documentary.</p>}
      </section>}
      <dl>{Object.entries(d).filter(([k]) => !['name', 'original_text', 'normalized_statement', 'is_fixture'].includes(k)).map(([key, value]) => <React.Fragment key={key}><dt>{label(key)}</dt><dd>{Array.isArray(value) ? value.map(v => byId.has(v) ? name(byId.get(v)) : v).join(', ') || '—' : byId.has(value) ? <button onClick={() => setInspected(value)}>{name(byId.get(value))}</button> : String(value ?? '—')}</dd></React.Fragment>)}</dl>
      {d.normalized_statement && <p>{d.normalized_statement}</p>}{d.original_text && <blockquote>{d.original_text}</blockquote>}
      {statement && <section><h3>Source provenance</h3><button onClick={() => setInspected(statement.id)}>{name(statement)}</button><p>Pinned statement revision {d.statement_revision}. Use its history to inspect that exact wording.</p><button disabled={busy} onClick={() => run(async () => { const h = checked(await api.getNervousBreakdownHistory(statement.id)).history.find(v => v.revision === d.statement_revision); if (!h) throw new Error('Pinned source revision is unavailable'); setNotice(`Exact source wording (${h.snapshot.data.location}): ${h.snapshot.data.original_text}`); })}>Show exact pinned wording</button></section>}
      {source && <button disabled={busy} onClick={() => run(() => original(current), 'Original source version downloaded.')}>Open original source version</button>}
      {current.kind === 'role' && <section><h3>Formal role coverage</h3><p>{records.filter(r => r.kind === 'responsibility' && r.data.role_id === current.id).length} formal responsibilities · {d.mapping_state}</p><button onClick={() => { setFilters(f => ({ ...f, role_id: current.id, fixtures: String(d.is_fixture) })); select(''); setRoleFocus({id:current.id,request:Date.now()}); setTab('explore'); }}>Explore this role’s network</button></section>}
      {current.kind === 'statement' && !(tab === 'explore' && filters.mode === 'draft_review') && <button disabled={busy} onClick={async () => { if (!(await discard())) return; setTab('govern'); setKind('responsibility'); setReason(''); setReviewed(false); setDraft({ kind: 'responsibility', revision: 0, data: { status: 'draft', is_fixture: d.is_fixture, notes: '', review_status: 'draft', statement_id: current.id, statement_revision: current.revision, role_id: source?.data.role_id, domain_ids: [], responsibility_type_ids: [], authority_type_ids: [] } }); }}>Add an atomic responsibility from this statement</button>}
      <h3>Related records</h3>{records.filter(r => r.id !== current.id && Object.values(r.data).some(v => v === current.id || Array.isArray(v) && v.includes(current.id))).map(r => <p key={r.id}><button onClick={() => r.kind === 'responsibility' ? select(r.id) : setInspected(r.id)}>{name(r)}</button>{r.kind === 'connection' && <> · {r.data.evidence} <button onClick={() => select(r.data.from_id === current.id ? r.data.to_id : r.data.from_id)}>Follow connection</button></>}</p>)}
      <h3>Revision history</h3>{history.map(h => <details key={h.revision}><summary>Revision {h.revision} · {h.created_at}</summary><p>{h.reason} · actor {h.actor_id}</p><dl>{Object.entries(h.snapshot.data).map(([k,v]) => <React.Fragment key={k}><dt>{label(k)}</dt><dd style={{whiteSpace:'pre-wrap'}}>{Array.isArray(v) ? v.join(', ') : String(v ?? '—')}</dd></React.Fragment>)}</dl></details>)}
    </aside>;
  }
}
