import React,{useEffect,useState}from"react";
import * as api from"../../api/client";
import Pagination from "../components/Pagination";

const blank={subject_component:"",subject_type:"",subject_id:"",role:"owner",party_type:"staff",party_id:"",status:"active",escalation_party_type:"staff",escalation_party_id:"",notes:""};
export default function OwnershipWidget({askConfirmation}){
 const [rows,setRows]=useState([]),[form,setForm]=useState(blank),[page,setPage]=useState(1),[total,setTotal]=useState(0),[search,setSearch]=useState(""),[message,setMessage]=useState(""),[error,setError]=useState("");
 const [action,setAction]=useState(null),[actionForm,setActionForm]=useState({party_type:"staff",party_id:"",reason:"",ends_at:""});
 const load=async()=>{try{const r=await api.listResponsibilities({page,limit:50,q:search});setRows(r.data.responsibilities||[]);setTotal(r.data.total||0);setError("");}catch(e){setError(e.response?.data?.error?.message||e.message);}};
 useEffect(()=>{void load();},[page,search]);
 useEffect(()=>{window.dispatchEvent(new CustomEvent("principaled:dirty-state",{detail:Boolean(form.subject_id||action)}));return()=>window.dispatchEvent(new CustomEvent("principaled:dirty-state",{detail:false}));},[form.subject_id,action]);
 const save=async e=>{e.preventDefault();try{await api.assignResponsibility(form);setForm(blank);setMessage("Responsibility assigned");await load();}catch(err){setError(err.response?.data?.error?.message||err.message);}};
 const lifecycle=async(row,status)=>{if(await askConfirmation({title:`${status==="withdrawn"?"Withdraw":"Reinstate"} responsibility?`,message:`This changes responsibility for ${row.subject_type} ${row.subject_id}.`,confirmLabel:status==="withdrawn"?"Withdraw":"Reinstate",destructive:status==="withdrawn"})){await api.setResponsibilityStatus(row.id,status,"Changed by user");await load();}};
 const submitAction=async e=>{e.preventDefault();try{const {row,type}=action;if(type==="contributor")await api.addResponsibilityContributor(row.id,{...actionForm,contribution_role:"contributor"});if(type==="delegate")await api.delegateResponsibility(row.id,actionForm);if(type==="handover")await api.handoverResponsibility(row.id,actionForm);if(type==="escalate")await api.escalateResponsibility(row.id,actionForm);setAction(null);setActionForm({party_type:"staff",party_id:"",reason:"",ends_at:""});setMessage(`${type} recorded`);await load();}catch(err){setError(err.response?.data?.error?.message||err.message);}};
 return <div className="space-y-5"><header><span className="text-xs uppercase tracking-widest text-purple-400">Reusable workflow component</span><h1 className="text-3xl font-semibold">Ownership and responsibility</h1><p className="text-gray-400">Assign accountability to any platform record without copying that record or its profile.</p></header>{error&&<p className="rounded border border-red-700 bg-red-950/40 p-3 text-red-200">{error}</p>}{message&&<p className="text-emerald-400">{message}</p>}
 <form onSubmit={save} className="rounded border border-gray-800 bg-gray-900/60 p-4"><h2 className="mb-3 font-semibold">Assign responsibility</h2><div className="grid gap-3 md:grid-cols-3"><input required className="rounded bg-gray-950 p-2" placeholder="Subject component, e.g. calendar" value={form.subject_component} onChange={e=>setForm({...form,subject_component:e.target.value})}/><input required className="rounded bg-gray-950 p-2" placeholder="Subject type, e.g. calendar_entry" value={form.subject_type} onChange={e=>setForm({...form,subject_type:e.target.value})}/><input required className="rounded bg-gray-950 p-2" placeholder="Subject identifier" value={form.subject_id} onChange={e=>setForm({...form,subject_id:e.target.value})}/><input required className="rounded bg-gray-950 p-2" placeholder="Responsibility role" value={form.role} onChange={e=>setForm({...form,role:e.target.value})}/><select className="rounded bg-gray-950 p-2" value={form.party_type} onChange={e=>setForm({...form,party_type:e.target.value})}><option value="staff">Staff</option><option value="user">User</option><option value="team">Team</option><option value="external">External party</option></select><input required className="rounded bg-gray-950 p-2" placeholder="Responsible party identifier" value={form.party_id} onChange={e=>setForm({...form,party_id:e.target.value})}/><select className="rounded bg-gray-950 p-2" value={form.escalation_party_type} onChange={e=>setForm({...form,escalation_party_type:e.target.value})}><option value="staff">Escalate to staff</option><option value="user">Escalate to user</option><option value="team">Escalate to team</option><option value="external">Escalate externally</option></select><input className="rounded bg-gray-950 p-2" placeholder="Escalation party identifier" value={form.escalation_party_id} onChange={e=>setForm({...form,escalation_party_id:e.target.value})}/><input className="rounded bg-gray-950 p-2" placeholder="Notes" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></div><div className="mt-3 flex gap-2"><button className="rounded bg-purple-600 px-4 py-2">Assign</button>{form.subject_id&&<button type="button" className="rounded bg-gray-700 px-4 py-2" onClick={()=>setForm(blank)}>Cancel</button>}</div></form>
 {action&&<form onSubmit={submitAction} className="rounded border border-purple-700 bg-purple-950/20 p-4"><h2 className="font-semibold capitalize">{action.type}: {action.row.subject_type} {action.row.subject_id}</h2><div className="mt-3 grid gap-3 md:grid-cols-4"><select className="rounded bg-gray-950 p-2" value={actionForm.party_type} onChange={e=>setActionForm({...actionForm,party_type:e.target.value})}><option value="staff">Staff</option><option value="user">User</option><option value="team">Team</option><option value="external">External</option></select><input required={action.type!=="escalate"} className="rounded bg-gray-950 p-2" placeholder={action.type==="escalate"?"Party identifier (uses configured path if blank)":"Party identifier"} value={actionForm.party_id} onChange={e=>setActionForm({...actionForm,party_id:e.target.value})}/>{action.type==="delegate"&&<input required type="datetime-local" className="rounded bg-gray-950 p-2" value={actionForm.ends_at} onChange={e=>setActionForm({...actionForm,ends_at:e.target.value})}/>}<input className="rounded bg-gray-950 p-2" placeholder="Reason" value={actionForm.reason} onChange={e=>setActionForm({...actionForm,reason:e.target.value})}/></div><div className="mt-3 flex gap-2"><button className="rounded bg-purple-600 px-4 py-2">Record {action.type}</button><button type="button" className="rounded bg-gray-700 px-4 py-2" onClick={()=>setAction(null)}>Cancel</button></div></form>}
 <section><label className="block text-sm text-gray-300">Search<input className="mt-1 w-full max-w-md rounded bg-gray-900 p-2" placeholder="Subject, role or party" value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}}/></label><div className="mt-3 overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead><tr className="border-b border-gray-700 text-left text-gray-400"><th className="p-2">#</th><th>Subject</th><th>Role</th><th>Responsible party</th><th>Status</th><th>Contributors</th><th>Actions</th></tr></thead><tbody>{rows.map((row,i)=><tr key={row.id} className="border-b border-gray-800"><td className="p-2">{(page-1)*50+i+1}</td><td>{row.subject_component} / {row.subject_type} / {row.subject_id}</td><td>{row.role}</td><td>{row.party_type}: {row.party_id}</td><td>{row.status}</td><td>{row.contributors.length}</td><td><div className="flex flex-wrap gap-2 text-xs"><button className="text-blue-300" onClick={()=>setAction({row,type:"contributor"})}>Contributor</button><button className="text-amber-300" onClick={()=>setAction({row,type:"delegate"})}>Delegate</button><button className="text-purple-300" onClick={()=>setAction({row,type:"handover"})}>Handover</button><button className="text-orange-300" onClick={()=>setAction({row,type:"escalate"})}>Escalate</button><button className={row.status==="withdrawn"?"text-emerald-300":"text-red-300"} onClick={()=>lifecycle(row,row.status==="withdrawn"?"active":"withdrawn")}>{row.status==="withdrawn"?"Reinstate":"Withdraw"}</button></div></td></tr>)}</tbody></table>{!rows.length&&<p className="p-8 text-center text-gray-500">No responsibilities found.</p>}</div><Pagination page={page} pageSize={50} total={total} onPageChange={setPage}/></section></div>;
}
