import React,{useEffect,useState}from"react";
import * as api from"../../api/client";
import Pagination from"../components/Pagination";
import ProgrammeSetupWizard from"../components/ProgrammeSetupWizard";

const msg=e=>e?.response?.data?.error?.message||e.message;
const label=x=>String(x||"").replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());
const Field=({label:caption,...props})=><label className="field"><span>{caption}</span><input {...props}/></label>;
const blank={programme_type:"activities",operating_mode:"mixed",respondent_mode:"student"};

export default function ProgrammeManagerWidget({askConfirmation}){
 const[programmes,setProgrammes]=useState([]),[page,setPage]=useState(1),[total,setTotal]=useState(0),[selected,setSelected]=useState(null),[offerings,setOfferings]=useState([]),[surveys,setSurveys]=useState([]),[survey,setSurvey]=useState(null),[run,setRun]=useState(null),[interventions,setInterventions]=useState([]),[enrolments,setEnrolments]=useState([]),[insights,setInsights]=useState(null),[years,setYears]=useState([]),[tab,setTab]=useState("programmes"),[form,setForm]=useState(blank),[decision,setDecision]=useState(null),[reason,setReason]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 const loadRun=async s=>{const r=await api.listProgrammeAllocationRuns(s.id,{page:1,limit:1}),current=r.data.runs?.[0]||null;setRun(current);setInterventions(current?(await api.getProgrammeInterventions(current.id,{page:1,limit:50})).data.interventions||[]:[])};
 const loadDetail=async p=>{if(!p){setOfferings([]);setSurveys([]);setEnrolments([]);return}const[o,s,e]=await Promise.all([api.listProgrammeOfferings(p.id,{limit:50}),api.listProgrammeSurveys(p.id,{limit:50}),api.listProgrammeEnrolments({programme_id:p.id,limit:50})]);setOfferings(o.data.offerings||[]);setSurveys(s.data.surveys||[]);setEnrolments(e.data.enrolments||[]);const current=s.data.surveys?.[0]||null;setSurvey(current);if(current)await loadRun(current)};
 const load=async()=>{try{const[p,i,y]=await Promise.all([api.listManagedProgrammes({page,limit:50}),api.getProgrammeManagerInsights(),api.listAcademicYears({limit:50})]);setProgrammes(p.data.programmes||[]);setTotal(p.data.total||0);setInsights(i.data.insights);setYears(y.data.years||[]);const current=(p.data.programmes||[]).find(x=>x.id===selected?.id)||(p.data.programmes||[])[0]||null;setSelected(current);await loadDetail(current);setError("")}catch(e){setError(msg(e))}};
 useEffect(()=>{load()},[page]);
 const act=async fn=>{setBusy(true);try{await fn();await load()}catch(e){setError(msg(e))}finally{setBusy(false)}};
 const create=e=>{e.preventDefault();act(async()=>{await api.createManagedProgramme({external_key:`programme:${form.name.toLowerCase().replace(/[^a-z0-9]+/g,"-")}:${Date.now()}`,academic_year_id:+form.academic_year_id,name:form.name,description:form.description,programme_type:form.programme_type,operating_mode:form.operating_mode,respondent_mode:form.respondent_mode,configuration:{}});setForm(blank)})};
 const select=p=>{setSelected(p);loadDetail(p).catch(e=>setError(msg(e)))};
 const selectSurvey=s=>{setSurvey(s);loadRun(s).catch(e=>setError(msg(e)))};
 const requestDecision=(kind,target,action,destructive=false)=>{setDecision({kind,target,action,destructive});setReason("")};
 const applyDecision=async e=>{e.preventDefault();const accepted=!askConfirmation||await askConfirmation({title:`Confirm ${label(decision.kind)}?`,message:"This decision is recorded permanently and will not be made automatically.",confirmLabel:"Confirm",destructive:decision.destructive});if(!accepted)return;await act(()=>decision.action(reason));setDecision(null);setReason("")};
 const generate=async()=>{if(!survey)return;const accepted=!askConfirmation||await askConfirmation({title:"Generate allocation recommendations?",message:"Timestamp, ranked choices and hard constraints will be evaluated. No enrolments are created.",confirmLabel:"Generate"});if(accepted)act(()=>api.generateProgrammeAllocations(survey.id,{external_key:`ui:${survey.id}:${Date.now()}`}))};
 const summary=insights?.counts||{};
 return <div className="programme-workspace space-y-5"><header className="workspace-hero"><div><span className="eyebrow">Scheduler-bound · explainable · human confirmed</span><h1>Programme Manager</h1><p>Set up programmes, build offerings inside published timetable windows, collect choices and confirm every allocation.</p></div><button disabled={busy} onClick={load}>Refresh</button></header>{error&&<div className="workspace-error">{error}</div>}{insights&&<><div className="scheduler-summary"><Summary title="Readiness" value={label(insights.readiness)}/><Summary title="Programmes" value={insights.total}/><Summary title="Pending decisions" value={summary.allocation_decisions_pending||0}/><Summary title="Active enrolments" value={summary.enrolments?.active||0}/><Summary title="Failed hand-offs" value={summary.failed_attendance_handoffs||0}/></div>{insights.alerts?.length>0&&<section className="scheduler-insights"><h2>Current insights</h2><ul>{insights.alerts.map((x,i)=><li key={i} className={`scheduler-${x.severity}`}>{x.message}</li>)}</ul></section>}</>}
 {decision&&<form className="decision-panel" onSubmit={applyDecision}><div><strong>{label(decision.kind)}</strong><p>A reason is required for the audit trail.</p></div><input required autoFocus value={reason} onChange={e=>setReason(e.target.value)}/><button className="primary">Confirm</button><button type="button" onClick={()=>setDecision(null)}>Cancel</button></form>}
 <div className="subtabs">{[["programmes","Programmes & setup"],["offerings","Offerings"],["selection","Survey & allocation"],["enrolments","Enrolments"]].map(([id,name])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}>{name}</button>)}</div>
 {tab==="programmes"&&<div className="programme-grid"><Panel title="Programme register"><form className="form-card" onSubmit={create}><h3>New programme</h3><label className="field"><span>Academic year</span><select required value={form.academic_year_id||""} onChange={e=>setForm({...form,academic_year_id:e.target.value})}><option value="">Select…</option>{years.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><Field label="Name" value={form.name||""} onChange={e=>setForm({...form,name:e.target.value})} required/><Field label="Description" value={form.description||""} onChange={e=>setForm({...form,description:e.target.value})}/><label className="field"><span>Programme type</span><select value={form.programme_type} onChange={e=>setForm({...form,programme_type:e.target.value})}>{["activities","electives","enrichment","after_school","custom"].map(x=><option key={x}>{label(x)}</option>)}</select></label><label className="field"><span>Operating mode</span><select value={form.operating_mode} onChange={e=>setForm({...form,operating_mode:e.target.value})}>{["on_timetable","off_timetable","mixed"].map(x=><option key={x}>{label(x)}</option>)}</select></label><button className="primary">Create programme</button></form><Table heads={["#","Programme","Type","Status"]}>{programmes.map((p,i)=><tr key={p.id} className={selected?.id===p.id?"selected":""} onClick={()=>select(p)}><td>{(page-1)*50+i+1}</td><td><strong>{p.name}</strong><small>{p.external_key}</small></td><td>{label(p.programme_type)}</td><td><Status value={p.status}/></td></tr>)}</Table><Pagination page={page} pageSize={50} total={total} onPageChange={setPage}/></Panel><Panel title={selected?.name||"Programme setup"}>{selected?<ProgrammeSetupWizard programme={selected} onError={setError} onChanged={load} askConfirmation={askConfirmation}/>:<Empty/>}</Panel></div>}
 {tab==="offerings"&&<Panel title={`Scheduler-authorised offerings · ${selected?.name||"select a programme"}`}><p className="programme-note">Offerings cannot use times, staff, rooms or resources that Scheduler reports unavailable.</p><Table heads={["#","Offering","Scheduler window","Capacity","Status"]}>{offerings.map((o,i)=><tr key={o.id}><td>{i+1}</td><td><strong>{o.name}</strong><small>{o.external_key}</small></td><td>{o.scheduler_window_id}</td><td>{o.capacity_max} · {label(o.capacity_mode)}</td><td><Status value={o.status}/></td></tr>)}</Table>{!offerings.length&&<Empty text="Confirm programme setup, then create offerings inside its Scheduler windows."/>}</Panel>}
 {tab==="selection"&&<div className="programme-grid"><Panel title="Selection surveys"><Table heads={["#","Survey","Status","Responses"]}>{surveys.map((s,i)=><tr key={s.id} className={survey?.id===s.id?"selected":""} onClick={()=>selectSurvey(s)}><td>{i+1}</td><td>{s.name}</td><td><Status value={s.status}/></td><td>{s.response_count||"—"}</td></tr>)}</Table>{survey&&<div className="programme-actions"><button onClick={()=>act(()=>api.reconcileProgrammeIdentities(survey.id))}>Reconcile identities</button><button className="primary" onClick={generate}>Generate recommendations</button></div>}</Panel><Panel title={run?`Human intervention queue · run ${run.id}`:"Allocation run"}>{!run?<Empty text="Publish a survey and reconcile identities before generating recommendations."/>:<><div className="programme-run"><Status value={run.status}/><span>{interventions.filter(x=>!x.decision).length} awaiting decisions</span></div><Table heads={["#","Student","Outcome","Offering","Decision"]}>{interventions.map((i,n)=><tr key={i.id} className={["review_required","unplaced"].includes(i.state)?"attention":""}><td>{n+1}</td><td>{i.canonical_student_id}</td><td><Status value={i.state}/><small>{label(i.reason_code)}</small></td><td>{i.recommended_offering_id||"Unplaced"}</td><td>{i.decision?<Status value={i.decision.action}/>:<div className="programme-actions"><button disabled={i.state!=="recommended"} onClick={()=>requestDecision("accept recommendation",i,r=>api.decideProgrammeRecommendation(i.id,{action:"accepted",confirm:true,reason:r}))}>Accept</button><button onClick={()=>requestDecision("reject recommendation",i,r=>api.decideProgrammeRecommendation(i.id,{action:"rejected",confirm:true,reason:r}),true)}>Reject</button></div>}</td></tr>)}</Table><div className="programme-actions"><button onClick={()=>requestDecision("seal allocation decisions",run,r=>api.confirmProgrammeAllocationRun(run.id,{confirm:true,reason:r}))}>Seal decisions</button><button className="primary" onClick={()=>requestDecision("publish enrolments",run,r=>api.publishProgrammeEnrolments(run.id,{confirm:true,reason:r}))}>Publish enrolments</button></div></>}</Panel></div>}
 {tab==="enrolments"&&<Panel title={`Programme enrolments · ${selected?.name||"select a programme"}`}><Table heads={["#","Student","Offering","Window","Status","Actions"]}>{enrolments.map((e,i)=><tr key={e.id}><td>{i+1}</td><td>{e.canonical_student_id}</td><td>{e.offering_id}</td><td>{e.scheduler_window_id}</td><td><Status value={e.status}/></td><td><button onClick={()=>requestDecision(e.status==="active"?"withdraw enrolment":"reinstate enrolment",e,r=>e.status==="active"?api.withdrawProgrammeEnrolment(e.id,{expected_revision:e.revision,confirm:true,reason:r}):api.reinstateProgrammeEnrolment(e.id,{expected_revision:e.revision,confirm:true,reason:r}),e.status==="active")}>{e.status==="active"?"Withdraw":"Reinstate"}</button></td></tr>)}</Table>{!enrolments.length&&<Empty text="No published enrolments for this programme."/>}</Panel>}
 </div>;
}
function Summary({value,title}){return <article><strong>{value??0}</strong><span>{title}</span></article>}
function Status({value}){return <span className={`programme-status programme-${value}`}>{label(value)}</span>}
function Panel({title,children}){return <section className="programme-panel"><h2>{title}</h2><div className="programme-scroll">{children}</div></section>}
function Table({heads,children}){return <table><thead><tr>{heads.map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{children}</tbody></table>}
function Empty({text="Select a record to continue."}){return <p className="workspace-empty">{text}</p>}
