import React,{useEffect,useState} from "react";
import * as api from "../../api/client";
import Pagination from "../components/Pagination";

const msg=e=>e.response?.data?.error?.message||e.message;
const label=x=>String(x||"").replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());
const reason=promptText=>window.prompt(promptText)||"";
export default function ProgrammeManagerWidget({askConfirmation}){
 const[programmes,setProgrammes]=useState([]),[page,setPage]=useState(1),[total,setTotal]=useState(0),[selected,setSelected]=useState(null),[offerings,setOfferings]=useState([]),[surveys,setSurveys]=useState([]),[survey,setSurvey]=useState(null),[run,setRun]=useState(null),[interventions,setInterventions]=useState([]),[enrolments,setEnrolments]=useState([]),[insights,setInsights]=useState(null),[tab,setTab]=useState("programmes"),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 const confirm=async o=>!askConfirmation||await askConfirmation(o);
 const loadDetail=async p=>{if(!p){setOfferings([]);setSurveys([]);return}const[o,s,e]=await Promise.all([api.listProgrammeOfferings(p.id,{page:1,limit:50}),api.listProgrammeSurveys(p.id,{page:1,limit:50}),api.listProgrammeEnrolments({programme_id:p.id,page:1,limit:50})]);setOfferings(o.data.offerings||[]);setSurveys(s.data.surveys||[]);setEnrolments(e.data.enrolments||[]);const current=(s.data.surveys||[]).find(x=>x.id===survey?.id)||(s.data.surveys||[])[0]||null;setSurvey(current);if(current)await loadRun(current)};
 const loadRun=async s=>{const runs=await api.listProgrammeAllocationRuns(s.id,{page:1,limit:1}),current=runs.data.runs?.[0]||null;setRun(current);if(current){const q=await api.getProgrammeInterventions(current.id,{page:1,limit:50});setInterventions(q.data.interventions||[])}else setInterventions([])};
 const load=async()=>{try{const[p,i]=await Promise.all([api.listManagedProgrammes({page,limit:50}),api.getProgrammeManagerInsights()]);setProgrammes(p.data.programmes||[]);setTotal(p.data.total||0);setInsights(i.data.insights);const current=(p.data.programmes||[]).find(x=>x.id===selected?.id)||(p.data.programmes||[])[0]||null;setSelected(current);await loadDetail(current);setError("")}catch(e){setError(msg(e))}};
 useEffect(()=>{void load()},[page]);
 const act=async fn=>{setBusy(true);try{await fn();await load()}catch(e){setError(msg(e))}finally{setBusy(false)}};
 const selectProgramme=p=>{setSelected(p);setRun(null);setInterventions([]);loadDetail(p).catch(e=>setError(msg(e)))};
 const selectSurvey=s=>{setSurvey(s);loadRun(s).catch(e=>setError(msg(e)))};
 const generate=async()=>{if(!survey||!await confirm({title:"Generate allocation recommendations?",message:"Responses will be ordered by their current priority timestamp and ranked choices. No student will be enrolled.",confirmLabel:"Generate recommendations"}))return;act(()=>api.generateProgrammeAllocations(survey.id,{external_key:`ui:${survey.id}:${Date.now()}`}))};
 const decide=async(i,action)=>{let offering_id;if(action==="manual_placement"){offering_id=+(window.prompt("Offering ID for manual placement")||0);if(!offering_id)return}const why=reason("Reason for this human decision");if(!why||!await confirm({title:`${label(action)}?`,message:`Student ${i.canonical_student_id}. This records an auditable human decision.`,confirmLabel:"Record decision",destructive:action==="rejected"}))return;act(()=>api.decideProgrammeRecommendation(i.id,{action,offering_id,confirm:true,reason:why}))};
 const seal=async()=>{const why=reason("Reason for sealing this complete decision set");if(!why||!await confirm({title:"Seal allocation decisions?",message:"Every actionable result must be decided. Sealing makes this decision set immutable.",confirmLabel:"Seal decisions"}))return;act(()=>api.confirmProgrammeAllocationRun(run.id,{confirm:true,reason:why}))};
 const publish=async()=>{const why=reason("Reason for publishing programme enrolments");if(!why||!await confirm({title:"Publish enrolments?",message:"Only accepted and manually placed students will become active programme enrolments.",confirmLabel:"Publish enrolments"}))return;act(()=>api.publishProgrammeEnrolments(run.id,{confirm:true,reason:why}))};
 const lifecycle=async(e,kind)=>{const why=reason(`Reason to ${kind} this enrolment`);if(!why||!await confirm({title:`${label(kind)} enrolment?`,message:`${e.canonical_student_id} · offering ${e.offering_id}`,confirmLabel:label(kind),destructive:kind==="withdraw"}))return;act(()=>kind==="withdraw"?api.withdrawProgrammeEnrolment(e.id,{expected_revision:e.revision,confirm:true,reason:why}):api.reinstateProgrammeEnrolment(e.id,{expected_revision:e.revision,confirm:true,reason:why}))};
 const summary=insights?.counts||{};
 return <div className="programme-workspace space-y-5"><header className="workspace-hero"><div><span className="eyebrow">Scheduler-bound · explainable · human confirmed</span><h1>Programme Manager</h1><p>Configure programme choices, monitor survey intake, resolve allocation interventions, publish enrolments and open occurrence rosters in Event Attendance.</p></div><button disabled={busy} onClick={load}>Refresh</button></header>{error&&<div className="workspace-error">{error}</div>}{insights&&<><div className="scheduler-summary"><Summary title="Readiness" value={label(insights.readiness)}/><Summary title="Programmes" value={insights.total}/><Summary title="Pending decisions" value={summary.allocation_decisions_pending||0}/><Summary title="Active enrolments" value={summary.enrolments?.active||0}/><Summary title="Failed handoffs" value={summary.failed_attendance_handoffs||0}/></div>{insights.alerts?.length>0&&<section className="scheduler-insights"><h2>Current insights</h2><ul>{insights.alerts.map((x,i)=><li key={i} className={`scheduler-${x.severity}`}>{x.message}</li>)}</ul></section>}</>}
 <nav className="cover-tabs"><button className={tab==="programmes"?"active":""} onClick={()=>setTab("programmes")}>Programmes</button><button className={tab==="selection"?"active":""} onClick={()=>setTab("selection")}>Selection & allocation</button><button className={tab==="enrolments"?"active":""} onClick={()=>setTab("enrolments")}>Enrolments</button></nav>
 {tab==="programmes"&&<div className="programme-grid"><Panel title="Programmes"><Table heads={["#","Programme","Type","Status"]}>{programmes.map((p,i)=><tr key={p.id} className={selected?.id===p.id?"selected":""} onClick={()=>selectProgramme(p)}><td>{(page-1)*50+i+1}</td><td><strong>{p.name}</strong><small>{p.external_key}</small></td><td>{label(p.programme_type)}</td><td><Status value={p.status}/></td></tr>)}</Table><Pagination page={page} pageSize={50} total={total} onPageChange={setPage}/></Panel><Panel title={selected?.name||"Programme detail"}>{!selected?<Empty/>:<><p className="programme-note">Academic year {selected.academic_year_id} · {label(selected.operating_mode||"setup required")}</p><h3>Ready offerings ({offerings.length})</h3><Table heads={["#","Offering","Window","Capacity","Status"]}>{offerings.map((o,i)=><tr key={o.id}><td>{i+1}</td><td>{o.name}</td><td>{o.scheduler_window_id}</td><td>{o.capacity_max} · {label(o.capacity_mode)}</td><td><Status value={o.status}/></td></tr>)}</Table></>}</Panel></div>}
 {tab==="selection"&&<div className="programme-grid"><Panel title="Selection surveys"><Table heads={["#","Survey","Status","Responses"]}>{surveys.map((s,i)=><tr key={s.id} className={survey?.id===s.id?"selected":""} onClick={()=>selectSurvey(s)}><td>{i+1}</td><td>{s.name}</td><td><Status value={s.status}/></td><td>{s.response_count||"—"}</td></tr>)}</Table>{survey&&<div className="programme-actions"><button onClick={()=>act(()=>api.reconcileProgrammeIdentities(survey.id))}>Reconcile identities</button><button onClick={generate}>Generate recommendations</button></div>}</Panel><Panel title={run?`Intervention queue · run ${run.id}`:"Allocation run"}>{!run?<Empty text="Generate recommendations after survey publication and identity review."/>:<><div className="programme-run"><Status value={run.status}/><span>{interventions.filter(x=>!x.decision).length} awaiting human decisions</span></div><Table heads={["#","Student","Outcome","Offering","Decision"]}>{interventions.map((i,n)=><tr key={i.id} className={["review_required","unplaced"].includes(i.state)?"attention":""}><td>{n+1}</td><td>{i.canonical_student_id}</td><td><Status value={i.state}/><small>{label(i.reason_code)}</small></td><td>{i.recommended_offering_id||"Unplaced"}</td><td>{i.decision?<Status value={i.decision.action}/>:<div className="programme-actions"><button disabled={i.state!=="recommended"} onClick={()=>decide(i,"accepted")}>Accept</button><button onClick={()=>decide(i,"manual_placement")}>Place</button><button onClick={()=>decide(i,"rejected")}>Reject</button></div>}</td></tr>)}</Table><div className="programme-actions"><button onClick={seal}>Seal complete decisions</button><button onClick={publish}>Publish enrolments</button></div></>}</Panel></div>}
 {tab==="enrolments"&&<Panel title={`Programme enrolments · ${selected?.name||"select a programme"}`}><Table heads={["#","Student","Offering","Window","Status","Actions"]}>{enrolments.map((e,i)=><tr key={e.id}><td>{i+1}</td><td>{e.canonical_student_id}</td><td>{e.offering_id}</td><td>{e.scheduler_window_id}</td><td><Status value={e.status}/></td><td><button onClick={()=>lifecycle(e,e.status==="active"?"withdraw":"reinstate")}>{e.status==="active"?"Withdraw":"Reinstate"}</button></td></tr>)}</Table>{!enrolments.length&&<Empty text="No published enrolments for this programme."/>}</Panel>}</div>;
}
function Summary({value,title}){return <article><strong>{value??0}</strong><span>{title}</span></article>}
function Status({value}){return <span className={`programme-status programme-${value}`}>{label(value)}</span>}
function Panel({title,children}){return <section className="programme-panel"><h2>{title}</h2><div className="programme-scroll">{children}</div></section>}
function Table({heads,children}){return <table><thead><tr>{heads.map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{children}</tbody></table>}
function Empty({text="Select a record to continue."}){return <p className="workspace-empty">{text}</p>}
