import React,{useEffect,useState} from "react";
import * as api from "../../api/client";
import Pagination from "../components/Pagination";

const message=e=>e.response?.data?.error?.message||e.message;
const label=x=>String(x||"").replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());
export default function SchedulerWidget({askConfirmation}){
 const[years,setYears]=useState([]),[year,setYear]=useState(""),[setup,setSetup]=useState(null),[insights,setInsights]=useState(null),[versions,setVersions]=useState([]),[page,setPage]=useState(1),[total,setTotal]=useState(0),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{api.listAcademicYears({limit:50}).then(r=>{setYears(r.data.years);if(r.data.years[0])setYear(String(r.data.years[0].id))}).catch(e=>setError(message(e)))},[]);
 const load=async()=>{if(!year)return;try{const s=(await api.getSchedulerSetup(year)).data.setup;setSetup(s);if(!s){setInsights(null);setVersions([]);setTotal(0);return}const[i,v]=await Promise.all([api.getSchedulerInsights(s.id),api.listSchedulerVersions(s.id,{page,limit:50})]);setInsights(i.data.insights);setVersions(v.data.versions);setTotal(v.data.total);setError("")}catch(e){setError(message(e))}};
 useEffect(()=>{void load()},[year,page]);
 const run=async fn=>{setBusy(true);try{await fn();await load()}catch(e){setError(message(e))}finally{setBusy(false)}};
 const create=()=>run(()=>api.saveSchedulerSetup({academic_year_id:+year,name:`${years.find(x=>String(x.id)===year)?.name||"Academic year"} timetable`,scope_mode:"school",status:"draft",timezone:Intl.DateTimeFormat().resolvedOptions().timeZone||"UTC",week_starts_on:1,configuration:{}}));
 const act=async(v,kind)=>{let reason="";if(["reject","publish"].includes(kind)){reason=window.prompt(kind==="reject"?"Reason for rejection":"Publication note")||"";if(!reason)return}if(askConfirmation&&!await askConfirmation({title:`${label(kind)} schedule?`,message:`${v.name} · alternative ${v.alternative_number}`,confirmLabel:label(kind),destructive:kind==="reject"}))return;const calls={select:()=>api.selectScheduleDraft(v.id,v.revision),submit:()=>api.submitSchedule(v.id,"Ready for principal review",v.revision),approve:()=>api.approveSchedule(v.id,"Reviewed and approved",v.revision),reject:()=>api.rejectSchedule(v.id,reason,v.revision),publish:()=>api.publishSchedule(v.id,reason,v.revision)};run(calls[kind])};
 return <div className="scheduler-workspace space-y-5"><header className="workspace-hero"><div><span className="eyebrow">Explainable whole-school timetable planning</span><h1>Scheduler</h1><p>Configure, generate, compare, govern and publish timetables. Operational lessons flow to Calendar and Gradebook only after approval.</p></div><button disabled={busy} onClick={load}>Refresh</button></header>{error&&<div className="workspace-error">{error}</div>}<section className="scheduler-toolbar"><label>Academic year <select value={year} onChange={e=>{setPage(1);setYear(e.target.value)}}><option value="">Select year</option>{years.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>{!setup&&year&&<button disabled={busy} onClick={create}>Start whole-school setup</button>}{setup&&<button disabled={busy} onClick={()=>run(()=>api.generateSchedules({scheduler_setup_id:setup.id,name:"Generated timetable",alternative_count:3}))}>Generate 3 alternatives</button>}</section>{setup&&insights&&<><div className="scheduler-summary"><Summary value={label(insights.readiness)} title="Readiness"/><Summary value={insights.counts.active_scopes} title="Active scopes"/><Summary value={insights.counts.operating_days} title="Operating days"/><Summary value={insights.counts.active_requirements} title="Requirements"/><Summary value={insights.counts.schedule_versions} title="Versions"/></div>{insights.issues.length>0&&<section className="scheduler-insights"><h2>Current insights</h2><ul>{insights.issues.map((x,i)=><li key={i} className={`scheduler-${x.severity}`}><strong>{label(x.severity)}</strong> {x.message}</li>)}</ul></section>}<div className="overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead><tr className="border-b border-gray-700 text-left text-gray-400">{["#","Schedule","Alternative","Status","Feasible","Score","Placements","Actions"].map(x=><th className="p-2" key={x}>{x}</th>)}</tr></thead><tbody>{versions.map((v,i)=><tr key={v.id} className={!v.feasible?"border-b border-red-800 bg-red-950/30":"border-b border-gray-800"}><td className="p-2">{(page-1)*50+i+1}</td><td>{v.name}</td><td>{v.alternative_number}</td><td>{label(v.status)}</td><td>{v.feasible?"Yes":"No"}</td><td>{v.score}</td><td>{v.placements.length}</td><td className="space-x-3">{v.status==="generated"&&v.feasible&&<button onClick={()=>act(v,"select")}>Select draft</button>}{v.status==="draft"&&<button onClick={()=>act(v,"submit")}>Submit</button>}{v.status==="submitted"&&<><button onClick={()=>act(v,"approve")}>Approve</button><button className="text-red-300" onClick={()=>act(v,"reject")}>Reject</button></>}{v.status==="approved"&&<button className="text-emerald-300" onClick={()=>act(v,"publish")}>Publish</button>}</td></tr>)}</tbody></table></div><Pagination page={page} pageSize={50} total={total} onPageChange={setPage}/></>}</div>;
}
function Summary({value,title}){return <article><strong>{value}</strong><span>{title}</span></article>}
