import React,{useEffect,useState}from"react";
import * as api from"../../api/client";
import Pagination from"../components/Pagination";
import SchedulerConfigurationPanel from"../components/SchedulerConfigurationPanel";
import ScheduleReviewPanel from"../components/ScheduleReviewPanel";

const message=e=>e?.response?.data?.error?.message||e.message;
const label=x=>String(x||"").replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());

export default function SchedulerWidget({askConfirmation}){
 const[years,setYears]=useState([]),[year,setYear]=useState(""),[setup,setSetup]=useState(null),[insights,setInsights]=useState(null),[versions,setVersions]=useState([]),[page,setPage]=useState(1),[total,setTotal]=useState(0),[error,setError]=useState(""),[busy,setBusy]=useState(false),[configuring,setConfiguring]=useState(false),[selected,setSelected]=useState(null),[pending,setPending]=useState(null),[reason,setReason]=useState("");
 useEffect(()=>{api.listAcademicYears({limit:50}).then(r=>{setYears(r.data.years||[]);if(r.data.years?.[0])setYear(String(r.data.years[0].id))}).catch(e=>setError(message(e)))},[]);
 const load=async()=>{if(!year)return;try{const s=(await api.getSchedulerSetup(year)).data.setup;setSetup(s);if(!s){setInsights(null);setVersions([]);setTotal(0);return}const[i,v]=await Promise.all([api.getSchedulerInsights(s.id),api.listSchedulerVersions(s.id,{page,limit:50})]);setInsights(i.data.insights);setVersions(v.data.versions||[]);setTotal(v.data.total||0);setSelected(current=>current?(v.data.versions||[]).find(x=>x.id===current.id)||null:null);setError("")}catch(e){setError(message(e))}};
 useEffect(()=>{load()},[year,page]);
 const run=async fn=>{setBusy(true);try{await fn();await load()}catch(e){setError(message(e))}finally{setBusy(false)}};
 const create=()=>run(()=>api.saveSchedulerSetup({academic_year_id:+year,name:`${years.find(x=>String(x.id)===year)?.name||"Academic year"} timetable`,scope_mode:"school",status:"draft",timezone:Intl.DateTimeFormat().resolvedOptions().timeZone||"UTC",week_starts_on:1,configuration:{}}));
 const act=async(v,kind,note="")=>{if(["reject","publish"].includes(kind)&&!note.trim()){setPending({v,kind});setReason("");return}if(askConfirmation&&!await askConfirmation({title:`${label(kind)} schedule?`,message:`${v.name} · alternative ${v.alternative_number}`,confirmLabel:label(kind),destructive:kind==="reject"}))return;const calls={select:()=>api.selectScheduleDraft(v.id,v.revision),submit:()=>api.submitSchedule(v.id,"Ready for principal review",v.revision),approve:()=>api.approveSchedule(v.id,"Reviewed and approved",v.revision),reject:()=>api.rejectSchedule(v.id,note,v.revision),publish:()=>api.publishSchedule(v.id,note,v.revision)};setPending(null);setReason("");run(calls[kind])};
 return <div className="scheduler-workspace space-y-5">
  <header className="workspace-hero"><div><span className="eyebrow">Explainable whole-school timetable planning</span><h1>Scheduler</h1><p>Configure, generate, compare, govern and publish timetables. Lessons flow to Calendar and Gradebook only after approval.</p></div><div className="header-actions">{setup&&<button onClick={()=>setConfiguring(x=>!x)}>{configuring?"Close configuration":"Configure timetable"}</button>}<button disabled={busy} onClick={load}>Refresh</button></div></header>
  {error&&<div className="workspace-error">{error}</div>}
  <section className="scheduler-toolbar"><label>Academic year <select value={year} onChange={e=>{setPage(1);setYear(e.target.value)}}><option value="">Select year</option>{years.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>{!setup&&year&&<button disabled={busy} onClick={create}>Start whole-school setup</button>}{setup&&<button className="primary" disabled={busy||insights?.readiness!=="ready"} title={insights?.readiness!=="ready"?"Complete timetable configuration first":""} onClick={()=>run(()=>api.generateSchedules({scheduler_setup_id:setup.id,name:"Generated timetable",alternative_count:3}))}>Generate 3 alternatives</button>}</section>
  {setup&&configuring&&<SchedulerConfigurationPanel setup={setup} askConfirmation={askConfirmation} onError={setError} onChanged={load}/>}
  {pending&&<form className="decision-panel" onSubmit={e=>{e.preventDefault();act(pending.v,pending.kind,reason)}}><div><strong>{pending.kind==="reject"?"Explain this rejection":"Publication note"}</strong><p>This note becomes part of the permanent audit trail.</p></div><input required autoFocus value={reason} onChange={e=>setReason(e.target.value)}/><button className="primary">Continue</button><button type="button" onClick={()=>setPending(null)}>Cancel</button></form>}
  {selected&&setup&&<ScheduleReviewPanel setup={setup} version={selected} askConfirmation={askConfirmation} onError={setError} onChanged={load}/>}
  {setup&&insights&&<><div className="scheduler-summary"><Summary value={label(insights.readiness)} title="Readiness"/><Summary value={insights.counts.active_scopes} title="Active scopes"/><Summary value={insights.counts.operating_days} title="Operating days"/><Summary value={insights.counts.active_requirements} title="Requirements"/><Summary value={insights.counts.schedule_versions} title="Versions"/></div>{insights.issues.length>0&&<section className="scheduler-insights"><h2>Before generation</h2><ul>{insights.issues.map((x,i)=><li key={i} className={`scheduler-${x.severity}`}><strong>{label(x.severity)}</strong> {x.message}</li>)}</ul></section>}<div className="table-card"><table><thead><tr>{["#","Schedule","Alternative","Status","Feasible","Score","Placements","Actions"].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{versions.map((v,i)=><tr key={v.id} className={!v.feasible?"row-alert":""}><td>{(page-1)*50+i+1}</td><td><button className="table-link" onClick={()=>setSelected(selected?.id===v.id?null:v)}>{v.name}</button><small>{v.stale?"Inputs changed — regenerate":"Input snapshot preserved"}</small></td><td>{v.alternative_number}</td><td><span className="status-pill">{label(v.status)}</span></td><td>{v.feasible?"Yes":"No"}</td><td>{v.score}</td><td>{v.placements.length}</td><td className="header-actions">{v.status==="generated"&&v.feasible&&!v.stale&&<button onClick={()=>act(v,"select")}>Select draft</button>}{v.status==="draft"&&<button onClick={()=>act(v,"submit")}>Submit</button>}{v.status==="submitted"&&<><button onClick={()=>act(v,"approve")}>Approve</button><button onClick={()=>act(v,"reject")}>Reject</button></>}{v.status==="approved"&&<button onClick={()=>act(v,"publish")}>Publish</button>}</td></tr>)}</tbody></table></div><Pagination page={page} pageSize={50} total={total} onPageChange={setPage}/></>}
 </div>;
}
function Summary({value,title}){return <article><strong>{value}</strong><span>{title}</span></article>}
