import React,{useEffect,useMemo,useState}from"react";
import * as api from"../../api/client";
const label=s=>String(s||"").replaceAll("_"," ");
const tone=s=>({healthy:"health-good",idle:"health-idle",degraded:"health-warn",blocked:"health-bad",unhealthy:"health-bad"}[s]||"health-idle");
export default function SystemHealthDashboard(){
 const[data,setData]=useState(null),[error,setError]=useState(""),[filter,setFilter]=useState("all"),[open,setOpen]=useState({});
 const load=()=>api.getSystemHealth().then(r=>{setData(r.data.health);setError("")}).catch(e=>setError(e.response?.data?.error?.message||e.message));
 useEffect(()=>{load()},[]);
 const rows=useMemo(()=>data?data.modules.filter(m=>filter==="all"||m.status===filter):[],[data,filter]);
 if(!data)return <div className="workspace-empty">{error||"Checking platform health…"}</div>;
 return <div className="system-health-dashboard"><header className="workspace-hero"><div><span className="eyebrow">Principal-safe platform observability</span><h1>System Health</h1><p>One view of every operational module and component. Parts are listed only to explain what a component contains. Idle means available but not recently used.</p></div><button onClick={load}>Refresh health</button></header>{error&&<div className="workspace-error">{error}</div>}<div className="health-summary"><Summary n={data.totalModules} t="Modules"/><Summary n={data.totalComponents} t="Components"/>{Object.entries(data.counts).map(([k,v])=><button key={k} className={tone(k)} onClick={()=>setFilter(filter===k?"all":k)}><strong>{v}</strong><span>{label(k)}</span></button>)}</div><div className="health-toolbar"><strong>{rows.length} modules shown</strong><button onClick={()=>setFilter("all")}>Clear filter</button></div><div className="health-scroll">{rows.map(m=><section key={m.name} className="health-module"><button className="health-module-head" onClick={()=>setOpen({...open,[m.name]:!open[m.name]})}><div><span className={`health-pill ${tone(m.status)}`}>{m.status}</span><h2>{label(m.name)}</h2><p>v{m.version} · {m.certification.status} · {m.routes.healthy}/{m.routes.declared} routes · {m.usage.requests} requests · {m.usage.events} events</p></div><div className="health-usage"><strong>{m.usage.averageLatencyMs} ms</strong><span>average response</span><strong>{m.usage.errors}</strong><span>server errors</span></div><span>{open[m.name]?"−":"+"}</span></button>{open[m.name]&&<div className="health-detail"><div className="health-dependencies"><strong>Dependencies</strong>{m.dependencies.length?<ul>{m.dependencies.map(d=><li key={d.name}><span className={tone(d.status)}>●</span> {label(d.name)}</li>)}</ul>:<p>No module dependencies.</p>}{m.usage.lastActivity&&<p>Last activity: {new Date(m.usage.lastActivity).toLocaleString()}</p>}</div>{m.components.length?<div className="health-components">{m.components.map(c=><article key={c.name}><div><strong>{label(c.name)}</strong><span className={`health-pill ${tone(c.status)}`}>{c.status}</span></div><p>v{c.version} · {c.certification.status} · {label(c.classification)} · {c.recordCount} records · {c.dataQualityEntities} intelligence entities</p>{c.parts.length>0&&<><small>Internal parts (descriptive only)</small><div className="health-parts">{c.parts.map(p=><span key={p}>{label(p)}</span>)}</div></>}</article>)}</div>:<p className="health-platform-note">Platform-only module: heartbeat, dependency, route, usage and performance telemetry are active.</p>}</div>}</section>)}</div></div>;
}
function Summary({n,t}){return <div><strong>{n}</strong><span>{t}</span></div>}
