import React,{useEffect,useState}from"react";
import * as api from"../../api/client";
import Pagination from"../components/Pagination";

const empty={title:"",description:"",subject_component:"",subject_type:"",subject_id:"",responsibility_id:"",priority:"normal",starts_at:"",due_at:""};
export default function TasksWidget({askConfirmation}){
 const [rows,setRows]=useState([]),[form,setForm]=useState(empty),[editing,setEditing]=useState(null),[page,setPage]=useState(1),[total,setTotal]=useState(0),[search,setSearch]=useState(""),[status,setStatus]=useState(""),[error,setError]=useState(""),[message,setMessage]=useState("");
 const [dependency,setDependency]=useState(null),[dependencyForm,setDependencyForm]=useState({prerequisite_task_id:"",dependency_type:"blocks"});
 const load=async()=>{try{const r=await api.listTasks({page,limit:50,q:search,status:status||undefined});setRows(r.data.tasks||[]);setTotal(r.data.total||0);setError("");}catch(e){setError(e.response?.data?.error?.message||e.message);}};
 useEffect(()=>{void load();},[page,search,status]);
 useEffect(()=>{window.dispatchEvent(new CustomEvent("principaled:dirty-state",{detail:Boolean(form.title||editing||dependency)}));return()=>window.dispatchEvent(new CustomEvent("principaled:dirty-state",{detail:false}));},[form.title,editing,dependency]);
 const save=async e=>{e.preventDefault();try{const payload={...form,responsibility_id:form.responsibility_id||null};if(editing)await api.updateTask(editing,payload);else await api.createTask(payload);setForm(empty);setEditing(null);setMessage(editing?"Task updated":"Task created");await load();}catch(err){setError(err.response?.data?.error?.message||err.message);}};
 const edit=row=>{setEditing(row.id);setForm({title:row.title||"",description:row.description||"",subject_component:row.subject_component||"",subject_type:row.subject_type||"",subject_id:row.subject_id||"",responsibility_id:row.responsibility_id||"",priority:row.priority||"normal",starts_at:row.starts_at||"",due_at:row.due_at||""});window.scrollTo({top:0,behavior:"smooth"});};
 const changeStatus=async(row,next)=>{const prompted=["completed","withdrawn"].includes(next);if(prompted&&!await askConfirmation({title:`${next==="completed"?"Complete":"Withdraw"} task?`,message:row.title,confirmLabel:next==="completed"?"Complete":"Withdraw",destructive:next==="withdrawn"}))return;try{await api.setTaskStatus(row.id,next);await load();}catch(err){setError(err.response?.data?.error?.message||err.message);}};
 const addDependency=async e=>{e.preventDefault();try{await api.addTaskDependency(dependency.id,{...dependencyForm,prerequisite_task_id:Number(dependencyForm.prerequisite_task_id)});setDependency(null);setDependencyForm({prerequisite_task_id:"",dependency_type:"blocks"});await load();}catch(err){setError(err.response?.data?.error?.message||err.message);}};
 const removeDependency=async(row,id)=>{if(await askConfirmation({title:"Remove task dependency?",message:"The tasks will no longer be linked.",confirmLabel:"Remove",destructive:true})){await api.removeTaskDependency(row.id,id);await load();}};
 return <div className="space-y-5"><header><span className="text-xs uppercase tracking-widest text-purple-400">Reusable workflow component</span><h1 className="text-3xl font-semibold">Tasks</h1><p className="text-gray-400">Track discrete work and prerequisites. Responsibility remains in the Ownership component.</p></header>{error&&<p className="rounded border border-red-700 bg-red-950/40 p-3 text-red-200">{error}</p>}{message&&<p className="text-emerald-400">{message}</p>}
 <form onSubmit={save} className="rounded border border-gray-800 bg-gray-900/60 p-4"><h2 className="mb-3 font-semibold">{editing?"Edit task":"Create task"}</h2><div className="grid gap-3 md:grid-cols-3"><input required className="rounded bg-gray-950 p-2" placeholder="Task title" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><select className="rounded bg-gray-950 p-2" value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}><option value="low">Low priority</option><option value="normal">Normal priority</option><option value="high">High priority</option><option value="urgent">Urgent</option></select><input type="datetime-local" className="rounded bg-gray-950 p-2" aria-label="Due date" value={form.due_at} onChange={e=>setForm({...form,due_at:e.target.value})}/><input className="rounded bg-gray-950 p-2" placeholder="Subject component (optional)" value={form.subject_component} onChange={e=>setForm({...form,subject_component:e.target.value})}/><input className="rounded bg-gray-950 p-2" placeholder="Subject type (optional)" value={form.subject_type} onChange={e=>setForm({...form,subject_type:e.target.value})}/><input className="rounded bg-gray-950 p-2" placeholder="Subject identifier (optional)" value={form.subject_id} onChange={e=>setForm({...form,subject_id:e.target.value})}/><input type="number" min="1" className="rounded bg-gray-950 p-2" placeholder="Responsibility ID (optional)" value={form.responsibility_id} onChange={e=>setForm({...form,responsibility_id:e.target.value})}/><textarea className="rounded bg-gray-950 p-2 md:col-span-2" placeholder="Description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></div><div className="mt-3 flex gap-2"><button className="rounded bg-purple-600 px-4 py-2">{editing?"Save changes":"Create task"}</button>{(editing||form.title)&&<button type="button" className="rounded bg-gray-700 px-4 py-2" onClick={()=>{setEditing(null);setForm(empty);}}>Cancel</button>}</div></form>
 {dependency&&<form onSubmit={addDependency} className="rounded border border-purple-700 bg-purple-950/20 p-4"><h2 className="font-semibold">Add prerequisite to {dependency.title}</h2><div className="mt-3 flex flex-wrap gap-3"><input required type="number" min="1" className="rounded bg-gray-950 p-2" placeholder="Prerequisite task ID" value={dependencyForm.prerequisite_task_id} onChange={e=>setDependencyForm({...dependencyForm,prerequisite_task_id:e.target.value})}/><select className="rounded bg-gray-950 p-2" value={dependencyForm.dependency_type} onChange={e=>setDependencyForm({...dependencyForm,dependency_type:e.target.value})}><option value="blocks">Blocks completion</option><option value="related">Related only</option></select><button className="rounded bg-purple-600 px-4 py-2">Add</button><button type="button" className="rounded bg-gray-700 px-4 py-2" onClick={()=>setDependency(null)}>Cancel</button></div></form>}
 <section><div className="grid gap-3 sm:grid-cols-2"><input className="rounded bg-gray-900 p-2" placeholder="Search tasks" value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}}/><select className="rounded bg-gray-900 p-2" value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="">All statuses</option><option value="pending">Pending</option><option value="in_progress">In progress</option><option value="blocked">Blocked</option><option value="completed">Completed</option><option value="withdrawn">Withdrawn</option></select></div><div className="mt-3 overflow-x-auto"><table className="w-full min-w-[1050px] text-sm"><thead><tr className="border-b border-gray-700 text-left text-gray-400"><th className="p-2">#</th><th>ID</th><th>Task</th><th>Priority</th><th>Due</th><th>Status</th><th>Prerequisites</th><th>Actions</th></tr></thead><tbody>{rows.map((row,i)=><tr key={row.id} className={`border-b border-gray-800 ${row.blocked_by?"bg-red-950/30":""}`}><td className="p-2">{(page-1)*50+i+1}</td><td>{row.id}</td><td><div>{row.title}</div>{row.subject_id&&<div className="text-xs text-gray-500">{row.subject_component}/{row.subject_type}/{row.subject_id}</div>}</td><td>{row.priority}</td><td>{row.due_at?new Date(row.due_at).toLocaleString():"—"}</td><td>{row.status}{row.blocked_by?` (${row.blocked_by} blocker)`:""}</td><td>{row.dependencies.map(d=><div key={d.id} className="text-xs">#{d.prerequisite_task_id} {d.prerequisite_title} ({d.prerequisite_status}) <button className="text-red-300" onClick={()=>removeDependency(row,d.id)}>Remove</button></div>)}</td><td><div className="flex flex-wrap gap-2 text-xs"><button className="text-blue-300" onClick={()=>edit(row)}>Edit</button><button className="text-purple-300" onClick={()=>setDependency(row)}>Dependency</button>{row.status==="pending"&&<button className="text-amber-300" onClick={()=>changeStatus(row,"in_progress")}>Start</button>}{!['completed','withdrawn'].includes(row.status)&&<button className="text-emerald-300" onClick={()=>changeStatus(row,"completed")}>Complete</button>}<button className={row.status==="withdrawn"?"text-emerald-300":"text-red-300"} onClick={()=>changeStatus(row,row.status==="withdrawn"?"pending":"withdrawn")}>{row.status==="withdrawn"?"Reinstate":"Withdraw"}</button></div></td></tr>)}</tbody></table>{!rows.length&&<p className="p-8 text-center text-gray-500">No tasks found.</p>}</div><Pagination page={page} pageSize={50} total={total} onPageChange={setPage}/></section></div>;
}
