import React,{useEffect,useState} from "react";
import * as api from "../../api/client";
import Pagination from "../components/Pagination";

const msg=e=>e.response?.data?.error?.message||e.message;
const label=x=>String(x||"").replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());
export default function TeacherPreferencesWidget({askConfirmation}){
 const[cycles,setCycles]=useState([]),[cycle,setCycle]=useState(""),[rows,setRows]=useState([]),[insights,setInsights]=useState(null),[years,setYears]=useState([]),[setup,setSetup]=useState(null),[page,setPage]=useState(1),[total,setTotal]=useState(0),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 const load=async()=>{try{const[c,p,i,y]=await Promise.all([api.listTeacherPreferenceCycles({limit:50}),api.listTeacherPreferences({page,limit:50,...(cycle?{cycle_id:cycle}:{})}),api.getTeacherPreferenceInsights(),api.listAcademicYears({limit:50})]);setCycles(c.data.cycles);setRows(p.data.preferences);setTotal(p.data.total);setInsights(i.data.insights);setYears(y.data.years);const selected=y.data.years[0];setSetup(selected?(await api.getSchedulerSetup(selected.id)).data.setup:null);setError("")}catch(e){setError(msg(e))}};
 useEffect(()=>{void load()},[page,cycle]);
 const run=async fn=>{setBusy(true);try{await fn();await load()}catch(e){setError(msg(e))}finally{setBusy(false)}};
 const createCycle=()=>{const year=years[0];if(!year)return setError("Create an academic year before opening preference collection.");const name=window.prompt("Preference cycle name",`${year.name} teacher preferences`);if(name)run(()=>api.createTeacherPreferenceCycle({academic_year_id:year.id,external_key:`preferences:${year.id}:${Date.now()}`,name}))};
 const add=()=>{if(!cycle)return setError("Select an open collection cycle first.");const staff_id=window.prompt("Staff ID");const target_label=window.prompt("Preferred subject, grade, activity or role");if(staff_id&&target_label)run(()=>api.createTeacherPreference({cycle_id:+cycle,staff_id,domain:"subject",stance:"prefer",target_key:target_label.toLowerCase().replace(/\s+/g,"-"),target_label,confidence:"medium"}))};
 const confirm=async(row,kind)=>{const reason=window.prompt(kind==="withdraw"?"Reason for withdrawal":"Reason for review");if(!reason)return;const ok=!askConfirmation||await askConfirmation({title:`${label(kind)} preference?`,message:row.target_label,confirmLabel:label(kind),destructive:kind==="withdraw"});if(!ok)return;run(()=>kind==="withdraw"?api.withdrawTeacherPreference(row.id,reason,row.revision):api.reviewTeacherRestriction(row.id,kind,reason,row.revision))};
 return <div className="space-y-5"><header className="workspace-hero"><div><span className="eyebrow">Advisory evidence; human decisions remain authoritative</span><h1>Teacher Preferences</h1><p>Collect ranked preferences and reviewed declarations, then deliberately supply them to Scheduler as explainable soft evidence.</p></div><button disabled={busy} onClick={load}>Refresh</button></header>{error&&<div className="workspace-error">{error}</div>}{insights&&<><div className="scheduler-summary"><Summary title="Readiness" value={label(insights.readiness)}/><Summary title="Active" value={insights.counts.active}/><Summary title="Staff coverage" value={`${insights.coverage_percent}%`}/><Summary title="Pending reviews" value={insights.counts.pending_restrictions}/></div><p>{insights.narrative}</p>{insights.alerts.length>0&&<ul>{insights.alerts.map((x,i)=><li key={i}><strong>{label(x.severity)}:</strong> {x.message}</li>)}</ul>}</>}
 <section className="scheduler-toolbar"><label>Collection cycle <select value={cycle} onChange={e=>{setPage(1);setCycle(e.target.value)}}><option value="">All cycles</option>{cycles.map(x=><option key={x.id} value={x.id}>{x.name} ({label(x.status)})</option>)}</select></label><button disabled={busy} onClick={createCycle}>Create cycle</button><button disabled={busy||!cycle} onClick={add}>Add preference</button><button disabled={busy||!setup} onClick={()=>run(()=>api.syncTeacherPreferences(setup.id))}>Sync to Scheduler</button></section>
 <div className="overflow-x-auto"><table className="w-full min-w-[1000px] text-sm"><thead><tr className="border-b border-gray-700 text-left text-gray-400">{["#","Staff","Domain","Preference","Stance","Rank","Confidence","Review","Status","Actions"].map(x=><th className="p-2" key={x}>{x}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id} className={r.review_state==="pending"?"border-b border-red-800 bg-red-950/30":"border-b border-gray-800"}><td className="p-2">{(page-1)*50+i+1}</td><td>{r.staff_id}</td><td>{label(r.domain)}</td><td>{r.target_label}</td><td>{label(r.stance)}</td><td>{r.rank||"—"}</td><td>{label(r.confidence)}</td><td>{label(r.review_state)}</td><td>{label(r.status)}</td><td className="space-x-3">{r.status==="draft"&&<button onClick={()=>run(()=>api.submitTeacherPreference(r.id,r.revision))}>Submit</button>}{r.status==="active"&&<button className="text-red-300" onClick={()=>confirm(r,"withdraw")}>Withdraw</button>}{r.status==="active"&&r.review_state==="pending"&&<><button onClick={()=>confirm(r,"confirmed")}>Confirm</button><button onClick={()=>confirm(r,"declined")}>Decline</button></>}</td></tr>)}</tbody></table></div><Pagination page={page} pageSize={50} total={total} onPageChange={setPage}/></div>;
}
function Summary({value,title}){return <article><strong>{value}</strong><span>{title}</span></article>}
