import React,{useEffect,useState}from"react";
import * as api from"../../api/client";
import Pagination from"../components/Pagination";

const msg=e=>e?.response?.data?.error?.message||e.message;
const label=x=>String(x||"").replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());
const blank={staff_id:"",domain:"subject",stance:"prefer",target_label:"",rank:1,confidence:"medium",rationale:""};
const Field=({label:caption,...props})=><label className="field"><span>{caption}</span><input {...props}/></label>;

export default function TeacherPreferencesWidget({askConfirmation}){
 const[cycles,setCycles]=useState([]),[cycle,setCycle]=useState(""),[rows,setRows]=useState([]),[insights,setInsights]=useState(null),[years,setYears]=useState([]),[setup,setSetup]=useState(null),[contract,setContract]=useState(null),[providers,setProviders]=useState([]),[history,setHistory]=useState([]),[selectedStaff,setSelectedStaff]=useState(""),[page,setPage]=useState(1),[total,setTotal]=useState(0),[tab,setTab]=useState("entries"),[form,setForm]=useState(blank),[cycleForm,setCycleForm]=useState({}),[decision,setDecision]=useState(null),[reason,setReason]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 const load=async()=>{try{const[c,p,i,y,k,pr]=await Promise.all([api.listTeacherPreferenceCycles({limit:50}),api.listTeacherPreferences({page,limit:50,...(cycle?{cycle_id:cycle}:{})}),api.getTeacherPreferenceInsights(),api.listAcademicYears({limit:50}),api.getTeacherPreferencesContract(),api.listTeacherPreferenceProviderRecords({limit:50})]);setCycles(c.data.cycles||[]);setRows(p.data.preferences||[]);setTotal(p.data.total||0);setInsights(i.data.insights);setYears(y.data.years||[]);setContract(k.data.contract);setProviders(pr.data.records||[]);const selected=y.data.years?.[0];setSetup(selected?(await api.getSchedulerSetup(selected.id)).data.setup:null);setError("")}catch(e){setError(msg(e))}};
 useEffect(()=>{load()},[page,cycle]);
 const run=async fn=>{setBusy(true);try{await fn();await load()}catch(e){setError(msg(e))}finally{setBusy(false)}};
 const createCycle=e=>{e.preventDefault();const year=years.find(x=>String(x.id)===String(cycleForm.year));run(()=>api.createTeacherPreferenceCycle({academic_year_id:year.id,external_key:`preferences:${year.id}:${Date.now()}`,name:cycleForm.name,opens_at:cycleForm.opens_at||null,closes_at:cycleForm.closes_at||null}))};
 const add=e=>{e.preventDefault();if(!cycle)return setError("Select an open collection cycle first.");run(async()=>{await api.createTeacherPreference({...form,cycle_id:+cycle,target_key:form.target_label.toLowerCase().replace(/[^a-z0-9]+/g,"-")});setForm(blank)})};
 const cycleAction=async(c,kind)=>{if(askConfirmation&&!await askConfirmation({title:`${label(kind)} collection?`,message:c.name,confirmLabel:label(kind)}))return;run(()=>kind==="open"?api.openTeacherPreferenceCycle(c.id):api.closeTeacherPreferenceCycle(c.id))};
 const decide=async()=>{const{row,kind}=decision;if(!reason.trim())return;run(()=>kind==="withdraw"?api.withdrawTeacherPreference(row.id,reason,row.revision):api.reviewTeacherRestriction(row.id,kind,reason,row.revision));setDecision(null);setReason("")};
 const staffHistory=async id=>{setSelectedStaff(id);if(!id)return setHistory([]);try{const r=await api.getTeacherPreferenceStaffHistory(id);setHistory(r.data.history||[])}catch(e){setError(msg(e))}};
 return <div className="preference-workspace space-y-5"><header className="workspace-hero"><div><span className="eyebrow">Advisory evidence · human authority</span><h1>Teacher Preferences</h1><p>Collect preferences and declared restrictions, review them openly, and deliberately supply advisory evidence to Scheduler.</p></div><button disabled={busy} onClick={load}>Refresh</button></header>{error&&<div className="workspace-error">{error}</div>}{insights&&<><div className="scheduler-summary"><Summary title="Readiness" value={label(insights.readiness)}/><Summary title="Active" value={insights.counts.active}/><Summary title="Staff coverage" value={`${insights.coverage_percent}%`}/><Summary title="Pending reviews" value={insights.counts.pending_restrictions}/></div><p>{insights.narrative}</p></>}
 <div className="subtabs">{[["entries","Preferences"],["cycles","Collection cycles"],["history","Staff history"],["provider","Scheduler hand-off"]].map(([id,name])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}>{name}</button>)}</div>
 {decision&&<form className="decision-panel" onSubmit={e=>{e.preventDefault();decide()}}><div><strong>{label(decision.kind)} preference</strong><p>{decision.row.target_label}</p></div><input required autoFocus placeholder="Reason" value={reason} onChange={e=>setReason(e.target.value)}/><button className="primary">Confirm</button><button type="button" onClick={()=>setDecision(null)}>Cancel</button></form>}
 {tab==="entries"&&<><section className="scheduler-toolbar"><label>Collection cycle <select value={cycle} onChange={e=>{setPage(1);setCycle(e.target.value)}}><option value="">All cycles</option>{cycles.map(x=><option key={x.id} value={x.id}>{x.name} ({label(x.status)})</option>)}</select></label></section><form className="inline-create" onSubmit={add}><Field label="Staff ID" value={form.staff_id} onChange={e=>setForm({...form,staff_id:e.target.value})} required/><label className="field"><span>Domain</span><select value={form.domain} onChange={e=>setForm({...form,domain:e.target.value})}>{(contract?.domains||["subject","grade","activity","role","time","location"]).map(x=><option key={x}>{x}</option>)}</select></label><label className="field"><span>Stance</span><select value={form.stance} onChange={e=>setForm({...form,stance:e.target.value})}>{(contract?.stances||["prefer","avoid","declared_restriction"]).map(x=><option key={x}>{label(x)}</option>)}</select></label><Field label="Preference or restriction" value={form.target_label} onChange={e=>setForm({...form,target_label:e.target.value})} required/><Field label="Rank" type="number" min="1" value={form.rank} onChange={e=>setForm({...form,rank:+e.target.value})}/><Field label="Rationale" value={form.rationale} onChange={e=>setForm({...form,rationale:e.target.value})}/><button className="primary" disabled={!cycles.find(x=>String(x.id)===cycle&&x.status==="open")}>Add draft</button></form><PreferenceTable rows={rows} page={page} onSubmit={r=>run(()=>api.submitTeacherPreference(r.id,r.revision))} onDecision={(row,kind)=>{setDecision({row,kind});setReason("")}}/><Pagination page={page} pageSize={50} total={total} onPageChange={setPage}/></>}
 {tab==="cycles"&&<div className="split-workspace"><form className="form-card" onSubmit={createCycle}><h3>New collection cycle</h3><label className="field"><span>Academic year</span><select required value={cycleForm.year||""} onChange={e=>setCycleForm({...cycleForm,year:e.target.value})}><option value="">Select…</option>{years.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><Field label="Cycle name" value={cycleForm.name||""} onChange={e=>setCycleForm({...cycleForm,name:e.target.value})} required/><Field label="Opens" type="datetime-local" value={cycleForm.opens_at||""} onChange={e=>setCycleForm({...cycleForm,opens_at:e.target.value})}/><Field label="Closes" type="datetime-local" value={cycleForm.closes_at||""} onChange={e=>setCycleForm({...cycleForm,closes_at:e.target.value})}/><button className="primary">Create draft cycle</button></form><div className="record-list">{cycles.map(x=><div key={x.id}><span><strong>{x.name}</strong><small>{label(x.status)}</small></span>{x.status==="open"?<button onClick={()=>cycleAction(x,"close")}>Close</button>:<button onClick={()=>cycleAction(x,"open")}>Open</button>}</div>)}</div></div>}
 {tab==="history"&&<><label className="field student-picker"><span>Staff member</span><select value={selectedStaff} onChange={e=>staffHistory(e.target.value)}><option value="">Select from recorded staff…</option>{[...new Set(rows.map(x=>x.staff_id))].map(x=><option key={x}>{x}</option>)}</select></label><div className="record-list">{history.map((x,i)=><div key={x.id}><span><strong>{i+1}. {x.target_label}</strong><small>{label(x.domain)} · {label(x.stance)} · revision {x.revision}</small></span><span>{label(x.status)}</span></div>)}</div></>}
 {tab==="provider"&&<><section className="callout"><strong>Scheduler receives advice, not decisions.</strong><p>Confirmed restrictions may create hard gates. Preferences only affect explainable ranking and never override qualifications or availability.</p><button className="primary" disabled={!setup||busy} onClick={()=>run(()=>api.syncTeacherPreferences(setup.id))}>Synchronise with Scheduler</button></section><div className="record-list">{providers.map((x,i)=><div key={x.external_key}><span><strong>{i+1}. {x.payload?.target_label||x.external_key}</strong><small>{x.payload?.staff_id} · advisory weight {x.payload?.advisory_weight??0}</small></span><span>{label(x.status)}</span></div>)}</div></>}
 </div>;
}
function PreferenceTable({rows,page,onSubmit,onDecision}){return <div className="table-card"><table><thead><tr>{["#","Staff","Domain","Preference","Stance","Rank","Review","Status","Actions"].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id} className={r.review_state==="pending"?"row-alert":""}><td>{(page-1)*50+i+1}</td><td>{r.staff_id}</td><td>{label(r.domain)}</td><td><strong>{r.target_label}</strong><small>{r.rationale}</small></td><td>{label(r.stance)}</td><td>{r.rank||"—"}</td><td>{label(r.review_state)}</td><td>{label(r.status)}</td><td className="header-actions">{r.status==="draft"&&<button onClick={()=>onSubmit(r)}>Submit</button>}{r.status==="active"&&<button onClick={()=>onDecision(r,"withdraw")}>Withdraw</button>}{r.status==="active"&&r.review_state==="pending"&&<><button onClick={()=>onDecision(r,"confirmed")}>Confirm</button><button onClick={()=>onDecision(r,"declined")}>Decline</button></>}</td></tr>)}</tbody></table></div>}
function Summary({value,title}){return <article><strong>{value??0}</strong><span>{title}</span></article>}
