'use strict';
var fs=require('fs'),path=require('path'),crypto=require('crypto'),appScope=require('../../shared/services/appScope');
var MAX_BYTES=10*1024*1024,DENIED_MIME=['text/html','application/javascript','text/javascript','application/x-msdownload','application/x-executable'],DENIED_EXT=['.exe','.com','.bat','.cmd','.ps1','.js','.mjs','.html','.htm','.svg'];
function scope(req){return appScope.fromRequest(req);} function bad(message,code,statusCode){return{success:false,statusCode:statusCode||400,error:{code:code||'VALIDATION_ERROR',message:message}};}
function get(ctx,id,s){return ctx.db.query('SELECT * FROM documents WHERE id=? AND app_id=?',[id,s]).rows[0];}
function storageRoot(){return path.resolve((process.env.DB_PATH||path.resolve(__dirname,'../../data/timsys.sqlite'))+'.documents');}
function audit(ctx,action,req,oldValue,newValue,id){ctx.db.query('INSERT INTO audit_log (timestamp,user_id,action,entity_type,entity_id,old_value,new_value,ip_address) VALUES (?,?,?,?,?,?,?,?)',[Date.now(),String(req.user.id),action,'document',String(id),oldValue?JSON.stringify(oldValue):null,newValue?JSON.stringify(newValue):null,null]);}
function hydrate(ctx,row){row.links=ctx.db.query('SELECT * FROM document_links WHERE document_id=? ORDER BY id',[row.id]).rows;row.versions=ctx.db.query('SELECT id,document_id,version_number,original_filename,mime_type,byte_size,sha256,notes,uploaded_by,created_at FROM document_versions WHERE document_id=? ORDER BY version_number DESC',[row.id]).rows;return row;}
function boot(ctx){fs.mkdirSync(storageRoot(),{recursive:true});ctx.log.info('documents booting',{module:'documents'});} function teardown(){}
async function list(req,ctx){var s=scope(req),where=['app_id=?'],params=[s];['status','category'].forEach(function(k){if(req.query[k]){where.push(k+'=?');params.push(req.query[k]);}});if(req.query.subject_component){where.push('EXISTS (SELECT 1 FROM document_links l WHERE l.document_id=documents.id AND l.subject_component=? AND l.subject_type=? AND l.subject_id=?)');params.push(req.query.subject_component,req.query.subject_type||'',req.query.subject_id||'');}if(req.query.q){where.push('(title LIKE ? OR description LIKE ? OR category LIKE ?)');var q='%'+req.query.q+'%';params.push(q,q,q);}var page=Math.max(1,Number(req.query.page)||1),limit=Math.min(50,Math.max(1,Number(req.query.limit)||50)),clause=' WHERE '+where.join(' AND '),total=ctx.db.query('SELECT COUNT(*) AS total FROM documents'+clause,params).rows[0].total;var rows=ctx.db.query('SELECT * FROM documents'+clause+' ORDER BY updated_at DESC,id DESC LIMIT ? OFFSET ?',params.concat([limit,(page-1)*limit])).rows.map(function(row){return hydrate(ctx,row);});return{success:true,documents:rows,total:Number(total),page:page,limit:limit,maxFileBytes:MAX_BYTES};}
async function create(req,ctx){var b=req.body||{},s=scope(req);if(!String(b.title||'').trim())return bad('Document title is required');var result=ctx.db.query('INSERT INTO documents (app_id,title,description,category,created_by) VALUES (?,?,?,?,?)',[s,String(b.title).trim(),b.description||null,String(b.category||'general').trim()||'general',String(req.user.id)]);var row=hydrate(ctx,get(ctx,result.lastInsertRowid,s));audit(ctx,'documents.create',req,null,row,row.id);ctx.events.publish('documents.created',{entityType:'document',entityId:row.id,record:row,__module:'documents'});return{success:true,document:row};}
async function update(req,ctx){var s=scope(req),row=get(ctx,req.params.id,s),b=req.body||{};if(!row)return bad('Document not found','NOT_FOUND',404);if(b.title!==undefined&&!String(b.title).trim())return bad('Document title is required');ctx.db.query("UPDATE documents SET title=?,description=?,category=?,updated_at=datetime('now') WHERE id=?",[b.title===undefined?row.title:String(b.title).trim(),b.description===undefined?row.description:b.description,b.category===undefined?row.category:String(b.category).trim()||'general',row.id]);var next=hydrate(ctx,get(ctx,row.id,s));audit(ctx,'documents.update',req,row,next,row.id);ctx.events.publish('documents.updated',{entityId:row.id,record:next,__module:'documents'});return{success:true,document:next};}
async function setStatus(req,ctx){var s=scope(req),row=get(ctx,req.params.id,s),to=req.body&&req.body.status;if(!row)return bad('Document not found','NOT_FOUND',404);if(!['active','withdrawn'].includes(to))return bad('Invalid document status');ctx.db.query("UPDATE documents SET status=?,updated_at=datetime('now') WHERE id=?",[to,row.id]);var next=hydrate(ctx,get(ctx,row.id,s));audit(ctx,'documents.status',req,row,next,row.id);ctx.events.publish(to==='withdrawn'?'documents.withdrawn':'documents.reinstated',{entityId:row.id,__module:'documents'});return{success:true,document:next};}
async function addLink(req,ctx){var s=scope(req),row=get(ctx,req.params.id,s),b=req.body||{};if(!row)return bad('Document not found','NOT_FOUND',404);if(!b.subject_component||!b.subject_type||!b.subject_id)return bad('Complete subject reference is required');try{var result=ctx.db.query('INSERT INTO document_links (document_id,subject_component,subject_type,subject_id,link_role,created_by) VALUES (?,?,?,?,?,?)',[row.id,b.subject_component,b.subject_type,String(b.subject_id),b.link_role||'attachment',String(req.user.id)]);audit(ctx,'documents.link',req,null,b,row.id);ctx.events.publish('documents.linked',{entityId:row.id,linkId:result.lastInsertRowid,subject:b,__module:'documents'});return{success:true,document:hydrate(ctx,get(ctx,row.id,s))};}catch(e){if(String(e.message).includes('UNIQUE'))return bad('Document link already exists','LINK_EXISTS',409);throw e;}}
async function removeLink(req,ctx){var s=scope(req),row=get(ctx,req.params.id,s);if(!row)return bad('Document not found','NOT_FOUND',404);var link=ctx.db.query('SELECT * FROM document_links WHERE id=? AND document_id=?',[req.params.linkId,row.id]).rows[0];if(!link)return bad('Document link not found','NOT_FOUND',404);ctx.db.query('DELETE FROM document_links WHERE id=?',[link.id]);audit(ctx,'documents.unlink',req,link,null,row.id);ctx.events.publish('documents.unlinked',{entityId:row.id,linkId:link.id,__module:'documents'});return{success:true,document:hydrate(ctx,get(ctx,row.id,s))};}
async function addVersion(req,ctx){var s=scope(req),row=get(ctx,req.params.id,s),b=req.body||{};if(!row)return bad('Document not found','NOT_FOUND',404);var filename=path.basename(String(b.filename||'')).trim(),mime=String(b.mime_type||'application/octet-stream').toLowerCase();if(!filename||!b.content_base64)return bad('Filename and file content are required');if(DENIED_MIME.includes(mime)||DENIED_EXT.includes(path.extname(filename).toLowerCase()))return bad('Executable or active web content is not accepted','UNSAFE_FILE_TYPE');if(!/^[A-Za-z0-9+/]*={0,2}$/.test(b.content_base64)||b.content_base64.length%4!==0)return bad('File content is not valid base64','INVALID_FILE_CONTENT');var bytes=Buffer.from(b.content_base64,'base64');if(!bytes.length||bytes.length>MAX_BYTES)return bad('File must be between 1 byte and 10 MiB','FILE_SIZE_LIMIT',413);var key=crypto.randomUUID()+'.bin',target=path.join(storageRoot(),key),hash=crypto.createHash('sha256').update(bytes).digest('hex'),number=Number(ctx.db.query('SELECT COALESCE(MAX(version_number),0)+1 AS number FROM document_versions WHERE document_id=?',[row.id]).rows[0].number);fs.mkdirSync(storageRoot(),{recursive:true});fs.writeFileSync(target,bytes,{flag:'wx'});try{var result=ctx.db.query('INSERT INTO document_versions (document_id,version_number,original_filename,mime_type,byte_size,sha256,storage_key,notes,uploaded_by) VALUES (?,?,?,?,?,?,?,?,?)',[row.id,number,filename,mime,bytes.length,hash,key,b.notes||null,String(req.user.id)]);ctx.db.query("UPDATE documents SET current_version_id=?,updated_at=datetime('now') WHERE id=?",[result.lastInsertRowid,row.id]);var next=hydrate(ctx,get(ctx,row.id,s));audit(ctx,'documents.version.add',req,null,next.versions[0],row.id);ctx.events.publish('documents.version_added',{entityId:row.id,versionId:result.lastInsertRowid,versionNumber:number,sha256:hash,__module:'documents'});return{success:true,document:next};}catch(e){try{fs.unlinkSync(target);}catch(ignore){}throw e;}}
async function content(req,ctx){var s=scope(req),row=get(ctx,req.params.id,s);if(!row)return bad('Document not found','NOT_FOUND',404);var version=ctx.db.query('SELECT * FROM document_versions WHERE id=? AND document_id=?',[req.params.versionId,row.id]).rows[0];if(!version)return bad('Document version not found','NOT_FOUND',404);var target=path.resolve(storageRoot(),version.storage_key);if(!target.startsWith(storageRoot()+path.sep)||!fs.existsSync(target))return bad('Stored file is unavailable','FILE_UNAVAILABLE',410);var bytes=fs.readFileSync(target),hash=crypto.createHash('sha256').update(bytes).digest('hex');if(hash!==version.sha256)return bad('Stored file failed its integrity check','FILE_INTEGRITY_FAILURE',409);return{success:true,filename:version.original_filename,mimeType:version.mime_type,byteSize:version.byte_size,sha256:version.sha256,contentBase64:bytes.toString('base64')};}
async function history(req,ctx){var row=get(ctx,req.params.id,scope(req));if(!row)return bad('Document not found','NOT_FOUND',404);return{success:true,document:hydrate(ctx,row),audit:ctx.db.query('SELECT * FROM audit_log WHERE entity_type=? AND entity_id=? ORDER BY timestamp DESC LIMIT 100',['document',String(row.id)]).rows};}
module.exports={boot:boot,teardown:teardown,list:list,create:create,update:update,setStatus:setStatus,addLink:addLink,removeLink:removeLink,addVersion:addVersion,content:content,history:history};
