'use strict';

const appScope=require('../../shared/services/appScope');

function scope(req){return appScope.fromRequest(req);}
function text(value){return String(value==null?'':value).trim();}
function norm(value){return text(value).toLocaleLowerCase().replace(/[^\p{L}\p{N}]+/gu,'');}
function number(value,fallback){const n=Number(value);return Number.isFinite(n)?n:fallback;}
function bad(message,code,statusCode,details){return{success:false,statusCode:statusCode||400,error:{code:code||'VALIDATION_ERROR',message,details}};}
function parse(value,fallback){try{return JSON.parse(value);}catch(_){return fallback;}}
function page(req){return{page:Math.max(1,number(req.query.page,1)),limit:Math.min(50,Math.max(1,number(req.query.limit,50)))};}
function response(ctx,appId,id){return ctx.db.query('SELECT * FROM programme_manager_responses WHERE app_id=? AND id=?',[appId,id]).rows[0];}
function resolution(ctx,responseId){return ctx.db.query('SELECT * FROM programme_manager_identity_resolutions WHERE response_id=?',[responseId]).rows[0];}
function student(ctx,id){return ctx.db.query('SELECT * FROM students WHERE id=? OR student_id=?',[id,String(id)]).rows[0];}
function candidates(ctx,resolutionId,revision){return ctx.db.query('SELECT * FROM programme_manager_identity_candidates WHERE resolution_id=? AND resolution_revision=? ORDER BY score DESC,display_name,student_record_id',[resolutionId,revision]).rows.map(x=>{x.signals=parse(x.signals_json,[]);delete x.signals_json;return x;});}
function hydrate(ctx,row){if(!row)return row;row.evidence=parse(row.evidence_json,{});delete row.evidence_json;row.candidates=candidates(ctx,row.id,row.revision);return row;}
function audit(ctx,row,action,fromRevision,actor,reason){ctx.db.query('INSERT INTO programme_manager_identity_audit(app_id,programme_id,survey_id,response_id,resolution_id,action,from_revision,to_revision,snapshot_json,actor_id,reason) VALUES(?,?,?,?,?,?,?,?,?,?,?)',[row.app_id,row.programme_id,row.survey_id,row.response_id,row.id,action,fromRevision,row.revision,JSON.stringify(hydrate(ctx,{...row})),String(actor),reason||null]);}
function auditDuplicate(ctx,row,action,fromRevision,actor,reason){ctx.db.query('INSERT INTO programme_manager_duplicate_audit(app_id,survey_id,duplicate_case_id,action,from_revision,to_revision,snapshot_json,actor_id,reason) VALUES(?,?,?,?,?,?,?,?,?)',[row.app_id,row.survey_id,row.id,action,fromRevision,row.revision,JSON.stringify(hydrateDuplicate({...row})),String(actor),reason||null]);}
function identityFromResponse(row){const raw=parse(row.raw_identity_json,{}),answers=parse(row.answers_json,{});return{student_id:text(raw.student_id||raw.canonical_student_id||answers.identity_student),first_name:text(raw.first_name||raw.given_name),last_name:text(raw.last_name||raw.family_name),preferred_name:text(raw.preferred_name),date_of_birth:text(raw.date_of_birth||raw.dob),grade_level:text(raw.grade_id||raw.grade_level||answers.identity_grade),homeroom:text(raw.class_id||raw.homeroom||answers.identity_class)};}
function scoreStudent(identity,value){const signals=[];let score=0,exact=false;const signal=(field,points)=>{score+=points;signals.push({field,points});};if(identity.student_id&&norm(identity.student_id)===norm(value.student_id)){signal('student_id',100);exact=true;}else{if(identity.date_of_birth&&identity.date_of_birth===value.date_of_birth)signal('date_of_birth',35);if(identity.last_name&&norm(identity.last_name)===norm(value.last_name))signal('last_name',30);if(identity.first_name&&norm(identity.first_name)===norm(value.first_name))signal('first_name',20);else if(identity.first_name&&norm(identity.first_name)===norm(value.preferred_name))signal('preferred_name',20);if(identity.grade_level&&norm(identity.grade_level)===norm(value.current_grade_level))signal('grade_level',10);if(identity.homeroom&&norm(identity.homeroom)===norm(value.homeroom))signal('homeroom',10);}return{score:exact?100:Math.min(99,score),exact,signals};}
function buildCandidates(ctx,identity){return ctx.db.query("SELECT * FROM students WHERE enrollment_status<>'expelled' ORDER BY last_name,first_name,id").rows.map(value=>({student:value,result:scoreStudent(identity,value)})).filter(x=>x.result.score>=30).sort((a,b)=>b.result.score-a.result.score||a.student.id-b.student.id).slice(0,10);}
function ensureResolution(ctx,row){let saved=resolution(ctx,row.id);if(!saved){ctx.db.query('INSERT INTO programme_manager_identity_resolutions(app_id,programme_id,survey_id,response_id) VALUES(?,?,?,?)',[row.app_id,row.programme_id,row.survey_id,row.id]);saved=resolution(ctx,row.id);}return saved;}
function updateDuplicateCase(ctx,row){if(!row.student_record_id)return null;const matches=ctx.db.query("SELECT r.response_id,p.priority_timestamp FROM programme_manager_identity_resolutions r JOIN programme_manager_responses p ON p.id=r.response_id WHERE r.app_id=? AND r.survey_id=? AND r.student_record_id=? AND r.status='matched' AND p.status<>'withdrawn' ORDER BY p.priority_timestamp,p.id",[row.app_id,row.survey_id,row.student_record_id]).rows,ids=matches.map(x=>String(x.response_id)),existing=ctx.db.query('SELECT * FROM programme_manager_duplicate_cases WHERE survey_id=? AND student_record_id=?',[row.survey_id,row.student_record_id]).rows[0];if(matches.length<2){if(existing){ctx.db.query("UPDATE programme_manager_duplicate_cases SET response_ids_json=?,status='resolved',disposition='allow_multiple',primary_response_id=NULL,excluded_response_ids_json='[]',revision=revision+1,resolved_by='system:identity_refresh',resolved_at=?,resolution_reason='No duplicate responses remain after identity reconciliation',updated_at=datetime('now') WHERE id=?",[JSON.stringify(ids),new Date().toISOString(),existing.id]);const saved=ctx.db.query('SELECT * FROM programme_manager_duplicate_cases WHERE id=?',[existing.id]).rows[0];auditDuplicate(ctx,saved,'automatically_cleared',existing.revision,'system:identity_refresh','No duplicate responses remain after identity reconciliation');return saved;}return null;}if(existing){const previous=parse(existing.response_ids_json,[]).map(String),changed=ids.some(id=>!previous.includes(id))||previous.some(id=>!ids.includes(id));if(!changed)return existing;ctx.db.query("UPDATE programme_manager_duplicate_cases SET response_ids_json=?,status='open',disposition=NULL,primary_response_id=NULL,excluded_response_ids_json='[]',revision=revision+1,updated_at=datetime('now') WHERE id=?",[JSON.stringify(ids),existing.id]);const saved=ctx.db.query('SELECT * FROM programme_manager_duplicate_cases WHERE id=?',[existing.id]).rows[0];auditDuplicate(ctx,saved,'reopened',existing.revision,'system:identity_refresh','Matched response membership changed');return saved;}const result=ctx.db.query('INSERT INTO programme_manager_duplicate_cases(app_id,programme_id,survey_id,student_record_id,canonical_student_id,response_ids_json) VALUES(?,?,?,?,?,?)',[row.app_id,row.programme_id,row.survey_id,row.student_record_id,row.canonical_student_id,JSON.stringify(ids)]),saved=ctx.db.query('SELECT * FROM programme_manager_duplicate_cases WHERE id=?',[result.lastInsertRowid]).rows[0];auditDuplicate(ctx,saved,'opened',0,'system:identity_refresh','Multiple responses matched the same student');return saved;}
function reconcileOne(ctx,row,actor){const old=ensureResolution(ctx,row),identity=identityFromResponse(row),ranked=buildCandidates(ctx,identity),exact=ranked.filter(x=>x.result.exact),nextRevision=old.revision+1;let status='unresolved',matched=null,method='no_match',confidence=ranked[0]?ranked[0].result.score:0;if(exact.length===1){status='matched';matched=exact[0].student;method='exact_canonical_id';confidence=100;}else if(ranked.length){status='ambiguous';method='candidate_recommendation';}ctx.db.transaction(db=>{db.query("UPDATE programme_manager_identity_resolutions SET status=?,student_record_id=?,canonical_student_id=?,method=?,confidence=?,evidence_json=?,revision=revision+1,confirmed_by=?,confirmed_at=?,confirmation_reason=?,updated_at=datetime('now') WHERE id=? AND revision=?",[status,matched&&matched.id,matched&&matched.student_id,method,confidence,JSON.stringify({input:identity,candidate_count:ranked.length,decision_authority:status==='matched'?'exact_unique_identifier':'authorised_human'}),status==='matched'?'system:exact_id':null,status==='matched'?new Date().toISOString():null,status==='matched'?'Unique exact canonical student ID':null,old.id,old.revision]);for(const item of ranked)db.query('INSERT INTO programme_manager_identity_candidates(resolution_id,resolution_revision,student_record_id,canonical_student_id,display_name,score,signals_json) VALUES(?,?,?,?,?,?,?)',[old.id,nextRevision,item.student.id,item.student.student_id,[item.student.preferred_name||item.student.first_name,item.student.last_name].join(' '),item.result.score,JSON.stringify(item.result.signals)]);db.query('UPDATE programme_manager_responses SET identity_resolution_status=?,updated_at=datetime(\'now\') WHERE id=?',[status,row.id]);const saved=db.query('SELECT * FROM programme_manager_identity_resolutions WHERE id=?',[old.id]).rows[0];audit({db},saved,'evaluated',old.revision,actor,status==='matched'?'Exact canonical identifier matched':'Identity candidates evaluated');});const saved=resolution(ctx,row.id);if(old.student_record_id&&old.student_record_id!==saved.student_record_id)updateDuplicateCase(ctx,old);const duplicate=updateDuplicateCase(ctx,saved);ctx.events.publish('programme_identity.evaluated',{entityId:saved.id,response_id:row.id,status:saved.status,duplicate_case_id:duplicate&&duplicate.id,source:'programme_manager',__module:'programme_manager'});return hydrate(ctx,saved);}

async function reconcileSurvey(req,ctx){const appId=scope(req),surveyId=Number(req.params.surveyId),limit=Math.min(500,Math.max(1,number((req.body||{}).limit,100))),rows=ctx.db.query("SELECT * FROM programme_manager_responses WHERE app_id=? AND survey_id=? AND status<>'withdrawn' AND identity_resolution_status='pending' ORDER BY id LIMIT ?",[appId,surveyId,limit]).rows;if(!ctx.db.query('SELECT id FROM programme_manager_surveys WHERE app_id=? AND id=?',[appId,surveyId]).rows[0])return bad('Survey not found','NOT_FOUND',404);const resolutions=rows.map(row=>reconcileOne(ctx,row,req.user.id)),counts={matched:0,ambiguous:0,unresolved:0};for(const item of resolutions)counts[item.status]=(counts[item.status]||0)+1;return{success:true,processed:rows.length,counts,resolutions,human_review_required:counts.ambiguous+counts.unresolved};}
async function reconcileResponse(req,ctx){const row=response(ctx,scope(req),req.params.responseId);if(!row)return bad('Response not found','NOT_FOUND',404);if(row.status==='withdrawn')return bad('Withdrawn responses cannot be reconciled','INVALID_STATE',409);return{success:true,resolution:reconcileOne(ctx,row,req.user.id)};}
async function getIdentityQueue(req,ctx){const appId=scope(req),pg=page(req),where=["r.app_id=?","p.status<>'withdrawn'"],params=[appId];if(req.query.survey_id){where.push('r.survey_id=?');params.push(req.query.survey_id);}if(req.query.status){where.push('r.status=?');params.push(req.query.status);}else where.push("r.status IN ('ambiguous','unresolved')");const clause=' WHERE '+where.join(' AND '),total=Number(ctx.db.query('SELECT COUNT(*) n FROM programme_manager_identity_resolutions r JOIN programme_manager_responses p ON p.id=r.response_id'+clause,params).rows[0].n),rows=ctx.db.query('SELECT r.* FROM programme_manager_identity_resolutions r JOIN programme_manager_responses p ON p.id=r.response_id'+clause+' ORDER BY r.updated_at,r.id LIMIT ? OFFSET ?',params.concat([pg.limit,(pg.page-1)*pg.limit])).rows.map(x=>hydrate(ctx,x));return{success:true,resolutions:rows,total,...pg};}
async function decideIdentity(req,ctx){const appId=scope(req),row=response(ctx,appId,req.params.responseId),body=req.body||{};if(!row)return bad('Response not found','NOT_FOUND',404);const old=ensureResolution(ctx,row);if(body.expected_revision==null||Number(body.expected_revision)!==Number(old.revision))return bad('Identity resolution was changed by another user; reload before continuing','REVISION_CONFLICT',409);if(body.confirm!==true||!text(body.reason))return bad('Explicit human confirmation and a reason are required','HUMAN_CONFIRMATION_REQUIRED',409);if(!['matched','unresolved'].includes(body.decision))return bad('decision must be matched or unresolved');let matched=null;if(body.decision==='matched'){matched=student(ctx,body.student_id||body.student_record_id);if(!matched)return bad('Student not found','NOT_FOUND',404);}ctx.db.transaction(db=>{db.query("UPDATE programme_manager_identity_resolutions SET status=?,student_record_id=?,canonical_student_id=?,method='human_confirmed',confidence=?,evidence_json=?,revision=revision+1,confirmed_by=?,confirmed_at=?,confirmation_reason=?,updated_at=datetime('now') WHERE id=? AND revision=?",[body.decision,matched&&matched.id,matched&&matched.student_id,matched?100:0,JSON.stringify({decision_authority:'authorised_human',selected_student_id:matched&&matched.student_id}),String(req.user.id),new Date().toISOString(),text(body.reason),old.id,old.revision]);db.query('UPDATE programme_manager_responses SET identity_resolution_status=?,updated_at=datetime(\'now\') WHERE id=?',[body.decision,row.id]);const saved=db.query('SELECT * FROM programme_manager_identity_resolutions WHERE id=?',[old.id]).rows[0];audit({db},saved,'human_decision',old.revision,req.user.id,text(body.reason));});const saved=resolution(ctx,row.id);if(old.student_record_id&&old.student_record_id!==saved.student_record_id)updateDuplicateCase(ctx,old);const duplicate=updateDuplicateCase(ctx,saved);ctx.events.publish('programme_identity.confirmed',{entityId:saved.id,response_id:row.id,status:saved.status,student_id:saved.canonical_student_id,duplicate_case_id:duplicate&&duplicate.id,source:'programme_manager',__module:'programme_manager'});return{success:true,resolution:hydrate(ctx,saved),duplicate_case:duplicate&&hydrateDuplicate(duplicate),human_confirmation:true};}
function hydrateDuplicate(row){if(!row)return row;row.response_ids=parse(row.response_ids_json,[]);row.excluded_response_ids=parse(row.excluded_response_ids_json,[]);delete row.response_ids_json;delete row.excluded_response_ids_json;return row;}
async function listDuplicateCases(req,ctx){const appId=scope(req),pg=page(req),where=['app_id=?'],params=[appId];if(req.query.survey_id){where.push('survey_id=?');params.push(req.query.survey_id);}if(req.query.status){where.push('status=?');params.push(req.query.status);}const clause=' WHERE '+where.join(' AND '),total=Number(ctx.db.query('SELECT COUNT(*) n FROM programme_manager_duplicate_cases'+clause,params).rows[0].n),cases=ctx.db.query('SELECT * FROM programme_manager_duplicate_cases'+clause+' ORDER BY status,id LIMIT ? OFFSET ?',params.concat([pg.limit,(pg.page-1)*pg.limit])).rows.map(hydrateDuplicate);return{success:true,cases,total,...pg};}
async function decideDuplicateCase(req,ctx){const appId=scope(req),old=ctx.db.query('SELECT * FROM programme_manager_duplicate_cases WHERE app_id=? AND id=?',[appId,req.params.caseId]).rows[0],body=req.body||{};if(!old)return bad('Duplicate case not found','NOT_FOUND',404);if(body.expected_revision==null||Number(body.expected_revision)!==Number(old.revision))return bad('Duplicate case was changed by another user; reload before continuing','REVISION_CONFLICT',409);if(body.confirm!==true||!text(body.reason))return bad('Explicit human confirmation and a reason are required','HUMAN_CONFIRMATION_REQUIRED',409);if(!['primary_only','allow_multiple'].includes(body.disposition))return bad('disposition must be primary_only or allow_multiple');const ids=parse(old.response_ids_json,[]).map(String);let primary=null,excluded=[];if(body.disposition==='primary_only'){primary=String(body.primary_response_id||'');if(!ids.includes(primary))return bad('Primary response must belong to this duplicate case');excluded=ids.filter(id=>id!==primary);}ctx.db.query("UPDATE programme_manager_duplicate_cases SET status='resolved',disposition=?,primary_response_id=?,excluded_response_ids_json=?,revision=revision+1,resolved_by=?,resolved_at=?,resolution_reason=?,updated_at=datetime('now') WHERE id=? AND revision=?",[body.disposition,primary||null,JSON.stringify(excluded),String(req.user.id),new Date().toISOString(),text(body.reason),old.id,old.revision]);const saved=ctx.db.query('SELECT * FROM programme_manager_duplicate_cases WHERE id=?',[old.id]).rows[0];auditDuplicate(ctx,saved,'resolved',old.revision,req.user.id,text(body.reason));ctx.events.publish('programme_duplicate.resolved',{entityId:saved.id,survey_id:saved.survey_id,student_id:saved.canonical_student_id,disposition:saved.disposition,source:'programme_manager',__module:'programme_manager'});return{success:true,case:hydrateDuplicate(saved),human_confirmation:true,responses_preserved:true};}
async function duplicateHistory(req,ctx){const appId=scope(req),saved=ctx.db.query('SELECT * FROM programme_manager_duplicate_cases WHERE app_id=? AND id=?',[appId,req.params.caseId]).rows[0],pg=page(req);if(!saved)return bad('Duplicate case not found','NOT_FOUND',404);const total=Number(ctx.db.query('SELECT COUNT(*) n FROM programme_manager_duplicate_audit WHERE app_id=? AND duplicate_case_id=?',[appId,saved.id]).rows[0].n),history=ctx.db.query('SELECT * FROM programme_manager_duplicate_audit WHERE app_id=? AND duplicate_case_id=? ORDER BY id DESC LIMIT ? OFFSET ?',[appId,saved.id,pg.limit,(pg.page-1)*pg.limit]).rows.map(x=>{x.snapshot=parse(x.snapshot_json,{});delete x.snapshot_json;return x;});return{success:true,history,total,...pg};}
async function identityHistory(req,ctx){const appId=scope(req),row=response(ctx,appId,req.params.responseId),pg=page(req);if(!row)return bad('Response not found','NOT_FOUND',404);const total=Number(ctx.db.query('SELECT COUNT(*) n FROM programme_manager_identity_audit WHERE app_id=? AND response_id=?',[appId,row.id]).rows[0].n),history=ctx.db.query('SELECT * FROM programme_manager_identity_audit WHERE app_id=? AND response_id=? ORDER BY id DESC LIMIT ? OFFSET ?',[appId,row.id,pg.limit,(pg.page-1)*pg.limit]).rows.map(x=>{x.snapshot=parse(x.snapshot_json,{});delete x.snapshot_json;return x;});return{success:true,history,total,...pg};}

module.exports={reconcileSurvey,reconcileResponse,getIdentityQueue,decideIdentity,listDuplicateCases,decideDuplicateCase,duplicateHistory,identityHistory};
