'use strict';

const appScope=require('../../shared/services/appScope');
const contract=require('../../contracts/programmeManager');

function scope(req){return appScope.fromRequest(req);}
function text(value){return String(value==null?'':value).trim();}
function bad(message,code,statusCode,details){return{success:false,statusCode:statusCode||400,error:{code:code||'VALIDATION_ERROR',message,details}};}
function parse(value,fallback){try{return JSON.parse(value);}catch(_){return fallback;}}
function programme(ctx,appId,id){return ctx.db.query('SELECT * FROM programme_manager_programmes WHERE app_id=? AND id=?',[appId,id]).rows[0];}
function raw(ctx,appId,id){return ctx.db.query('SELECT * FROM programme_manager_setup WHERE app_id=? AND programme_id=?',[appId,id]).rows[0];}
function readiness(setup){const completed=new Set(setup.completed_steps||parse(setup.completed_steps_json,[])),missing=contract.SETUP_STEPS.filter(x=>!completed.has(x));return{ready:!missing.length,completed:contract.SETUP_STEPS.length-missing.length,total:contract.SETUP_STEPS.length,percent:Math.round((contract.SETUP_STEPS.length-missing.length)*100/contract.SETUP_STEPS.length),missing_steps:missing,human_confirmation_required:true};}
function hydrate(row){if(!row)return row;for(const step of contract.SETUP_STEPS){row[step]=parse(row[step+'_json'],null);delete row[step+'_json'];}row.completed_steps=parse(row.completed_steps_json,[]);delete row.completed_steps_json;row.readiness=readiness(row);return row;}
function ensure(ctx,appId,programmeId){let row=raw(ctx,appId,programmeId);if(!row){ctx.db.query('INSERT INTO programme_manager_setup(app_id,programme_id) VALUES(?,?)',[appId,programmeId]);row=raw(ctx,appId,programmeId);}return row;}
function audit(ctx,appId,row,action,step,fromRevision,actor,reason){ctx.db.query('INSERT INTO programme_manager_setup_audit(app_id,programme_id,setup_id,action,step,from_revision,to_revision,snapshot_json,actor_id,reason) VALUES(?,?,?,?,?,?,?,?,?,?)',[appId,row.programme_id,row.id,action,step||null,fromRevision,row.revision,JSON.stringify(hydrate({...row})),String(actor),reason||null]);}
function nextStep(completed){return contract.SETUP_STEPS.find(x=>!completed.includes(x))||'review';}
async function scheduler(ctx,name,req){const descriptor=ctx.functionRegistry.get(name);if(!descriptor||typeof descriptor.implementation!=='function')return bad('Scheduler programme-window capability is unavailable','DEPENDENCY_UNAVAILABLE',503);return descriptor.implementation(req,ctx);}

async function getSetupSchema(){return{success:true,schema:{version:1,ordered_steps:contract.SETUP_STEPS,steps:[{key:'purpose',answers:['summary','intended_outcome','programme_categories','notes'],determines:'what'},{key:'timing',answers:['scheduler_setup_id','scheduler_window_ids','delivery_notes'],determines:'when',authority:'published_scheduler'},{key:'location',answers:['strategy','requirements','notes'],determines:'where',strategies:contract.LOCATION_STRATEGIES,allocation_deferred:true},{key:'participation',answers:['participant_type','scope','respondent_mode','scope_notes'],determines:'who',scopes:contract.PARTICIPANT_SCOPES,respondent_modes:contract.RESPONDENT_MODES},{key:'governance',answers:['owner_staff_ids','submitter_roles','amendment_roles','manual_edit_roles','notes'],determines:'authority',submitter_roles:contract.SUBMITTER_ROLES,human_confirmation_required:true}],principles:{scheduler_controls_time_and_availability:true,setup_does_not_allocate:true,human_confirmation_required:true}}};}

async function getSetup(req,ctx){const appId=scope(req),p=programme(ctx,appId,req.params.id);if(!p)return bad('Programme not found','NOT_FOUND',404);return{success:true,programme:{id:p.id,name:p.name,status:p.status,revision:p.revision},setup:hydrate(ensure(ctx,appId,p.id))};}

async function validateTiming(req,ctx,value){const available=new Map();let page=1,total=0;do{const query={...req,query:{...(req.query||{}),scheduler_setup_id:String(value.scheduler_setup_id),limit:50,page}},result=await scheduler(ctx,'scheduler_listProgrammeWindows',query);if(!result||!result.success)return result||bad('Scheduler did not return programme windows','DEPENDENCY_UNAVAILABLE',503);for(const window of result.windows)available.set(String(window.id),window);total=Number(result.total)||0;page+=1;}while(available.size<total);const missing=value.scheduler_window_ids.filter(id=>!available.has(String(id)));if(missing.length)return bad('One or more selected windows are not present in the published Scheduler version','SCHEDULER_WINDOW_INVALID',409,{scheduler_window_ids:missing});const selected=value.scheduler_window_ids.map(id=>available.get(String(id)));return{success:true,fingerprint:selected.map(x=>x.fingerprint).sort().join(':'),windows:selected.map(x=>({id:String(x.id),name:x.window_name,fingerprint:x.fingerprint,schedule_version_id:x.schedule_version_id}))};}

async function putSetupStep(req,ctx){const appId=scope(req),p=programme(ctx,appId,req.params.id),step=text(req.params.step),body=req.body||{};if(!p)return bad('Programme not found','NOT_FOUND',404);if(!contract.SETUP_STEPS.includes(step))return bad('Unsupported setup step');if(!contract.canRevise(p.status))return bad('Programme setup cannot be revised from its current state','INVALID_STATE',409);const old=ensure(ctx,appId,p.id);if(body.expected_revision==null||Number(body.expected_revision)!==Number(old.revision))return bad('Setup was changed by another user; reload before continuing','REVISION_CONFLICT',409);let value;try{value=contract.validateSetupStep(step,body.answers);}catch(e){return bad(e.message);}let schedulerCheck=null;if(step==='timing'){schedulerCheck=await validateTiming(req,ctx,value);if(!schedulerCheck.success)return schedulerCheck;}const completed=[...new Set(parse(old.completed_steps_json,[]).concat(step))],current=nextStep(completed),status=completed.length===contract.SETUP_STEPS.length?'ready':'in_progress',column=step+'_json',params=[JSON.stringify(value),JSON.stringify(completed),current,status];let sql=`UPDATE programme_manager_setup SET ${column}=?,completed_steps_json=?,current_step=?,status=?,revision=revision+1,confirmed_by=NULL,confirmed_at=NULL,confirmation_reason=NULL`;
if(step==='timing'){sql+=',scheduler_fingerprint=?';params.push(schedulerCheck.fingerprint);}sql+=",updated_at=datetime('now') WHERE id=? AND revision=?";params.push(old.id,old.revision);ctx.db.query(sql,params);if(p.status==='configured')ctx.db.query("UPDATE programme_manager_programmes SET status='draft',revision=revision+1,updated_at=datetime('now') WHERE id=? AND app_id=?",[p.id,appId]);const saved=raw(ctx,appId,p.id);audit(ctx,appId,saved,'step_saved',step,old.revision,req.user.id,text(body.reason)||null);ctx.events.publish('programme.setup_step_saved',{entityId:p.id,programme_id:p.id,step,record:hydrate({...saved}),source:'programme_manager',__module:'programme_manager'});return{success:true,setup:hydrate(saved),scheduler_windows:schedulerCheck?schedulerCheck.windows:undefined};}

async function confirmSetup(req,ctx){const appId=scope(req),p=programme(ctx,appId,req.params.id),body=req.body||{};if(!p)return bad('Programme not found','NOT_FOUND',404);if(!contract.canRevise(p.status))return bad('Programme setup cannot be confirmed from its current state','INVALID_STATE',409);const old=ensure(ctx,appId,p.id),view=hydrate({...old});if(body.expected_revision==null||Number(body.expected_revision)!==Number(old.revision))return bad('Setup was changed by another user; reload before continuing','REVISION_CONFLICT',409);if(!view.readiness.ready)return bad('All setup steps must be completed before confirmation','SETUP_INCOMPLETE',409,{missing_steps:view.readiness.missing_steps});if(body.confirm!==true)return bad('Explicit human confirmation is required','HUMAN_CONFIRMATION_REQUIRED',409);if(!text(body.reason))return bad('Confirmation reason is required');const schedulerCheck=await validateTiming(req,ctx,view.timing);if(!schedulerCheck.success)return schedulerCheck;if(schedulerCheck.fingerprint!==old.scheduler_fingerprint)return bad('The selected Scheduler publication changed; review the timing step again','SCHEDULER_WINDOW_CHANGED',409);ctx.db.query("UPDATE programme_manager_setup SET status='confirmed',current_step='complete',revision=revision+1,confirmed_by=?,confirmed_at=datetime('now'),confirmation_reason=?,updated_at=datetime('now') WHERE id=? AND revision=?",[String(req.user.id),text(body.reason),old.id,old.revision]);ctx.db.query("UPDATE programme_manager_programmes SET status='configured',respondent_mode=?,revision=revision+1,updated_at=datetime('now') WHERE id=? AND app_id=?",[view.participation.respondent_mode,p.id,appId]);const configured=programme(ctx,appId,p.id),snapshot={...configured,configuration:parse(configured.configuration_json,{})};delete snapshot.configuration_json;ctx.db.query('INSERT INTO programme_manager_audit(app_id,programme_id,action,from_status,to_status,reason,revision,snapshot_json,actor_id) VALUES(?,?,?,?,?,?,?,?,?)',[appId,p.id,'configured',p.status,'configured',text(body.reason),configured.revision,JSON.stringify(snapshot),String(req.user.id)]);const saved=raw(ctx,appId,p.id);audit(ctx,appId,saved,'confirmed',null,old.revision,req.user.id,text(body.reason));ctx.events.publish('programme.configured',{entityId:p.id,programme_id:p.id,record:hydrate({...saved}),source:'programme_manager',__module:'programme_manager'});return{success:true,setup:hydrate(saved),programme:snapshot};}

async function getSetupHistory(req,ctx){const appId=scope(req),p=programme(ctx,appId,req.params.id);if(!p)return bad('Programme not found','NOT_FOUND',404);const limit=Math.min(50,Math.max(1,Number(req.query.limit)||50)),page=Math.max(1,Number(req.query.page)||1),total=Number(ctx.db.query('SELECT COUNT(*) n FROM programme_manager_setup_audit WHERE app_id=? AND programme_id=?',[appId,p.id]).rows[0].n),history=ctx.db.query('SELECT * FROM programme_manager_setup_audit WHERE app_id=? AND programme_id=? ORDER BY id DESC LIMIT ? OFFSET ?',[appId,p.id,limit,(page-1)*limit]).rows.map(x=>{x.snapshot=parse(x.snapshot_json,{});delete x.snapshot_json;return x;});return{success:true,history,total,page,limit};}

module.exports={getSetupSchema,getSetup,putSetupStep,confirmSetup,getSetupHistory};
