'use strict';
var appScope=require('../../shared/services/appScope');
var STATUSES=['pending','in_progress','blocked','completed','withdrawn'],PRIORITIES=['low','normal','high','urgent'];
function scope(req){return appScope.fromRequest(req);} function bad(message,code){return{success:false,statusCode:400,error:{code:code||'VALIDATION_ERROR',message:message}};}
function get(ctx,id,s){return ctx.db.query('SELECT * FROM tasks WHERE id=? AND app_id=?',[id,s]).rows[0];}
function audit(ctx,action,req,oldValue,newValue,id){ctx.db.query('INSERT INTO audit_log (timestamp,user_id,action,entity_type,entity_id,old_value,new_value,ip_address) VALUES (?,?,?,?,?,?,?,?)',[Date.now(),String(req.user.id),action,'task',String(id),oldValue?JSON.stringify(oldValue):null,newValue?JSON.stringify(newValue):null,null]);}
function hydrate(ctx,row){row.dependencies=ctx.db.query('SELECT d.*,t.title AS prerequisite_title,t.status AS prerequisite_status FROM task_dependencies d JOIN tasks t ON t.id=d.prerequisite_task_id WHERE d.task_id=? ORDER BY d.id',[row.id]).rows;row.blocked_by=row.dependencies.filter(function(d){return d.dependency_type==='blocks'&&d.prerequisite_status!=='completed';}).length;return row;}
function transition(ctx,row,to,reason,req){ctx.db.query('INSERT INTO task_transitions (task_id,from_status,to_status,reason,actor_id) VALUES (?,?,?,?,?)',[row.id,row.status,to,reason||null,String(req.user.id)]);}
function boot(ctx){ctx.log.info('tasks booting',{module:'tasks'});} function teardown(){}
async function list(req,ctx){var s=scope(req),where=['app_id=?'],params=[s];['status','priority','subject_component','subject_type','subject_id','responsibility_id'].forEach(function(k){if(req.query[k]){where.push(k+'=?');params.push(req.query[k]);}});if(req.query.q){where.push('(title LIKE ? OR description LIKE ? OR subject_id LIKE ?)');var q='%'+req.query.q+'%';params.push(q,q,q);}var page=Math.max(1,Number(req.query.page)||1),limit=Math.min(50,Math.max(1,Number(req.query.limit)||50)),clause=' WHERE '+where.join(' AND '),total=ctx.db.query('SELECT COUNT(*) AS total FROM tasks'+clause,params).rows[0].total;var rows=ctx.db.query("SELECT * FROM tasks"+clause+" ORDER BY CASE priority WHEN 'urgent' THEN 1 WHEN 'high' THEN 2 WHEN 'normal' THEN 3 ELSE 4 END,due_at IS NULL,due_at,id DESC LIMIT ? OFFSET ?",params.concat([limit,(page-1)*limit])).rows.map(function(row){return hydrate(ctx,row);});return{success:true,tasks:rows,total:Number(total),page:page,limit:limit};}
async function create(req,ctx){var b=req.body||{},s=scope(req);if(!String(b.title||'').trim())return bad('Task title is required');if(b.priority&&!PRIORITIES.includes(b.priority))return bad('Invalid priority');if(b.status&&!STATUSES.includes(b.status))return bad('Invalid status');if(b.responsibility_id&&!ctx.db.query('SELECT id FROM responsibilities WHERE id=? AND app_id=?',[b.responsibility_id,s]).rows[0])return bad('Responsibility must belong to this application','INVALID_RESPONSIBILITY');var result=ctx.db.query('INSERT INTO tasks (app_id,title,description,subject_component,subject_type,subject_id,responsibility_id,priority,status,starts_at,due_at,completed_at,created_by) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)',[s,String(b.title).trim(),b.description||null,b.subject_component||null,b.subject_type||null,b.subject_id?String(b.subject_id):null,b.responsibility_id||null,b.priority||'normal',b.status||'pending',b.starts_at||null,b.due_at||null,b.status==='completed'?new Date().toISOString():null,String(req.user.id)]);var row=get(ctx,result.lastInsertRowid,s);audit(ctx,'tasks.create',req,null,row,row.id);ctx.events.publish('tasks.created',{entityType:'task',entityId:row.id,record:row,__module:'tasks'});return{success:true,task:hydrate(ctx,row)};}
async function update(req,ctx){var s=scope(req),row=get(ctx,req.params.id,s),b=req.body||{};if(!row)return{success:false,statusCode:404,error:{code:'NOT_FOUND',message:'Task not found'}};if(b.title!==undefined&&!String(b.title).trim())return bad('Task title is required');if(b.priority!==undefined&&!PRIORITIES.includes(b.priority))return bad('Invalid priority');if(b.responsibility_id!==undefined&&b.responsibility_id!==null&&!ctx.db.query('SELECT id FROM responsibilities WHERE id=? AND app_id=?',[b.responsibility_id,s]).rows[0])return bad('Responsibility must belong to this application','INVALID_RESPONSIBILITY');ctx.db.query("UPDATE tasks SET title=?,description=?,subject_component=?,subject_type=?,subject_id=?,responsibility_id=?,priority=?,starts_at=?,due_at=?,updated_at=datetime('now') WHERE id=?",[b.title===undefined?row.title:String(b.title).trim(),b.description===undefined?row.description:b.description,b.subject_component===undefined?row.subject_component:b.subject_component,b.subject_type===undefined?row.subject_type:b.subject_type,b.subject_id===undefined?row.subject_id:b.subject_id,b.responsibility_id===undefined?row.responsibility_id:b.responsibility_id,b.priority===undefined?row.priority:b.priority,b.starts_at===undefined?row.starts_at:b.starts_at,b.due_at===undefined?row.due_at:b.due_at,row.id]);var next=get(ctx,row.id,s);audit(ctx,'tasks.update',req,row,next,row.id);ctx.events.publish('tasks.updated',{entityId:row.id,record:next,__module:'tasks'});return{success:true,task:hydrate(ctx,next)};}
async function setStatus(req,ctx){var s=scope(req),row=get(ctx,req.params.id,s),to=req.body&&req.body.status;if(!row)return{success:false,statusCode:404,error:{code:'NOT_FOUND',message:'Task not found'}};if(!STATUSES.includes(to))return bad('Invalid task status');if(to==='completed'){var blockers=hydrate(ctx,row).blocked_by;if(blockers)return{success:false,statusCode:409,error:{code:'PREREQUISITES_INCOMPLETE',message:'Complete blocking prerequisite tasks first',blockingCount:blockers}};}transition(ctx,row,to,req.body&&req.body.reason,req);ctx.db.query("UPDATE tasks SET status=?,completed_at=?,updated_at=datetime('now') WHERE id=?",[to,to==='completed'?new Date().toISOString():null,row.id]);var next=get(ctx,row.id,s);audit(ctx,'tasks.status',req,row,next,row.id);var channel=to==='completed'?'tasks.completed':to==='withdrawn'?'tasks.withdrawn':row.status==='withdrawn'?'tasks.reinstated':to==='in_progress'?'tasks.started':to==='blocked'?'tasks.blocked':'tasks.updated';ctx.events.publish(channel,{entityId:row.id,status:to,__module:'tasks'});return{success:true,task:hydrate(ctx,next)};}
function reaches(ctx,start,target,s,seen){if(start===target)return true;if(seen.has(start))return false;seen.add(start);var ids=ctx.db.query('SELECT d.prerequisite_task_id FROM task_dependencies d JOIN tasks t ON t.id=d.task_id WHERE d.task_id=? AND t.app_id=?',[start,s]).rows;return ids.some(function(x){return reaches(ctx,x.prerequisite_task_id,target,s,seen);});}
async function addDependency(req,ctx){var s=scope(req),row=get(ctx,req.params.id,s),b=req.body||{},prerequisite=get(ctx,b.prerequisite_task_id,s),type=b.dependency_type||'blocks';if(!row||!prerequisite)return{success:false,statusCode:404,error:{code:'NOT_FOUND',message:'Task or prerequisite task not found'}};if(!['blocks','related'].includes(type))return bad('Invalid dependency type');if(row.id===prerequisite.id||reaches(ctx,prerequisite.id,row.id,s,new Set()))return bad('Task dependencies cannot contain a cycle','DEPENDENCY_CYCLE');try{var result=ctx.db.query('INSERT INTO task_dependencies (task_id,prerequisite_task_id,dependency_type,created_by) VALUES (?,?,?,?)',[row.id,prerequisite.id,type,String(req.user.id)]);audit(ctx,'tasks.dependency.add',req,null,b,row.id);return{success:true,dependencyId:result.lastInsertRowid,task:hydrate(ctx,get(ctx,row.id,s))};}catch(e){if(String(e.message).includes('UNIQUE'))return{success:false,statusCode:409,error:{code:'DEPENDENCY_EXISTS',message:'Dependency already exists'}};throw e;}}
async function removeDependency(req,ctx){var s=scope(req),row=get(ctx,req.params.id,s);if(!row)return{success:false,statusCode:404,error:{code:'NOT_FOUND',message:'Task not found'}};var dep=ctx.db.query('SELECT * FROM task_dependencies WHERE id=? AND task_id=?',[req.params.dependencyId,row.id]).rows[0];if(!dep)return{success:false,statusCode:404,error:{code:'NOT_FOUND',message:'Dependency not found'}};ctx.db.query('DELETE FROM task_dependencies WHERE id=?',[dep.id]);audit(ctx,'tasks.dependency.remove',req,dep,null,row.id);return{success:true,task:hydrate(ctx,get(ctx,row.id,s))};}
async function history(req,ctx){var row=get(ctx,req.params.id,scope(req));if(!row)return{success:false,statusCode:404,error:{code:'NOT_FOUND',message:'Task not found'}};return{success:true,transitions:ctx.db.query('SELECT * FROM task_transitions WHERE task_id=? ORDER BY created_at DESC,id DESC',[row.id]).rows,audit:ctx.db.query('SELECT * FROM audit_log WHERE entity_type=? AND entity_id=? ORDER BY timestamp DESC LIMIT 100',['task',String(row.id)]).rows};}
module.exports={boot:boot,teardown:teardown,list:list,create:create,update:update,setStatus:setStatus,addDependency:addDependency,removeDependency:removeDependency,history:history};
