import React,{useEffect,useState} from 'react';
import {api,post} from './presentation.js';

export function QuickMcfUpload({busy,actor,provider,upload,connect}){const [file,setFile]=useState(null),[mode,setMode]=useState('reviews'),[category,setCategory]=useState('School');return <section className="card"><h2>Upload a document. Get an MCF analysis.</h2><p>Research’Ed prepares the text and proposes competencies with supporting passages. Review the findings, then optionally ask AI to interpret your approved results.</p><div className="form-grid"><label>Material<select value={mode} onChange={e=>setMode(e.target.value)}><option value="reviews">School or leadership reviews</option><option value="documentary">Curriculum, standards or other documents</option></select></label>{mode==='reviews'&&<label>Review type<select value={category} onChange={e=>setCategory(e.target.value)}>{['School','Principal','Director'].map(c=><option key={c}>{c}</option>)}</select></label>}</div><label>Document to analyse<input type="file" accept=".docx,.txt,.csv,.xlsx,.pdf,.html,.htm" onChange={e=>setFile(e.target.files?.[0]??null)}/></label><p>{provider?`Analysis uses ${provider.id} / ${provider.model}. Selected source text is sent to this connection when you start analysis.`:'Connect an AI provider to generate proposals. You can still upload and prepare the source now.'}</p>{!provider&&<button onClick={connect}>Connect AI</button>}<button className="primary" disabled={busy||!actor.trim()||!file} onClick={()=>upload(file,mode,mode==='documentary'?'Documentary':category)}>{provider?'Upload and analyse':'Upload and prepare'}</button><small>Compiled reviews and spreadsheet columns need a short confirmation before analysis. Original source files remain unchanged.</small></section>;}

export default function McfAnalysis({session,instrument,actor,provider,busy,readOnly,run,review,connect,onSaved,refreshKey=0}){
 const [data,setData]=useState(null),[error,setError]=useState(''),[selectedRun,setSelectedRun]=useState(''),[filter,setFilter]=useState('pending'),[page,setPage]=useState(0),[questions,setQuestions]=useState('What patterns and limitations are supported by the reviewed MCF findings?'),[rejectId,setRejectId]=useState(null),[reason,setReason]=useState(''),[saving,setSaving]=useState(false);
 const refresh=async()=>setData(await api('/sessions/'+session.id+'/ai'));
 useEffect(()=>{let active=true,timer;const poll=async()=>{try{const next=await api('/sessions/'+session.id+'/ai');if(active){setData(next);setError('');if(next.runs.some(r=>['queued','running'].includes(r.status)))timer=setTimeout(poll,2000);}}catch(e){if(active){setError(e.message);timer=setTimeout(poll,5000);}}};void poll();return()=>{active=false;clearTimeout(timer);};},[session,refreshKey]);
 if(session.blind||session.kind==='validation')return <p>Independent validation stays manual. AI proposals and interpretations are hidden here.</p>;
 const classification=data?.runs.filter(r=>r.kind==='classification')??[],current=classification.find(r=>r.id===selectedRun)??classification[0],proposals=(data?.proposals??[]).filter(p=>p.run_id===current?.id).sort((a,b)=>(session.units.find(u=>u.id===a.unit_id)?.session_ordinal??0)-(session.units.find(u=>u.id===b.unit_id)?.session_ordinal??0)),pending=proposals.filter(p=>!p.review),rows=proposals.filter(p=>filter==='all'||filter==='pending'&&!p.review||filter==='reviewed'&&p.review),active=data?.runs.find(r=>['queued','running'].includes(r.status));
 async function accept(p){setSaving(true);setError('');try{const unit=session.units.find(u=>u.id===p.unit_id);await api('/sessions/'+session.id+'/decisions/'+p.unit_id,post({...p.payload,unitId:undefined,proposalId:p.id,previousId:unit.decision?.id??null,actor}));await refresh();await onSaved();}catch(e){setError(e.message);}finally{setSaving(false);}}
 return <section className="card mcf-ai"><h3>MCF analysis</h3><p>{provider?`${provider.id} / ${provider.model}`:'No AI connection configured'}. Proposed findings are not researcher-approved decisions. Quotations link each proposal to your original text.</p>{!provider&&<button onClick={connect}>Connect AI</button>}{error&&<p role="alert">{error}</p>}{data?.workerError&&<p role="alert">Analysis queue needs attention: {data.workerError}</p>}
 <button className="primary" disabled={busy||saving||readOnly||!provider||!!active||!actor.trim()} onClick={()=>run('classification')}>{current?'Run a new MCF analysis':'Analyse with MCF'}</button>{active&&<div role="status"><p>{active.kind==='classification'?'Analysing text':'Interpreting reviewed findings'}: {active.completed} of {active.total} batches completed. You can leave this screen and return. Cancellation stops remaining work; already-sent requests may still finish.</p><button onClick={async()=>{try{await api('/sessions/'+session.id+'/ai-cancel/'+active.id,post({actor}));await refresh();}catch(e){setError(e.message);}}}>Cancel analysis</button></div>}
 {current&&<><p>{current.status==='completed'?'Analysis ready':current.status==='partial'?'Partial analysis — some text still needs attention':current.status==='failed'?'Analysis needs attention':current.status==='cancelled'?'Analysis cancelled': 'Analysis in progress'}. {proposals.length} sections have proposals; {pending.length} await researcher review.</p>{current.errors?.map((e,i)=><p className="mcf-callout" key={i}>{e}</p>)}<details><summary>Analysis history and provenance</summary><label>Proposal run<select aria-label="Proposal run" value={current.id} onChange={e=>{setSelectedRun(e.target.value);setPage(0);}}>{classification.map(r=><option key={r.id} value={r.id}>{new Date(r.created_at).toLocaleString()} · {r.status} · {r.configuration.provider.model}</option>)}</select></label><p>Requested by {current.actor}. Instrument and classification settings are recorded separately.</p><pre>{JSON.stringify(current.configuration,null,2)}</pre><a href={'/api/mcf/sessions/'+session.id+'/ai-export'}>Export AI proposals and review history (JSON)</a></details>
 <details><summary>Proposed competency counts</summary><p>These counts describe unverified model proposals, not institutional competence or documentary representation scores.</p><table><thead><tr><th>Competency</th><th>Proposed sections</th></tr></thead><tbody>{instrument.competencies.map(c=><tr key={c.id}><td>{c.competency}</td><td>{proposals.filter(p=>p.payload.codes.some(x=>x.competencyId===c.id)).length}</td></tr>)}</tbody></table></details>
 <label>Findings to show<select aria-label="Findings to show" value={filter} onChange={e=>{setFilter(e.target.value);setPage(0);}}><option value="pending">Awaiting review</option><option value="all">All proposals</option><option value="reviewed">Reviewed proposals</option></select></label><p>Page {page+1} of {Math.max(1,Math.ceil(rows.length/10))}</p>{rows.slice(page*10,page*10+10).map(p=>{const unit=session.units.find(u=>u.id===p.unit_id);return <article className="mcf-proposal" key={p.id}><h4>Section {unit?.session_ordinal} · {p.review?'Reviewed: '+p.review.outcome:'AI proposal — awaiting review'}</h4><blockquote>{unit?.original_text}</blockquote>{p.payload.codes.length?p.payload.codes.map(c=><div key={c.competencyId}><strong>{instrument.competencies.find(x=>x.id===c.competencyId)?.competency} · {c.evidenceStrength}</strong><p>{c.rationale}</p><blockquote>{c.evidence}</blockquote>{c.valence&&<small>Proposed valence: {c.valence}</small>}</div>):<p>AI proposes no applicable competency. This is not a reviewed no-code decision until you accept it.</p>}<p>{p.payload.notes}</p>{unit?.decision&&<small>This section already has researcher coding. Saving another decision retains the previous one in History.</small>}<button disabled={readOnly||saving||!actor.trim()} onClick={()=>accept(p)}>Accept proposal for section {unit?.session_ordinal}</button><button disabled={readOnly||saving} onClick={()=>review(unit?.id,p)}>Review or edit section {unit?.session_ordinal}</button><button disabled={readOnly||saving||!actor.trim()} onClick={()=>{setRejectId(p.id);setReason('');}}>Reject proposal for section {unit?.session_ordinal}</button>{rejectId===p.id&&<div><label>Why reject this proposal?<input value={reason} onChange={e=>setReason(e.target.value)}/></label><p>Rejection records your review; it does not alter any saved coding decision.</p><button disabled={!reason.trim()||saving} onClick={async()=>{setSaving(true);try{await api('/sessions/'+session.id+'/ai-reject/'+p.id,post({actor,reason}));setRejectId(null);await refresh();}catch(e){setError(e.message);}finally{setSaving(false);}}}>Record rejection</button></div>}</article>;})}<button disabled={!page} onClick={()=>setPage(page-1)}>Previous findings</button><button disabled={(page+1)*10>=rows.length} onClick={()=>setPage(page+1)}>Next findings</button></>}
 <details className="card"><summary>Interpret reviewed results with AI</summary><p>This reads a saved snapshot of your approved coding and documentary observations. Unreviewed proposals are excluded. Partial coding is labelled as partial.</p><label>Interpretation questions (one per line)<textarea aria-label="Interpretation questions" value={questions} onChange={e=>setQuestions(e.target.value)}/></label><button disabled={busy||readOnly||!provider||!!active||!actor.trim()||!questions.trim()||(!session.units.some(u=>u.decision)&&!session.representations.length)} onClick={()=>run('interpretation',questions.split('\n').map(q=>q.trim()).filter(Boolean))}>Interpret reviewed results</button>{data?.runs.filter(r=>r.kind==='interpretation'&&r.errors?.length).map(r=><div role="alert" key={r.id}><p>Interpretation {r.status} · {new Date(r.created_at).toLocaleString()}</p>{r.errors.map((e,i)=><p key={i}>{e}</p>)}</div>)}{data?.outputs.map(output=>{const r=data.runs.find(r=>r.id===output.run_id);return <article key={output.id}><h4>Interpretation · {new Date(output.created_at).toLocaleString()}</h4>{r?.stale&&<p className="mcf-callout">Coding has changed since this interpretation. Run it again to include the newer decisions.</p>}<p>{output.payload.detail}</p>{output.payload.answers?.map((a,i)=><section key={i}><h4>{a.question}</h4>{a.status==='not-found'?<p>Not found in the reviewed evidence.</p>:a.findings.map((f,j)=><div key={j}><p>{f.text}</p>{f.evidence.map((e,k)=><blockquote key={k}>{e.quote}{session.units.some(u=>u.id===e.id)&&<button onClick={()=>review(e.id)}>Open reviewed section</button>}</blockquote>)}</div>)}</section>)}</article>;})}</details>
 </section>;
}
