import React,{useEffect,useState} from 'react';
import './mcf.css';

const post=value=>({method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(value)});
async function api(path,options){const r=await fetch('/api/mcf'+path,options);const value=await r.json();if(!r.ok)throw Error((value.error??'Request failed').replaceAll('_',' ')+(value.issues?' — '+value.issues.map(i=>i.message).join('; '):''));return value;}
const valences=[['','Not assigned'],['positive','Positive'],['negative','Negative'],['neutral-descriptive','Neutral/descriptive'],['mixed-ambiguous','Mixed/ambiguous']];
function Valence({value,onChange,label='Passage valence'}){return <label>{label}<select aria-label={label} value={value??''} onChange={e=>onChange(e.target.value||null)}>{valences.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label>;}
function useDraft(key,initial){const [v,set]=useState(()=>{try{return JSON.parse(localStorage.getItem(key))??initial;}catch{return initial;}});useEffect(()=>{localStorage.setItem(key,JSON.stringify(v));},[key,v]);return[v,set,()=>localStorage.removeItem(key)];}
function PageList({items,render}){const [page,setPage]=useState(0);useEffect(()=>setPage(0),[items.length]);const start=page*50;return <><div className="mcf-pagination"><span>{items.length} records · page {page+1} of {Math.max(1,Math.ceil(items.length/50))}</span><button disabled={!page} onClick={()=>setPage(page-1)}>Previous</button><button disabled={start+50>=items.length} onClick={()=>setPage(page+1)}>Next</button></div>{render(items.slice(start,start+50),start)}</>;}

export default function McfWorkspace(){
 const [instrument,setInstrument]=useState(null),[datasets,setDatasets]=useState([]),[dataset,setDataset]=useState(null),[tab,setTab]=useState('Corpus'),[session,setSession]=useState(null),[notice,setNotice]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[upload,setUpload]=useState(null),[record,setRecord]=useState(null),[newDataset,setNewDataset]=useState(false);
 const [researcher,setResearcher]=useState(()=>localStorage.getItem('mcf-researcher')??'');
 useEffect(()=>{localStorage.setItem('mcf-researcher',researcher);},[researcher]);
 const refreshList=async()=>setDatasets((await api('/datasets')).items);
 const refresh=async(id=dataset?.id)=>{if(id)setDataset(await api('/datasets/'+id));};
 useEffect(()=>{Promise.all([api('/instrument').then(v=>setInstrument(v.instrument)),refreshList()]).catch(e=>setError(e.message));},[]);
 async function act(work,message){setBusy(true);setError('');setNotice('');try{await work();setNotice(message);return true;}catch(e){setError(e.message);return false;}finally{setBusy(false);}}
 async function openDataset(id){await act(async()=>{setDataset(await api('/datasets/'+id));setSession(null);setRecord(null);setUpload(null);setTab('Corpus');},'Dataset opened.');}
 async function openSession(id){await act(async()=>{setSession(await api('/sessions/'+id));},'Manual session opened. Only this session’s decisions are shown.');}
 const refreshSession=async()=>setSession(await api('/sessions/'+session.id));
 if(!instrument)return <section className="mcf"><p role="status">{error||'Loading MCF v1.0…'}</p></section>;
 return <section className="mcf" aria-label="MCF Analysis">
  <div className="mcf-heading"><div><span className="eyebrow">Management Competency Framework · v1.0</span><h2>Manual coding, traceable to the source</h2><p>Seven domains. Twenty-one competencies. No machine classification or external AI transmission.</p></div><label>Researcher name (required)<input value={researcher} onChange={e=>setResearcher(e.target.value)} maxLength={200}/></label></div>
  {error&&<p role="alert" className="feedback error">{error}. Your draft is retained. A stale revision requires reopening the session and reviewing the newer decision.</p>}{notice&&<p role="status" className="feedback success">{notice}</p>}{busy&&<p role="status">Saving or loading…</p>}
  <div className="toolbar"><label>Dataset<select aria-label="MCF dataset" disabled={busy} value={dataset?.id??''} onChange={e=>e.target.value&&openDataset(e.target.value)}><option value="">Choose a dataset</option>{datasets.map(d=><option key={d.id} value={d.id}>{d.title} · {d.review_category}</option>)}</select></label><button disabled={busy||!researcher.trim()} onClick={()=>setNewDataset(!newDataset)}>New dataset</button>{dataset&&<span>{dataset.mode==='reviews'?'Review corpus':'Documentary corpus'} · {dataset.review_category}</span>}</div>
  {!researcher.trim()&&<p className="muted">Enter a researcher name to create records or save decisions. Names identify local audit entries; this is not a multi-user authentication system.</p>}
  {newDataset&&<DatasetForm busy={busy||!researcher.trim()} save={v=>act(async()=>{const d=await api('/datasets',post({...v,actor:researcher}));await refreshList();await refresh(d.id);setSession(null);setNewDataset(false);setTab('Corpus');},'Dataset created.')}/>}
  <div className="mcf-tabs" role="tablist" aria-label="MCF workflow">{['Corpus','Coding','Representation','Validation','Instrument'].map(t=><button role="tab" aria-selected={tab===t} key={t} onClick={()=>setTab(t)}>{t}</button>)}</div>
  {tab==='Instrument'?<Instrument instrument={instrument}/>:!dataset?<div className="empty-state">Create or open a dataset. Keep Director, Principal and School reviews in separate datasets.</div>:<>
   {tab==='Corpus'&&<>
    <section className="card"><h3>Preserve and map source records</h3><p>Import raw review text only. Earlier sentiment or competency columns are not imported as coding. Original files and extraction output are preserved before mapping.</p><label>Upload DOCX, TXT, CSV, XLSX, PDF or HTML<input aria-label="MCF source file" type="file" accept=".docx,.txt,.csv,.xlsx,.pdf,.html,.htm" disabled={busy||!researcher.trim()} onChange={e=>{const f=e.target.files?.[0];e.target.value='';if(f)act(async()=>{setUpload(await api('/datasets/'+dataset.id+'/imports?filename='+encodeURIComponent(f.name)+'&actor='+encodeURIComponent(researcher),{method:'POST',body:f,headers:{'content-type':'application/octet-stream'}}));await refresh();},'Original preserved. Review the mapping before creating records.');}}/></label>
     {dataset.imports.map(i=><div className="mcf-import" key={i.id}><span>{i.filename} · {i.record_count} derived records</span><a href={'/api/mcf/imports/'+i.id+'/original'}>Download original</a>{!i.record_count&&<button onClick={()=>act(async()=>setUpload(await api('/imports/'+i.id)),'Import preview opened.')}>Map import</button>}</div>)}
    </section>
    {upload&&<ImportMapping key={upload.id} source={upload} category={dataset.review_category} busy={busy||!researcher.trim()} save={v=>act(async()=>{await api('/imports/'+upload.id+'/map',post({...v,actor:researcher}));setUpload(null);await refresh();},'Derived records and initial sentence units created. Original text is unchanged.')} close={()=>setUpload(null)}/>}
    <RecordList records={dataset.records} open={id=>act(async()=>setRecord(await api('/records/'+id)),'Record and segmentation opened.')}/>
    {record&&<Segmentation key={record.id+record.selectedSetId} record={record} openVersion={id=>act(async()=>setRecord(await api('/records/'+record.id+'?unitSet='+id)),'Segmentation version opened.')}  busy={busy||!researcher.trim()} close={()=>setRecord(null)} save={v=>act(async()=>{await api('/records/'+record.id+'/segment',post({...v,actor:researcher}));setRecord(await api('/records/'+record.id));await refresh();},'New segmentation version saved. Existing sessions and decisions retain their previous units.')}/>}
    <SessionForm kind="coding" busy={busy||!researcher.trim()||!dataset.records.length} create={v=>act(async()=>{const s=await api('/datasets/'+dataset.id+'/sessions',post({...v,actor:researcher}));await refresh();setSession(await api('/sessions/'+s.id));setTab('Coding');},'Manual session created with frozen segmentation.')}/>
   </>}
   {(tab==='Coding'||tab==='Representation')&&<>
    <label>Manual session<select aria-label="MCF session" value={session?.id??''} onChange={e=>e.target.value&&openSession(e.target.value)}><option value="">Choose a session</option>{dataset.sessions.map(s=><option key={s.id} value={s.id}>{s.title} · {s.kind}{s.blind?' · blind':''}</option>)}</select></label>
    {!session?<p className="empty-state">Create a manual session from Corpus, or a seeded sample from Validation.</p>:<>
     <div className="mcf-session"><strong>{session.title}</strong><span>{session.units.length} frozen units · MCF {session.instrument_version}</span><a href={'/api/mcf/sessions/'+session.id+'/export'}>Export session and decision history (JSON)</a></div>
     {session.blind&&<p className="mcf-callout">Blind validation: no coding from other sessions is exposed here or in this session’s export. Only your decisions in this sample are visible. Blinding is a review-workspace property; it does not prevent deliberately opening another local session.</p>}
     {tab==='Coding'?<Coding key={session.id} session={session} instrument={instrument} researcher={researcher} busy={busy} save={(unit,v)=>act(async()=>{await api('/sessions/'+session.id+'/decisions/'+unit,post({...v,actor:researcher}));await refreshSession();},'Researcher decision appended. Previous decisions remain unchanged.')}/>:dataset.mode!=='documentary'?<p>Representation coding applies to documentary datasets. Review corpora use competency coding and valence.</p>:<Representation key={session.id} session={session} instrument={instrument} busy={busy||!researcher.trim()} save={(id,v)=>act(async()=>{await api('/sessions/'+session.id+'/representations/'+id,post({...v,actor:researcher}));await refreshSession();},'Competency-level observation appended. No domain or institution roll-up was calculated.')}/>}
    </>}
   </>}
   {tab==='Validation'&&<><section className="card"><h3>Reproducible manual validation sample</h3><p>Sampling ranks the frozen unit IDs by SHA-256 of the seed and unit ID. Repeating the seed on the same population selects the same units. Revised segmentation or new imports change that population.</p><p>Samples record their full eligible population, selected IDs, seed and algorithm. No machine outputs, reliability scores or thresholds are produced in this phase.</p></section><SessionForm kind="validation" busy={busy||!researcher.trim()||!dataset.records.length} create={v=>act(async()=>{const s=await api('/datasets/'+dataset.id+'/sessions',post({...v,actor:researcher}));await refresh();setSession(await api('/sessions/'+s.id));setTab('Coding');},'Seeded validation sample created. Earlier coding is not copied.')} /></>}
  </>}
 </section>;
}

function DatasetForm({save,busy}){const [v,set,clear]=useDraft('mcf-new-dataset',{title:'',mode:'reviews',reviewCategory:'Director'});return <form className="card" onSubmit={async e=>{e.preventDefault();if(await save(v))clear();}}><h3>New MCF dataset</h3><label>Dataset title<input required value={v.title} onChange={e=>set({...v,title:e.target.value})}/></label><div className="form-grid"><label>Analysis mode<select value={v.mode} onChange={e=>set({...v,mode:e.target.value,reviewCategory:e.target.value==='reviews'?'Director':'Documentary'})}><option value="reviews">Review corpus</option><option value="documentary">Documentary representation</option></select></label><label>Review category<select value={v.reviewCategory} onChange={e=>set({...v,reviewCategory:e.target.value})}>{(v.mode==='reviews'?['Director','Principal','School']:['Documentary']).map(x=><option key={x}>{x}</option>)}</select></label></div><button className="primary" disabled={busy}>Create dataset</button></form>;}

function ImportMapping({source,category,save,busy,close}){
 const raw=source.extracted;const [v,set,clear]=useDraft('mcf-import-'+source.id,{sheet:raw.sheets[0]?.name??'',headerRow:1,textColumn:null,institutionColumn:null,identifierColumn:null,categoryColumn:null,institution:'',reviewIdentifier:'',recordMode:'document'});const sheet=raw.sheets.find(s=>s.name===v.sheet),headers=sheet?.rows.find(r=>r.row===v.headerRow)?.cells??[];
 const field=(key,label)=><label>{label}<select aria-label={label} value={v[key]??''} onChange={e=>set({...v,[key]:e.target.value===''?null:Number(e.target.value)})}><option value="">{key==='textColumn'?'Select text column':'Use supplied value / dataset category'}</option>{headers.map((h,i)=><option key={i} value={i}>Column {i+1}: {h||'(blank)'}</option>)}</select></label>;
 return <form className="card" onSubmit={async e=>{e.preventDefault();if(await save(v))clear();}}><h3>Map {source.filename}</h3><p>Original SHA-256: <code>{source.content_hash}</code></p>{raw.warnings.map((w,i)=><p className="mcf-callout" key={i}>{w}</p>)}
 {sheet?<><div className="form-grid"><label>Worksheet<select value={v.sheet} onChange={e=>set({...v,sheet:e.target.value,textColumn:null,institutionColumn:null,identifierColumn:null,categoryColumn:null})}>{raw.sheets.map(s=><option key={s.name}>{s.name}</option>)}</select></label><label>Header row<input type="number" min={1} max={1000} value={v.headerRow} onChange={e=>set({...v,headerRow:Number(e.target.value)})}/></label>{field('textColumn','Raw review/document text (required)')}{field('institutionColumn','Institution column')}{field('identifierColumn','Review identifier column')}{field('categoryColumn','Review category column (must match dataset)')}</div><div className="table-scroll"><table><caption>First five rows after the selected header</caption><thead><tr><th>Row</th>{headers.map((h,i)=><th key={i}>{h||'Column '+(i+1)}</th>)}</tr></thead><tbody>{sheet.rows.filter(r=>r.row>v.headerRow).slice(0,5).map(r=><tr key={r.row}><td>{r.row}</td>{r.cells.map((c,i)=><td key={i}>{c.slice(0,250)}</td>)}</tr>)}</tbody></table></div><p>Only selected text and metadata columns are used. Empty text rows are skipped. Mapping a previous classification column as raw text is not appropriate.</p></>:<><label>Record boundaries<select value={v.recordMode} onChange={e=>set({...v,recordMode:e.target.value})}><option value="document">Entire file is one review/document</option><option value="paragraphs">Each non-empty paragraph is a separate record</option></select></label><p>Use paragraph records only when each paragraph really is a separate review. For multiple reviews with structured metadata, CSV/XLSX mapping is preferable.</p><pre className="mcf-source">{raw.text.slice(0,4000)||'No extractable text. You may preserve an unavailable documentary source without assigning score 0.'}</pre></>}
 <div className="form-grid"><label>Institution fallback<input value={v.institution} onChange={e=>set({...v,institution:e.target.value})}/></label><label>Review identifier fallback<input value={v.reviewIdentifier} onChange={e=>set({...v,reviewIdentifier:e.target.value})}/></label></div><p>Dataset category: <strong>{category}</strong>. Missing institutions remain unspecified. Unspecified identifiers receive document/row locators.</p><button className="primary" disabled={busy||(sheet&&v.textColumn===null)}>Confirm mapping and create derived records</button><button type="button" onClick={close}>Close preview</button></form>;
}
function RecordList({records,open}){const [q,setQ]=useState(''),[sort,setSort]=useState('id');const rows=records.filter(r=>(r.review_identifier+' '+r.institution).toLowerCase().includes(q.toLowerCase())).sort((a,b)=>String(sort==='institution'?a.institution:a.review_identifier).localeCompare(String(sort==='institution'?b.institution:b.review_identifier)));return <section className="card"><h3>Derived records and segmentation</h3><div className="toolbar"><input aria-label="Search MCF records" placeholder="Search identifier or institution" value={q} onChange={e=>setQ(e.target.value)}/><select aria-label="Sort MCF records" value={sort} onChange={e=>setSort(e.target.value)}><option value="id">Review identifier</option><option value="institution">Institution</option></select></div><PageList items={rows} render={items=><table><thead><tr><th>Review identifier</th><th>Institution</th><th>Characters</th><th>Segmentation</th><th>Review</th></tr></thead><tbody>{items.map(r=><tr key={r.id}><td>{r.review_identifier}</td><td>{r.institution||'Not supplied'}</td><td>{r.characters}</td><td>v{r.segmentation_version}</td><td><button onClick={()=>open(r.id)}>Inspect units</button></td></tr>)}</tbody></table>}/>{!records.length&&<p>No records yet. Upload and confirm an import mapping.</p>}</section>;}
function Segmentation({record,save,busy,close,openVersion}){const [ordinal,setOrdinal]=useState(1),[offset,setOffset]=useState(1),[reason,setReason]=useState('');const unit=record.units.find(u=>u.ordinal===ordinal),selectedSet=record.sets.find(s=>s.id===record.selectedSetId),historic=selectedSet.id!==record.sets[0].id;return <section className="card"><button onClick={close}>Close segmentation</button><h3>{record.review_identifier} · segmentation v{selectedSet.version}</h3><label>Segmentation version<select value={record.selectedSetId} onChange={e=>openVersion(e.target.value)}>{record.sets.map(s=><option key={s.id} value={s.id}>v{s.version} — {s.reason}</option>)}</select></label>{historic&&<p className="mcf-callout">Historical version. Select the latest version to split or join units.</p>}<p>Splits use a character offset within the original unit (UTF-16). Joins combine this unit with its immediate successor. Existing sessions keep their old units; coding is never silently transferred.</p><details><summary>Original record text and provenance</summary><pre className="mcf-source">{record.original_text}</pre><pre>{JSON.stringify(record.locator,null,2)}</pre><a href={'/api/mcf/imports/'+record.import_id+'/original'}>Download original file</a></details><label>Unit<select value={ordinal} onChange={e=>setOrdinal(Number(e.target.value))}>{record.units.map(u=><option key={u.id} value={u.ordinal}>{u.ordinal}. {u.original_text.slice(0,95)}</option>)}</select></label>{unit&&<><pre className="mcf-source">{unit.original_text}</pre><label>Split after this many characters<input type="number" min={1} max={unit.original_text.length-1} value={offset} onChange={e=>setOffset(Number(e.target.value))}/></label><div className="mcf-split"><pre>{unit.original_text.slice(0,offset)}</pre><pre>{unit.original_text.slice(offset)}</pre></div><label>Reason for segmentation change (required)<input value={reason} onChange={e=>setReason(e.target.value)}/></label><button disabled={busy||historic||!reason.trim()} onClick={()=>save({baseSetId:record.sets[0].id,operation:'split',ordinal,offset,reason})}>Save split as a new version</button><button disabled={busy||historic||!reason.trim()||ordinal===record.units.length} onClick={()=>save({baseSetId:record.sets[0].id,operation:'join',ordinal,reason})}>Join next unit as a new version</button></>}<details><summary>Segmentation history ({record.sets.length} versions)</summary>{record.sets.map(s=><p key={s.id}>v{s.version} · {s.actor} · {s.reason} · {new Date(s.created_at).toLocaleString()}</p>)}</details></section>;}
function SessionForm({kind,busy,create}){const [v,set,clear]=useDraft('mcf-new-session-'+kind,{title:kind==='coding'?'Pilot manual coding':'Pilot blind validation',kind,blind:kind==='validation',seed:'pilot-1',sampleSize:10});return <form className="card" onSubmit={async e=>{e.preventDefault();if(await create(v))clear();}}><h3>{kind==='coding'?'Begin a manual coding session':'Create validation sample'}</h3><label>Session title<input required value={v.title} onChange={e=>set({...v,title:e.target.value})}/></label>{kind==='validation'&&<><div className="form-grid"><label>Random seed<input required value={v.seed} onChange={e=>set({...v,seed:e.target.value})}/></label><label>Sample size (units)<input type="number" min={1} max={10000} value={v.sampleSize} onChange={e=>set({...v,sampleSize:Number(e.target.value)})}/></label></div><label className="checkbox"><input type="checkbox" checked={v.blind} onChange={e=>set({...v,blind:e.target.checked})}/>Blind manual review</label></>}<p>Creates a fixed snapshot of the latest segmentation. Earlier decisions remain in their own sessions.</p><button className="primary" disabled={busy}>{kind==='coding'?'Create manual session':'Create reproducible sample'}</button></form>;}
function Coding({session,instrument,researcher,busy,save}){
 const [selected,setSelected]=useState(null),[q,setQ]=useState(''),[filter,setFilter]=useState('all'),[competency,setCompetency]=useState(''),[sort,setSort]=useState('original');
 const rows=session.units.filter(u=>u.original_text.toLowerCase().includes(q.toLowerCase())&&(!competency||u.decision?.codes.some(c=>c.competencyId===competency))&&(filter==='all'||filter==='unreviewed'&&!u.decision||filter==='uncoded'&&u.decision?.reviewed_no_code||filter==='multi'&&u.decision?.codes.length>1||filter==='reviewed'&&u.decision)).sort((a,b)=>sort==='institution'?a.institution.localeCompare(b.institution):a.session_ordinal-b.session_ordinal);
 const unit=session.units.find(u=>u.id===selected),reviewed=session.units.filter(u=>u.decision).length;
 return <><p>{reviewed}/{session.units.length} units reviewed · {session.units.filter(u=>u.decision?.reviewed_no_code).length} reviewed with no applicable code. Neutral/descriptive does not mean factual or unbiased.</p><section className="card"><div className="toolbar"><input aria-label="Search MCF units" placeholder="Search original passage" value={q} onChange={e=>setQ(e.target.value)}/><select aria-label="MCF coding filter" value={filter} onChange={e=>setFilter(e.target.value)}>{[['all','All units'],['unreviewed','Unreviewed'],['reviewed','Reviewed'],['uncoded','Reviewed: no code'],['multi','Multiple codes']].map(([id,label])=><option key={id} value={id}>{label}</option>)}</select><select aria-label="Competency filter" value={competency} onChange={e=>setCompetency(e.target.value)}><option value="">All competencies</option>{instrument.competencies.map(c=><option key={c.id} value={c.id}>{c.competency}</option>)}</select><select aria-label="Sort MCF units" value={sort} onChange={e=>setSort(e.target.value)}><option value="original">Session order</option><option value="institution">Institution</option></select></div><PageList items={rows} render={items=><table><thead><tr><th>#</th><th>Original passage</th><th>Record / institution</th><th>Status</th><th>Action</th></tr></thead><tbody>{items.map(u=><tr key={u.id}><td>{u.session_ordinal}</td><td>{u.original_text.slice(0,240)}</td><td>{u.review_identifier}<small>{u.institution||'Not supplied'}</small></td><td>{!u.decision?'Unreviewed':u.decision.reviewed_no_code?'Reviewed: no code':u.decision.codes.length+' code(s)'}</td><td><button onClick={()=>setSelected(u.id)}>Code passage</button></td></tr>)}</tbody></table>}/></section>{unit&&<DecisionForm key={session.id+unit.id+(unit.decision?.id??'')} unit={unit} session={session} instrument={instrument} busy={busy||!researcher.trim()} save={v=>save(unit.id,v)}/>}</>;
}
function DecisionForm({unit,session,instrument,busy,save}){
 const originalRecord=session.records.find(r=>r.id===unit.record_id);
 const existing=unit.decision;const [v,set,clear]=useDraft('mcf-coding-'+session.id+'-'+unit.id+'-'+(existing?.id??'new'),{previousId:existing?.id??null,codes:existing?.codes??[],valence:existing?.valence??null,reviewedNoCode:existing?.reviewed_no_code??false,notes:existing?.notes??''});const [history,setHistory]=useState(null),[historyError,setHistoryError]=useState('');
 const update=(id,values)=>set({...v,codes:v.codes.map(c=>c.competencyId===id?{...c,...values}:c)});
 return <form className="card mcf-editor" onSubmit={async e=>{e.preventDefault();if(await save(v))clear();}}><h3>Code passage {unit.session_ordinal}</h3><small>{unit.filename} · {unit.review_identifier} · unit {unit.ordinal} · offsets {unit.start_offset}–{unit.end_offset}</small><div className="mcf-context"><p>{unit.context_before}</p><blockquote>{unit.original_text}</blockquote><p>{unit.context_after}</p></div><details><summary>Original record and location within source</summary><pre>{JSON.stringify(unit.locator,null,2)}</pre><pre className="mcf-source">{originalRecord?.original_text}</pre><a href={'/api/mcf/imports/'+originalRecord?.import_id+'/original'}>Download original file</a></details><fieldset><legend>MCF competencies — select zero, one or several</legend>{instrument.domains.map(d=><div className="mcf-domain" key={d.id}><h4>{d.id}. {d.name}</h4>{instrument.competencies.filter(c=>c.domainId===d.id).map(c=><div key={c.id}><label className="checkbox"><input type="checkbox" checked={v.codes.some(x=>x.competencyId===c.id)} onChange={e=>set({...v,reviewedNoCode:false,codes:e.target.checked?[...v.codes,{competencyId:c.id,evidenceStrength:'Explicit',valence:null,rationale:'',evidence:unit.original_text}]:v.codes.filter(x=>x.competencyId!==c.id)})}/>{c.competency}</label><details><summary>Definition and boundaries</summary><p>{c.suppliedText}</p></details></div>)}</div>)}</fieldset>
 {v.codes.map(c=><div className="mcf-code" key={c.competencyId}><h4>{instrument.competencies.find(x=>x.id===c.competencyId).competency}</h4><div className="form-grid"><label>Evidence strength<select value={c.evidenceStrength} onChange={e=>update(c.competencyId,{evidenceStrength:e.target.value})}><option>Explicit</option><option>Implicit</option></select></label>{session.mode==='reviews'&&<Valence label={'Code valence: '+c.competencyId} value={c.valence} onChange={valence=>update(c.competencyId,{valence})}/>}</div><label>Exact supporting span<textarea required value={c.evidence} onChange={e=>update(c.competencyId,{evidence:e.target.value})}/></label><label>Researcher rationale / boundary or exclusion considerations<textarea value={c.rationale} onChange={e=>update(c.competencyId,{rationale:e.target.value})}/></label></div>)}
 {!v.codes.length&&<label className="checkbox"><input type="checkbox" checked={v.reviewedNoCode} onChange={e=>set({...v,reviewedNoCode:e.target.checked})}/>Reviewed — no applicable MCF competency</label>}{session.mode==='reviews'&&<Valence value={v.valence} onChange={valence=>set({...v,valence})}/>}<label>Researcher notes<textarea value={v.notes} onChange={e=>set({...v,notes:e.target.value})}/></label><p>Saving appends a decision. No machine suggestion, confidence score or exclusion rule is inferred.</p><button className="primary" disabled={busy||(!v.codes.length&&!v.reviewedNoCode)}>Save researcher decision</button><button type="button" onClick={async()=>{try{setHistory((await api('/sessions/'+session.id+'/decisions/'+unit.id)).items);setHistoryError('');}catch(e){setHistoryError(e.message);}}}>Show this session’s decision history</button>{historyError&&<p role="alert">{historyError}</p>}{history&&<DecisionHistory items={history} instrument={instrument}/>}</form>;
}
function DecisionHistory({items,instrument}){return <div><h4>Append-only history</h4>{!items.length&&<p>No saved decisions.</p>}{items.map(d=><details key={d.id}><summary>Revision {d.revision} · {d.actor} · {new Date(d.created_at).toLocaleString()}</summary>{d.codes?.map(c=><p key={c.competencyId}>{instrument.competencies.find(x=>x.id===c.competencyId)?.competency} · {c.evidenceStrength} · {c.valence??'Valence not assigned'}<br/>{c.evidence}<br/>{c.rationale}</p>)}{d.reviewed_no_code&&<p>Reviewed with no applicable competency.</p>}{d.state&&<p>{d.competency_id}: {d.state} {d.score??''}</p>}<p>Passage valence: {d.valence??'Not assigned'}</p><p>{d.notes}</p></details>)}</div>;}
function Representation({session,instrument,busy,save}){const [record,setRecord]=useState(session.records[0]?.id??''),[competency,setCompetency]=useState('A1');const previous=session.representations.find(r=>r.record_id===record&&r.competency_id===competency);return <><section className="card"><h3>Twenty-one competency-level observations</h3><p>0 Not represented · 1 Referenced · 2 Developed · 3 Assessed/Evaluated. No averages or automatic domain/institution roll-ups. Representation is not professional competence.</p><label>Document<select value={record} onChange={e=>setRecord(e.target.value)}>{session.records.map(r=><option key={r.id} value={r.id}>{r.review_identifier} · {r.filename}</option>)}</select></label><table><thead><tr><th>Competency</th><th>Assessment state / score</th><th>Evidence passages</th></tr></thead><tbody>{instrument.competencies.map(c=>{const v=session.representations.find(r=>r.record_id===record&&r.competency_id===c.id);return <tr key={c.id}><td><button onClick={()=>setCompetency(c.id)}>{c.competency}</button></td><td>{!v?'Not yet assessed':v.state==='assessed'?v.score+' — '+['Not represented','Referenced','Developed','Assessed/Evaluated'][v.score]:v.state.replaceAll('-',' ')}</td><td>{v?.evidence_unit_ids.length??0}</td></tr>;})}</tbody></table></section><RepresentationForm key={record+competency+(previous?.id??'')} record={record} competency={instrument.competencies.find(c=>c.id===competency)} previous={previous} session={session} busy={busy} save={v=>save(record,v)} instrument={instrument}/></>;}
function RepresentationForm({record,competency,previous,session,busy,save,instrument}){const [v,set,clear]=useDraft('mcf-representation-'+session.id+record+competency.id+(previous?.id??''),{previousId:previous?.id??null,competencyId:competency.id,state:previous?.state??'not-yet-assessed',score:previous?.score??null,evidenceUnitIds:previous?.evidence_unit_ids??[],notes:previous?.notes??''});const [history,setHistory]=useState(null),[err,setErr]=useState('');const units=session.units.filter(u=>u.record_id===record);return <form className="card" onSubmit={async e=>{e.preventDefault();if(await save(v))clear();}}><h3>{competency.competency}</h3><p>{competency.suppliedText}</p><label>Representation assessment<select aria-label="Representation assessment" value={v.state==='assessed'?String(v.score):v.state} onChange={e=>{const value=e.target.value,assessed=/^[0-3]$/.test(value);set({...v,state:assessed?'assessed':value,score:assessed?Number(value):null});}}><option value="not-yet-assessed">Not yet assessed</option><option value="source-unavailable">Source unavailable</option>{['Not represented','Referenced','Developed','Assessed/Evaluated'].map((x,i)=><option key={i} value={String(i)}>{i} — {x}</option>)}</select></label><EvidencePicker units={units} value={v.evidenceUnitIds} onChange={evidenceUnitIds=>set({...v,evidenceUnitIds})}/><label>Researcher notes<textarea value={v.notes} onChange={e=>set({...v,notes:e.target.value})}/></label><button className="primary" disabled={busy||v.score>0&&!v.evidenceUnitIds.length}>Save representation observation</button><button type="button" onClick={async()=>{try{setHistory((await api('/sessions/'+session.id+'/representations/'+record)).items.filter(x=>x.competency_id===competency.id));setErr('');}catch(e){setErr(e.message);}}}>Show observation history</button>{err&&<p role="alert">{err}</p>}{history&&<DecisionHistory items={history} instrument={instrument}/>}</form>;}
function Instrument({instrument}){return <section className="card"><h3>Frozen MCF v{instrument.version}</h3><p>Operational definitions and boundaries below reproduce the supplied research instrument. Candidate terms, synonyms and classifier aids are held separately and remain unconfigured.</p>{instrument.domains.map(d=><section key={d.id}><h3>{d.id}. {d.name}</h3>{instrument.competencies.filter(c=>c.domainId===d.id).map(c=><article key={c.id}><h4>{c.competency}</h4><p>{c.suppliedText}</p></article>)}</section>)}</section>;}

function EvidencePicker({units,value,onChange}){const [query,setQuery]=useState('');const visible=units.filter(u=>u.original_text.toLowerCase().includes(query.toLowerCase()));return <fieldset><legend>Supporting passages (required above 0)</legend><label>Find evidence passage<input value={query} onChange={e=>setQuery(e.target.value)}/></label><p>{value.length} selected passages</p>{!units.length&&<p>No readable units in this session’s document.</p>}<PageList items={visible} render={items=><>{items.map(u=><label className="checkbox mcf-evidence-choice" key={u.id}><input type="checkbox" checked={value.includes(u.id)} onChange={e=>onChange(e.target.checked?[...value,u.id]:value.filter(id=>id!==u.id))}/><span>{u.ordinal}. {u.original_text}</span></label>)}</>}/></fieldset>;}
