import CompiledReviewMapping from './CompiledReviewMapping.jsx';
import LifecycleActions from './LifecycleActions.jsx';
import React,{useEffect,useState,useRef} from 'react';
import {api,post,steps,count,sourceName,institutionName,progress,competencyResults} from './presentation.js';
import './mcf.css';
const valences=[['','Not assigned'],['positive','Positive'],['negative','Negative'],['neutral-descriptive','Neutral/descriptive'],['mixed-ambiguous','Mixed/ambiguous']];
function Valence({value,onChange,label='Passage valence'}){return <label>{label}<select aria-label={label} value={value??''} onChange={e=>onChange(e.target.value||null)}>{valences.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label>;}
function useDraft(key,initial){const [v,set]=useState(()=>{try{return JSON.parse(localStorage.getItem(key))??initial;}catch{return initial;}});useEffect(()=>{localStorage.setItem(key,JSON.stringify(v));},[key,v]);return[v,set,()=>localStorage.removeItem(key)];}
function PageList({items,render}){const [page,setPage]=useState(0);useEffect(()=>setPage(0),[items.length]);const start=page*30;return <>{items.length>30&&<div className="mcf-pagination"><span>{count(items.length,'item')} · page {page+1} of {Math.ceil(items.length/30)}</span><button disabled={!page} onClick={()=>setPage(page-1)}>Previous page</button><button disabled={start+30>=items.length} onClick={()=>setPage(page+1)}>Next page</button></div>}{render(items.slice(start,start+30),start)}</>;}
export default function McfWorkspace(){
 const [instrument,setInstrument]=useState(null),[datasets,setDatasets]=useState([]),[dataset,setDataset]=useState(null),[tab,setTab]=useState('Sources'),[session,setSession]=useState(null),[notice,setNotice]=useState(''),[error,setError]=useState(null),[busy,setBusy]=useState(false),[upload,setUpload]=useState(null),[compiled,setCompiled]=useState(null),[record,setRecord]=useState(null),[newDataset,setNewDataset]=useState(false),[showArchived,setShowArchived]=useState(false),[query,setQuery]=useState(''),[focusUnit,setFocusUnit]=useState(null),[editResearcher,setEditResearcher]=useState(()=>!localStorage.getItem('mcf-researcher'));
 const [researcher,setResearcher]=useState(()=>localStorage.getItem('mcf-researcher')??'');
 const fileInput=useRef(null);
 useEffect(()=>{localStorage.setItem('mcf-researcher',researcher);},[researcher]);
 const refreshList=async(show=showArchived)=>setDatasets((await api('/datasets'+(show?'?archived=true':''))).items);
 const refresh=async(id=dataset?.id)=>{if(id)setDataset(await api('/datasets/'+id));};
 async function act(work,message){setBusy(true);setError(null);setNotice('');try{await work();setNotice(message);return true;}catch(e){setError(e);return false;}finally{setBusy(false);}}
 async function openDataset(id){await act(async()=>{setDataset(await api('/datasets/'+id));setSession(null);setRecord(null);setUpload(null);setCompiled(null);setTab('Sources');setFocusUnit(null);},'Dataset opened.');}
 async function openSession(id,nextTab='Code'){await act(async()=>{setSession(await api('/sessions/'+id));setTab(nextTab);setFocusUnit(null);},'Coding session opened.');}
 const refreshSession=async()=>setSession(await api('/sessions/'+session.id));
 useEffect(()=>{(async()=>{try{setInstrument((await api('/instrument')).instrument);await refreshList();const c=JSON.parse(localStorage.getItem('mcf-context')??'null');if(c?.dataset){const d=await api('/datasets/'+c.dataset);setDataset(d);if(c.session)setSession(await api('/sessions/'+c.session));setTab(steps[c.tab]?c.tab:'Sources');}}catch(e){setError(e);localStorage.removeItem('mcf-context');}})();},[]);
 useEffect(()=>{if(dataset)localStorage.setItem('mcf-context',JSON.stringify({dataset:dataset.id,session:session?.id,tab}));},[dataset?.id,session?.id,tab]);
 const afterLifecycle=async(kind,id,result)=>{if(result.action==='delete'){for(const key of Object.keys(localStorage))if(key.startsWith('mcf-')&&result.removedIds?.some(removed=>key.includes(removed)))localStorage.removeItem(key);}setUpload(null);setCompiled(null);setRecord(null);if(kind==='datasets'&&result.action!=='rename'&&result.action!=='restore'){if(dataset?.id===id){setDataset(null);setSession(null);localStorage.removeItem('mcf-context');}}else if(dataset){await refresh();if(session){if(kind==='sessions'&&session.id===id&&['delete','archive'].includes(result.action)){setSession(null);setTab('Code');}else await refreshSession();}}await refreshList();setNotice(result.pendingFiles?'Item removed. Original-file cleanup is pending; another delete operation will retry it.':result.action==='delete'?'Item deleted.':result.action==='archive'?'Item archived. Use Show archived to find or restore it.':result.action==='restore'?'Item restored.':'Name updated.');};
 const actions=(kind,item,label)=> <LifecycleActions kind={kind} id={item.id} label={label} archived={item.archived} actor={researcher} disabled={busy} onChanged={r=>afterLifecycle(kind,item.id,r)}/>;
 const prepared=dataset?.records.filter(r=>r.active_mapping&&!r.source_archived&&!r.mapping_archived)??[];
 const sections=prepared.reduce((n,r)=>n+r.section_count,0),readOnly=dataset?.archived||session?.presentation?.archived;
 async function inspectRecord(id){await act(async()=>{setRecord(await api('/records/'+id));setTab('Prepare');},'Review the text divisions before coding.');}
 async function prepareImport(id){await act(async()=>{const source=await api('/imports/'+id);setTab('Prepare');setRecord(null);setCompiled(null);setUpload(source);},'Source preview opened.');}
 const createSession=kind=>v=>act(async()=>{const s=await api('/datasets/'+dataset.id+'/sessions',post({...v,kind,actor:researcher}));await refresh();await refreshList();setSession(await api('/sessions/'+s.id));setTab('Code');setFocusUnit(null);},'Coding session created. Begin with the first text section.');
 const goCode=id=>{setFocusUnit(id);setTab('Code');};
 if(!instrument)return <section className="mcf"><p role="status">{error?.message??'Opening MCF Analysis…'}</p></section>;
 return <section className="mcf" aria-label="MCF Analysis">
 <div className="mcf-heading"><div><h1>Management Competency Framework Analysis</h1><p>Analyse documents manually against the MCF. Add your sources, review the text sections, then record your coding decisions.</p><details><summary>Research integrity</summary><p>Your original sources are preserved. You make all coding decisions; this workflow does not classify text automatically or send it to an external AI service. Every saved decision remains traceable.</p><p>Framework version: MCF v1.0. Existing sessions keep the framework and text they started with.</p><p>Researcher names identify local decisions; they are not login accounts.</p></details></div><div className="mcf-researcher">{!researcher.trim()||editResearcher?<><label>Researcher<input value={researcher} onChange={e=>setResearcher(e.target.value)} maxLength={200}/></label><small>Enter your name so Research’Ed can record who made each decision.</small><button disabled={!researcher.trim()} onClick={()=>setEditResearcher(false)}>Use this name</button></>:<><strong>Researcher: {researcher}</strong><button onClick={()=>setEditResearcher(true)}>Change researcher</button></>}</div></div>
 {error&&<div role="alert" className="feedback error"><p>{error.message} Your coding draft is kept on this device.</p><details><summary>Technical details</summary><pre>{error.details??error.message}</pre></details><button onClick={()=>dataset?openDataset(dataset.id):act(()=>refreshList(),'List refreshed.')}>Reopen latest work</button></div>}{notice&&<p role="status" className="feedback success">{notice}</p>}{busy&&<p role="status">Working…</p>}
 <div className="toolbar"><label>Dataset<select aria-label="MCF dataset" value={dataset?.id??''} disabled={busy} onChange={e=>e.target.value&&openDataset(e.target.value)}><option value="">Choose a dataset</option>{datasets.map(d=><option key={d.id} value={d.id}>{d.display_title??d.title}{d.archived?' (archived)':''}</option>)}</select></label><button disabled={busy||!researcher.trim()} onClick={()=>setNewDataset(!newDataset)}>New dataset</button><button onClick={()=>{setDataset(null);setSession(null);localStorage.removeItem('mcf-context');}}>All datasets</button><label className="checkbox"><input type="checkbox" checked={showArchived} onChange={e=>{setShowArchived(e.target.checked);act(()=>refreshList(e.target.checked),'Dataset list refreshed.');}}/>Show archived</label></div>
 {newDataset&&<DatasetForm busy={busy||!researcher.trim()} save={v=>act(async()=>{const d=await api('/datasets',post({...v,actor:researcher}));await refreshList();await refresh(d.id);setSession(null);setNewDataset(false);setTab('Sources');},'Dataset created. Add your first source.')}/>}
 {!dataset?<section><h2>Your datasets</h2><p>A dataset is the collection of source material you analyse together.</p><label>Find a dataset<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Dataset name"/></label>{!datasets.length&&<div className="empty-state"><p>No datasets yet. Create one, then add the source material you want to analyse.</p><button className="primary" disabled={!researcher.trim()} onClick={()=>setNewDataset(true)}>Create your first dataset</button></div>}<div className="mcf-datasets">{datasets.filter(d=>(d.display_title??d.title).toLowerCase().includes(query.toLowerCase())).map(d=><article className="card" key={d.id}><h3>{d.display_title??d.title}</h3><p>{d.mode==='documentary'?'Documentary analysis':d.review_category+' review analysis'} · {count(d.source_count,'source document')}</p><p>{d.archived?'Archived':d.decision_count?'Coding recorded':d.session_count?'Coding not started':d.source_count?'Sources added':'Add your first source'}</p><small>Created {new Date(d.created_at).toLocaleDateString()}</small><button className="primary" onClick={()=>openDataset(d.id)}>Open dataset</button>{actions('datasets',d,d.display_title??d.title)}</article>)}</div></section>:<>
 <div className="mcf-dataset-title"><h2>{dataset.display_title??dataset.title}</h2>{actions('datasets',dataset,dataset.display_title??dataset.title)}</div>{dataset.archived&&<p className="mcf-callout">Archived dataset. You can inspect and export its research history. Restore it to make changes.</p>}
 <nav className="mcf-tabs" role="tablist" aria-label="Research workflow">{Object.keys(steps).map((t,i)=><button role="tab" aria-selected={tab===t} key={t} onClick={()=>setTab(t)}>{t==='Framework'?t:`${i+1}. ${t}`}</button>)}</nav><div className="mcf-step"><strong>Current step: {tab==='Prepare'?'Prepare text for coding':tab}</strong><p>{steps[tab]}</p></div>
 {tab==='Sources'&&<><section className="card"><h3>Source documents</h3><p>{count(dataset.imports.filter(i=>!i.archived).length,'uploaded document')} · {count(prepared.length,'prepared text record')} · {count(sections,'text section')} for coding.</p><button className="primary" disabled={busy||dataset.archived||!researcher.trim()} onClick={()=>fileInput.current?.click()}>Add source</button><label>Source file <small>DOCX, TXT, CSV, XLSX, PDF or HTML</small><input ref={fileInput} aria-label="MCF source file" type="file" accept=".docx,.txt,.csv,.xlsx,.pdf,.html,.htm" disabled={busy||dataset.archived||!researcher.trim()} onChange={e=>{const f=e.target.files?.[0];e.target.value='';if(f)act(async()=>{setUpload(await api('/datasets/'+dataset.id+'/imports?filename='+encodeURIComponent(f.name)+'&actor='+encodeURIComponent(researcher),{method:'POST',body:f}));setRecord(null);setCompiled(null);await refresh();await refreshList();setTab('Prepare');},'Source added. Check the extracted text before preparing it for coding.');}}/></label><p>Your uploaded original stays unchanged.</p>
 <PageList items={dataset.imports.filter(i=>showArchived||!i.archived)} render={items=><table><thead><tr><th>Source</th><th>Preparation</th><th>Actions</th></tr></thead><tbody>{items.map(i=>{const rows=prepared.filter(r=>r.import_id===i.id);return <tr key={i.id}><td>{i.display_label??i.filename}{i.archived&&<small>Archived</small>}</td><td>{rows.length?`${count(rows.length,'text record')} · ${count(rows.reduce((n,r)=>n+r.section_count,0),'section')}`:'Not prepared'}</td><td>{rows.length?<button onClick={()=>{setTab('Prepare');setRecord(null);setUpload(null);setCompiled(null);}}>Review text sections</button>:<button disabled={i.archived||dataset.archived} onClick={()=>prepareImport(i.id)}>Prepare source</button>}<a href={'/api/mcf/imports/'+i.id+'/original'}>Download original</a><button onClick={()=>prepareImport(i.id)}>Preview source</button>{i.filename.toLowerCase().endsWith('.docx')&&<button disabled={i.archived||dataset.archived} onClick={()=>act(async()=>{setCompiled({importId:i.id,...await api('/imports/'+i.id+'/structural-preview')});setUpload(null);setRecord(null);setTab('Prepare');},'Review the individual texts identified in your document.')}>Review individual texts</button>}{actions('imports',i,i.display_label??i.filename)}</td></tr>;})}</tbody></table>}/></section>{!!prepared.length&&<button className="primary" onClick={()=>setTab('Prepare')}>Continue to text preparation</button>}</>}
 {tab==='Prepare'&&<>
 {upload&&<>{upload.extracted.format==='docx'&&<section className="card"><h3>Does this document contain several reviews?</h3><p>Research’Ed can recognise repeated review questionnaires and help you check each review separately.</p><button disabled={busy||dataset.archived} onClick={()=>act(async()=>{setCompiled({importId:upload.id,...await api('/imports/'+upload.id+'/structural-preview')});setUpload(null);},'Review the texts found in your document.')}>Find individual reviews</button></section>}<ImportMapping key={upload.id} source={upload} category={dataset.review_category} busy={busy||dataset.archived||!researcher.trim()||dataset.imports.some(i=>i.id===upload.id&&i.record_count>0)} save={v=>act(async()=>{await api('/imports/'+upload.id+'/map',post({...v,actor:researcher}));setUpload(null);await refresh();},'Text prepared. Review the sections before coding.')} close={()=>setUpload(null)}/></>}
 {compiled&&<CompiledReviewMapping key={compiled.importId+compiled.nextVersion} preview={compiled} busy={busy||dataset.archived||!researcher.trim()} close={()=>setCompiled(null)} save={v=>act(async()=>{await api('/imports/'+compiled.importId+'/map',post({...v,actor:researcher}));setCompiled(null);await refresh();},'Source preparation saved. Existing coding stays unchanged.')}/>}
 {!upload&&!compiled&&!record&&<RecordList records={dataset.records} open={inspectRecord} actions={actions}/>}
 {record&&<Segmentation key={record.id+record.selectedSetId} record={record} actions={actions} openVersion={id=>act(async()=>setRecord(await api('/records/'+record.id+'?unitSet='+id)),'Earlier text preparation opened.')} busy={busy||dataset.archived||!researcher.trim()} close={()=>setRecord(null)} save={v=>act(async()=>{await api('/records/'+record.id+'/segment',post({...v,actor:researcher}));setRecord(await api('/records/'+record.id));await refresh();},'Text sections updated. Existing coding sessions are unchanged.')}/>}
 {!upload&&!compiled&&<button className="primary" disabled={!prepared.length||dataset.archived} onClick={()=>setTab('Code')}>Continue to coding</button>}</>}
 {tab==='Code'&&<><SessionPicker dataset={dataset} session={session} open={openSession} showArchived={showArchived} actions={actions}/>{!session?<SessionForm kind="coding" sections={sections} busy={busy||dataset.archived||!researcher.trim()||!prepared.length} create={createSession('coding')}/>:<><SessionContext session={session}/><Coding key={session.id} session={session} instrument={instrument} researcher={researcher} busy={busy||readOnly} focusUnit={focusUnit} onCheck={()=>setTab('Check')} save={(unit,v)=>act(async()=>{await api('/sessions/'+session.id+'/decisions/'+unit,post({...v,actor:researcher}));await refreshSession();await refresh();},'Coding saved.')}/><button onClick={()=>setSession(null)}>Start another coding session</button></>}</>}
 {tab==='Check'&&<><SessionPicker dataset={dataset} session={session} open={id=>openSession(id,'Check')} showArchived={showArchived} actions={actions}/>{session?<Checks session={session} goCode={goCode} results={()=>setTab('Results')} prepare={()=>{setSession(null);setTab('Prepare');}}/>:<p>Open a coding session to check which sections still need a decision.</p>}<details className="card"><summary>Validation sampling — independent manual review</summary><p>Create a repeatable sample for a separate manual review. Blind review shows only decisions from that sample. No reliability score or threshold is calculated.</p><SessionForm kind="validation" sections={sections} busy={busy||dataset.archived||!researcher.trim()||!sections} create={createSession('validation')}/></details></>}
 {tab==='Results'&&<><SessionPicker dataset={dataset} session={session} open={id=>openSession(id,'Results')} showArchived={showArchived} actions={actions}/>{session?<><SessionContext session={session}/><Results session={session} instrument={instrument} goCode={goCode}/>{dataset.mode==='documentary'&&<Representation key={session.id} session={session} instrument={instrument} busy={busy||readOnly||!researcher.trim()} save={(id,v)=>act(async()=>{await api('/sessions/'+session.id+'/representations/'+id,post({...v,actor:researcher}));await refreshSession();},'Documentary observation saved.')}/>}</>:<p>Open a coding session to inspect its results and evidence.</p>}</>}
 {tab==='Framework'&&<Instrument instrument={instrument}/>}
 </>}
 </section>;
}
function SessionPicker({dataset,session,open,showArchived,actions}){const visible=dataset.sessions.filter(s=>showArchived||!s.archived);return <section className="card"><h3>Coding sessions</h3>{!visible.length?<p>No coding sessions yet. Start with your prepared text.</p>:<><label>Open session<select aria-label="MCF session" value={session?.id??''} onChange={e=>e.target.value&&open(e.target.value)}><option value="">Choose a session</option>{visible.map(s=><option key={s.id} value={s.id}>{s.display_title??s.title}{s.archived?' (archived)':''}</option>)}</select></label><details><summary>Manage sessions</summary>{visible.map(s=><div className="mcf-session" key={s.id}><strong>{s.display_title??s.title}</strong><span>{s.coded_count} of {s.section_count} sections coded · {s.actor}{s.archived?' · Archived':''}</span><button onClick={()=>open(s.id)}>Open session</button>{actions('sessions',s,s.display_title??s.title)}</div>)}</details></>}</section>;}
function SessionContext({session}){return <div className="mcf-session-context"><strong>{session.presentation?.display_title??session.title}</strong><span> · MCF v{session.instrument_version} · {session.actor}</span>{session.presentation?.archived&&<p className="mcf-callout">Archived session. Restore it to make changes.</p>}{session.presentation?.historicalText&&<p className="mcf-callout">This session uses an earlier version of the prepared text. It continues to use the sections it started with. Start a new session to use your current text preparation.</p>}{session.blind&&<p>Blind validation: only this session’s decisions are shown.</p>}<details><summary>Methodology details</summary><p>Created {new Date(session.created_at).toLocaleString()} by {session.actor}. Framework: MCF v{session.instrument_version}.</p><pre>{JSON.stringify({sessionId:session.id,instrumentHash:session.instrument_hash,configuration:session.configuration},null,2)}</pre></details></div>;}
function Checks({session,goCode,results,prepare}){const p=progress(session),remaining=session.units.filter(u=>!u.decision);return <section className="card"><h3>Check your coding</h3><p>{p.coded} of {p.total} sections coded. {!p.total?'There are no readable sections. Review the source availability before interpreting results.':p.remaining?`${p.remaining} still need a decision.`:'Every section has a saved coding decision. This does not certify research validity.'}</p>{remaining.length>0&&<button className="primary" onClick={()=>goCode(remaining[0].id)}>Review next uncoded section</button>}<PageList items={remaining} render={items=><ul>{items.map(u=><li key={u.id}>Section {u.session_ordinal}: {u.original_text.slice(0,130)} <button onClick={()=>goCode(u.id)}>Review section {u.session_ordinal}</button></li>)}</ul>}/>{session.presentation?.historicalText&&<p className="mcf-callout">Review recommended: source preparation has changed. This session keeps its original text sections. <button onClick={prepare}>View current prepared text</button></p>}<p>Rationale is optional under the current coding rules. Reviewed sections with no applicable competency count as a recorded decision.</p>{session.mode==='documentary'&&<p>Documentary representation remains a separate assessment: {session.representations.filter(r=>r.state!=='not-yet-assessed').length} of {session.records.length*21} competency observations have an assessment or unavailable-source decision. Review these in Results.</p>}<button className="primary" onClick={results}>{p.remaining?'View provisional results':'View results'}</button></section>;}
function Results({session,instrument,goCode}){const [selected,setSelected]=useState(null),p=progress(session),rows=competencyResults(session,instrument);return <section className="card"><h3>Coding results</h3><p>{!p.complete?'Provisional — ':''}{p.coded} of {p.total} sections coded. Counts describe your coding, not an institution’s competence. A section may have several competencies.</p><a className="mcf-export" href={'/api/mcf/sessions/'+session.id+'/export'}>Export coding and research history (JSON)</a><table><thead><tr><th>Competency</th><th>Coded sections</th><th>Evidence</th></tr></thead><tbody>{rows.map(c=><tr key={c.id}><td>{c.competency}<small>{instrument.domains.find(d=>d.id===c.domainId)?.name}</small></td><td>{c.units.length}</td><td><button disabled={!c.units.length} onClick={()=>setSelected(c.id)}>View evidence for {c.competency}</button></td></tr>)}</tbody></table>{selected&&<div><h4>{rows.find(c=>c.id===selected)?.competency}: supporting sections</h4><PageList items={rows.find(c=>c.id===selected)?.units??[]} render={items=><>{items.map(u=><article key={u.id}><p>{u.original_text}</p><small>{sourceName(u)} · Section {u.session_ordinal}</small><button onClick={()=>goCode(u.id)}>Open coding for section {u.session_ordinal}</button><a href={'/api/mcf/imports/'+session.records.find(r=>r.id===u.record_id)?.import_id+'/original'}>Download original</a></article>)}</>}/></div>}</section>;}

function DatasetForm({save,busy}){const [v,set,clear]=useDraft('mcf-new-dataset',{title:'',mode:'reviews',reviewCategory:'Director'});return <form className="card" onSubmit={async e=>{e.preventDefault();if(await save(v))clear();}}><h3>New dataset</h3><label>Dataset name<input required value={v.title} onChange={e=>set({...v,title:e.target.value})}/></label><div className="form-grid"><label>Analysis mode<select value={v.mode} onChange={e=>set({...v,mode:e.target.value,reviewCategory:e.target.value==='reviews'?'Director':'Documentary'})}><option value="reviews">Review analysis</option><option value="documentary">Documentary analysis</option></select></label><label>Review category<select value={v.reviewCategory} onChange={e=>set({...v,reviewCategory:e.target.value})}>{(v.mode==='reviews'?['Director','Principal','School']:['Documentary']).map(x=><option key={x}>{x}</option>)}</select></label></div><button className="primary" disabled={busy}>Create dataset</button></form>;}

function ImportMapping({source,category,save,busy,close}){
 const raw=source.extracted;const [v,set,clear]=useDraft('mcf-import-'+source.id,{sheet:raw.sheets[0]?.name??'',headerRow:1,textColumn:null,institutionColumn:null,identifierColumn:null,categoryColumn:null,institution:'',reviewIdentifier:'',recordMode:'document'});const sheet=raw.sheets.find(s=>s.name===v.sheet),headers=sheet?.rows.find(r=>r.row===v.headerRow)?.cells??[];
 const field=(key,label)=><label>{label}<select aria-label={label} value={v[key]??''} onChange={e=>set({...v,[key]:e.target.value===''?null:Number(e.target.value)})}><option value="">{key==='textColumn'?'Select text column':'Use supplied value / dataset category'}</option>{headers.map((h,i)=><option key={i} value={i}>Column {i+1}: {h||'(blank)'}</option>)}</select></label>;
 return <form className="card" onSubmit={async e=>{e.preventDefault();if(await save(v))clear();}}><h3>Prepare {source.filename}</h3><p>Preview of extracted text. Choose the original text you want to code; previous analysis columns are not imported as coding decisions.</p><details><summary>Source and extraction details</summary><p>Original SHA-256: <code>{source.content_hash}</code></p>{raw.warnings.map((w,i)=><p key={i}>{w}</p>)}</details>
 {sheet?<><div className="form-grid"><label>Worksheet<select value={v.sheet} onChange={e=>set({...v,sheet:e.target.value,textColumn:null,institutionColumn:null,identifierColumn:null,categoryColumn:null})}>{raw.sheets.map(s=><option key={s.name}>{s.name}</option>)}</select></label><label>Header row<input type="number" min={1} max={1000} value={v.headerRow} onChange={e=>set({...v,headerRow:Number(e.target.value)})}/></label>{field('textColumn','Original text column (required)')}{field('institutionColumn','Institution column (optional)')}{field('identifierColumn','Source review identifier column (optional)')}{field('categoryColumn','Review category column')}</div><div className="table-scroll"><table><caption>First five rows after the selected header</caption><thead><tr><th>Row</th>{headers.map((h,i)=><th key={i}>{h||'Column '+(i+1)}</th>)}</tr></thead><tbody>{sheet.rows.filter(r=>r.row>v.headerRow).slice(0,5).map(r=><tr key={r.row}><td>{r.row}</td>{r.cells.map((c,i)=><td key={i}>{c.slice(0,250)}</td>)}</tr>)}</tbody></table></div><p>Only selected text and metadata columns are used. Empty text rows are skipped. Do not choose earlier classification columns as source text.</p></>:<><label>How is this text organised?<select value={v.recordMode} onChange={e=>set({...v,recordMode:e.target.value})}><option value="document">One document or review</option><option value="paragraphs">Each paragraph is a separate review</option></select></label><p>Keep multi-paragraph reviews together. Choose separate paragraphs only when each paragraph is genuinely a different review.</p><pre className="mcf-source">{raw.text.slice(0,4000)||'No readable text was extracted. You can preserve an unavailable documentary source, or upload a verified transcription. Scanned PDFs are not read automatically.'}</pre></>}
 <div className="form-grid"><label>Institution (optional)<input value={v.institution} onChange={e=>set({...v,institution:e.target.value})}/></label><label>Source review identifier (optional)<input value={v.reviewIdentifier} onChange={e=>set({...v,reviewIdentifier:e.target.value})}/></label></div><p>Dataset category: <strong>{category}</strong>. Missing institution details will not prevent coding.</p><button className="primary" disabled={busy||(sheet&&v.textColumn===null)}>Prepare text sections</button><button type="button" onClick={close}>Close preview</button></form>;
}
function RecordList({records,open,actions}){const [history,setHistory]=useState(false),[q,setQ]=useState('');const rows=records.filter(r=>(history||r.active_mapping&&!r.source_archived&&!r.mapping_archived)&&(sourceName(r)+' '+r.institution).toLowerCase().includes(q.toLowerCase()));return <section className="card"><h3>Review text sections</h3><p>Each section is coded separately. Adjust divisions only when a split would make the text difficult or misleading to code.</p><label>Find prepared text<input aria-label="Search prepared text" value={q} onChange={e=>setQ(e.target.value)} placeholder="Source, review or institution"/></label><details><summary>Earlier preparation and archived sources</summary><label className="checkbox"><input type="checkbox" checked={history} onChange={e=>setHistory(e.target.checked)}/>Show earlier and archived preparation</label></details><PageList items={rows} render={items=><table><thead><tr><th>Source text</th><th>Institution</th><th>Text sections</th><th>Actions</th></tr></thead><tbody>{items.map(r=><tr key={r.id}><td>{sourceName(r)}{(!r.active_mapping||r.mapping_archived||r.source_archived)&&<small>Earlier or archived preparation</small>}</td><td>{institutionName(r)}</td><td>{r.section_count}</td><td><button onClick={()=>open(r.id)}>Review text sections</button><details><summary>Details</summary><p>{count(r.characters,'character')} · Preparation v{r.mapping_version}</p><code>{r.id}</code>{actions?.('mappings',{id:r.mapping_id,archived:r.mapping_archived},`prepared source v${r.mapping_version}`)}</details></td></tr>)}</tbody></table>}/>{!rows.length&&<p>No prepared text yet. Add a source and check its extracted text.</p>}</section>;}
function Segmentation({record,save,busy,close,openVersion,actions}){
 const [ordinal,setOrdinal]=useState(()=>Number(localStorage.getItem('mcf-section-'+record.id)??1)),[offset,setOffset]=useState(null),[reason,setReason]=useState(''),[mode,setMode]=useState(null),[q,setQ]=useState('');
 const unit=record.units.find(u=>u.ordinal===ordinal)??record.units[0],selectedSet=record.sets.find(s=>s.id===record.selectedSetId),current=record.sets.find(s=>!s.archived),historic=!current||selectedSet.id!==current.id||selectedSet.archived;
 useEffect(()=>{localStorage.setItem('mcf-section-'+record.id,String(ordinal));setOffset(null);setMode(null);},[ordinal,record.id]);
 const next=unit&&record.units.find(u=>u.ordinal===unit.ordinal+1),filtered=record.units.filter(u=>u.original_text.toLowerCase().includes(q.toLowerCase()));
 return <section className="card"><button onClick={close}>Back to prepared sources</button><h3>Prepare text for coding</h3><p>{sourceName(record)} · {count(record.units.length,'text section')}</p><p>You are changing where the text is divided, not rewriting the source. Existing coding sessions remain unchanged.</p>{historic&&<p className="mcf-callout">This is earlier or archived preparation. Choose the current text in Section history to make changes.</p>}
 <label>Search text sections<input value={q} onChange={e=>setQ(e.target.value)}/></label><details><summary>Browse sections</summary><PageList items={filtered} render={items=><ol>{items.map(u=><li key={u.id}><button onClick={()=>setOrdinal(u.ordinal)}>Section {u.ordinal}: {u.original_text.slice(0,130)}</button></li>)}</ol>}/></details>
 {unit&&<><div className="toolbar"><button disabled={unit.ordinal===1} onClick={()=>setOrdinal(1)}>First section</button><button disabled={unit.ordinal===1} onClick={()=>setOrdinal(unit.ordinal-1)}>Previous section</button><label>Go to section<input type="number" min={1} max={record.units.length} value={unit.ordinal} onChange={e=>{const n=Number(e.target.value);if(n>0&&n<=record.units.length)setOrdinal(n);}}/></label><button disabled={!next} onClick={()=>setOrdinal(unit.ordinal+1)}>Next section</button></div><h4>Section {unit.ordinal} of {record.units.length}</h4><pre className="mcf-source">{unit.original_text}</pre><button disabled={busy||historic} onClick={()=>{setMode('split');setOffset(null);}}>Split section</button><button disabled={busy||historic||!next} onClick={()=>setMode('join')}>Combine with next section</button>
 {mode==='split'&&<><label>Choose the split point<small>Click in the text, or use the arrow keys, to place the cursor where the next section should begin. Typing cannot change the source.</small><textarea className="mcf-boundary-text" key={unit.id} readOnly defaultValue={unit.original_text} onKeyDown={e=>{if(e.shiftKey||!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const el=e.currentTarget,text=el.value;let n=e.key==='Home'?0:e.key==='End'?text.length:Math.max(0,Math.min(text.length,el.selectionStart+(e.key==='ArrowLeft'?-1:1)));if(n>0&&n<text.length&&/[\uD800-\uDBFF]/.test(text[n-1])&&/[\uDC00-\uDFFF]/.test(text[n]))n+=e.key==='ArrowLeft'?-1:1;el.setSelectionRange(n,n);setOffset(n);}} onKeyUp={e=>setOffset(e.currentTarget.selectionStart===e.currentTarget.selectionEnd?e.currentTarget.selectionStart:null)} onMouseUp={e=>setOffset(e.currentTarget.selectionStart===e.currentTarget.selectionEnd?e.currentTarget.selectionStart:null)}/></label>{offset!==null&&<div className="mcf-split"><div><strong>First section</strong><pre>{unit.original_text.slice(0,offset)}</pre></div><div><strong>Next section</strong><pre>{unit.original_text.slice(offset)}</pre></div></div>}</>}
 {mode==='join'&&next&&<div><p>These two sections will become one coding section.</p><pre className="mcf-source">{unit.original_text+next.original_text}</pre></div>}
 {mode&&<><label>Why are you changing this section?<input value={reason} maxLength={2000} onChange={e=>setReason(e.target.value)} placeholder="These sentences need to be coded together."/></label><button className="primary" disabled={busy||historic||!reason.trim()||mode==='split'&&(offset===null||!unit.original_text.slice(0,offset).trim()||!unit.original_text.slice(offset).trim())} onClick={()=>save({baseSetId:selectedSet.id,operation:mode,ordinal:unit.ordinal,...(mode==='split'?{offset}:{}),reason})}>{mode==='split'?'Split here':'Save combined section'}</button><button onClick={()=>setMode(null)}>Cancel adjustment</button></>}</>}
 <details><summary>Section history</summary><label>Prepared text version<select value={record.selectedSetId} onChange={e=>openVersion(e.target.value)}>{record.sets.map(s=><option key={s.id} value={s.id}>{s.id===current?.id?'Current':s.archived?'Archived':'Earlier'} — {new Date(s.created_at).toLocaleString()} · {s.actor}</option>)}</select></label>{record.sets.map(s=><div key={s.id}><p>{new Date(s.created_at).toLocaleString()} · {s.actor}<br/>{s.reason==='Initial sentence segmentation'?'Original text divisions':s.reason}</p>{actions?.('unit-sets',s,`text preparation v${s.version}`)}</div>)}</details>
 <details><summary>Source and methodology details</summary><a href={'/api/mcf/imports/'+record.import_id+'/original'}>Download original</a><p>Source text wording is unchanged. Internal offsets use UTF-16 code units. Version: {selectedSet.version}.</p><pre>{JSON.stringify(record.locator,null,2)}</pre><details><summary>All preserved source components</summary>{record.sourceComponents?record.sourceComponents.map(b=><div key={b.index}><strong>{b.component}</strong><pre className="mcf-source">{b.text}</pre></div>):<pre className="mcf-source">{record.original_text}</pre>}</details></details></section>;
}
function SessionForm({kind,busy,create,sections=0}){const [v,set,clear]=useDraft('mcf-new-session-'+kind,{title:kind==='coding'?'Pilot coding':'Independent validation',kind,blind:kind==='validation',seed:'pilot-1',sampleSize:10});return <form className="card" onSubmit={async e=>{e.preventDefault();if(await create(v))clear();}}><h3>{kind==='coding'?'Start coding':'Create validation sample'}</h3><p>{count(sections,'available text section')} · MCF v1.0. This session uses the text as prepared now. Later preparation changes will not alter its coding.</p><label>Session name<input required value={v.title} onChange={e=>set({...v,title:e.target.value})}/></label>{kind==='validation'&&<><div className="form-grid"><label>Sample seed<input required value={v.seed} onChange={e=>set({...v,seed:e.target.value})}/><small>Reuse this value on the same prepared text to select the same sample.</small></label><label>Sample size (text sections)<input type="number" min={1} max={10000} value={v.sampleSize} onChange={e=>set({...v,sampleSize:Number(e.target.value)})}/></label></div><label className="checkbox"><input type="checkbox" checked={v.blind} onChange={e=>set({...v,blind:e.target.checked})}/>Blind manual review — hide decisions from other sessions</label></>}<button className="primary" disabled={busy}>{kind==='coding'?'Start coding':'Create sample'}</button></form>;}
function Coding({session,instrument,researcher,busy,save,focusUnit,onCheck}){
 const first=session.units.find(u=>!u.decision)?.id??session.units[0]?.id;
 const [selected,setSelected]=useState(()=>focusUnit??localStorage.getItem('mcf-coding-position-'+session.id)??first),[q,setQ]=useState(''),[filter,setFilter]=useState('all'),[competency,setCompetency]=useState('');
 useEffect(()=>{if(focusUnit)setSelected(focusUnit);},[focusUnit]);useEffect(()=>{if(selected)localStorage.setItem('mcf-coding-position-'+session.id,selected);},[selected,session.id]);
 const rows=session.units.filter(u=>u.original_text.toLowerCase().includes(q.toLowerCase())&&(!competency||u.decision?.codes.some(c=>c.competencyId===competency))&&(filter==='all'||filter==='unreviewed'&&!u.decision||filter==='uncoded'&&u.decision?.reviewed_no_code||filter==='reviewed'&&u.decision));
 const unit=session.units.find(u=>u.id===selected)??session.units.find(u=>u.id===first),p=progress(session),index=session.units.findIndex(u=>u.id===unit?.id);
 const nextUncoded=()=>{const u=session.units.find((u,i)=>i>index&&!u.decision)??session.units.find(u=>u.id!==unit?.id&&!u.decision);if(u)setSelected(u.id);else onCheck();};
 return <><div className="mcf-coding-progress"><strong>{p.coded} of {p.total} sections coded · {p.remaining} remaining</strong><button onClick={nextUncoded}>Next uncoded section</button><button onClick={onCheck}>Check analysis</button></div>
 {unit&&<DecisionForm key={session.id+unit.id+(unit.decision?.id??'')} unit={unit} session={session} instrument={instrument} busy={busy||!researcher.trim()} save={v=>save(unit.id,v)} saveNext={async v=>{const ok=await save(unit.id,v);if(ok)nextUncoded();return ok;}} onPrev={index>0?()=>setSelected(session.units[index-1].id):null} onNext={index<session.units.length-1?()=>setSelected(session.units[index+1].id):null}/>}
 <details className="card"><summary>Browse and filter coding sections</summary><div className="toolbar"><label>Search source text<input value={q} onChange={e=>setQ(e.target.value)}/></label><label>Coding status<select value={filter} onChange={e=>setFilter(e.target.value)}>{[['all','All sections'],['unreviewed','Not yet coded'],['reviewed','Coded'],['uncoded','Reviewed: no applicable competency']].map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label>Competency<select value={competency} onChange={e=>setCompetency(e.target.value)}><option value="">All competencies</option>{instrument.competencies.map(c=><option key={c.id} value={c.id}>{c.competency}</option>)}</select></label></div><PageList items={rows} render={items=><table><thead><tr><th>Section</th><th>Source text</th><th>Status</th><th>Action</th></tr></thead><tbody>{items.map(u=><tr key={u.id}><td>{u.session_ordinal}</td><td>{u.original_text.slice(0,220)}<small>{sourceName(u)}</small></td><td>{u.decision?u.decision.reviewed_no_code?'Reviewed: no applicable competency':'Coded':'Not yet coded'}</td><td><button onClick={()=>setSelected(u.id)}>Code section {u.session_ordinal}</button></td></tr>)}</tbody></table>}/></details></>;
}
function DecisionForm({unit,session,instrument,busy,save,saveNext,onPrev,onNext}){
 const originalRecord=session.records.find(r=>r.id===unit.record_id),headingRef=useRef(null);useEffect(()=>{headingRef.current?.focus();},[unit.id]);
 const existing=unit.decision;const [v,set,clear]=useDraft('mcf-coding-'+session.id+'-'+unit.id+'-'+(existing?.id??'new'),{previousId:existing?.id??null,codes:existing?.codes??[],valence:existing?.valence??null,reviewedNoCode:existing?.reviewed_no_code??false,notes:existing?.notes??''});const [history,setHistory]=useState(null),[historyError,setHistoryError]=useState('');
 const update=(id,values)=>set({...v,codes:v.codes.map(c=>c.competencyId===id?{...c,...values}:c)});
 return <form className="card mcf-editor" onSubmit={async e=>{e.preventDefault();if(await (e.nativeEvent.submitter?.value==='next'?saveNext(v):save(v)))clear();}}><h3 ref={headingRef} tabIndex={-1}>Section {unit.session_ordinal} of {session.units.length}</h3><small>{sourceName(unit)} · {unit.decision?'Saved coding decision':'Not yet coded'}</small><div className="mcf-context"><blockquote>{unit.original_text}</blockquote><details><summary>Show surrounding text</summary><p>{unit.context_before}</p><strong>Current section</strong><p>{unit.original_text}</p><p>{unit.context_after}</p></details></div><details><summary>Source and methodology details</summary><pre>{JSON.stringify(unit.locator,null,2)}</pre><pre className="mcf-source">{originalRecord?.original_text}</pre><a href={'/api/mcf/imports/'+originalRecord?.import_id+'/original'}>Download original file</a></details><fieldset><legend>Which MCF competencies does this section represent? Select one or more, or mark it reviewed with no applicable competency.</legend>{instrument.domains.map(d=><div className="mcf-domain" key={d.id}><h4>{d.id}. {d.name}</h4>{instrument.competencies.filter(c=>c.domainId===d.id).map(c=><div key={c.id}><label className="checkbox"><input type="checkbox" checked={v.codes.some(x=>x.competencyId===c.id)} onChange={e=>set({...v,reviewedNoCode:false,codes:e.target.checked?[...v.codes,{competencyId:c.id,evidenceStrength:'Explicit',valence:null,rationale:'',evidence:unit.original_text}]:v.codes.filter(x=>x.competencyId!==c.id)})}/>{c.competency}</label><details><summary>Definition and boundaries</summary><p>{c.suppliedText}</p></details></div>)}</div>)}</fieldset>
 {v.codes.map(c=><div className="mcf-code" key={c.competencyId}><h4>{instrument.competencies.find(x=>x.id===c.competencyId).competency}</h4><div className="form-grid"><label>Evidence strength<select value={c.evidenceStrength} onChange={e=>update(c.competencyId,{evidenceStrength:e.target.value})}><option>Explicit</option><option>Implicit</option></select></label>{session.mode==='reviews'&&<Valence label={'Competency valence: '+c.competencyId} value={c.valence} onChange={valence=>update(c.competencyId,{valence})}/>}</div><label>Exact supporting span<textarea required value={c.evidence} onChange={e=>update(c.competencyId,{evidence:e.target.value})}/></label><label>Why does this section fit? (optional coding note)<textarea value={c.rationale} onChange={e=>update(c.competencyId,{rationale:e.target.value})}/></label></div>)}
 {!v.codes.length&&<label className="checkbox"><input type="checkbox" checked={v.reviewedNoCode} onChange={e=>set({...v,reviewedNoCode:e.target.checked})}/>Reviewed — no applicable MCF competency</label>}{session.mode==='reviews'&&<Valence value={v.valence} onChange={valence=>set({...v,valence})}/>}<label>Researcher notes<textarea aria-label="Researcher notes" value={v.notes} onChange={e=>set({...v,notes:e.target.value})}/></label><p>Your draft is kept on this device until you save. Previous decisions remain in History.</p><div className="mcf-savebar"><button type="button" disabled={!onPrev} onClick={onPrev}>Previous section</button><button className="primary" value="next" disabled={busy||(!v.codes.length&&!v.reviewedNoCode)}>Save & next</button><button disabled={busy||(!v.codes.length&&!v.reviewedNoCode)}>Save coding</button><button type="button" disabled={!onNext} onClick={onNext}>Next section without saving</button></div><button type="button" onClick={async()=>{try{setHistory((await api('/sessions/'+session.id+'/decisions/'+unit.id)).items);setHistoryError('');}catch(e){setHistoryError(e.message);}}}>Decision history</button>{historyError&&<p role="alert">{historyError}</p>}{history&&<DecisionHistory items={history} instrument={instrument}/>}</form>;
}
function DecisionHistory({items,instrument}){return <div><h4>Researcher decision history</h4>{!items.length&&<p>No saved decisions.</p>}{items.map(d=><details key={d.id}><summary>Decision {d.revision} · {d.actor} · {new Date(d.created_at).toLocaleString()}</summary>{d.codes?.map(c=><p key={c.competencyId}>{instrument.competencies.find(x=>x.id===c.competencyId)?.competency} · {c.evidenceStrength} · {c.valence??'Valence not assigned'}<br/>{c.evidence}<br/>{c.rationale}</p>)}{d.reviewed_no_code&&<p>Reviewed with no applicable competency.</p>}{d.state&&<p>{d.competency_id}: {d.state} {d.score??''}</p>}<p>Passage valence: {d.valence??'Not assigned'}</p><p>{d.notes}</p></details>)}</div>;}
function Representation({session,instrument,busy,save}){const [record,setRecord]=useState(session.records[0]?.id??''),[competency,setCompetency]=useState('A1');const previous=session.representations.find(r=>r.record_id===record&&r.competency_id===competency);return <><section className="card"><h3>Documentary representation: 21 competency observations</h3><p>0 Not represented · 1 Referenced · 2 Developed · 3 Assessed/Evaluated. Assess what each document covers. Each score above 0 needs source evidence. These observations do not measure professional competence; no averages are calculated.</p><label>Document<select value={record} onChange={e=>setRecord(e.target.value)}>{session.records.map(r=><option key={r.id} value={r.id}>{r.review_identifier} · {r.filename}</option>)}</select></label><table><thead><tr><th>Competency</th><th>Assessment state / score</th><th>Evidence passages</th></tr></thead><tbody>{instrument.competencies.map(c=>{const v=session.representations.find(r=>r.record_id===record&&r.competency_id===c.id);return <tr key={c.id}><td><button onClick={()=>setCompetency(c.id)}>{c.competency}</button></td><td>{!v?'Not yet assessed':v.state==='assessed'?v.score+' — '+['Not represented','Referenced','Developed','Assessed/Evaluated'][v.score]:v.state.replaceAll('-',' ')}</td><td>{v?.evidence_unit_ids.length??0}</td></tr>;})}</tbody></table></section><RepresentationForm key={record+competency+(previous?.id??'')} record={record} competency={instrument.competencies.find(c=>c.id===competency)} previous={previous} session={session} busy={busy} save={v=>save(record,v)} instrument={instrument}/></>;}
function RepresentationForm({record,competency,previous,session,busy,save,instrument}){const [v,set,clear]=useDraft('mcf-representation-'+session.id+record+competency.id+(previous?.id??''),{previousId:previous?.id??null,competencyId:competency.id,state:previous?.state??'not-yet-assessed',score:previous?.score??null,evidenceUnitIds:previous?.evidence_unit_ids??[],notes:previous?.notes??''});const [history,setHistory]=useState(null),[err,setErr]=useState('');const units=session.units.filter(u=>u.record_id===record);return <form className="card" onSubmit={async e=>{e.preventDefault();if(await save(v))clear();}}><h3>{competency.competency}</h3><p>{competency.suppliedText}</p><label>Representation assessment<select aria-label="Representation assessment" value={v.state==='assessed'?String(v.score):v.state} onChange={e=>{const value=e.target.value,assessed=/^[0-3]$/.test(value);set({...v,state:assessed?'assessed':value,score:assessed?Number(value):null});}}><option value="not-yet-assessed">Not yet assessed</option><option value="source-unavailable">Source unavailable</option>{['Not represented','Referenced','Developed','Assessed/Evaluated'].map((x,i)=><option key={i} value={String(i)}>{i} — {x}</option>)}</select></label><EvidencePicker units={units} value={v.evidenceUnitIds} onChange={evidenceUnitIds=>set({...v,evidenceUnitIds})}/><label>Researcher notes<textarea aria-label="Researcher notes" value={v.notes} onChange={e=>set({...v,notes:e.target.value})}/></label><button className="primary" disabled={busy||v.score>0&&!v.evidenceUnitIds.length}>Save documentary observation</button><button type="button" onClick={async()=>{try{setHistory((await api('/sessions/'+session.id+'/representations/'+record)).items.filter(x=>x.competency_id===competency.id));setErr('');}catch(e){setErr(e.message);}}}>Show observation history</button>{err&&<p role="alert">{err}</p>}{history&&<DecisionHistory items={history} instrument={instrument}/>}</form>;}
function Instrument({instrument}){return <section className="card"><h3>Management Competency Framework v{instrument.version}</h3><p>Seven domains and twenty-one competencies. Expand definitions while coding, or read the complete framework here. Definitions are unchanged from MCF v1.0.</p>{instrument.domains.map(d=><section key={d.id}><h3>{d.id}. {d.name}</h3>{instrument.competencies.filter(c=>c.domainId===d.id).map(c=><article key={c.id}><h4>{c.competency}</h4><p>{c.suppliedText}</p></article>)}</section>)}</section>;}

function EvidencePicker({units,value,onChange}){const [query,setQuery]=useState('');const visible=units.filter(u=>u.original_text.toLowerCase().includes(query.toLowerCase()));return <fieldset><legend>Supporting passages (required for a score above 0)</legend><label>Find evidence passage<input value={query} onChange={e=>setQuery(e.target.value)}/></label><p>{value.length} selected passages</p>{!units.length&&<p>No readable text sections in this document.</p>}<PageList items={visible} render={items=><>{items.map(u=><label className="checkbox mcf-evidence-choice" key={u.id}><input type="checkbox" checked={value.includes(u.id)} onChange={e=>onChange(e.target.checked?[...value,u.id]:value.filter(id=>id!==u.id))}/><span>{u.ordinal}. {u.original_text}</span></label>)}</>}/></fieldset>;}
