export const steps={Sources:'Add and prepare the documents you want to analyse.',Prepare:'Check that each text section can be coded meaningfully. Your source wording stays unchanged.',Code:'Read each section and decide which MCF competencies it represents.',Check:'Find sections still needing a decision and review changes to the prepared text.',Results:'Review your recorded coding and follow each result back to its evidence.',Framework:'View the seven domains and twenty-one competencies in MCF v1.0.'};
export const count=(n,one,many=one+'s')=>`${n} ${n===1?one:many}`;
export const sourceName=r=>(!r.review_identifier||r.review_identifier==='document')?(r.filename??'Source'):r.locator?.identifierIsGenerated?`${r.filename} · Review ${r.locator.candidateOrdinal}`:`${r.filename??'Source'} · ${r.review_identifier}`;
export const institutionName=r=>!r.institution?'Institution not provided':r.locator?.institution?.state==='proposed'?`${r.institution} (unconfirmed)`:r.institution;
export function progress(session){const total=session?.units.length??0,coded=session?.units.filter(u=>u.decision).length??0;return{total,coded,remaining:total-coded,complete:total>0&&total===coded};}
export function competencyResults(session,framework){return framework.competencies.map(c=>({...c,units:session.units.filter(u=>u.decision?.codes.some(x=>x.competencyId===c.id))}));}
const errors={stale_segmentation:'The text preparation changed after you opened this page. Reopen it before saving.',stale_mapping:'The source preparation changed after you opened this page. Preview it again before saving.',stale_structural_preview:'The source preview has changed. Open a fresh preview before saving.',stale_decision:'A newer coding decision has been saved. Reopen the session and review it before saving your draft.',protected_research_history:'This item is part of research history and cannot be permanently deleted. Archive it instead.',archived_work_restore_first:'This work is archived. Restore it before making changes.',research_item_not_found:'This item is no longer available. Return to your datasets and refresh.',dataset_not_found:'This dataset is no longer available. Return to your datasets.',select_text_column:'Choose the column containing the original text you want to code.',unsupported_import_format:'Choose a DOCX, TXT, CSV, XLSX, PDF or HTML source.',request_too_large:'This file or request is too large. Try a smaller source.',import_record_limit:'This source exceeds the import limit. Divide it into smaller files.',import_records_first:'Prepare a source before starting a coding session.',sample_size_exceeds_population:'Choose a sample no larger than the available text sections.',evidence_must_be_an_exact_unit_substring:'The supporting passage must match the source text exactly.',invalid_split_offset:'Choose a split point with meaningful text on both sides.',no_records_mapped:'No readable text was found for this selection. Review the source and selected columns.',selected_components_have_no_text:'Choose at least one component containing readable text.',source_has_no_readable_text_use_unavailable:'This source has no readable text. Record it as Source unavailable, not Not represented.',review_category_must_match_dataset:'The selected review categories do not match this dataset.',validation_failed:'Check the required fields and coding choices before saving.'};
export const errorMessage=code=>errors[code]??'Research’Ed could not complete this action. Your saved research has not been changed.';
export const post=value=>({method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(value)});
export async function api(path,options){const r=await fetch('/api/mcf'+path,options);const v=await r.json();if(!r.ok){const e=new Error(errorMessage(v.error));e.details=v.error;e.issues=v.issues;throw e;}return v;}
