'use strict';
const helper=require('../../helpers/test-server');
const payload=(id)=>({title:'Approve field trip',description:'Governed request',subject_component:'event_record',subject_type:'event',subject_id:id,stages:[{name:'Department review',approver_type:'role',approver_id:'department_head',required_decisions:1},{name:'Principal review',approver_type:'role',approver_id:'principal',required_decisions:1}]});
describe('approvals component',function(){let context,token;beforeAll(async function(){context=await helper.createTestServer('approvals');token=(await context.makeRequest('POST','/api/auth/dev-login',{})).data.token;});afterAll(async function(){if(context)await context.cleanup();});
 test('creates and edits a draft with ordered stages and pagination',async function(){var created=await context.makeRequest('POST','/approvals/requests',payload('TRIP-1'),token);expect(created.status).toBe(200);expect(created.data.request.stages.map(s=>s.sequence)).toEqual([1,2]);var updated=await context.makeRequest('PUT','/approvals/requests/'+created.data.request.id,{title:'Approve revised field trip'},token);expect(updated.data.request.title).toBe('Approve revised field trip');var list=await context.makeRequest('GET','/approvals/requests?page=1&limit=1&q=revised',null,token);expect(list.data.total).toBe(1);expect(list.data.limit).toBe(1);});
 test('activates stages sequentially and resolves only after final approval',async function(){var created=(await context.makeRequest('POST','/approvals/requests',payload('TRIP-2'),token)).data.request,id=created.id;var submitted=(await context.makeRequest('POST','/approvals/requests/'+id+'/submit',{},token)).data.request;expect(submitted.status).toBe('pending');expect(submitted.stages.map(s=>s.status)).toEqual(['pending','waiting']);expect((await context.makeRequest('PUT','/approvals/requests/'+id,{title:'Too late'},token)).status).toBe(409);var first=(await context.makeRequest('POST','/approvals/requests/'+id+'/stages/'+submitted.stages[0].id+'/decisions',{outcome:'approved',comments:'Suitable'},token)).data.request;expect(first.status).toBe('pending');expect(first.stages.map(s=>s.status)).toEqual(['approved','pending']);var final=(await context.makeRequest('POST','/approvals/requests/'+id+'/stages/'+first.stages[1].id+'/decisions',{outcome:'approved'},token)).data.request;expect(final.status).toBe('approved');expect(final.resolved_at).toBeTruthy();var history=await context.makeRequest('GET','/approvals/requests/'+id+'/history',null,token);expect(history.data.transitions.map(x=>x.to_status)).toEqual(expect.arrayContaining(['pending','approved']));expect(history.data.audit.length).toBeGreaterThanOrEqual(4);});
 test('rejection is final and recorded decisions prevent reinstating a withdrawn cycle',async function(){var rejected=(await context.makeRequest('POST','/approvals/requests',payload('TRIP-3'),token)).data.request;rejected=(await context.makeRequest('POST','/approvals/requests/'+rejected.id+'/submit',{},token)).data.request;var result=await context.makeRequest('POST','/approvals/requests/'+rejected.id+'/stages/'+rejected.stages[0].id+'/decisions',{outcome:'rejected',comments:'Unsafe'},token);expect(result.data.request.status).toBe('rejected');expect((await context.makeRequest('PUT','/approvals/requests/'+rejected.id+'/status',{status:'withdrawn'},token)).status).toBe(409);var active=(await context.makeRequest('POST','/approvals/requests',payload('TRIP-4'),token)).data.request;active=(await context.makeRequest('POST','/approvals/requests/'+active.id+'/submit',{},token)).data.request;await context.makeRequest('POST','/approvals/requests/'+active.id+'/stages/'+active.stages[0].id+'/decisions',{outcome:'approved'},token);expect((await context.makeRequest('PUT','/approvals/requests/'+active.id+'/status',{status:'withdrawn'},token)).data.request.status).toBe('withdrawn');var reinstate=await context.makeRequest('PUT','/approvals/requests/'+active.id+'/status',{status:'draft'},token);expect(reinstate.status).toBe(409);expect(reinstate.data.error.code).toBe('DECISIONS_IMMUTABLE');});
 test('withdraws and reinstates an undecided request without deleting its history',async function(){var request=(await context.makeRequest('POST','/approvals/requests',payload('TRIP-5'),token)).data.request;request=(await context.makeRequest('POST','/approvals/requests/'+request.id+'/submit',{},token)).data.request;expect((await context.makeRequest('PUT','/approvals/requests/'+request.id+'/status',{status:'withdrawn'},token)).data.request.status).toBe('withdrawn');var restored=(await context.makeRequest('PUT','/approvals/requests/'+request.id+'/status',{status:'draft'},token)).data.request;expect(restored.status).toBe('draft');expect(restored.stages.every(s=>s.status==='waiting')).toBe(true);});
});
