'use strict';
const helper=require('../../helpers/test-server');
const message=(id,recipients,scheduled_at)=>({title:'Field trip update',body:'The departure time has changed.',subject_component:'event_record',subject_type:'event',subject_id:id,scheduled_at:scheduled_at||null,recipients:recipients});
describe('communications component',function(){let context,token;beforeAll(async function(){context=await helper.createTestServer('communications');token=(await context.makeRequest('POST','/api/auth/dev-login',{})).data.token;});afterAll(async function(){if(context)await context.cleanup();});
 test('delivers in-app locally but leaves external channels truthfully queued',async function(){var created=(await context.makeRequest('POST','/communications',message('E-1',[{party_type:'staff',party_id:'S-1',channel:'in_app'},{party_type:'guardian',party_id:'G-1',channel:'email',address:'parent@example.test'}]),token)).data.communication;var sent=(await context.makeRequest('POST','/communications/'+created.id+'/dispatch',{},token)).data.communication;expect(sent.status).toBe('partially_delivered');expect(sent.recipients.map(r=>r.status)).toEqual(['delivered','queued']);expect(sent.recipients[1].provider_message_id).toBeNull();var read=await context.makeRequest('POST','/communications/'+created.id+'/recipients/'+sent.recipients[0].id+'/read',{},token);expect(read.data.communication.recipients[0].status).toBe('read');expect((await context.makeRequest('PUT','/communications/'+created.id,{title:'Rewrite'},token)).status).toBe(409);});
 test('holds scheduled in-app notifications until the due outbox is processed',async function(){var future=new Date(Date.now()+86400000).toISOString(),created=(await context.makeRequest('POST','/communications',message('E-2',[{party_type:'student',party_id:'ST-1',channel:'in_app'}],future),token)).data.communication;var queued=(await context.makeRequest('POST','/communications/'+created.id+'/dispatch',{},token)).data.communication;expect(queued.status).toBe('queued');expect((await context.makeRequest('POST','/communications/outbox/process',{},token)).data.processed).toBe(0);var db=require('../../../shared/services/db');db.query("UPDATE communications SET scheduled_at=datetime('now','-1 minute') WHERE id=?",[created.id]);expect((await context.makeRequest('POST','/communications/outbox/process',{},token)).data.processed).toBe(1);expect((await context.makeRequest('GET','/communications?q=Field&limit=50&page=1',null,token)).data.communications.find(x=>x.id===created.id).status).toBe('delivered');});
 test('withdrawal cancels undelivered recipients and only untouched messages can be reinstated',async function(){var draft=(await context.makeRequest('POST','/communications',message('E-3',[{party_type:'guardian',party_id:'G-2',channel:'sms',address:'+100000000'}]),token)).data.communication;expect((await context.makeRequest('PUT','/communications/'+draft.id+'/status',{status:'withdrawn'},token)).data.communication.recipients[0].status).toBe('cancelled');expect((await context.makeRequest('PUT','/communications/'+draft.id+'/status',{status:'draft'},token)).data.communication.recipients[0].status).toBe('pending');var partial=(await context.makeRequest('POST','/communications',message('E-4',[{party_type:'staff',party_id:'S-2',channel:'in_app'},{party_type:'guardian',party_id:'G-3',channel:'email',address:'g@example.test'}]),token)).data.communication;partial=(await context.makeRequest('POST','/communications/'+partial.id+'/dispatch',{},token)).data.communication;await context.makeRequest('PUT','/communications/'+partial.id+'/status',{status:'withdrawn'},token);var restore=await context.makeRequest('PUT','/communications/'+partial.id+'/status',{status:'draft'},token);expect(restore.status).toBe(409);expect(restore.data.error.code).toBe('DELIVERY_IMMUTABLE');});
 test('creates reusable templates and validates external addresses',async function(){var template=await context.makeRequest('POST','/communications/templates',{name:'Trip change',subject_template:'Trip update',body_template:'Please review the new time.',default_channel:'email'},token);expect(template.data.template.status).toBe('active');expect((await context.makeRequest('GET','/communications/templates',null,token)).data.templates).toHaveLength(1);var invalid=await context.makeRequest('POST','/communications',message('E-5',[{party_type:'guardian',party_id:'G-4',channel:'email'}]),token);expect(invalid.status).toBe(400);});
});
