import type { VisualFingerprint } from "../garment/visual-fingerprint.js";

export type StylingGarment=Readonly<{id:string;name:string;categorySlug:string;status:string;formality:number|null;seasons:readonly string[];fingerprintId:string|null;fingerprint:VisualFingerprint|null}>;
export type StylingContext=Readonly<{id:string;slug:string;name:string;formalityMin:number;formalityMax:number}>;
export type RuleParameters=Readonly<Record<string,Readonly<Record<string,number>>>>;
export type RuleOutcome=Readonly<{ruleId:string;domain:string;passed:boolean;hardFailure:boolean;scoreDelta:number;explanationCode:string;explanation:string;affectedGarmentIds:readonly string[];measurements:Readonly<Record<string,unknown>>}>;
export type StylingEvaluation=Readonly<{eligible:boolean;score:number;grade:"A"|"B"|"C"|null;strengths:readonly RuleOutcome[];cautions:readonly RuleOutcome[];majorPenalties:readonly RuleOutcome[];hardFailures:readonly RuleOutcome[];outcomes:readonly RuleOutcome[]}>;

const p=(parameters:RuleParameters,rule:string,key:string,fallback:number)=>parameters[rule]?.[key]??fallback;
const rounded=(value:number)=>Number(value.toFixed(3));
const outcome=(value:Omit<RuleOutcome,"affectedGarmentIds"|"measurements">&{affectedGarmentIds?:readonly string[];measurements?:Readonly<Record<string,unknown>>}):RuleOutcome=>Object.freeze({...value,affectedGarmentIds:value.affectedGarmentIds??[],measurements:value.measurements??{}});
function deltaE(first:readonly[number,number,number],second:readonly[number,number,number]){return Math.hypot(first[0]-second[0],first[1]-second[1],first[2]-second[2])}
function pairs<T>(items:readonly T[]):readonly(readonly[T,T])[]{const result:Array<readonly[T,T]>=[];for(let i=0;i<items.length;i++)for(let j=i+1;j<items.length;j++)result.push([items[i]!,items[j]!]);return result}

export function evaluateStyling(input:{garments:readonly StylingGarment[];context:StylingContext;season?:string|undefined;parameters?:RuleParameters|undefined;thresholds?:Readonly<{a:number;b:number;c:number}>|undefined}):StylingEvaluation{const params=input.parameters??{},outcomes:RuleOutcome[]=[];const ids=input.garments.map((g)=>g.id);const unavailable=input.garments.filter((g)=>g.status!=="available");outcomes.push(outcome({ruleId:"availability.required",domain:"availability",passed:unavailable.length===0,hardFailure:unavailable.length>0,scoreDelta:0,explanationCode:unavailable.length?"garment_unavailable":"all_available",explanation:unavailable.length?`${unavailable.map((g)=>g.name).join(", ")} cannot currently be worn.`:"Every selected garment is available.",affectedGarmentIds:unavailable.map((g)=>g.id)}));const missing=input.garments.filter((g)=>!g.fingerprint);outcomes.push(outcome({ruleId:"fingerprint.required",domain:"ensemble",passed:missing.length===0,hardFailure:missing.length>0,scoreDelta:0,explanationCode:missing.length?"fingerprint_missing":"fingerprints_present",explanation:missing.length?`${missing.map((g)=>g.name).join(", ")} needs photographic analysis before it can be scored.`:"Every garment has a versioned visual fingerprint.",affectedGarmentIds:missing.map((g)=>g.id)}));const outside=input.garments.filter((g)=>g.formality!==null&&(g.formality<input.context.formalityMin-p(params,"context.formality","tolerance",1)||g.formality>input.context.formalityMax+p(params,"context.formality","tolerance",1)));outcomes.push(outcome({ruleId:"context.formality",domain:"formality",passed:outside.length===0,hardFailure:outside.length>0,scoreDelta:0,explanationCode:outside.length?"context_formality_failure":"context_formality_valid",explanation:outside.length?`${outside.map((g)=>g.name).join(", ")} falls outside the ${input.context.name.toLowerCase()} formality range.`:`The garments fit the ${input.context.name.toLowerCase()} formality range.`,affectedGarmentIds:outside.map((g)=>g.id)}));
  const known=input.garments.filter((g)=>g.formality!==null).map((g)=>g.formality!),spread=known.length?Math.max(...known)-Math.min(...known):0,coherent=spread<=p(params,"formality.coherence","maximumSpread",1);outcomes.push(outcome({ruleId:"formality.coherence",domain:"formality",passed:coherent,hardFailure:false,scoreDelta:coherent?p(params,"formality.coherence","reward",7):p(params,"formality.coherence","penalty",-8),explanationCode:coherent?"formality_coherent":"formality_spread_high",explanation:coherent?"Formality is coherent across the ensemble.":`Formality varies by ${spread} levels across the ensemble.`,affectedGarmentIds:ids,measurements:{spread}}));
  const valid=input.garments.filter((g)=>g.fingerprint!==null),validPairs=pairs(valid),distances=validPairs.map(([a,b])=>deltaE(a.fingerprint!.combined.palette[0]!.lab,b.fingerprint!.combined.palette[0]!.lab)),averageDelta=distances.length?distances.reduce((s,v)=>s+v,0)/distances.length:30;let colourDelta=p(params,"colour.contrast","reward",8),colourCode="colour_contrast_controlled",colourText=`Dominant-colour separation is controlled (average ΔE ${averageDelta.toFixed(1)}).`;if(averageDelta<p(params,"colour.contrast","low",8)){colourDelta=p(params,"colour.contrast","matchingPenalty",-12);colourCode="colour_matching_excessive";colourText=`Dominant colours are extremely similar (average ΔE ${averageDelta.toFixed(1)}).`;}else if(averageDelta>p(params,"colour.contrast","high",70)){colourDelta=p(params,"colour.contrast","clashPenalty",-5);colourCode="colour_contrast_extreme";colourText=`Dominant-colour contrast is unusually high (average ΔE ${averageDelta.toFixed(1)}).`;}outcomes.push(outcome({ruleId:"colour.contrast",domain:"colour",passed:colourDelta>=0,hardFailure:false,scoreDelta:colourDelta,explanationCode:colourCode,explanation:colourText,affectedGarmentIds:ids,measurements:{averageDeltaE:rounded(averageDelta)}}));
  const patterned=valid.filter((g)=>g.fingerprint!.combined.solidConfidence<.65),patternDiffs=pairs(patterned).map(([a,b])=>Math.abs(a.fingerprint!.combined.patternDensity-b.fingerprint!.combined.patternDensity)),minimumPatternDifference=patternDiffs.length?Math.min(...patternDiffs):1,patternSeparated=minimumPatternDifference>=p(params,"pattern.scale","minimumDensityDifference",.04);outcomes.push(outcome({ruleId:"pattern.scale",domain:"pattern",passed:patternSeparated,hardFailure:false,scoreDelta:patternSeparated?p(params,"pattern.scale","reward",6):p(params,"pattern.scale","penalty",-10),explanationCode:patternSeparated?"pattern_scale_separated":"pattern_scale_too_similar",explanation:patterned.length<2?"The ensemble does not contain competing active patterns.":patternSeparated?"Active patterns have useful scale separation.":"Multiple active patterns have nearly identical density and may compete.",affectedGarmentIds:patterned.map((g)=>g.id),measurements:{patternedItems:patterned.length,minimumPatternDifference:rounded(minimumPatternDifference)}}));
  const complexity=valid.reduce((s,g)=>s+g.fingerprint!.combined.visualComplexity,0);let complexityDelta=p(params,"ensemble.complexity","reward",4),complexityCode="complexity_controlled";if(complexity>p(params,"ensemble.complexity","high",1.6)){complexityDelta=p(params,"ensemble.complexity","highPenalty",-12);complexityCode="complexity_excessive";}else if(complexity>p(params,"ensemble.complexity","low",1.1)){complexityDelta=p(params,"ensemble.complexity","mediumPenalty",-6);complexityCode="complexity_elevated";}outcomes.push(outcome({ruleId:"ensemble.complexity",domain:"ensemble",passed:complexityDelta>=0,hardFailure:false,scoreDelta:complexityDelta,explanationCode:complexityCode,explanation:complexityDelta>=0?"Cumulative visual complexity remains controlled.":complexityDelta<=-12?"Too many visually active elements compete for attention.":"Overall visual complexity is elevated.",affectedGarmentIds:ids,measurements:{cumulativeComplexity:rounded(complexity)}}));
  const textures=valid.map((g)=>g.fingerprint!.combined.textureStrength),textureDifference=textures.length>1?Math.max(...textures)-Math.min(...textures):0,textureSeparated=textures.length<2||textureDifference>=p(params,"texture.balance","minimumDifference",.08);outcomes.push(outcome({ruleId:"texture.balance",domain:"texture",passed:textureSeparated,hardFailure:false,scoreDelta:textureSeparated?p(params,"texture.balance","reward",4):p(params,"texture.balance","penalty",-3),explanationCode:textureSeparated?"texture_separation_useful":"texture_repetition_flat",explanation:textureSeparated?"Texture relationships provide useful separation.":"Texture is repeated very closely across the ensemble.",affectedGarmentIds:ids,measurements:{textureDifference:rounded(textureDifference)}}));
  const tie=valid.find((g)=>g.categorySlug==="ties"),square=valid.find((g)=>g.categorySlug==="pocket-squares");let duplicate=false,duplicateDelta=0,duplicatePattern=1;if(tie&&square){const d=deltaE(tie.fingerprint!.combined.palette[0]!.lab,square.fingerprint!.combined.palette[0]!.lab);duplicatePattern=Math.abs(tie.fingerprint!.combined.patternDensity-square.fingerprint!.combined.patternDensity);duplicate=d<p(params,"tie_square.duplication","maximumDeltaE",10)&&duplicatePattern<p(params,"tie_square.duplication","maximumPatternDifference",.03);duplicateDelta=duplicate?p(params,"tie_square.duplication","penalty",-15):4;}outcomes.push(outcome({ruleId:"tie_square.duplication",domain:"ensemble",passed:!duplicate,hardFailure:false,scoreDelta:duplicateDelta,explanationCode:duplicate?"tie_square_duplicate":"tie_square_complement",explanation:!tie||!square?"Tie and pocket-square duplication is not applicable.":duplicate?"Tie and pocket square are too similar in dominant colour and pattern activity.":"Tie and pocket square complement one another without direct duplication.",affectedGarmentIds:tie&&square?[tie.id,square.id]:[],measurements:{patternDensityDifference:rounded(duplicatePattern)}}));
  if(input.season){const unsuitable=input.garments.filter((g)=>g.seasons.length>0&&!g.seasons.includes("all-season")&&!g.seasons.includes(input.season!)),suitable=unsuitable.length===0;outcomes.push(outcome({ruleId:"season.suitability",domain:"season",passed:suitable,hardFailure:false,scoreDelta:suitable?p(params,"season.suitability","reward",3):p(params,"season.suitability","penalty",-10),explanationCode:suitable?"season_suitable":"season_mismatch",explanation:suitable?`All garments support ${input.season}.`:`${unsuitable.map((g)=>g.name).join(", ")} is not marked for ${input.season}.`,affectedGarmentIds:unsuitable.map((g)=>g.id)}));}
  const eligible=!outcomes.some((value)=>value.hardFailure),score=rounded(Math.max(0,Math.min(100,70+outcomes.reduce((sum,value)=>sum+value.scoreDelta,0)))),thresholds=input.thresholds??{a:85,b:72,c:60},grade=!eligible?null:score>=thresholds.a?"A":score>=thresholds.b?"B":score>=thresholds.c?"C":null;return Object.freeze({eligible,score,grade,strengths:Object.freeze(outcomes.filter((value)=>!value.hardFailure&&value.scoreDelta>0)),cautions:Object.freeze(outcomes.filter((value)=>!value.hardFailure&&value.scoreDelta<0&&value.scoreDelta>-10)),majorPenalties:Object.freeze(outcomes.filter((value)=>!value.hardFailure&&value.scoreDelta<=-10)),hardFailures:Object.freeze(outcomes.filter((value)=>value.hardFailure)),outcomes:Object.freeze(outcomes)});}
