import React, {useMemo,useState} from 'react';
const day = value => Date.parse(`${value}T00:00:00Z`) / 86400000;
export default function Timeline({instance,selected,onSelect}) {
 const [scale,setScale]=useState('fit'),[anchor,setAnchor]=useState(instance.local_date);
 const dated=instance.tasks.filter(t=>t.available_on||t.due_on);
 const undated=instance.tasks.filter(t=>!t.available_on&&!t.due_on);
 const range=useMemo(()=>{const dates=[instance.local_date,instance.target_on,...dated.flatMap(t=>[t.available_on,t.due_on]),...instance.milestones.map(m=>m.target_on)].filter(Boolean).map(day);let start=Math.min(...dates)-1,end=Math.max(...dates)+1;if(scale!=='fit'){const span={day:28,week:84,month:366}[scale];start=day(anchor||instance.local_date)-7;end=start+span-1;}return {start,end,span:Math.max(7,end-start+1)};},[instance,scale,anchor]);
 const width=Math.max(750,Math.min(2400,range.span*35)),x=value=>(day(value)-range.start+.5)/range.span*width;
 const tasks=[...dated].filter(t=>day(t.due_on||t.available_on)>=range.start&&day(t.available_on||t.due_on)<=range.end).sort((a,b)=>instance.phases.findIndex(p=>p.id===a.phase_id)-instance.phases.findIndex(p=>p.id===b.phase_id)||String(a.available_on||a.due_on).localeCompare(String(b.available_on||b.due_on)));
 const index=new Map(tasks.map((t,i)=>[t.id,i]));const rowHeight=64;
 return <section aria-label="Work Timeline"><div className="ex-toolbar"><label>Scale <select value={scale} onChange={e=>setScale(e.target.value)}><option value="fit">Fit all dates</option><option value="day">Day · four weeks</option><option value="week">Week · twelve weeks</option><option value="month">Month · one year</option></select></label>{scale!=='fit'&&<label>Around <input type="date" value={anchor} onChange={e=>setAnchor(e.target.value)}/></label>}</div><p className="ex-muted">Availability and due dates, not estimated effort. Select work to see its direct handoffs. ◆ Event and milestone dates; dashed line = today.</p>{tasks.length<dated.length&&<p className="ex-warning">{dated.length-tasks.length} dated tasks are outside this range. Readiness still includes every dependency. <button onClick={()=>setScale('fit')}>Fit all dates</button></p>}<div className="ex-timeline-scroll"><div className="ex-timeline" style={{width:width+300}}><div className="ex-timeline-labels"><div style={{height:48}}>Task / phase</div>{tasks.map(t=><button key={t.id} onClick={()=>onSelect(t.id)} className={selected===t.id?'selected':''} style={{height:rowHeight}}><strong>{t.title}</strong><small>{instance.phases.find(p=>p.id===t.phase_id)?.title||'No phase'} · {t.person_name||'Unassigned'} · {t.state}</small></button>)}</div><svg width={width} height={48+tasks.length*rowHeight+55} role="img" aria-label="Dated tasks and direct dependencies; task names and statuses are also available in the Tasks view"><defs><marker id="ex-arrow" markerWidth="7" markerHeight="7" refX="6" refY="3.5" orient="auto"><path d="M0 0 L7 3.5 L0 7" fill="currentColor"/></marker></defs>
 {Array.from({length:Math.min(12,range.span)},(_,i)=>{const value=range.start+Math.round(i*range.span/Math.min(12,range.span));const xx=(value-range.start+.5)/range.span*width;return <g key={i}><line x1={xx} x2={xx} y1={35} y2={48+tasks.length*rowHeight} stroke="#475569" opacity=".25"/><text x={xx} y={24} textAnchor="middle" fill="currentColor" fontSize="12">{new Date(value*86400000).toLocaleDateString('en-GB',{day:'numeric',month:'short',timeZone:'UTC'})}</text></g>})}
 <line x1={x(instance.local_date)} x2={x(instance.local_date)} y1={35} y2={48+tasks.length*rowHeight} stroke="#fbbf24" strokeDasharray="5 5"/><text x={x(instance.local_date)+4} y={44} fill="#fbbf24" fontSize="11">Today</text>
 {tasks.map((t,i)=>{const start=x(t.available_on||t.due_on),end=x(t.due_on||t.available_on),y=48+i*rowHeight;return <g key={t.id}><rect x={0} y={y} width={width} height={rowHeight} fill={selected===t.id?'#6366f122':'transparent'}/>{t.available_on&&t.due_on?<rect x={start} y={y+10} width={Math.max(8,end-start)} height={26} rx={5} fill={t.lifecycle==='completed'?'#64748b':'#6366f1'}/>:<path d={`M${start},${y+8} l12,15 -12,15 -12,-15 Z`} fill="#818cf8"/>}<text x={start+4} y={y+53} fontSize="11" fill="currentColor">{t.available_on||'Start unknown'} → {t.due_on||'Due unknown'}</text></g>})}
 {instance.dependencies.filter(e=>e.state==='active'&&(e.from_id===selected||e.to_id===selected)&&index.has(e.from_id)&&index.has(e.to_id)).map(e=>{const a=tasks[index.get(e.from_id)],b=tasks[index.get(e.to_id)],ax=x(a.due_on||a.available_on),bx=x(b.available_on||b.due_on),ay=48+index.get(a.id)*rowHeight+39,by=48+index.get(b.id)*rowHeight+39,mid=Math.min(width-10,Math.max(ax,bx)+16);return <path key={e.id} d={`M${ax},${ay} H${mid} V${by} H${bx}`} stroke="currentColor" strokeWidth={1.5} fill="none" markerEnd="url(#ex-arrow)"/>})}
 {[...(instance.target_on?[{id:'event',title:'Event',target_on:instance.target_on}]:[]),...instance.milestones.filter(m=>m.target_on)].map((m,i)=><g key={m.id}><line x1={x(m.target_on)} x2={x(m.target_on)} y1={45} y2={48+tasks.length*rowHeight} stroke="#a78bfa" strokeDasharray="2 6"/><text x={x(m.target_on)} y={48+tasks.length*rowHeight+16+(i%2)*18} textAnchor="middle" fontSize="11" fill="currentColor">◆ {m.title}</text></g>)}
 </svg></div></div>{undated.length>0&&<div className="ex-panel"><h3>Unscheduled work</h3><p>Dates can remain unknown.</p>{undated.map(t=><button key={t.id} onClick={()=>onSelect(t.id)}>{t.title}</button>)}</div>}</section>;
}
