'use strict';
const appScope=require('../../shared/services/appScope');
const schedule=require('./schedule');
const intake=require('./intake');
const reconciliation=require('./reconciliation');
const equivalence=require('./equivalence');
const workflows=require('./workflows');
const dashboardProvider=require('./dashboard');
const analyticsProvider=require('./analytics');
const access=require('./access');
const hardening=require('./hardening');
function scope(req){return appScope.fromRequest(req)}function bad(message,code,statusCode){return{success:false,statusCode:statusCode||400,error:{code:code||'VALIDATION_ERROR',message}}}function text(v){return String(v==null?'':v).trim()}function emit(ctx,event,row){ctx.events.publish(event,{entityId:row.id,record:row,__module:'late_entries'})}function boot(ctx){ctx.log.info('late_entries attendance reconciliation foundation ready',{module:'late_entries'})}function teardown(){}
function hydratePolicy(row){if(!row)return row;try{row.rules=JSON.parse(row.rules_json)}catch(_){row.rules={}}delete row.rules_json;row.count_excused=Boolean(row.count_excused);return row}
async function listPolicies(req,ctx){const appId=scope(req),rows=ctx.db.query('SELECT * FROM late_entry_policy_versions WHERE app_id=? ORDER BY version DESC',[appId]).rows.map(hydratePolicy);return{success:true,policies:rows,active:rows.find(x=>x.status==='active')||null}}
async function createPolicy(req,ctx){const appId=scope(req),b=req.body||{},effective=text(b.effective_from);if(!/^\d{4}-\d{2}-\d{2}$/.test(effective))return bad('Policy effective date is required');for(const key of ['school_day_grace_minutes','class_grace_minutes'])if(b[key]!=null&&(!Number.isInteger(Number(b[key]))||Number(b[key])<0))return bad('Grace periods must be whole non-negative minutes');for(const key of ['school_tardies_per_absence','class_tardies_per_absence'])if(b[key]!=null&&(!Number.isInteger(Number(b[key]))||Number(b[key])<1))return bad('Tardy equivalence must be a positive whole number or blank');const version=Number(ctx.db.query('SELECT COALESCE(MAX(version),0)+1 version FROM late_entry_policy_versions WHERE app_id=?',[appId]).rows[0].version),x=ctx.db.query('INSERT INTO late_entry_policy_versions(app_id,version,effective_from,effective_to,school_day_grace_minutes,class_grace_minutes,school_tardies_per_absence,class_tardies_per_absence,count_excused,rules_json,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?)',[appId,version,effective,b.effective_to||null,Number(b.school_day_grace_minutes||0),Number(b.class_grace_minutes||0),b.school_tardies_per_absence==null?null:Number(b.school_tardies_per_absence),b.class_tardies_per_absence==null?null:Number(b.class_tardies_per_absence),b.count_excused?1:0,JSON.stringify(b.rules||{}),String(req.user.id)]),row=hydratePolicy(ctx.db.query('SELECT * FROM late_entry_policy_versions WHERE id=?',[x.lastInsertRowid]).rows[0]);ctx.db.query('INSERT INTO late_entry_audit(app_id,action,actor_id,new_value_json) VALUES(?,?,?,?)',[appId,'policy_created',String(req.user.id),JSON.stringify(row)]);emit(ctx,'late_entry.policy_created',row);return{success:true,policy:row,human_confirmation_required:true}}
async function activatePolicy(req,ctx){const appId=scope(req),row=ctx.db.query("SELECT * FROM late_entry_policy_versions WHERE id=? AND app_id=? AND status='draft'",[req.params.id,appId]).rows[0];if(!row)return bad('Draft policy not found','NOT_FOUND',404);if(req.body?.confirmed_by_human!==true)return bad('Explicit human confirmation is required','HUMAN_CONFIRMATION_REQUIRED',409);ctx.db.transaction(db=>{db.query("UPDATE late_entry_policy_versions SET status='retired',effective_to=COALESCE(effective_to,date(?,'-1 day')) WHERE app_id=? AND status='active'",[row.effective_from,appId]);db.query("UPDATE late_entry_policy_versions SET status='active',confirmed_by=?,confirmed_at=datetime('now') WHERE id=?",[String(req.user.id),row.id]);db.query('INSERT INTO late_entry_audit(app_id,action,actor_id,old_value_json,new_value_json) VALUES(?,?,?,?,?)',[appId,'policy_activated',String(req.user.id),JSON.stringify(hydratePolicy({...row})),JSON.stringify({id:row.id,status:'active'})])});const next=hydratePolicy(ctx.db.query('SELECT * FROM late_entry_policy_versions WHERE id=?',[row.id]).rows[0]);emit(ctx,'late_entry.policy_activated',next);return{success:true,policy:next}}
async function listReasons(req,ctx){const appId=scope(req);return{success:true,reasons:ctx.db.query('SELECT * FROM late_entry_reasons WHERE app_id=? ORDER BY label',[appId]).rows.map(x=>({...x,evidence_required:Boolean(x.evidence_required),restricted:Boolean(x.restricted),enabled:Boolean(x.enabled)}))}}
async function saveReason(req,ctx){const appId=scope(req),b=req.body||{},code=text(b.code);if(!/^[a-z][a-z0-9_]*$/.test(code)||!text(b.label)||!['excused','unexcused','pending'].includes(b.classification))return bad('Valid reason code, label and classification are required');ctx.db.query("INSERT INTO late_entry_reasons(app_id,code,label,classification,evidence_required,restricted,enabled) VALUES(?,?,?,?,?,?,?) ON CONFLICT(app_id,code) DO UPDATE SET label=excluded.label,classification=excluded.classification,evidence_required=excluded.evidence_required,restricted=excluded.restricted,enabled=excluded.enabled,updated_at=datetime('now')",[appId,code,text(b.label),b.classification,b.evidence_required?1:0,b.restricted?1:0,b.enabled===false?0:1]);const row=ctx.db.query('SELECT * FROM late_entry_reasons WHERE app_id=? AND code=?',[appId,code]).rows[0];ctx.db.query('INSERT INTO late_entry_audit(app_id,action,actor_id,new_value_json) VALUES(?,?,?,?)',[appId,'reason_configured',String(req.user.id),JSON.stringify(row)]);emit(ctx,'late_entry.reason_configured',row);return listReasons(req,ctx)}
async function insights(req,ctx){const appId=scope(req),policies=Number(ctx.db.query('SELECT COUNT(*) n FROM late_entry_policy_versions WHERE app_id=?',[appId]).rows[0].n),active=ctx.db.query("SELECT id,version,effective_from FROM late_entry_policy_versions WHERE app_id=? AND status='active'",[appId]).rows[0],reasons=Number(ctx.db.query('SELECT COUNT(*) n FROM late_entry_reasons WHERE app_id=? AND enabled=1',[appId]).rows[0].n),issues=[];if(!active)issues.push({severity:'warning',message:'No attendance lateness policy has been reviewed and activated.'});if(!reasons)issues.push({severity:'critical',message:'No enabled late-entry reasons are available.'});return{success:true,insights:{readiness:active?'intake_contract_ready':'configuration_required',counts:{policy_versions:policies,enabled_reasons:reasons},active_policy:active||null,health:{heartbeat:'ok',migrations:1,decision_automation:false},issues,human_confirmation_required:true}}}
module.exports={boot,teardown,listPolicies,createPolicy,activatePolicy,listReasons,saveReason,insights:analyticsProvider.insights,previewContext:schedule.preview,create:intake.create,list:intake.list,read:intake.read,history:intake.history,proposeReconciliation:reconciliation.propose,applyReconciliation:reconciliation.apply,rejectReconciliation:reconciliation.reject,calculateEquivalence:equivalence.calculate,confirmEquivalence:equivalence.confirm,listEquivalences:equivalence.list,listThresholds:workflows.listDefinitions,saveThreshold:workflows.saveDefinition,evaluateThresholds:workflows.evaluate,decideThreshold:workflows.decide,listThresholdCases:workflows.listCases,dashboard:dashboardProvider.dashboard,retryContext:dashboardProvider.retryContext,analytics:analyticsProvider.analytics,studentProfileContribution:analyticsProvider.studentContribution,staffProfileContribution:analyticsProvider.staffContribution,correct:hardening.correct,resolveException:hardening.resolveException,getActionPolicy:access.getPolicy,saveActionPolicy:access.savePolicy};
