'use strict';const appScope=require('../../shared/services/appScope');function boot(c){c.log.info('academic_commentary booting',{module:'academic_commentary'})}function teardown(){}function scope(r){return appScope.fromRequest(r)}function text(v){return String(v==null?'':v).trim()}function bad(m,x,s){return{success:false,statusCode:s||400,error:{code:x||'VALIDATION_ERROR',message:m}}}function emit(c,ch,row){c.events.publish(ch,{entityId:row.id,record:row,__module:'academic_commentary'})}
function result(c,id,s,gid,student){return c.db.query('SELECT gr.* FROM grade_results gr JOIN gradebook_instances g ON g.id=gr.gradebook_id WHERE gr.id=? AND gr.gradebook_id=? AND gr.student_id=? AND g.app_id=?',[id,gid,student,s]).rows[0]}
function studentName(c,id){const x=c.db.query('SELECT preferred_name,first_name FROM students WHERE student_id=?',[id]).rows[0];return x?text(x.preferred_name)||text(x.first_name)||'The student':'The student'}
function context(c,gid,student,period){const behaviours=c.db.query("SELECT i.domain,AVG(l.numeric_value) average,COUNT(*) count FROM behaviour_observations o JOIN behaviour_indicators i ON i.id=o.indicator_id JOIN assessment_scale_levels l ON l.id=o.scale_level_id WHERE o.gradebook_id=? AND o.student_id=? AND o.status='active' GROUP BY i.domain ORDER BY i.domain",[gid,student]).rows,attendance=c.db.query("SELECT m.attendance_status,COUNT(*) count FROM class_attendance_marks m JOIN class_attendance_sessions s ON s.id=m.session_id WHERE s.gradebook_id=? AND m.student_id=? AND m.status='active' GROUP BY m.attendance_status",[gid,student]).rows;return{behaviours,attendance,reporting_period_id:period||null}}
function narrative(name,grade,ctx){let outcome=grade.overridden_value!=null?grade.overridden_value:(grade.text_result||grade.numeric_result),parts=[name+' has a current academic outcome of '+(outcome==null?'insufficient evidence':outcome)+'.'];if(grade.confidence==='insufficient')parts.push('Further academic evidence is needed before drawing a secure conclusion.');else parts.push('This outcome is based on '+JSON.parse(grade.source_evidence_json).length+' current evidence item(s).');if(ctx.behaviours.length)parts.push('Learning behaviour observations are available across '+ctx.behaviours.map(x=>x.domain).join(', ')+'.');const absent=ctx.attendance.find(x=>x.attendance_status==='absent');if(absent)parts.push('Recorded classroom absences in this context: '+absent.count+'.');return parts.join(' ')}
async function generate(r,c){const s=scope(r),student=text(r.params.studentId),b=r.body||{},grade=result(c,b.grade_result_id,s,r.params.id,student);if(!grade)return bad('Grade result not found','NOT_FOUND',404);const ctx=context(c,+r.params.id,student,grade.reporting_period_id),snapshot={grade_result:grade,context:ctx},v=+c.db.query('SELECT COALESCE(MAX(version),0)+1 v FROM academic_commentary_drafts WHERE gradebook_id=? AND student_id=? AND reporting_period_id IS ?',[r.params.id,student,grade.reporting_period_id]).rows[0].v,previous=c.db.query('SELECT id FROM academic_commentary_drafts WHERE gradebook_id=? AND student_id=? AND reporting_period_id IS ? ORDER BY version DESC LIMIT 1',[r.params.id,student,grade.reporting_period_id]).rows[0],x=c.db.query('INSERT INTO academic_commentary_drafts(app_id,gradebook_id,student_id,reporting_period_id,grade_result_id,version,content,input_snapshot_json,created_by,supersedes_id) VALUES(?,?,?,?,?,?,?,?,?,?)',[s,r.params.id,student,grade.reporting_period_id,grade.id,v,narrative(studentName(c,student),grade,ctx),JSON.stringify(snapshot),String(r.user.id),previous?.id||null]),row=c.db.query('SELECT * FROM academic_commentary_drafts WHERE id=?',[x.lastInsertRowid]).rows[0];emit(c,'academic_commentary.generated',row);return{success:true,draft:row}}
function owned(c,id,s){return c.db.query('SELECT * FROM academic_commentary_drafts WHERE id=? AND app_id=?',[id,s]).rows[0]}
async function edit(r,c){const old=owned(c,r.params.id,scope(r)),content=text((r.body||{}).content);if(!old)return bad('Draft not found','NOT_FOUND',404);if(!content)return bad('Commentary content is required');const v=+c.db.query('SELECT MAX(version)+1 v FROM academic_commentary_drafts WHERE gradebook_id=? AND student_id=? AND reporting_period_id IS ?',[old.gradebook_id,old.student_id,old.reporting_period_id]).rows[0].v,x=c.db.query("INSERT INTO academic_commentary_drafts(app_id,gradebook_id,student_id,reporting_period_id,grade_result_id,version,content,input_snapshot_json,status,generated,created_by,supersedes_id) VALUES(?,?,?,?,?,?,?,?, 'draft',0,?,?)",[old.app_id,old.gradebook_id,old.student_id,old.reporting_period_id,old.grade_result_id,v,content,old.input_snapshot_json,String(r.user.id),old.id]),row=c.db.query('SELECT * FROM academic_commentary_drafts WHERE id=?',[x.lastInsertRowid]).rows[0];emit(c,'academic_commentary.edited',row);return{success:true,draft:row}}
async function markReady(r,c){const row=owned(c,r.params.id,scope(r));if(!row)return bad('Draft not found','NOT_FOUND',404);c.db.query("UPDATE academic_commentary_drafts SET status='ready',updated_at=datetime('now') WHERE id=?",[row.id]);const next=owned(c,row.id,row.app_id);emit(c,'academic_commentary.ready',next);return{success:true,draft:next}}
async function list(r,c){const s=scope(r),p=[r.params.id,text(r.params.studentId),s],w=['gradebook_id=?','student_id=?','app_id=?'];if(r.query.reporting_period_id){w.push('reporting_period_id=?');p.push(r.query.reporting_period_id)}return{success:true,drafts:c.db.query('SELECT * FROM academic_commentary_drafts WHERE '+w.join(' AND ')+' ORDER BY version DESC',p).rows}}
const commentaryContext=context;context=function(c,gid,student,period){const base=commentaryContext(c,gid,student,period);if(!period)return base;const p=c.db.query('SELECT * FROM reporting_periods WHERE id=?',[period]).rows[0];if(!p)return base;base.behaviours=c.db.query("SELECT i.domain,AVG(l.numeric_value) average,COUNT(*) count FROM behaviour_observations o JOIN behaviour_indicators i ON i.id=o.indicator_id JOIN assessment_scale_levels l ON l.id=o.scale_level_id WHERE o.gradebook_id=? AND o.student_id=? AND o.status='active' AND o.observed_at BETWEEN ? AND ? GROUP BY i.domain ORDER BY i.domain",[gid,student,p.starts_on,p.ends_on]).rows;base.attendance=c.db.query("SELECT m.attendance_status,COUNT(*) count FROM class_attendance_marks m JOIN class_attendance_sessions s ON s.id=m.session_id WHERE s.gradebook_id=? AND m.student_id=? AND m.status='active' AND s.session_date BETWEEN ? AND ? GROUP BY m.attendance_status",[gid,student,p.starts_on,p.ends_on]).rows;return base};
module.exports={boot,teardown,generate,edit,markReady,list};
for(const name of ['generate','edit']){const original=module.exports[name];module.exports[name]=function(r,c){let promise;c.db.transaction(()=>{promise=original(r,c)});return promise}}
