'use strict';
const appScope = require('../../shared/services/appScope');
const access = require('./access');
const campus = require('./campus');
const relationships = require('./relationships');
const operations = require('./operations');
const insightProvider = require('./insights');
const TERMINAL = new Set(['checked_in', 'closed', 'cancelled', 'denied']);
const TRANSITIONS = { requested: ['approved', 'denied', 'cancelled'], approved: ['checked_out', 'cancelled'], checked_out: ['received', 'returned', 'closed', 'escalated'], received: ['returned', 'closed', 'escalated'], returned: ['checked_in', 'escalated'], escalated: ['returned', 'checked_in', 'closed', 'cancelled'] };
function boot(c) { c.log.info('student_exits governance and state engine ready', { module: 'student_exits' }); }
function teardown() {}
function bad(message, code, statusCode) { return { success: false, statusCode: statusCode || 400, error: { code: code || 'VALIDATION_ERROR', message } }; }
function scope(r) { return appScope.fromRequest(r); }
function get(c, id, appId) { return c.db.query('SELECT * FROM student_exits WHERE id=? AND app_id=?', [id, appId]).rows[0]; }
function parseWorkflow(row) { try { return JSON.parse(row.workflow_json); } catch (_) { return null; } }
function allowedTargets(record, workflow) { if (!record || TERMINAL.has(record.status)) return []; const configured = new Set((workflow && workflow.states) || []); return (TRANSITIONS[record.status] || []).filter(target => target === 'escalated' || target === 'cancelled' || configured.has(target)); }
function hydrate(c, row, r) { if (!row) return row; const type = c.db.query('SELECT label,workflow_json,operational_visibility FROM student_exit_types WHERE app_id=? AND code=?', [row.app_id, row.exit_type_code]).rows[0], visible = !type || type.operational_visibility !== 'restricted' || !r || access.can(r, c, row.app_id, 'restricted_view'), copy = Object.assign({}, row, { exit_type_label: type ? type.label : row.exit_type_code }); if (!visible) { copy.operational_reason = 'Authorised student support'; delete copy.restricted_reference_type; delete copy.restricted_reference_id; } copy.next_actions = allowedTargets(row, type && parseWorkflow(type)).filter(target => !r || access.can(r, c, row.app_id, actionFor(row, target))); return copy; }
function actionFor(row, target) { if (target === 'approved' || target === 'denied') return row.movement_mode === 'campus_release' ? 'campus_authorise' : 'approve'; if (target === 'checked_out') return row.movement_mode === 'campus_release' ? 'campus_release' : 'release'; if (target === 'received') return 'receive'; if (target === 'returned') return 'return'; if (target === 'checked_in' || target === 'closed') return 'check_in'; if (target === 'cancelled') return 'cancel'; return 'release'; }
async function list(r, c) { const appId = scope(r), denied = access.requireAction(r,c,appId,'read'); if(denied)return denied; const q = r.query || {}, page = Math.max(1, Number(q.page) || 1), limit = Math.min(50, Math.max(1, Number(q.limit) || 50)), where = ['app_id=?'], params = [appId]; if(String(q.live)==='true')where.push("status NOT IN ('checked_in','closed','cancelled','denied')"); for (const key of ['status', 'student_id', 'exit_type_code', 'destination_room_id', 'released_by_staff_id', 'movement_mode']) if (q[key]) { where.push(key + '=?'); params.push(String(q[key])); } const clause = ' WHERE ' + where.join(' AND '), total = c.db.query('SELECT COUNT(*) total FROM student_exits' + clause, params).rows[0].total, rows = c.db.query('SELECT * FROM student_exits' + clause + ' ORDER BY created_at DESC,id DESC LIMIT ? OFFSET ?', params.concat([limit, (page - 1) * limit])).rows.map(row => hydrate(c, row, r)); return { success: true, exits: rows, total: Number(total), page, limit }; }
async function read(r, c) { const appId=scope(r),denied=access.requireAction(r,c,appId,'read');if(denied)return denied; const row = get(c, r.params.id, appId); return row ? { success: true, exit: hydrate(c, row, r) } : bad('Student exit not found', 'NOT_FOUND', 404); }
async function history(r, c) { const appId = scope(r),denied=access.requireAction(r,c,appId,'read');if(denied)return denied; const row = get(c, r.params.id, appId); if (!row) return bad('Student exit not found', 'NOT_FOUND', 404); const transitions = c.db.query('SELECT * FROM student_exit_transitions WHERE app_id=? AND student_exit_id=? ORDER BY occurred_at,id', [appId, row.id]).rows.map(x=>{if(!access.can(r,c,appId,'restricted_view'))x.operational_note=null;return x}); return { success: true, exit: hydrate(c, row, r), transitions }; }
async function nextActions(r, c) { const result = await read(r, c); return result.success ? { success: true, status: result.exit.status, actions: result.exit.next_actions } : result; }
async function dashboard(r,c){const appId=scope(r),denied=access.requireAction(r,c,appId,'read');if(denied)return denied;const q=r.query||{},where=['e.app_id=?'],params=[appId];for(const key of ['student_id','exit_type_code','destination_room_id','released_by_staff_id','movement_mode'])if(q[key]){where.push('e.'+key+'=?');params.push(String(q[key]))}const clause=' WHERE '+where.join(' AND '),row=c.db.query("SELECT COUNT(*) total,SUM(CASE WHEN e.status NOT IN ('checked_in','closed','cancelled','denied') THEN 1 ELSE 0 END) current_exited,SUM(CASE WHEN e.status NOT IN ('checked_in','closed','cancelled','denied') AND e.expected_return_at IS NOT NULL AND julianday(e.expected_return_at)<julianday('now') THEN 1 ELSE 0 END) overdue,SUM(CASE WHEN e.status='checked_out' AND e.movement_mode='destination_handoff' THEN 1 ELSE 0 END) awaiting_receipt,SUM(CASE WHEN e.status='escalated' THEN 1 ELSE 0 END) escalated,SUM(CASE WHEN e.status IN ('requested','approved') THEN 1 ELSE 0 END) awaiting_approval,SUM(CASE WHEN e.movement_mode='campus_release' AND e.status IN ('requested','approved') THEN 1 ELSE 0 END) awaiting_collection,SUM(CASE WHEN e.movement_mode='campus_release' AND e.status NOT IN ('checked_in','closed','cancelled','denied') THEN 1 ELSE 0 END) off_campus_or_pending,SUM(CASE WHEN e.movement_mode='campus_release' AND e.status IN ('checked_out','received','escalated') THEN 1 ELSE 0 END) unresolved_custody FROM student_exits e"+clause,params).rows[0]||{},attention=c.db.query("SELECT e.*,s.first_name student_first_name,s.last_name student_last_name,st.first_name released_by_first_name,st.last_name released_by_last_name FROM student_exits e LEFT JOIN students s ON s.student_id=e.student_id LEFT JOIN staff st ON st.staff_id=e.released_by_staff_id"+clause+" AND e.status NOT IN ('checked_in','closed','cancelled','denied') AND (e.status='escalated' OR (e.expected_return_at IS NOT NULL AND julianday(e.expected_return_at)<julianday('now'))) ORDER BY CASE WHEN e.status='escalated' THEN 0 ELSE 1 END,e.expected_return_at LIMIT 50",params).rows.map(x=>hydrate(c,x,r));return{success:true,summary:{total:Number(row.total||0),current_exited:Number(row.current_exited||0),overdue:Number(row.overdue||0),awaiting_receipt:Number(row.awaiting_receipt||0),escalated:Number(row.escalated||0),awaiting_approval:Number(row.awaiting_approval||0),awaiting_collection:Number(row.awaiting_collection||0),off_campus_or_pending:Number(row.off_campus_or_pending||0),unresolved_custody:Number(row.unresolved_custody||0)},attention,refreshed_at:new Date().toISOString()};}
async function create(r, c) {
  const appId = scope(r), body = r.body || {}; if (!body.student_id || !body.exit_type_code) return bad('Student and exit type are required');
  if (body.client_request_id) { const existing = c.db.query('SELECT * FROM student_exits WHERE app_id=? AND client_request_id=?',[appId,String(body.client_request_id)]).rows[0]; if(existing)return{success:true,exit:hydrate(c,existing,r),duplicate:true,warnings:[]}; }
  const student = c.db.query('SELECT id,student_id,enrollment_status FROM students WHERE CAST(id AS TEXT)=? OR student_id=?', [String(body.student_id), String(body.student_id)]).rows[0]; if (!student) return bad('Student not found', 'STUDENT_NOT_FOUND', 404); if (student.enrollment_status && student.enrollment_status !== 'active') return bad('Student is not actively enrolled', 'STUDENT_INACTIVE', 409);
  const type = c.db.query('SELECT * FROM student_exit_types WHERE app_id=? AND code=? AND enabled=1', [appId, body.exit_type_code]).rows[0]; if (!type) return bad('Enabled exit type not found', 'EXIT_TYPE_NOT_FOUND', 404); const workflow = parseWorkflow(type); if (!workflow || !workflow.start_status || !Array.isArray(workflow.states)) return bad('Exit type workflow is invalid', 'INVALID_WORKFLOW', 409); const denied=access.requireAction(r,c,appId,workflow.start_status==='checked_out'?(type.movement_mode==='campus_release'?'campus_release':'release'):'request');if(denied)return denied;
  const related=relationships.resolveCreateContext(c,appId,student.student_id,body);if(related.error)return related.error;const actorId = String(r.user.id), expectedReturn = body.expected_return_at || (type.expected_duration_minutes ? new Date(Date.now() + Number(type.expected_duration_minutes) * 60000).toISOString() : null),warnings=operations.preflight(c,appId,body,type); let row;
  c.db.transaction(db => { const values=[appId, String(student.student_id), type.code, type.movement_mode, workflow.start_status, body.operational_reason || null, body.restricted_reference_type || null, body.restricted_reference_id || null, related.origin_room_id, related.destination_room_id, body.released_by_staff_id || actorId, expectedReturn, actorId,related.scheduler_placement_id,related.teaching_group_ref,related.source_context_type,related.source_context_id],hasRetryColumn=db.query('PRAGMA table_info(student_exits)').rows.some(column=>column.name==='client_request_id'),inserted = db.query(`INSERT INTO student_exits(app_id,student_id,exit_type_code,movement_mode,status,operational_reason,restricted_reference_type,restricted_reference_id,origin_room_id,destination_room_id,released_by_staff_id,expected_return_at,created_by,scheduler_placement_id,teaching_group_ref,source_context_type,source_context_id${hasRetryColumn?',client_request_id':''}) VALUES(${values.map(()=>'?').join(',')}${hasRetryColumn?',?':''})`,hasRetryColumn?values.concat(body.client_request_id?String(body.client_request_id):null):values); db.query('INSERT INTO student_exit_transitions(app_id,student_exit_id,from_status,to_status,actor_id,operational_note) VALUES(?,?,?,?,?,?)', [appId, inserted.lastInsertRowid, null, workflow.start_status, actorId, body.operational_note || null]); row = get({ db }, inserted.lastInsertRowid, appId); });
  const result = hydrate(c, row, r); c.events.publish('student_exit.created', { entityId: row.id, record: result, attendanceSemantics:'temporary_movement_only_no_attendance_mutation', __module: 'student_exits' }); operations.queue(c,appId,row,'created'); return { success: true, exit: result, warnings };
}
async function bulkCreate(r,c){const records=Array.isArray(r.body?.records)?r.body.records:null;if(!records||!records.length||records.length>200)return bad('Provide between 1 and 200 student exit records');const results=[];for(let index=0;index<records.length;index++){try{const result=await create({...r,body:{...records[index],source_context_type:records[index].source_context_type||(r.body.emergency?'emergency_bulk':undefined)}},c);results.push({index,...result})}catch(error){results.push({index,success:false,error:{code:'CREATE_FAILED',message:error.message}})}}return{success:true,total:records.length,created:results.filter(x=>x.success&&!x.duplicate).length,duplicates:results.filter(x=>x.duplicate).length,failed:results.filter(x=>!x.success).length,results,decision:'Every record is reported; failed records require human correction'}}
async function transition(r, c) {
  const appId = scope(r), body = r.body || {}, actorId = String(r.user.id), target = body.to_status; if (!target) return bad('Target status is required'); let updated, failure;
  c.db.transaction(db => { const current = get({ db }, r.params.id, appId); if (!current) { failure = bad('Student exit not found', 'NOT_FOUND', 404); return; } if(current.movement_mode==='campus_release'&&['approved','checked_out','closed'].includes(target)){failure=bad('Use the governed campus custody workflow for this action','CAMPUS_WORKFLOW_REQUIRED',409);return;} const denied=access.requireAction(r,{db},appId,actionFor(current,target));if(denied){failure=denied;return;} if (body.expected_status && body.expected_status !== current.status) { failure = bad('Exit status changed; refresh before acting', 'STALE_EXIT_STATE', 409); return; } const type = db.query('SELECT workflow_json FROM student_exit_types WHERE app_id=? AND code=?', [appId, current.exit_type_code]).rows[0]; if (!allowedTargets(current, type && parseWorkflow(type)).includes(target)) { failure = bad(`Cannot transition from ${current.status} to ${target}`, 'INVALID_TRANSITION', 409); return; } const changed = db.query("UPDATE student_exits SET status=?,updated_at=datetime('now') WHERE id=? AND app_id=? AND status=?", [target, current.id, appId, current.status]); if (changed.changes !== 1) { failure = bad('Exit status changed; refresh before acting', 'STALE_EXIT_STATE', 409); return; } db.query('INSERT INTO student_exit_transitions(app_id,student_exit_id,from_status,to_status,actor_id,operational_note) VALUES(?,?,?,?,?,?)', [appId, current.id, current.status, target, actorId, body.operational_note || null]); updated = get({ db }, current.id, appId); });
  if (failure) return failure; const result = hydrate(c, updated, r); c.events.publish('student_exit.transitioned', { entityId: updated.id, record: result, attendanceSemantics:'temporary_movement_only_no_attendance_mutation', __module: 'student_exits' }); operations.queue(c,appId,updated,target); return { success: true, exit: result };
}
function validWorkflow(w){const allowed=new Set(Object.keys(TRANSITIONS).concat([...TERMINAL]));return w&&Array.isArray(w.states)&&w.states.length>0&&w.states.includes(w.start_status)&&new Set(w.states).size===w.states.length&&w.states.every(x=>allowed.has(x));}
async function listTypes(r,c){const appId=scope(r),denied=access.requireAction(r,c,appId,'read');if(denied)return denied;return{success:true,types:c.db.query('SELECT * FROM student_exit_types WHERE app_id=? ORDER BY label',[appId]).rows.map(x=>{x.workflow=parseWorkflow(x);try{x.constraints=JSON.parse(x.constraints_json)}catch(_){x.constraints={}}delete x.workflow_json;delete x.constraints_json;return x})};}
async function saveType(r,c){const appId=scope(r),denied=access.requireAction(r,c,appId,'configure'),b=r.body||{};if(denied)return denied;if(!/^[a-z][a-z0-9_]*$/.test(b.code||'')||!b.label||!['routine','destination_handoff','campus_release'].includes(b.movement_mode)||!validWorkflow(b.workflow))return bad('Code, label, movement mode and a valid workflow are required');c.db.query("INSERT INTO student_exit_types(app_id,code,label,movement_mode,workflow_json,expected_duration_minutes,operational_visibility,enabled,constraints_json) VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT(app_id,code) DO UPDATE SET label=excluded.label,movement_mode=excluded.movement_mode,workflow_json=excluded.workflow_json,expected_duration_minutes=excluded.expected_duration_minutes,operational_visibility=excluded.operational_visibility,enabled=excluded.enabled,constraints_json=excluded.constraints_json,updated_at=datetime('now')",[appId,b.code,b.label,b.movement_mode,JSON.stringify(b.workflow),b.expected_duration_minutes||null,b.operational_visibility==='restricted'?'restricted':'standard',b.enabled===false?0:1,JSON.stringify(b.constraints||{})]);return listTypes(r,c);}
async function getPolicy(r,c){const appId=scope(r),denied=access.requireAction(r,c,appId,'configure');return denied||{success:true,policy:access.policy(c,appId)};}
async function savePolicy(r,c){const appId=scope(r),denied=access.requireAction(r,c,appId,'configure'),b=r.body||{};if(denied)return denied;if(!access.DEFAULTS[b.action]||!Array.isArray(b.roles)||!b.roles.length||b.roles.some(x=>!/^[a-z][a-z0-9_-]*$/.test(x)))return bad('A recognised action and at least one valid role are required');c.db.query("INSERT INTO student_exit_action_policy(app_id,action,roles_json,updated_by) VALUES(?,?,?,?) ON CONFLICT(app_id,action) DO UPDATE SET roles_json=excluded.roles_json,updated_by=excluded.updated_by,updated_at=datetime('now')",[appId,b.action,JSON.stringify([...new Set(b.roles)]),String(r.user.id)]);return getPolicy(r,c);}
async function listDestinations(r,c){const appId=scope(r),denied=access.requireAction(r,c,appId,'read');return denied||{success:true,destinations:c.db.query('SELECT * FROM student_exit_destinations WHERE app_id=? ORDER BY label',[appId]).rows.map(x=>{try{x.opening_hours=JSON.parse(x.opening_hours_json)}catch(_){x.opening_hours={}}delete x.opening_hours_json;return x})};}
async function saveDestination(r,c){const appId=scope(r),denied=access.requireAction(r,c,appId,'configure'),b=r.body||{};if(denied)return denied;if(!/^[a-z][a-z0-9_:-]*$/.test(b.code||'')||!b.label||b.capacity!=null&&Number(b.capacity)<1)return bad('Valid destination code, label and capacity are required');c.db.query("INSERT INTO student_exit_destinations(app_id,code,label,room_id,opening_hours_json,capacity,enabled,updated_by) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(app_id,code) DO UPDATE SET label=excluded.label,room_id=excluded.room_id,opening_hours_json=excluded.opening_hours_json,capacity=excluded.capacity,enabled=excluded.enabled,updated_by=excluded.updated_by,updated_at=datetime('now')",[appId,b.code,b.label,b.room_id||null,JSON.stringify(b.opening_hours||{}),b.capacity||null,b.enabled===false?0:1,String(r.user.id)]);return listDestinations(r,c);}
async function listStudentRules(r,c){const appId=scope(r),denied=access.requireAction(r,c,appId,'restricted_view');if(denied)return denied;return{success:true,rules:c.db.query('SELECT * FROM student_exit_student_rules WHERE app_id=? AND student_id=? AND active=1 ORDER BY created_at',[appId,String(r.params.studentId)]).rows.map(x=>{try{x.rule=JSON.parse(x.rule_json)}catch(_){x.rule={}}delete x.rule_json;return x})};}
async function saveStudentRule(r,c){const appId=scope(r),denied=access.requireAction(r,c,appId,'configure'),b=r.body||{};if(denied)return denied;if(!['allow','restrict','accommodation'].includes(b.rule_kind))return bad('Valid student rule kind is required');c.db.query('INSERT INTO student_exit_student_rules(app_id,student_id,exit_type_code,rule_kind,rule_json,reason_visibility,active,updated_by) VALUES(?,?,?,?,?,?,?,?)',[appId,String(r.params.studentId),b.exit_type_code||null,b.rule_kind,JSON.stringify(b.rule||{}),b.reason_visibility==='standard'?'standard':'restricted',b.active===false?0:1,String(r.user.id)]);return listStudentRules(r,c);}
module.exports = { boot, teardown, list, create, bulkCreate, read, history, nextActions, transition, dashboard, allowedTargets, listTypes, saveType, getPolicy, savePolicy, listDestinations, saveDestination, listStudentRules, saveStudentRule, authoriseCampus:campus.authorise, releaseCampus:campus.release, closeCampus:campus.close, campusHistory:campus.history, getContext:relationships.context, listLinks:relationships.listLinks, addLink:relationships.addLink, reportException:operations.report, listExceptions:operations.list, resolveException:operations.resolve, reconcile:operations.reconcile, correct:operations.correct, getNotificationRules:operations.getRules, saveNotificationRule:operations.saveRule, analytics:insightProvider.analytics, insights:insightProvider.insights };
