import { describe, expect, test } from "vitest";
import type { VisualFingerprint } from "../../src/domain/garment/visual-fingerprint.js";
import { generateEnsembles, type SlottedGarment } from "../../src/domain/outfit/ensemble-engine.js";

const context={id:"context",slug:"smart-casual",name:"Smart casual",formalityMin:2,formalityMax:5};
const requirements=[{slotId:"top",requirement:"required" as const,minimumItems:1,maximumItems:1},{slotId:"bottom",requirement:"required" as const,minimumItems:1,maximumItems:1},{slotId:"footwear",requirement:"required" as const,minimumItems:1,maximumItems:1}];
function fingerprint(lab:readonly[number,number,number]):VisualFingerprint{return{schemaVersion:"1.0.0",algorithmVersion:"classical-pixels-1.0.0",whole:null,detail:null,combined:{palette:[{rgb:[0,0,0],lab,proportion:1,label:"fixture"}],averageLightness:lab[0],averageChroma:Math.hypot(lab[1],lab[2]),contrast:.25,patternDensity:.02,textureStrength:.2,visualComplexity:.25,solidConfidence:.9},confidence:.9}}
function garment(n:number,slotId:string,lab:readonly[number,number,number]):SlottedGarment{return{id:`00000000-0000-4000-8000-${String(n).padStart(12,"0")}`,name:`Garment ${n}`,categorySlug:slotId,status:"available",formality:3,seasons:["all-season"],fingerprintId:`fingerprint-${n}`,fingerprint:fingerprint(lab),slotId,imageId:null}}
const available=[garment(1,"top",[88,0,0]),garment(2,"bottom",[35,4,-18]),garment(3,"footwear",[25,2,3]),garment(4,"bottom",[55,18,22]),garment(5,"footwear",[75,0,2])];

describe("ensemble generator",()=>{
  test("is deterministic, retains the anchor, and fills every required slot",()=>{const input={selected:available[0]!,available,requirements,context,parameters:{},thresholds:{a:90,b:80,c:70}};const first=generateEnsembles(input),second=generateEnsembles(input);expect(second).toEqual(first);const results=[...first.a,...first.b,...first.c];expect(results.length).toBeGreaterThan(0);for(const candidate of results){expect(candidate.garments.map((item)=>item.id)).toContain(available[0]!.id);expect(new Set(candidate.garments.map((item)=>item.slotId))).toEqual(new Set(["top","bottom","footwear"]))}});
  test("honours relationship bans and favourite score adjustments",()=>{const baseline=generateEnsembles({selected:available[0]!,available,requirements,context,parameters:{},thresholds:{a:90,b:80,c:70}}),target=[...baseline.a,...baseline.b,...baseline.c][0]!;const relationship=target.garments.slice(0,2).map((item)=>item.id);const banned=generateEnsembles({selected:available[0]!,available,requirements,context,parameters:{},thresholds:{a:90,b:80,c:70},overrides:[{type:"ban",scope:"relationship",garmentIds:relationship,scoreDelta:0}]});expect([...banned.a,...banned.b,...banned.c].some((candidate)=>relationship.every((id)=>candidate.garments.some((item)=>item.id===id)))).toBe(false);const favourite=generateEnsembles({selected:available[0]!,available,requirements,context,parameters:{},thresholds:{a:90,b:80,c:70},overrides:[{type:"favourite",scope:"exact_outfit",garmentIds:target.garments.map((item)=>item.id),scoreDelta:3}]});const adjusted=[...favourite.a,...favourite.b,...favourite.c].find((candidate)=>candidate.key===target.key);expect(adjusted?.evaluation.score).toBe(Math.min(100,target.evaluation.score+3));expect(adjusted?.evaluation.outcomes.some((outcome)=>outcome.ruleId==="override.favourite")).toBe(true)});
});
