import { describe,expect,test } from "vitest";
import type { VisualFingerprint } from "../../src/domain/garment/visual-fingerprint.js";
import { evaluateStyling,type StylingGarment } from "../../src/domain/outfit/styling-engine.js";

function fingerprint(lab:readonly[number,number,number],input:{complexity?:number;solid?:number;pattern?:number;texture?:number}={}):VisualFingerprint{return{schemaVersion:"1.0.0",algorithmVersion:"classical-pixels-1.0.0",whole:null,detail:null,combined:{palette:[{rgb:[0,0,0],lab,proportion:1,label:"fixture"}],averageLightness:lab[0],averageChroma:Math.hypot(lab[1],lab[2]),contrast:.3,patternDensity:input.pattern??.02,textureStrength:input.texture??.2,visualComplexity:input.complexity??.3,solidConfidence:input.solid??.9},confidence:.9}}
function garment(id:string,name:string,categorySlug:string,print:VisualFingerprint,formality=4):StylingGarment{return{id,name,categorySlug,status:"available",formality,seasons:["all-season"],fingerprintId:id,fingerprint:print}}
const context={id:"context",slug:"formal-business",name:"Formal business",formalityMin:4,formalityMax:5};

describe("deterministic styling rules",()=>{
  test("awards an A to a coherent controlled ensemble with exact explanations",()=>{const garments=[garment("00000000-0000-4000-8000-000000000001","Navy jacket","blazers",fingerprint([35,5,-20])),garment("00000000-0000-4000-8000-000000000002","White shirt","formal-shirts",fingerprint([90,0,0],{texture:.4}))];const first=evaluateStyling({garments,context,season:"winter"}),second=evaluateStyling({garments,context,season:"winter"});expect(second).toEqual(first);expect(first).toMatchObject({eligible:true,score:100,grade:"A"});expect(first.strengths.map((value)=>value.ruleId)).toEqual(expect.arrayContaining(["formality.coherence","colour.contrast","ensemble.complexity"]));expect(first.hardFailures).toEqual([])});
  test("detects accumulated pattern activity and direct tie-square duplication",()=>{const active={complexity:.9,solid:.2,pattern:.2,texture:.3};const garments=[garment("00000000-0000-4000-8000-000000000003","Tie","ties",fingerprint([40,15,-10],active)),garment("00000000-0000-4000-8000-000000000004","Square","pocket-squares",fingerprint([42,15,-10],{...active,pattern:.21}))];const result=evaluateStyling({garments,context});expect(result.grade).toBeNull();expect(result.majorPenalties.map((value)=>value.explanationCode)).toEqual(expect.arrayContaining(["colour_matching_excessive","pattern_scale_too_similar","complexity_excessive","tie_square_duplicate"]));expect(result.outcomes.find((value)=>value.ruleId==="tie_square.duplication")?.scoreDelta).toBe(-15)});
  test("hard failures explain why an ensemble is ineligible",()=>{const item={...garment("00000000-0000-4000-8000-000000000005","Repairing jacket","blazers",fingerprint([30,0,0])),status:"unavailable"};const result=evaluateStyling({garments:[item,garment("00000000-0000-4000-8000-000000000006","Shirt","formal-shirts",fingerprint([85,0,0]))],context});expect(result.eligible).toBe(false);expect(result.grade).toBeNull();expect(result.hardFailures[0]).toMatchObject({ruleId:"availability.required",explanationCode:"garment_unavailable",affectedGarmentIds:[item.id]})});
});
