import test from 'node:test';
import assert from 'node:assert/strict';
import {adapt,layout,selectGraph,DEFAULTS} from '../../../apps/principaled/src/dashboard/widgets/layer1/model.mjs';
import {focusLayout,visibleEdges} from '../../../apps/principaled/src/dashboard/widgets/layer1/semantic-layout.mjs';
const term=(id,category,parent_id=null)=>({id,kind:'term',data:{name:id,category,parent_id}});
function fixture(){return adapt({revision:'test',references:[term('D1','domain'),term('D2','domain'),term('G1','domain','D1'),term('G2','domain','D2'),...['LEV-01','LEV-02','LEV-05'].map(id=>term(id,'responsibility_level'))],nodes:[['a','D1','LEV-05','S1','G1'],['b','D1','LEV-01','S1','G1'],['c','D2','LEV-02','S2','G2'],['isolate','D1','LEV-01','S3','G1'],['unknown',null,null,'S4',null]].map(([id,domain,level,statement,subdomain])=>({id,kind:'responsibility',data:{name:id,role_id:'same-role',domain_ids:[domain,subdomain].filter(Boolean),level_id:level,statement_id:statement,statement_revision:1,review_status:'draft'}})),edges:[{id:'companion',data:{from_id:'a',to_id:'b',review_status:'draft'},semantics:{grouping:'source_statement',directionality:'symmetric',source_statement_id:'S1',statement_revision:1}},{id:'up',data:{from_id:'b',to_id:'c',relationship_type_id:'REL-004',evidence:'inferred',review_status:'draft'},semantics:{directionality:'directed'}}],gaps:[]});}
test('semantic geography is deterministic and classifications, not role or graph depth, anchor height',()=>{const m=fixture(),before=JSON.stringify(m.nodes),g=layout(m);assert.deepEqual(g.positions,layout(m).positions);assert(g.positions.get('a').y>g.positions.get('c').y);assert(g.positions.get('c').y>g.positions.get('b').y);assert.equal(g.positions.get('b').y,g.positions.get('isolate').y);assert(g.positions.get('unknown').y<g.positions.get('b').y);assert.equal(JSON.stringify(m.nodes),before);assert.equal(g.meta.get('b').domain,'D1');assert.equal(g.meta.get('c').domain,'D2');assert.notDeepEqual(g.positions,g.positions2d);});
test('filtering preserves geography; focus preserves root, endpoints, evidence and return geography',()=>{const m=fixture(),g=layout(m),original=structuredClone(g.positions),graph=selectGraph(m,{...DEFAULTS},'b'),f=focusLayout(m,g,graph,'b');assert.deepEqual(f.positions.get('b'),g.positions.get('b'));assert.equal(f.positions.size,m.nodes.length);assert.deepEqual(g.positions,original);assert.equal(graph.edges.find(e=>e.id==='up').data.from_id,'b');assert.equal(graph.edges.find(e=>e.id==='up').data.evidence,'inferred');assert.equal(graph.edges.find(e=>e.id==='up').data.review_status,'draft');assert.deepEqual(f.positions.get('isolate'),g.positions.get('isolate'));const filtered=selectGraph(m,{...DEFAULTS,domain:'D1',context:false},'');assert(filtered.nodes.every(n=>g.positions.get(n.id)===original.get(n.id)||JSON.stringify(g.positions.get(n.id))===JSON.stringify(original.get(n.id))));});
test('documentary family identity survives semantic splitting; progressive lines never remove governed edges',()=>{const m=fixture(),g=layout(m),graph=selectGraph(m,{...DEFAULTS},'');assert.deepEqual(g.families.get('S1:1'),['a','b']);assert.equal(g.segments.filter(f=>f.family==='S1:1').length,2);assert.equal(visibleEdges(graph,'').length,1);assert.equal(graph.edges.length,2);assert.equal(visibleEdges(selectGraph(m,{...DEFAULTS},'b'),'b').length,1);assert.equal(visibleEdges(graph,'',true).length,2);assert.equal(DEFAULTS.depth,'1');});

test('cache serialization and reordered input preserve semantic anchors and parent-specific subdomains',()=>{const m=fixture(),g=layout(m),saved=JSON.stringify(g,(_,v)=>v instanceof Map?{__map:[...v]}:v),restored=JSON.parse(saved,(_,v)=>v?.__map?new Map(v.__map):v);assert.deepEqual(restored.positions,g.positions);assert.deepEqual(restored.positions2d,g.positions2d);assert.equal(g.meta.get('a').subdomain,'G1');assert.equal(g.meta.get('c').subdomain,'G2');const reordered=layout({...m,nodes:[...m.nodes].reverse(),edges:[...m.edges].reverse()});for(const [id,p] of g.positions)assert.deepEqual(reordered.positions.get(id),p);});
test('a new governed level remains explicit and unpositioned until presentation calibration',()=>{const m=fixture();m.references.set('LEV-NEW',term('LEV-NEW','responsibility_level'));m.byId.get('c').data.level_id='LEV-NEW';const g=layout(m);assert.equal(g.meta.get('c').level,'LEV-NEW');assert.equal(g.meta.get('c').band,-1);assert(g.levels.some(l=>l.id==='LEV-NEW'));});
