'use strict';
const fs=require('fs'),path=require('path');
const modulesDir=path.resolve(__dirname,'../../modules');
const platformServices=new Set(['db','cache','auth','log','validate','events','intelligence']);
function inventory(){const modules=new Map();fs.readdirSync(modulesDir,{withFileTypes:true}).filter(e=>e.isDirectory()).forEach(e=>{const manifestPath=path.join(modulesDir,e.name,'module.json');if(!fs.existsSync(manifestPath))return;const manifest=JSON.parse(fs.readFileSync(manifestPath,'utf8'));if(manifest.status!=='draft')modules.set(e.name,{dir:path.join(modulesDir,e.name),manifest});});return modules;}
describe('platform connectivity contracts',()=>{
 test('every route, function, schema and event subscription resolves',()=>{const failures=[],modules=inventory();for(const [folder,record] of modules){const {dir,manifest}=record,indexPath=path.join(dir,'index.js'),implementation=require(indexPath),functions=new Map((manifest.functions||[]).map(f=>[f.name,f.exports||f.name]));if(manifest.name!==folder)failures.push(`${folder}: manifest name is ${manifest.name}`);for(const route of manifest.routes||[]){const exported=functions.get(route.handler);if(!exported)failures.push(`${folder}: route ${route.method} ${route.path} has no function contract`);else if(typeof implementation[exported]!=='function')failures.push(`${folder}: route handler export ${exported} is missing`);}for(const fn of manifest.functions||[]){const exported=fn.exports||fn.name;if(typeof implementation[exported]!=='function')failures.push(`${folder}: declared function export ${exported} is missing`);}for(const migration of (manifest.schema&&manifest.schema.migrations)||[]){if(!fs.existsSync(path.join(dir,migration)))failures.push(`${folder}: migration ${migration} is missing`);}for(const channel of (manifest.events&&manifest.events.subscribes)||[]){const handler='on_'+channel.replace(/\./g,'_');if(typeof implementation[handler]!=='function')failures.push(`${folder}: subscription ${channel} has no ${handler} handler`);}}expect(failures).toEqual([]);});
 test('every required capability and component dependency has one real provider',()=>{const failures=[],modules=inventory(),providers=new Map();for(const [folder,{manifest}] of modules)for(const cap of manifest.provides||[]){if(providers.has(cap))failures.push(`${cap}: duplicate providers ${providers.get(cap)} and ${folder}`);providers.set(cap,folder);}for(const [folder,{dir,manifest}] of modules){for(const cap of manifest.requires||[])if(!providers.has(cap))failures.push(`${folder}: capability ${cap} has no provider`);const componentPath=path.join(dir,'component.json');if(!fs.existsSync(componentPath))continue;const component=JSON.parse(fs.readFileSync(componentPath,'utf8'));const actual=[...(component.capabilities||[])].sort(),declared=[...(manifest.provides||[])].sort();if(JSON.stringify(actual)!==JSON.stringify(declared))failures.push(`${folder}: component capabilities differ from module provides`);for(const dep of component.dependencies||[])if(!modules.has(dep)&&!platformServices.has(dep))failures.push(`${folder}: component dependency ${dep} does not resolve`);}expect(failures).toEqual([]);});
 test('event planning subject relationships use the canonical polymorphic contract',()=>{const modules=inventory(),tables=['responsibilities','tasks','approval_requests','communications','invitations','attendance_sessions','venue_bookings','resource_reservations','transport_journeys','catering_plans','risk_assessments','safeguarding_requirements','medical_referrals','contingency_plans','financial_budgets','expenditure_requests'];const sql=[];for(const {dir,manifest} of modules.values())for(const migration of (manifest.schema&&manifest.schema.migrations)||[])sql.push(fs.readFileSync(path.join(dir,migration),'utf8'));const all=sql.join('\n');for(const table of tables){const start=all.search(new RegExp(`CREATE TABLE(?: IF NOT EXISTS)? ${table}\\s*\\(`,'i'));expect(start).toBeGreaterThanOrEqual(0);const block=all.slice(start,all.indexOf(');',start)+2);for(const column of ['app_id','subject_component','subject_type','subject_id'])expect(block).toMatch(new RegExp(`\\b${column}\\b`));}});
 test('dependency graph records reverse edges regardless of discovery order',()=>{const graph=require('../../shared/registry/dependencyGraph');graph.clear();graph.addModule('consumer',['provider']);graph.addModule('provider',[]);expect(graph.getDependencies('consumer')).toEqual(['provider']);expect(graph.getDependents('provider')).toEqual(['consumer']);expect(graph.computeBootOrder()).toEqual(['provider','consumer']);graph.clear();});
 test('every persisted planning component contributes nodes to the world model',()=>{const modules=inventory(),excluded=new Set(['event_planner']);for(const name of ['event_record','ownership','tasks','approvals','documents','communications','audiences','invitations','attendance','venue_bookings','resource_reservations','transportation','catering','risk_assessments','safeguarding_requirements','medical_referrals','contingency','financial_planning']){if(excluded.has(name))continue;const component=JSON.parse(fs.readFileSync(path.join(modules.get(name).dir,'component.json'),'utf8'));expect(component.intelligence&&component.intelligence.entities&&component.intelligence.entities.length).toBeGreaterThan(0);}});
});
