'use strict';const contract=require('../../contracts/scheduler');
describe('Scheduler foundation contract',()=>{
 const requirement={external_key:'programme:math-9a',academic_year_id:'2035',teaching_group_external_key:'math-9a',name:'Grade 9 Math',occurrences_per_cycle:5,duration_minutes:50,eligible_staff_ids:['T-1'],eligible_room_ids:['R-1'],eligible_resource_ids:[],allowed_period_template_keys:['single'],status:'active'};
 test('supports whole-school and section-scoped construction',()=>{expect(contract.validateScope({type:'school',id:'whole-school'})).toBeTruthy();expect(contract.validateScope({type:'section',id:'secondary'})).toBeTruthy()});
 test('supports generic rotations rather than hard-coding A/B',()=>{expect(contract.validateCycle({week_count:3,week_labels:['A','B','C']})).toBeTruthy();expect(()=>contract.validateCycle({week_count:2,week_labels:['A']})).toThrow('must match')});
 test('keeps duration templates configurable',()=>{expect(contract.validatePeriodTemplate({external_key:'double',name:'Double',duration_minutes:100,multiplier:2})).toBeTruthy()});
 test('validates provider-neutral requirements and stable identities',()=>{expect(contract.validateRequirement(requirement)).toBeTruthy();expect(contract.requirementIdentity(requirement)).toBe('2035:programme:math-9a')});
 test('models all five availability meanings distinctly',()=>{expect(contract.AVAILABILITY_STATES).toEqual(['available','unavailable','preferred','discouraged','conditional']);for(const state of contract.AVAILABILITY_STATES)expect(contract.validateAvailability({external_key:'a-'+state,entity_type:'staff',entity_id:'T-1',state,week_index:1})).toBeTruthy()});
 test('separates hard, soft and advisory philosophy rules',()=>{for(const level of contract.CONSTRAINT_LEVELS)expect(contract.validateConstraint({code:'RULE_'+level,name:level,level,scope:{type:'section',id:'secondary'},weight:level==='hard'?0:10,explanation_template:'Explain the scheduling outcome'})).toBeTruthy()});
 test('makes scheduled lessons versioned and idempotent',()=>{const placement={external_key:'lesson-1',schedule_version_id:'version-7',requirement_external_key:requirement.external_key,teaching_group_external_key:requirement.teaching_group_external_key,week_index:1,day_index:2,start_time:'08:00',end_time:'08:50',status:'proposed'};expect(contract.placementIdentity(placement)).toBe('version-7:lesson-1');expect(contract.validateEnvelope('scheduled_lesson.created',{event_id:'event-1',occurred_at:'2035-01-01T00:00:00.000Z',source:'scheduler',schedule_version_id:'version-7',scheduled_lesson:placement})).toBeTruthy()});
 test('ranks infeasible and compromise outcomes transparently',()=>{const clean=contract.rankOutcome({hard_violations:0,soft_penalty:5,advisory_count:2}),blocked=contract.rankOutcome({hard_violations:1});expect(clean.feasible).toBe(true);expect(blocked.feasible).toBe(false);expect(blocked.score).toBeGreaterThan(clean.score);expect(clean.breakdown).toEqual({hard_violations:0,unplaced_requirements:0,soft_penalty:5,advisory_count:2})});
 test('reserves future module boundaries without owning their internals',()=>{expect(contract.PROVIDERS).toMatchObject({programme_manager:'programme_manager',teacher_preferences:'teacher_preferences',cover:'cover'})});
});
