'use strict';
const fs = require('fs'), path = require('path'), Database = require('better-sqlite3'), service = require('../../modules/student_exits');
function context() { const connection = new Database(':memory:'); connection.exec("CREATE TABLE students(id INTEGER PRIMARY KEY,student_id TEXT,enrollment_status TEXT); INSERT INTO students VALUES(1,'ST-1','active');"); for(const file of ['001_student_exits_foundation.sql','002_student_exits_governance.sql','003_student_exits_campus_custody.sql','004_student_exits_relationships.sql'])connection.exec(fs.readFileSync(path.join(__dirname, '..', '..', 'modules', 'student_exits', 'migrations', file), 'utf8')); const db = { query(sql, params) { const s = connection.prepare(sql); if (s.reader) return { rows: s.all(params || []), changes: 0 }; const x = s.run(params || []); return { rows: [], changes: x.changes, lastInsertRowid: x.lastInsertRowid }; }, transaction(fn) { return connection.transaction(() => fn(db))(); } }; return { db, events: { published: [], publish(name, payload) { this.published.push({ name, payload }); } }, close() { connection.close(); } }; }
function request(body, params, user) { return { body: body || {}, query: {}, params: params || {}, user: user || { id: 'USER-1', permissions:['admin:*'] } }; }
describe('student exits core state engine', () => { let ctx; beforeEach(() => { ctx = context(); }); afterEach(() => ctx.close());
  test('creates a routine exit and records history', async () => { const created = await service.create(request({ student_id: 'ST-1', exit_type_code: 'bathroom' }), ctx); expect(created.exit.status).toBe('checked_out'); expect(created.exit.next_actions).toEqual(expect.arrayContaining(['returned', 'escalated'])); const h = await service.history(request(null, { id: created.exit.id }), ctx); expect(h.transitions).toHaveLength(1); expect(h.transitions[0]).toMatchObject({ from_status: null, to_status: 'checked_out', actor_id: 'USER-1' }); });
  test('does not skip destination receipt', async () => { let x = await service.create(request({ student_id: 'ST-1', exit_type_code: 'medical' }), ctx); expect(await service.transition(request({ to_status: 'checked_in', expected_status: 'checked_out' }, { id: x.exit.id }), ctx)).toMatchObject({ statusCode: 409, error: { code: 'INVALID_TRANSITION' } }); for (const status of ['received', 'returned', 'checked_in']) { x = await service.transition(request({ to_status: status, expected_status: x.exit.status }, { id: x.exit.id }), ctx); expect(x.exit.status).toBe(status); } expect(x.exit.next_actions).toEqual([]); });
  test('rejects stale duplicate actions without false history', async () => { const x = await service.create(request({ student_id: 'ST-1', exit_type_code: 'bathroom' }), ctx); expect((await service.transition(request({ to_status: 'returned', expected_status: 'checked_out' }, { id: x.exit.id }), ctx)).success).toBe(true); expect(await service.transition(request({ to_status: 'returned', expected_status: 'checked_out' }, { id: x.exit.id }), ctx)).toMatchObject({ statusCode: 409, error: { code: 'STALE_EXIT_STATE' } }); expect((await service.history(request(null, { id: x.exit.id }), ctx)).transitions.map(r => r.to_status)).toEqual(['checked_out', 'returned']); });
  test('rejects unknown and inactive students', async () => { expect(await service.create(request({ student_id: 'missing', exit_type_code: 'bathroom' }), ctx)).toMatchObject({ statusCode: 404 }); ctx.db.query("UPDATE students SET enrollment_status='withdrawn' WHERE student_id='ST-1'"); expect(await service.create(request({ student_id: 'ST-1', exit_type_code: 'bathroom' }), ctx)).toMatchObject({ statusCode: 409, error: { code: 'STUDENT_INACTIVE' } }); });
  test('redacts restricted reasons while preserving workflow actions', async () => { const teacher={id:'T-1',role:'teacher',permissions:[]},medical={id:'M-1',role:'medical',permissions:[]}; const created=await service.create(request({student_id:'ST-1',exit_type_code:'medical',operational_reason:'Private clinical context',restricted_reference_type:'medical_referrals',restricted_reference_id:'88'},null,teacher),ctx); expect(created.exit.operational_reason).toBe('Authorised student support'); expect(created.exit.restricted_reference_id).toBeUndefined(); const viewed=await service.read(request(null,{id:created.exit.id},medical),ctx); expect(viewed.exit.operational_reason).toBe('Private clinical context'); expect(viewed.exit.restricted_reference_id).toBe('88'); });
});
