'use strict';
var appScope=require('../../shared/services/appScope');
var PARTY=['staff','user','team','external'];
function scope(req){return appScope.fromRequest(req);}
function bad(message){return{success:false,statusCode:400,error:{code:'VALIDATION_ERROR',message:message}};}
function audit(ctx,action,req,oldValue,newValue,id){ctx.db.query('INSERT INTO audit_log (timestamp,user_id,action,entity_type,entity_id,old_value,new_value,ip_address) VALUES (?,?,?,?,?,?,?,?)',[Date.now(),String(req.user.id),action,'responsibility',String(id),oldValue?JSON.stringify(oldValue):null,newValue?JSON.stringify(newValue):null,null]);}
function get(ctx,id,s){return ctx.db.query('SELECT * FROM responsibilities WHERE id=? AND app_id=?',[id,s]).rows[0];}
function hydrate(ctx,row){row.contributors=ctx.db.query('SELECT * FROM responsibility_contributors WHERE responsibility_id=? ORDER BY id',[row.id]).rows;return row;}
function validate(b){if(!b.subject_component||!b.subject_type||!b.subject_id||!b.party_id)return 'Subject component, type, identifier and responsible party are required';if(!PARTY.includes(b.party_type))return 'Invalid party type';return null;}
function transition(ctx,row,type,to,b,req,status){ctx.db.query('INSERT INTO responsibility_transitions (responsibility_id,transition_type,from_party_type,from_party_id,to_party_type,to_party_id,reason,effective_at,ends_at,status,actor_id) VALUES (?,?,?,?,?,?,?,?,?,?,?)',[row.id,type,row.party_type,row.party_id,to&&to.party_type,to&&to.party_id,b.reason||null,b.effective_at||new Date().toISOString(),b.ends_at||null,status||'completed',String(req.user.id)]);}
function boot(ctx){ctx.log.info('ownership booting',{module:'ownership'});} function teardown(){}
async function list(req,ctx){var s=scope(req),conditions=['app_id=?'],params=[s];['subject_component','subject_type','subject_id','party_type','party_id','status'].forEach(function(k){if(req.query[k]){conditions.push(k+'=?');params.push(req.query[k]);}});var page=Math.max(1,Number(req.query.page)||1),limit=Math.min(50,Math.max(1,Number(req.query.limit)||50)),offset=(page-1)*limit;if(req.query.q){conditions.push('(subject_id LIKE ? OR role LIKE ? OR party_id LIKE ?)');var q='%'+req.query.q+'%';params.push(q,q,q);}var where=' WHERE '+conditions.join(' AND '),count=ctx.db.query('SELECT COUNT(*) AS total FROM responsibilities'+where,params).rows[0].total;var rows=ctx.db.query('SELECT * FROM responsibilities'+where+' ORDER BY updated_at DESC,id DESC LIMIT ? OFFSET ?',params.concat([limit,offset])).rows.map(function(row){return hydrate(ctx,row);});return{success:true,responsibilities:rows,total:Number(count),page:page,limit:limit};}
async function assign(req,ctx){var b=req.body||{},error=validate(b);if(error)return bad(error);var s=scope(req);try{var result=ctx.db.query('INSERT INTO responsibilities (app_id,subject_component,subject_type,subject_id,role,party_type,party_id,status,starts_at,ends_at,escalation_party_type,escalation_party_id,notes,created_by) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)',[s,b.subject_component,b.subject_type,String(b.subject_id),b.role||'owner',b.party_type,String(b.party_id),b.status||'active',b.starts_at||null,b.ends_at||null,b.escalation_party_type||null,b.escalation_party_id||null,b.notes||null,String(req.user.id)]);var row=get(ctx,result.lastInsertRowid,s);audit(ctx,'ownership.assign',req,null,row,row.id);ctx.events.publish('ownership.assigned',{entityType:'responsibility',entityId:row.id,record:row,subject:{component:row.subject_component,type:row.subject_type,id:row.subject_id},__module:'ownership'});return{success:true,responsibility:hydrate(ctx,row)};}catch(e){if(String(e.message).includes('UNIQUE'))return{success:false,statusCode:409,error:{code:'ACTIVE_RESPONSIBILITY_EXISTS',message:'This subject already has an active party for that responsibility role'}};throw e;}}
async function update(req,ctx){var s=scope(req),row=get(ctx,req.params.id,s);if(!row)return{success:false,statusCode:404,error:{code:'NOT_FOUND',message:'Responsibility not found'}};var b=req.body||{};ctx.db.query("UPDATE responsibilities SET role=?,starts_at=?,ends_at=?,escalation_party_type=?,escalation_party_id=?,notes=?,updated_at=datetime('now') WHERE id=?",[b.role===undefined?row.role:b.role,b.starts_at===undefined?row.starts_at:b.starts_at,b.ends_at===undefined?row.ends_at:b.ends_at,b.escalation_party_type===undefined?row.escalation_party_type:b.escalation_party_type,b.escalation_party_id===undefined?row.escalation_party_id:b.escalation_party_id,b.notes===undefined?row.notes:b.notes,row.id]);var next=get(ctx,row.id,s);audit(ctx,'ownership.update',req,row,next,row.id);ctx.events.publish('ownership.updated',{entityId:row.id,record:next,__module:'ownership'});return{success:true,responsibility:hydrate(ctx,next)};}
async function setStatus(req,ctx){var s=scope(req),row=get(ctx,req.params.id,s),next=req.body&&req.body.status;if(!row)return{success:false,statusCode:404,error:{code:'NOT_FOUND',message:'Responsibility not found'}};if(!['proposed','active','completed','withdrawn'].includes(next))return bad('Invalid responsibility status');ctx.db.query("UPDATE responsibilities SET status=?,updated_at=datetime('now') WHERE id=?",[next,row.id]);transition(ctx,row,'status_change',null,{reason:req.body.reason},req);var updated=get(ctx,row.id,s);audit(ctx,'ownership.status',req,row,updated,row.id);ctx.events.publish(next==='withdrawn'?'ownership.withdrawn':next==='active'?'ownership.reinstated':'ownership.updated',{entityId:row.id,status:next,__module:'ownership'});return{success:true,responsibility:hydrate(ctx,updated)};}
async function addContributor(req,ctx){var s=scope(req),row=get(ctx,req.params.id,s),b=req.body||{};if(!row)return{success:false,statusCode:404,error:{code:'NOT_FOUND',message:'Responsibility not found'}};if(!PARTY.includes(b.party_type)||!b.party_id)return bad('Valid contributor party is required');try{ctx.db.query('INSERT INTO responsibility_contributors (responsibility_id,party_type,party_id,contribution_role,status,added_by) VALUES (?,?,?,?,?,?)',[row.id,b.party_type,String(b.party_id),b.contribution_role||'contributor','active',String(req.user.id)]);}catch(e){if(String(e.message).includes('UNIQUE'))return{success:false,statusCode:409,error:{code:'CONTRIBUTOR_EXISTS',message:'Contributor is already assigned'}};throw e;}audit(ctx,'ownership.contributor.add',req,null,b,row.id);return{success:true,responsibility:hydrate(ctx,get(ctx,row.id,s))};}
async function delegate(req,ctx){var s=scope(req),row=get(ctx,req.params.id,s),b=req.body||{};if(!row)return{success:false,statusCode:404,error:{code:'NOT_FOUND',message:'Responsibility not found'}};if(!PARTY.includes(b.party_type)||!b.party_id||!b.ends_at)return bad('Delegate party and delegation end are required');transition(ctx,row,'delegation',{party_type:b.party_type,party_id:String(b.party_id)},b,req,'pending');ctx.db.query("UPDATE responsibilities SET status='delegated',updated_at=datetime('now') WHERE id=?",[row.id]);audit(ctx,'ownership.delegate',req,row,b,row.id);ctx.events.publish('ownership.delegated',{entityId:row.id,toParty:{type:b.party_type,id:String(b.party_id)},endsAt:b.ends_at,__module:'ownership'});return{success:true,responsibility:hydrate(ctx,get(ctx,row.id,s))};}
async function handover(req,ctx){var s=scope(req),row=get(ctx,req.params.id,s),b=req.body||{};if(!row)return{success:false,statusCode:404,error:{code:'NOT_FOUND',message:'Responsibility not found'}};if(!PARTY.includes(b.party_type)||!b.party_id)return bad('Handover party is required');ctx.db.query("UPDATE responsibilities SET status='handed_over',ends_at=?,updated_at=datetime('now') WHERE id=?",[b.effective_at||new Date().toISOString(),row.id]);transition(ctx,row,'handover',{party_type:b.party_type,party_id:String(b.party_id)},b,req);var previous=get(ctx,row.id,s);var result=ctx.db.query('INSERT INTO responsibilities (app_id,subject_component,subject_type,subject_id,role,party_type,party_id,status,starts_at,escalation_party_type,escalation_party_id,notes,created_by) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)',[s,row.subject_component,row.subject_type,row.subject_id,row.role,b.party_type,String(b.party_id),'active',b.effective_at||new Date().toISOString(),row.escalation_party_type,row.escalation_party_id,b.notes||row.notes,String(req.user.id)]);var successor=get(ctx,result.lastInsertRowid,s);audit(ctx,'ownership.handover',req,row,successor,row.id);ctx.events.publish('ownership.handed_over',{entityId:row.id,successorId:successor.id,__module:'ownership'});return{success:true,previous:previous,responsibility:hydrate(ctx,successor)};}
async function escalate(req,ctx){var s=scope(req),row=get(ctx,req.params.id,s),b=req.body||{};if(!row)return{success:false,statusCode:404,error:{code:'NOT_FOUND',message:'Responsibility not found'}};var to={party_type:b.party_type||row.escalation_party_type,party_id:String(b.party_id||row.escalation_party_id||'')};if(!PARTY.includes(to.party_type)||!to.party_id)return bad('No valid escalation party is configured');transition(ctx,row,'escalation',to,b,req);audit(ctx,'ownership.escalate',req,row,to,row.id);ctx.events.publish('ownership.escalated',{entityId:row.id,toParty:to,reason:b.reason||null,__module:'ownership'});return{success:true,escalated:true,toParty:to};}
async function history(req,ctx){var row=get(ctx,req.params.id,scope(req));if(!row)return{success:false,statusCode:404,error:{code:'NOT_FOUND',message:'Responsibility not found'}};return{success:true,transitions:ctx.db.query('SELECT * FROM responsibility_transitions WHERE responsibility_id=? ORDER BY created_at DESC,id DESC',[row.id]).rows,audit:ctx.db.query('SELECT * FROM audit_log WHERE entity_type=? AND entity_id=? ORDER BY timestamp DESC LIMIT 100',['responsibility',String(row.id)]).rows};}
module.exports={boot:boot,teardown:teardown,list:list,assign:assign,update:update,setStatus:setStatus,addContributor:addContributor,delegate:delegate,handover:handover,escalate:escalate,history:history};
