#!/usr/bin/env bash
#
# TimSyS Architecture Map Updater
# Scans ~/TimSyS_v6 and writes ARCHITECTURE_MAP.md
#
# Usage: bash Tools/update_architecture_map.sh
#

ROOT="${TIMSYS_ROOT:-$HOME/TimSyS_v6}"
OUTPUT="$ROOT/ARCHITECTURE_MAP.md"

if [ ! -d "$ROOT" ]; then
  echo "ERROR: TimSyS root not found at $ROOT"
  exit 1
fi

cat > "$OUTPUT" << 'HEADER'
# TimSyS Architecture Map
# Auto-generated by Tools/update_architecture_map.sh
# Do not edit manually — run the script instead.

## Layer Overview

| Layer | Path | Purpose |
|-------|------|---------|
| Contracts | /contracts/ | Frozen service interface specifications |
| Services | /shared/services/ | Platform service implementations |
| Registries | /shared/registry/ | Entity tracking stores |
| Pipeline | /shared/pipeline/ | Automated module staging mechanism |
| Migrations | /migrations/ | Platform-level schema migrations |
| Modules | /modules/ | Self-describing deployable units |
| Tests | /tests/ | Test suites |
| Scripts | /scripts/ | Bootstrap and migration utilities |
| Data | /data/ | SQLite database, session store |
| Tools | /Tools/ | Development utility scripts |

## Contract → Service Mapping

| Contract | Service Implementation(s) | Status |
|----------|---------------------------|--------|
| /contracts/db.js | /shared/services/db.js | — |
| /contracts/cache.js | /shared/services/cache.js | — |
| /contracts/auth.js | /shared/services/auth.js, /shared/services/session.js | — |
| /contracts/log.js | /shared/services/log.js, /shared/services/audit.js | — |
| /contracts/validate.js | /shared/services/validate.js | — |
| /contracts/events.js | /shared/services/events.js | — |

**Notes:**
- `auth.js` + `session.js` jointly implement AuthService (token/perm logic + session persistence)
- `log.js` + `audit.js` jointly implement LogService (structured logging + immutable audit trail)
- `metrics.js` is platform-internal — no contract, not exposed through Context

## File Tree

HEADER

# Generate the directory tree
# Exclude .git, node_modules, and hidden files
find "$ROOT" \
  -not -path '*/\.git/*' \
  -not -path '*/node_modules/*' \
  -not -path '*/\.git' \
  -not -name '.gitignore' \
  -not -name '.DS_Store' \
  | sed "s|$ROOT|.|" \
  | sort \
  >> "$OUTPUT"

cat >> "$OUTPUT" << 'FOOTER'

## Frozen Documents
- CONSTITUTION_V6.0.md — Locked at v6.0.0. Never modify.
- LEXICON_V6.0.0.md — Locked at v6.0.0. Never modify.
- All files in /contracts/ — Frozen at v6.0.0. Never modify after freeze.

## Change Log
- Auto-updated on each run. Manual edits will be overwritten.
FOOTER

echo "Architecture map written to $OUTPUT"
