import React,{useState} from 'react';
import {Check,Pager,TextField} from './shared.jsx';

export function CleanLinks({links,draft,change}){const keep=draft.linkIds??links.map(l=>l.id),[query,setQuery]=useState('');return <><h2>Keep the links you want</h2><p>Repeated links have been combined. Nothing has been visited yet. Remove anything that does not belong in this analysis.</p><TextField label="Find a link" value={query} onChange={setQuery}/><p>{keep.length} of {links.length} links kept</p><Pager items={links.filter(l=>l.url.toLowerCase().includes(query.toLowerCase()))} render={items=>items.map(l=><article className="wb-source" key={l.id}><Check checked={keep.includes(l.id)} onChange={yes=>change({linkIds:yes?[...keep,l.id]:keep.filter(id=>id!==l.id)},yes?'Restored link':'Removed link')}>{l.url}</Check><details><summary>Where this came from</summary>{l.occurrences.map((o,i)=><p key={i}>{o.context} <small>{o.locator}</small></p>)}</details></article>)}/><small>Removing a link excludes it from this draft. Undo restores it.</small></>;}

export function CleanText({units,draft,change}){const keep=draft.unitIds??units.map(u=>u.id),[query,setQuery]=useState(''),[record,setRecord]=useState('');const records=[...new Map(units.map(u=>[u.record_id,u])).values()],selected=records.some(r=>r.record_id===record)?record:records[0]?.record_id,visible=units.filter(u=>u.record_id===selected);return <><h2>Check the text you want to use</h2><p>Your original file stays untouched. Remove irrelevant passages from this draft. Nothing is analysed yet.</p>{records.length>1&&<label className="wb-field">Document or review<select aria-label="Document or review" value={selected} onChange={e=>setRecord(e.target.value)}>{records.map((r,i)=><option key={r.record_id} value={r.record_id}>{i+1}. {r.filename}{r.review_identifier&&r.review_identifier!=='document'?' · Original identifier: '+r.review_identifier:''}</option>)}</select></label>}<TextField label="Find text" value={query} onChange={setQuery}/><p>{keep.length} of {units.length} passages kept</p><Pager items={visible.filter(u=>u.original_text.toLowerCase().includes(query.toLowerCase()))} render={items=>items.map((u)=><article className="wb-source" key={u.id}><Check checked={keep.includes(u.id)} onChange={yes=>change({unitIds:yes?[...keep,u.id]:keep.filter(id=>id!==u.id)},yes?'Restored passage':'Removed passage')}><span className="wb-source-label">{u.filename} {u.review_identifier&&u.review_identifier!=='document'?' · '+u.review_identifier:''}</span><span className="wb-text">{u.original_text}</span></Check>{u.original_text.includes('\uFFFD')&&<p className="wb-warning">Some characters could not be read. Check the original file; no repair has been guessed.</p>}</article>)}/><small>Remove a passage by clearing its checkbox. Undo restores your selection.</small></>;}

export function SheetChoice({source,value,change}){const sheets=source.extracted.sheets,sheet=sheets.find(s=>s.name===value?.sheet)??sheets[0],header=sheet.rows.find(r=>r.row===(value?.headerRow??1))??sheet.rows[0];return <><h2>Which column contains the text?</h2><p>Each non-empty row will become a separate record. Old classifications are not imported as answers.</p><label className="wb-field">Sheet<select value={sheet.name} onChange={e=>change({sheet:e.target.value,textColumn:null})}>{sheets.map(s=><option key={s.name}>{s.name}</option>)}</select></label><TextField label="Row containing column names" type="number" min="1" value={value?.headerRow??1} onChange={v=>change({headerRow:Number(v)})}/>{[['textColumn','Text to analyse'],['institutionColumn','Institution or organisation (optional)'],['identifierColumn','Original identifier (optional)']].map(([key,label])=><label className="wb-field" key={key}>{label}<select aria-label={label} value={value?.[key]??''} onChange={e=>change({[key]:e.target.value===''?null:Number(e.target.value)})}><option value="">{key==='textColumn'?'Choose a column':'Not supplied'}</option>{header.cells.map((c,i)=><option value={i} key={i}>{c||'Column '+(i+1)}</option>)}</select></label>)}<details><summary>Preview the first rows</summary>{sheet.rows.slice(0,5).map((r,i)=><p key={i}>{r.cells.join(' | ')}</p>)}</details></>;}

export function ReviewBreaks({preview,value,change}){
 const records=value??preview.candidates.map(c=>({start:c.start,end:c.end,confirmed:false,institution:{state:'unassigned',name:'',note:''},include:['narrative'],notes:''}));const [index,setIndex]=useState(0),[split,setSplit]=useState('');const i=Math.min(index,records.length-1),r=records[i],blocks=preview.blocks.slice(r.start,r.end),meta=preview.candidates.find(c=>c.start===r.start&&c.end===r.end);
 const update=patch=>change(records.map((x,n)=>n===i?{...x,...patch}:x));
 return <><h2>Check where each review starts and ends</h2><p>We found {records.length} possible reviews. Check the breaks before continuing. Institution names can stay blank.</p><div className="wb-inline"><label>Review<select aria-label="Review to check" value={i} onChange={e=>setIndex(Number(e.target.value))}>{records.map((x,n)=><option key={n} value={n}>{n+1} · {x.confirmed?'Checked':'Needs checking'}</option>)}</select></label><span>{records.filter(x=>x.confirmed).length} / {records.length} checked</span></div>{meta?.confidence!=='high'&&<p className="wb-warning">This review needs a closer look: {meta?.warnings?.map(w=>w.replaceAll('_',' ')).join('; ')||'You changed its boundaries.'}</p>}
 <div className="wb-reading">{blocks.map(b=><p key={b.index}><small>{({narrative:'Review text',questionnaire:'Questionnaire answers',editorial:'Editor’s note',heading:'Original heading',marker:'Review marker'})[b.component]}</small><span className="wb-text">{b.text}</span></p>)}</div>
 <fieldset><legend>Include in analysis</legend>{[['narrative','Review text'],['questionnaire','Questionnaire answers'],['heading','Original headings'],['editorial','Editor’s notes']].map(([key,label])=><Check key={key} checked={r.include.includes(key)} onChange={yes=>update({include:yes?[...r.include,key]:r.include.filter(c=>c!==key),confirmed:false})}>{label}</Check>)}</fieldset>
 <details><summary>Adjust this review</summary><label className="wb-field">Start a new review before<select value={split} onChange={e=>setSplit(e.target.value)}><option value="">Choose a paragraph</option>{blocks.slice(1).map(b=><option value={b.index} key={b.index}>{b.text.slice(0,95)||'Blank paragraph'}</option>)}</select></label><button disabled={!split} onClick={()=>{const at=Number(split);change(records.flatMap((x,n)=>n===i?[{...x,end:at,confirmed:false},{...x,start:at,confirmed:false,institution:{state:'unassigned',name:'',note:''}}]:[x]));setSplit('');}}>Split here</button><button disabled={i===records.length-1} onClick={()=>change(records.flatMap((x,n)=>n===i?[{...x,end:records[i+1].end,confirmed:false}]:n===i+1?[]:[x]))}>Join with next review</button><TextField label="Institution or organisation (optional)" value={r.institution.name} onChange={name=>update({institution:{...r.institution,name,state:name?'proposed':'unassigned'}})}/>{r.institution.name&&<Check checked={r.institution.state==='confirmed'} onChange={yes=>update({institution:{...r.institution,state:yes?'confirmed':'proposed'}})}>I have verified this institution name</Check>}<TextField label="My note" value={r.notes} onChange={notes=>update({notes})}/></details>
 <button disabled={!r.include.length} onClick={()=>{update({confirmed:true});setIndex(Math.min(i+1,records.length-1));}}>This review looks right</button><button onClick={()=>change(records.map(x=>preview.candidates.some(c=>c.start===x.start&&c.end===x.end&&c.confidence==='high')&&x.include.length?{...x,confirmed:true}:x))}>Accept the clearly identified review breaks</button><p>Ambiguous breaks still need your check. All original headings, dates and notes remain preserved.</p>
 </>;
}
