const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function reportHtml({tool,draft,run,session,instrument}){
 let content='';
 if(tool==='content')for(const task of run?.tasks??[]){if(draft.hiddenTasks?.includes(task.id))continue;content+=`<section><h2>${escape(task.result?.title??task.url)}</h2><p>${escape(task.url)}</p>`;if(task.error)content+=`<p>Source problem: ${escape(task.error.detail)}</p>`;for(const answer of task.result?.ai?.answers??[]){content+=`<h3>${escape(answer.question)}</h3>`;if(answer.status==='not-found')content+='<p>Not found in the inspected material.</p>';for(const finding of answer.findings){content+=`<p>${escape(finding.text)}</p>`;for(const evidence of finding.evidence)content+=`<blockquote>${escape(evidence.quote)}</blockquote>`;}}if(!task.result?.ai?.answers)for(const page of task.result?.pages??[]){content+=`<h3>${escape(page.title)}</h3><p>${escape(page.url)}</p>`;for(const block of page.blocks)content+=`<blockquote>${escape(block.text)}</blockquote>`;}if(draft.resultNotes?.[task.id])content+=`<p>Researcher note: ${escape(draft.resultNotes[task.id])}</p>`;for(const warning of task.result?.warnings??[])content+=`<p>Limitation: ${escape(warning)}</p>`;content+='</section>';}
 else {content+=`<p>Reviewed ${Object.keys(draft.decisions??{}).length} of ${session?.units.length??0} passages. Unreviewed proposals are excluded.</p>`;for(const unit of session?.units??[]){const decision=draft.decisions?.[unit.id];if(!decision)continue;content+=`<section><h2>Passage ${unit.session_ordinal}</h2><p>${escape(unit.filename)}${unit.institution?' · '+escape(unit.institution):''}</p><blockquote>${escape(unit.original_text)}</blockquote>`;for(const code of decision.codes)content+=`<h3>${escape(instrument.competencies.find(c=>c.id===code.competencyId)?.competency)}</h3><p>${escape(code.evidenceStrength)}${code.valence?' · '+escape(code.valence):''}</p><blockquote>${escape(code.evidence)}</blockquote><p>${escape(code.rationale)}</p>`;if(!decision.codes.length)content+='<p>Reviewed: no competency applies.</p>';if(decision.notes)content+=`<p>Researcher note: ${escape(decision.notes)}</p>`;content+='</section>';}
 for(const observation of draft.observations??[]){const v=observation.value;content+=`<section><h2>${escape(instrument.competencies.find(c=>c.id===v.competencyId)?.competency)}</h2><p>${escape(session.records.find(r=>r.id===observation.recordId)?.filename)}</p><p>${v.state==='assessed'?v.score+' — '+['Not represented','Referenced','Developed','Assessed / evaluated'][v.score]:escape(v.state.replaceAll('-',' '))}</p>`;for(const id of v.evidenceUnitIds)content+=`<blockquote>${escape(session.units.find(u=>u.id===id)?.original_text)}</blockquote>`;content+=`<p>${escape(v.notes)}</p></section>`;}}
 return `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>${escape(draft.title)}</title><style>body{font:17px/1.65 system-ui,sans-serif;max-width:860px;margin:48px auto;padding:0 24px;color:#243b2f}h1,h2,h3{line-height:1.3}section{border-top:1px solid #ccc;padding:24px 0}blockquote{white-space:pre-wrap;border-left:3px solid #59866c;padding:10px 20px;background:#f1f6ef;margin:16px 0}p{overflow-wrap:anywhere}@media print{section{break-inside:avoid}}</style><h1>${escape(draft.title)}</h1><p>${tool==='content'?'Content analysis':'MCF analysis'} · Confirmed ${escape(draft.confirmedAt)}</p>${content}</html>`;
}
export function downloadReport(data){const url=URL.createObjectURL(new Blob([reportHtml(data)],{type:'text/html;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=(data.draft.title.replace(/[^\w -]/g,'').trim()||'ResearchEd')+'.html';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
