import {formatWorkTime} from './time.js';
import React,{useEffect,useRef,useState} from 'react';
export const steps=['Upload','Clean','Choose analysis','Check draft','Confirm','Results'];
export const fields={curriculum:'Course content',outcomes:'Skills you will gain',assessment:'Assignments and assessment',practice:'Professional development',delivery:'How it is taught',duration:'Time commitment',admissions:'Entry requirements'};
export const defaultPlan={goal:'Explain what each course offers.',fields:Object.keys(fields),maxDepth:2,maxPages:8,allowedHosts:[],followWebpages:false,followDocuments:false,aiEnabled:true,questions:[]};
export const post=v=>({method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(v)});
export async function api(path,options){const r=await fetch('/api/'+path,options),v=await r.json();if(!r.ok){const names={draft_changed_reload:'This draft changed in another window. Reopen it before making changes.',ai_provider_not_configured:'Connect your AI helper, or choose to work without AI.',review_at_least_one_passage:'Keep at least one finding or record a coverage assessment first.',evidence_must_be_an_exact_unit_substring:'The quotation must match the source exactly.',no_links_found:'No links were found. Try another document or paste the links.',no_selected_links:'Keep at least one link.',validation_failed:'Please check the required choices.'};throw Error(names[v.error]??String(v.error??'Something went wrong. Please retry.').replaceAll('_',' '));}return v;}
export function useProject(onError){
 const [project,setProject]=useState(null),[draft,setDraft]=useState(null),[saving,setSaving]=useState(false);const ref=useRef(null),current=useRef(null),timer=useRef(null),chain=useRef(Promise.resolve()),dirty=useRef(false);
 function load(p){clearTimeout(timer.current);ref.current=p;current.current=p.state;dirty.current=false;setProject(p);setDraft(p.state);}
 async function persist(label='Edited draft'){
  clearTimeout(timer.current);if(!dirty.current)return chain.current;const state=current.current;dirty.current=false;
  chain.current=chain.current.catch(()=>{}).then(async()=>{setSaving(true);try{const p=ref.current;const next=await api('workbench/'+p.id,{...post({revision:p.revision,title:state.title??p.title,state,label}),method:'PATCH'});ref.current=next;setProject(next);}catch(e){dirty.current=true;onError(e.message);throw e;}finally{setSaving(false);}});return chain.current;
 }
 function change(patch,label='Edited draft'){current.current={...current.current,...patch};setDraft(current.current);dirty.current=true;clearTimeout(timer.current);timer.current=setTimeout(()=>{void persist(label).catch(()=>{});},450);}
 async function action(name){await persist();await chain.current;const p=await api('workbench/'+ref.current.id+'/'+name,post({revision:ref.current.revision}));load(p);return p;}
 useEffect(()=>()=>clearTimeout(timer.current),[]);
 return {project,draft,saving,load,change,flush:persist,action,hasDirty:()=>dirty.current};
}
export function TextField({label,value,onChange,...props}){return <label className="wb-field"><span>{label}</span><input value={value??''} onChange={e=>onChange(e.target.value)} {...props}/></label>;}
export function Check({checked,onChange,children,disabled=false}){return <label className="wb-check"><input type="checkbox" checked={checked} disabled={disabled} onChange={e=>onChange(e.target.checked)}/><span>{children}</span></label>;}
export function Pager({items,render,size=15}){const [page,setPage]=useState(0);const safe=Math.min(page,Math.max(0,Math.ceil(items.length/size)-1));return <>{render(items.slice(safe*size,(safe+1)*size))}{items.length>size&&<div className="wb-pagination"><button disabled={!safe} onClick={()=>setPage(safe-1)}>Previous</button><span>{safe+1} of {Math.ceil(items.length/size)}</span><button disabled={(safe+1)*size>=items.length} onClick={()=>setPage(safe+1)}>Next</button></div>}</>;}
export function Connection({done}){const [v,set]=useState({protocol:'openai-responses',baseUrl:'https://api.openai.com',model:'',apiKey:''}),[busy,setBusy]=useState(false),[error,setError]=useState('');return <form onSubmit={async e=>{e.preventDefault();setBusy(true);try{await api('content/provider',post(v));done();}catch(e){setError(e.message);}finally{setBusy(false);}}}><h2>Connect your AI helper</h2><p>Use your own service and model. You can also work without AI. Connection details stay in memory until the app closes.</p><label className="wb-field">Service<select aria-label="Protocol" value={v.protocol} onChange={e=>set({...v,protocol:e.target.value})}><option value="openai-responses">OpenAI</option><option value="openai-chat">OpenAI-compatible service</option><option value="anthropic-messages">Anthropic</option><option value="generic-json">Custom service</option></select></label>{[['baseUrl','Service URL'],['model','Model'],['apiKey','API key']].map(([key,label])=><TextField key={key} label={label} value={v[key]} required={key!=='apiKey'} type={key==='apiKey'?'password':'text'} autoComplete="off" onChange={value=>set({...v,[key]:value})}/>)}{error&&<p role="alert">{error}</p>}<button className="wb-primary" disabled={busy}>Connect</button><button type="button" onClick={done}>Cancel</button></form>;}

export function WorkDates({work}){return <div className="wb-dates">{[['Created',work?.created_at],['Last saved',work?.updated_at],['Draft created',work?.draft_created_at],['Processing started',work?.processing_started_at],['Processing finished',work?.processing_finished_at],['Confirmed',work?.confirmed_at]].filter(([,v])=>v).map(([label,value])=><div key={label}>{label}: <time dateTime={value}>{formatWorkTime(value)}</time></div>)}{work?.processing_status&&<div>Processing: {work.processing_status}</div>}</div>;}
