import {downloadReport} from './report.js';
import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {api,post,steps,fields,defaultPlan,useProject,WorkDates,TextField,Check,Connection} from './shared.jsx';
import {CleanLinks,CleanText,ReviewBreaks,SheetChoice} from './Clean.jsx';
import {ContentDraft,McfDraft,Coverage} from './Review.jsx';
import './workbench.css';

function Workbench(){
 const [error,setError]=useState(''),[busy,setBusy]=useState(''),[notice,setNotice]=useState(''),[items,setItems]=useState([]),[connection,setConnection]=useState(false),[catalog,setCatalog]=useState(null),[instrument,setInstrument]=useState(null),[sources,setSources]=useState({}),[units,setUnits]=useState([]),[links,setLinks]=useState([]),[session,setSession]=useState(null),[run,setRun]=useState(null),[machine,setMachine]=useState(null),[deleteDialog,setDeleteDialog]=useState(null),[interpretation,setInterpretation]=useState(null);
 const model=useProject(setError),{project,draft,change}=model;
 const list=async()=>setItems((await api('workbench')).items);
 async function act(label,fn){setBusy(label);setError('');setNotice('');try{return await fn();}catch(e){setError(e.message);return null;}finally{setBusy('');}}
 async function readContext(p){const s=p.state;if(p.tool==='content'&&s.workflowId){const w=await api('content/workflows/'+s.workflowId);setLinks(w.links);if(s.runId)setRun(await api('content/runs/'+s.runId));else setRun(null);}if(p.tool==='mcf'){
  const loaded={};for(const source of s.sources??[]){loaded[source.id]=await api('mcf/imports/'+source.id);if(source.compiled)loaded[source.id].preview=await api('mcf/imports/'+source.id+'/structural-preview');}setSources(loaded);
  if(s.datasetId){const d=await api('mcf/datasets/'+s.datasetId),mapped=d.records.filter(r=>r.active_mapping&&(s.sources??[]).some(x=>x.id===r.import_id&&x.mappingId===r.mapping_id));const records=await Promise.all(mapped.map(r=>api('mcf/records/'+r.id)));setUnits(records.flatMap(r=>r.units.map(u=>({...u,filename:r.filename,import_id:r.import_id,review_identifier:r.review_identifier}))));}
  if(s.sessionId){setSession(await api('mcf/sessions/'+s.sessionId));setMachine(await api('mcf/sessions/'+s.sessionId+'/ai'));}else {setSession(null);setMachine(null);}setInterpretation(null);
 }}
 useEffect(()=>{void act('Opening Research’Ed',async()=>{await list();setCatalog(await api('content/catalog'));setInstrument((await api('mcf/instrument')).instrument);const saved=localStorage.getItem('researched-simple-project');if(saved){const p=await api('workbench/'+saved);model.load(p);await readContext(p);}});},[]);
 useEffect(()=>{if(project?.id)localStorage.setItem('researched-simple-project',project.id);},[project?.id]);
 useEffect(()=>{if(!draft||draft.step<3)return;let stopped=false,timer;const poll=async()=>{try{if(project.tool==='content'&&draft.runId){const r=await api('content/runs/'+draft.runId);if(!stopped){setRun(r);if(r.status==='running')timer=setTimeout(poll,1500);}}else if(draft.sessionId){const data=await api('mcf/sessions/'+draft.sessionId+'/ai');if(!stopped){setMachine(data);if(data.runs.some(r=>['queued','running'].includes(r.status)))timer=setTimeout(poll,1500);}}}catch(e){if(!stopped)setError(e.message);}};void poll();return()=>{stopped=true;clearTimeout(timer);};},[project?.id,draft?.runId,draft?.sessionId,draft?.step,draft?.analysisAttempt]);
 async function open(id){await model.flush();const p=await api('workbench/'+id);model.load(p);await readContext(p);}
 async function create(tool){const p=await api('workbench',post({tool,title:tool==='content'?'New content analysis':'New MCF analysis',state:{step:0,title:tool==='content'?'New content analysis':'New MCF analysis',sources:[],plan:defaultPlan,mode:'general',category:'',useAi:true,coverage:false,researcher:localStorage.getItem('mcf-researcher')??'',decisions:{},observations:[]}}));model.load(p);setUnits([]);setLinks([]);setSources({});setSession(null);setRun(null);setMachine(null);await list();}
 const actor=draft?.researcher?.trim()||'Local researcher';
 async function upload(file,urls){
  await model.flush();let s={...draft};
  if(project.tool==='content'){
   if(!s.sources.length&&s.workflowId){s.linkIds=[];}
   if(!s.workflowId){const w=await api('content/workflows',post({title:s.title,plan:{...s.plan,aiEnabled:false}}));s.workflowId=w.id;change({workflowId:w.id});await model.flush('Created source list');}
   if(file){const result=await api('content/workflows/'+s.workflowId+'/document?filename='+encodeURIComponent(file.name),{method:'POST',body:file});setLinks(result.workflow.links);s.linkIds=result.workflow.links.map(l=>l.id);const documentId=result.workflow.documents.at(-1)?.id;s.sources=[...(s.sources??[]),{id:documentId,name:file.name,linkIds:result.workflow.links.filter(l=>l.occurrences.some(o=>o.sourceDocumentId===documentId)).map(l=>l.id)}];s.linkIds=[...new Set(s.sources.flatMap(x=>x.linkIds??[]))];setNotice(result.import.warnings.join(' '));}
   else {const w=await api('content/workflows/'+s.workflowId+'/links',post({urls:urls.split('\n').map(x=>x.trim()).filter(Boolean)}));setLinks(w.links);s.linkIds=w.links.map(l=>l.id);s.sources=[...(s.sources??[]),{id:crypto.randomUUID(),name:'Pasted links',linkIds:w.links.filter(l=>l.occurrences.some(o=>urls.split('\n').map(v=>v.trim()).includes(o.context))).map(l=>l.id)}];s.linkIds=[...new Set(s.sources.flatMap(x=>x.linkIds??[]))];}
  }else {
   if(!s.datasetId){s.mode='general';s.category='';const d=await api('mcf/datasets',post({title:s.title,mode:s.mode,reviewCategory:s.mode==='documentary'?'Documentary':s.mode==='general'?'':s.category,actor}));s.datasetId=d.id;change({datasetId:d.id,mode:s.mode,category:s.category});await model.flush('Created document collection');}
   const imported=await api('mcf/datasets/'+s.datasetId+'/imports?filename='+encodeURIComponent(file.name)+'&actor='+encodeURIComponent(actor),{method:'POST',body:file});let preview=null;if(imported.extracted.format==='docx')preview=await api('mcf/imports/'+imported.id+'/structural-preview');
   const source={id:imported.id,name:file.name,compiled:!!preview?.candidates.length};s.sources=[...(s.sources??[]),source];
   setSources({...sources,[source.id]:{...imported,...(preview?{preview}:{})}});
   if(!source.compiled&&!imported.extracted.sheets.length){const mapped=await api('mcf/imports/'+source.id+'/map',post({actor}));source.mappingId=mapped.mappingId;}
  }
  s.step=1;delete s.sessionId;delete s.runId;s.decisions={};s.observations=[];change(s,'Uploaded source');await model.flush('Uploaded source');await readContext({...project,state:s});await list();
 }
 async function prepare(){
  let s={...draft};if(project.tool==='mcf'){
   for(const source of s.sources){if(source.mappingId)continue;const loaded=sources[source.id];let mapping={actor,previousMappingId:loaded.latestMappingId};if(source.compiled){const preview=loaded.preview,records=s.breaks?.[source.id];if(!records?.length||records.some(r=>!r.confirmed))throw Error('Check every review break before continuing.');mapping.structural={profile:`${preview.profile.id}@${preview.profile.version}`,hash:preview.hash,previousMappingId:preview.previousMappingId,reason:'Researcher checked review breaks and selected source components',records};}
    else{const selection=s.sheetChoices?.[source.id];if(selection?.textColumn==null)throw Error('Choose the column containing the text to analyse.');mapping={...mapping,...selection};}
    const mapped=await api('mcf/imports/'+source.id+'/map',post(mapping));s.sources=s.sources.map(x=>x.id===source.id?{...x,mappingId:mapped.mappingId}:x);change({sources:s.sources},'Prepared source');await model.flush('Prepared source');
   }
   // First show the extracted passages after mapping; choosing them precedes analysis.
   if(draft.sources.some(x=>!x.mappingId)){await readContext({...project,state:s});setNotice('Your text is ready. Check the passages below, then continue.');return;}
   if(!(s.unitIds??units.filter(u=>s.sources.some(source=>source.id===u.import_id)).map(u=>u.id)).length)throw Error('Keep at least one passage.');s.unitIds=s.unitIds??units.filter(u=>s.sources.some(source=>source.id===u.import_id)).map(u=>u.id);
  }else if(!(s.linkIds??[]).length)throw Error('Keep at least one link.');
  change({...s,step:2},'Finished cleaning');await model.flush('Finished cleaning');
 }
 async function analyse(){
  await model.flush();const s={...draft,step:3,decisions:{},observations:[],hiddenTasks:[],resultNotes:{},analysisAttempt:(draft.analysisAttempt??0)+1};
  if(project.tool==='content'){
   const plan={...s.plan,questions:s.plan.questions.some(q=>q.trim())?s.plan.questions.map(q=>q.trim()).filter(Boolean):s.plan.fields.map(id=>({curriculum:'What topics and modules are covered?',outcomes:'What skills will I gain?',assessment:'How is learning assessed?',practice:'What professional development is offered?',delivery:'How is the course taught?',duration:'How long does it take?',admissions:'What are the entry requirements?'})[id])};
   const started=await api('content/workflows/'+s.workflowId+'/run',post({plan,selectedLinkIds:s.linkIds}));s.runId=started.id;setRun(await api('content/runs/'+started.id));
  }else{
   const created=await api('mcf/datasets/'+s.datasetId+'/sessions',post({title:s.title+' — draft',kind:'coding',actor,includedUnitIds:s.unitIds}));s.sessionId=created.id;setSession(await api('mcf/sessions/'+created.id));setMachine(null);if(s.useAi)await api('mcf/sessions/'+created.id+'/ai',post({kind:'classification',actor}));
  }
  change(s,'Created analysis draft');await model.flush('Created analysis draft');
 }
 const active=project?.tool==='content'?run?.status==='running':machine?.runs.some(r=>['queued','running'].includes(r.status))||interpretation?.runs.some(r=>['queued','running'].includes(r.status));
 const waiting=project?.tool==='content'?run?.tasks.filter(t=>['queued','running','retry'].includes(t.status)).length:machine?.runs[0]?.total-(machine?.runs[0]?.completed??0);
 async function stop(){if(project.tool==='content')await api('content/runs/'+run.id+'/cancel',post({}));else {const r=machine.runs.find(r=>['queued','running'].includes(r.status));if(r)await api('mcf/sessions/'+draft.sessionId+'/ai-cancel/'+r.id,post({actor}));}change({analysisAttempt:(draft.analysisAttempt??0)+1},'Stopped analysis');await model.flush();setNotice('Stopped. Completed draft findings are kept. Use Create a new draft to start again.');}
 async function undo(name){if(active)throw Error('Stop the analysis before changing its inputs.');const p=await model.action(name);await readContext(p);setNotice(name==='undo'?'Change undone.':'Change restored.');}
 async function home(){await model.flush();model.load(nullProject);localStorage.removeItem('researched-simple-project');await list();}
 // load(null) is deliberately avoided: the hook also keeps a server revision reference.
 const nullProject={id:null,state:null};
 const processing=project?.tool==='content'?run:machine?.runs.find(r=>r.kind==='classification');
 const timedProject={...project,...(processing?{processing_started_at:processing.created_at,processing_finished_at:processing.completed_at??processing.finished_at,processing_status:processing.status}:{})};
 const frozen=!!busy||model.saving,hasProject=!!project?.id;
 return <div className="wb-app"><header className="wb-header"><button className="wb-brand" onClick={()=>act('Saving draft',home)}>Research’Ed <small className="wb-version">0.6.2</small></button><nav><button onClick={()=>act('Saving draft',home)}>My work</button><button onClick={()=>setConnection(true)}>AI connection</button><a href="?expert=1">Specialist tools</a></nav></header>
 <main>{error&&<div role="alert" className="wb-error">{error}<button onClick={()=>setError('')} aria-label="Dismiss error">×</button></div>}{notice&&<div role="status" className="wb-notice">{notice}<button onClick={()=>setNotice('')} aria-label="Dismiss message">×</button></div>}{busy&&<p role="status" className="wb-working">{busy}…</p>}
 {!hasProject?<><div className="wb-intro"><h1>What would you like to understand?</h1><p>Upload. Clean. Choose. Check. Confirm. Get your results.</p></div><div className="wb-tools"><button onClick={()=>act('Creating draft',()=>create('content'))}><span className="wb-tool-icon">↗</span><strong>Content analysis</strong><span>Explore websites and documents. Ask questions and collect evidence.</span></button><button onClick={()=>act('Creating draft',()=>create('mcf'))}><span className="wb-tool-icon">▤</span><strong>MCF analysis</strong><span>Find management competencies in your documents.</span></button></div><section><h2>Your saved work</h2>{items.length===0?<p className="wb-muted">Your drafts and results will appear here.</p>:items.map(p=><article className="wb-saved" key={p.id}><div><h3>{p.title}</h3><small>{p.tool==='mcf'?'MCF analysis':'Content analysis'} · {steps[Number(p.step)]}{p.deleted_at?' · Previously removed':''}</small><WorkDates work={p}/></div><div>{!p.deleted_at&&<button onClick={()=>act('Opening draft',()=>open(p.id))}>Open</button>}<button onClick={()=>setDeleteDialog(p)}>Delete</button></div></article>)}</section></>:<>
 <div className="wb-project-title"><div><small>{project.tool==='content'?'Content analysis':'MCF analysis'}</small><h1>{draft.title}</h1><WorkDates work={timedProject}/></div><div className="wb-history"><button disabled={frozen||active||(!project.can_undo&&!model.hasDirty())} onClick={()=>act('Undoing change',()=>undo('undo'))}>↶ Undo</button><button disabled={frozen||active||!project.can_redo} onClick={()=>act('Restoring change',()=>undo('redo'))}>↷ Redo</button><button disabled={frozen} onClick={()=>setDeleteDialog(project)}>Delete</button><small>{model.saving?'Saving…':'Draft saved automatically'}</small></div></div>
 <ol className="wb-steps" aria-label="Analysis steps">{steps.map((name,i)=><li key={name} className={i===draft.step?'current':i<draft.step?'done':''} aria-current={i===draft.step?'step':undefined}><span>{i<draft.step?'✓':i+1}</span>{name}</li>)}</ol>
 <section className="wb-panel" key={project.id+'-'+draft.step}>
 {draft.step===0&&<Upload units={units} tool={project.tool} draft={draft} change={change} busy={frozen} upload={(file,urls)=>act('Reading your source',()=>upload(file,urls))}/>}
 {draft.step===1&&<>{project.tool==='content'?<CleanLinks links={links} draft={draft} change={change}/>:<>{draft.sources.map(source=>!source.mappingId&&sources[source.id]&&<section key={source.id}>{source.compiled?<ReviewBreaks preview={sources[source.id].preview} value={draft.breaks?.[source.id]} change={records=>change({breaks:{...draft.breaks,[source.id]:records}},'Edited review breaks')}/>:<SheetChoice source={sources[source.id]} value={draft.sheetChoices?.[source.id]} change={v=>change({sheetChoices:{...draft.sheetChoices,[source.id]:{sheet:sources[source.id].extracted.sheets[0].name,...draft.sheetChoices?.[source.id],...v}}},'Changed text columns')}/>}</section>)}{draft.sources.every(s=>s.mappingId)&&<CleanText units={units.filter(u=>draft.sources.some(s=>s.id===u.import_id))} draft={draft} change={change}/>}</>}<footer className="wb-footer"><button disabled={frozen} onClick={()=>change({step:0},'Returned to upload')}>Back</button><button className="wb-primary" disabled={frozen} onClick={()=>act('Preparing your selection',prepare)}>{draft.sources.some(s=>project.tool==='mcf'&&!s.mappingId)?'Show the extracted text':'Continue'}</button></footer></>}
 {draft.step===2&&<><Choices tool={project.tool} draft={draft} change={change} connected={!!catalog?.aiAvailable} connect={()=>setConnection(true)}/><footer className="wb-footer"><button disabled={frozen} onClick={()=>change({step:1},'Returned to cleaning')}>Back</button><button className="wb-primary" disabled={frozen||((project.tool==='content'?draft.plan.aiEnabled:draft.useAi)&&!catalog?.aiAvailable)||project.tool==='content'&&!draft.plan.fields.length} onClick={()=>act('Creating your draft',analyse)}>Create draft</button></footer></>}
 {draft.step===3&&<><h2>Check your draft</h2>{active&&<div role="status" className="wb-notice">Preparing findings. {Number.isFinite(waiting)?`${waiting} remaining.`:''} You can leave and return.<button onClick={()=>act('Stopping analysis',stop)}>Stop</button></div>}{machine?.runs[0]?.errors?.map((e,i)=><p className="wb-warning" key={i}>{e}</p>)}{project.tool==='content'?<ContentDraft run={run} draft={draft} change={change}/>:<><McfDraft session={session} proposals={machine?.proposals??[]} instrument={instrument} draft={draft} change={change}/>{draft.coverage&&session&&<Coverage session={session} instrument={instrument} draft={draft} change={change}/>}</>}<footer className="wb-footer"><button disabled={frozen||active} onClick={()=>change({step:2},'Returned to analysis choices')}>Back</button><button disabled={frozen||active||(project.tool==='mcf'&&!Object.keys(draft.decisions??{}).length&&!(draft.observations??[]).length)||project.tool==='content'&&(!run||run.tasks.every(t=>(draft.hiddenTasks??[]).includes(t.id)))} className="wb-primary" onClick={()=>change({step:4},'Checked draft')}>Continue to confirmation</button></footer></>}
 {draft.step===4&&<><h2>Ready to keep these results?</h2><p>Take one final look. You can still go back and change anything.</p><dl className="wb-summary"><dt>Sources</dt><dd>{draft.sources.map(s=>s.name).join(', ')}</dd><dt>Analysis</dt><dd>{project.tool==='content'?draft.plan.fields.map(f=>fields[f]).join(', '):'Management competencies'+(draft.coverage?' and document coverage':'')}</dd><dt>Included in results</dt><dd>{project.tool==='content'?`${run?.tasks.length-(draft.hiddenTasks??[]).length} sources, including reported access problems`:`${Object.keys(draft.decisions??{}).length} reviewed passages; ${session?.units.length-Object.keys(draft.decisions??{}).length} still unreviewed`}</dd></dl>{project.tool==='mcf'&&<TextField label="Your name" value={draft.researcher} onChange={researcher=>{localStorage.setItem('mcf-researcher',researcher);change({researcher},'Changed researcher name');}}/>}<p className="wb-muted">Confirm saves a fixed result. Undo returns to your draft; the previous confirmation stays in research history.</p><footer className="wb-footer"><button disabled={frozen} onClick={()=>change({step:3},'Returned to draft')}>Back to draft</button><button className="wb-primary" disabled={frozen||project.tool==='mcf'&&!draft.researcher.trim()} onClick={()=>act('Saving your results',async()=>{await model.action('confirm');await list();})}>Confirm results</button></footer></>}
 {draft.step===5&&<><div className="wb-inline"><h2>Your results</h2><div><button onClick={()=>downloadReport({tool:project.tool,draft,run,session,instrument,project:timedProject})}>Download report</button><button onClick={()=>window.print()}>Print / save PDF</button></div></div>{project.tool==='content'?<ContentDraft run={run} draft={draft} readonly/>:<><McfDraft session={session} proposals={[]} instrument={instrument} draft={draft} readonly/>{draft.coverage&&session&&<Coverage session={session} instrument={instrument} draft={draft} readonly/>}<details className="wb-interpret"><summary>Ask AI to explain these reviewed findings</summary><Interpret sessionId={draft.finalSessionId} actor={actor} connected={!!catalog?.aiAvailable} connect={()=>setConnection(true)} value={interpretation} setValue={setInterpretation} hidden={draft.hiddenInterpretations??[]} hide={id=>change({hiddenInterpretations:[...(draft.hiddenInterpretations??[]),id]},'Removed AI explanation')}/></details></>}<footer className="wb-footer"><button disabled={frozen||active} onClick={()=>change({step:3,confirmedAt:null,finalSessionId:null},'Returned to draft')}>Edit draft</button><button disabled={frozen||active} onClick={()=>change({step:3,confirmedAt:null,finalSessionId:null},'Reopened draft')}>Reopen draft</button><a href={project.tool==='content'?'/api/content/runs/'+draft.runId+'/export?format=json':'/api/mcf/sessions/'+draft.finalSessionId+'/export'}>Download research evidence</a><button onClick={()=>act('Saving work',home)}>Done</button></footer></>}
 </section></>}
 </main>{connection&&<div className="wb-overlay"><section role="dialog" aria-modal="true" aria-label="AI connection"><Connection done={()=>{setConnection(false);void api('content/catalog').then(setCatalog);}}/></section></div>}{deleteDialog&&<div className="wb-overlay"><section role="dialog" aria-modal="true" aria-label="Delete work"><h2>Delete “{deleteDialog.title}”?</h2><p>This permanently deletes this work, its uploaded copies, drafts, results and history. It cannot be undone. Original files on your computer and data used by other saved work are kept. Active processing will be stopped; requests already sent cannot be recalled.</p><button onClick={()=>setDeleteDialog(null)}>Keep it</button><button className="wb-danger" onClick={()=>act('Deleting work',async()=>{if(project?.id===deleteDialog.id)await model.flush();const p=await api('workbench/'+deleteDialog.id);const result=await api('workbench/'+p.id+'/delete',post({revision:p.revision}));setDeleteDialog(null);if(project?.id===p.id)await home();await list();setNotice(result.pendingFiles?'Work deleted. Some stored files could not yet be removed; Research’Ed will retry cleanup when you open My work.':result.sharedCollectionsRetained?'Work permanently deleted. Data used by other saved work has been kept.':'Work and its stored files permanently deleted.');})}>Delete</button></section></div>}</div>;
}

function Upload({units,tool,draft,change,busy,upload}){const [file,setFile]=useState(null),[method,setMethod]=useState('file'),[urls,setUrls]=useState('');return <><h2>{draft.sources.length?'Your uploaded sources':'Start with your source'}</h2><p>{tool==='content'?'Upload a document containing links, or paste the links yourself.':'Upload a document. You will check its text before choosing what to analyse.'}</p><TextField label="Name this work" value={draft.title} onChange={title=>change({title},'Renamed work')} maxLength={200}/>{draft.sources.map(s=><div className="wb-saved" key={s.id}><span>{s.name}</span><button onClick={()=>{const remaining=draft.sources.filter(x=>x.id!==s.id);change({sources:remaining,unitIds:(draft.unitIds??units.map(u=>u.id)).filter(id=>units.some(u=>u.id===id&&remaining.some(x=>x.id===u.import_id))),linkIds:tool==='content'?(draft.linkIds??[]).filter(id=>remaining.some(x=>x.linkIds?.includes(id))):draft.linkIds},'Removed source');}}>Remove source</button></div>)}{tool==='content'&&<fieldset><legend>How would you like to add links?</legend><label><input type="radio" name="method" checked={method==='file'} onChange={()=>setMethod('file')}/> Upload a document</label><label><input type="radio" name="method" checked={method==='links'} onChange={()=>setMethod('links')}/> Paste links</label></fieldset>}{method==='file'?<label className="wb-drop">Choose a document<input aria-label="Choose a document" type="file" accept={tool==='content'?'.docx,.pdf':'.docx,.txt,.csv,.xlsx,.pdf,.html,.htm'} onChange={e=>setFile(e.target.files?.[0]??null)}/><small>{tool==='content'?'Word or PDF':'Word, text, spreadsheet, PDF or HTML'}</small></label>:<label className="wb-field">Links, one per line<textarea aria-label="Links, one per line" rows={7} value={urls} onChange={e=>setUrls(e.target.value)}/></label>}<p className="wb-muted">Uploading does not start analysis. You will check the source first.</p><footer className="wb-footer">{draft.sources.length>0&&<button disabled={busy} onClick={()=>change({step:1},'Continued to cleaning')}>Continue with uploaded sources</button>}<button className="wb-primary" disabled={busy||!draft.title.trim()||(method==='file'?!file:!urls.trim())} onClick={()=>upload(method==='file'?file:null,urls)}>{method==='file'?'Upload and check':'Add links and check'}</button></footer></>;}

function Choices({tool,draft,change,connected,connect}){const plan=draft.plan;return <><h2>What would you like to find out?</h2>{tool==='content'?<><fieldset><legend>Find information about</legend>{Object.entries(fields).map(([id,label])=><Check key={id} checked={plan.fields.includes(id)} onChange={yes=>change({plan:{...plan,fields:yes?[...plan.fields,id]:plan.fields.filter(f=>f!==id)}},'Changed analysis tools')}>{label}</Check>)}</fieldset><label className="wb-field">Your goal<textarea value={plan.goal} onChange={e=>change({plan:{...plan,goal:e.target.value}},'Changed goal')}/></label><label className="wb-field">Your own questions (optional, one per line)<textarea value={plan.questions.join('\n')} onChange={e=>change({plan:{...plan,questions:e.target.value.split('\n')}},'Changed questions')}/></label><fieldset><legend>May Research’Ed open extra material?</legend><Check checked={plan.followWebpages} onChange={yes=>change({plan:{...plan,followWebpages:yes}},'Changed webpage access')}>Follow relevant links to other webpages</Check><Check checked={plan.followDocuments} onChange={yes=>change({plan:{...plan,followDocuments:yes}},'Changed document access')}>Read linked PDFs and documents</Check></fieldset><Check checked={plan.aiEnabled} onChange={yes=>change({plan:{...plan,aiEnabled:yes}},'Changed AI choice')}>Use AI to write answers from the evidence</Check><details><summary>Reading limits</summary><TextField label="Maximum pages per link" type="number" min="1" max="15" value={plan.maxPages} onChange={v=>change({plan:{...plan,maxPages:Number(v)}})}/><TextField label="How many links deep?" type="number" min="0" max="2" value={plan.maxDepth} onChange={v=>change({plan:{...plan,maxDepth:Number(v)}})}/><TextField label="Other trusted websites (comma separated)" value={plan.allowedHosts.join(', ')} onChange={v=>change({plan:{...plan,allowedHosts:v.split(',').map(x=>x.trim()).filter(Boolean)}})}/></details></>:<><p>Use the Management Competency Framework to identify the skills and behaviours described in your text.</p><Check checked={draft.useAi} onChange={useAi=>change({useAi},'Changed AI choice')}>Let AI suggest competencies for me to check</Check><p className="wb-muted">Leave this off to choose competencies yourself. You can change every suggestion before confirming.</p>{draft.mode!=='reviews'&&<Check checked={draft.coverage} onChange={coverage=>change({coverage},'Changed coverage tool')}>Also assess how deeply each document covers the competencies</Check>}</>}{(tool==='content'?plan.aiEnabled:draft.useAi)&&<p className="wb-note">{connected?'Creating the draft sends the selected text to your connected AI helper.':'Connect an AI helper, or turn off the AI option to continue manually.'}{!connected&&<button onClick={connect}>Connect AI</button>}</p>}<p>You’ll see a draft first. You decide what to keep.</p></>;}

function Interpret({sessionId,actor,connected,connect,value,setValue,hidden,hide}){const [question,setQuestion]=useState('What patterns and limitations are supported by these reviewed findings?'),[busy,setBusy]=useState(false),[error,setError]=useState('');useEffect(()=>{let timer,closed=false;const poll=async()=>{try{const data=await api('mcf/sessions/'+sessionId+'/ai');if(!closed){setValue(data);const active=data.runs.some(r=>['queued','running'].includes(r.status));setBusy(active);if(active)timer=setTimeout(poll,1500);}}catch(e){if(!closed)setError(e.message);}};void poll();return()=>{closed=true;clearTimeout(timer);};},[sessionId,busy]);return <><p>This uses only your confirmed coding, including its partial coverage. AI explanations remain interpretations.</p><TextField label="Question about these findings" value={question} onChange={setQuestion}/>{!connected&&<button onClick={connect}>Connect AI</button>}<button disabled={!connected||busy||!question.trim()} onClick={async()=>{try{await api('mcf/sessions/'+sessionId+'/ai',post({kind:'interpretation',actor,questions:[question]}));setBusy(true);}catch(e){setError(e.message);}}}>{busy?'Preparing explanation…':'Explain my findings'}</button>{error&&<p role="alert">{error}</p>}{value?.runs.flatMap(r=>r.errors??[]).map((e,i)=><p role="alert" key={i}>{e}</p>)}{busy&&<button onClick={async()=>{const active=value?.runs.find(r=>['queued','running'].includes(r.status));if(active){await api('mcf/sessions/'+sessionId+'/ai-cancel/'+active.id,post({actor}));setBusy(false);}}}>Stop explanation</button>}{value?.outputs.filter(o=>!hidden.includes(o.id)).map(o=><article key={o.id}><button onClick={()=>hide(o.id)}>Remove explanation</button>{o.payload.answers?.map((a,i)=><section key={i}><h4>{a.question}</h4>{a.findings.map((f,j)=><div key={j}><p>{f.text}</p><details><summary>Supporting evidence</summary>{f.evidence.map((e,k)=><blockquote key={k}>{e.quote}</blockquote>)}</details></div>)}</section>)}</article>)}</>;}

createRoot(document.getElementById('root')).render(<Workbench/>);
