import { describe, expect, it, vi } from "vitest";
import { loadExchangeAdapterConfiguration } from "../../src/infrastructure/providers/exchange/config.js";
import { BinanceRestAdapter, ExchangeRateLimitError } from "../../src/infrastructure/providers/exchange/binance-rest.js";
import { BackfillCoordinator, CandleContinuityTracker, EventDeduplicator } from "../../src/infrastructure/providers/exchange/continuity.js";
import { ExchangeIngestionService } from "../../src/infrastructure/providers/exchange/ingestion.js";
import { BinanceStreamRuntime } from "../../src/infrastructure/providers/exchange/stream-runtime.js";

const response=(status:number,data:unknown,retry:string|null=null)=>({ok:status>=200&&status<300,status,headers:{get:()=>retry},json:async()=>data});
describe("exchange runtime verification gates",()=>{
 it("separates public configuration and admits paper_internal only",()=>{const base={BINANCE_PUBLIC_REST_URL:"https://example.test",BINANCE_PUBLIC_WS_URL:"wss://example.test"};const c=loadExchangeAdapterConfiguration({...base,CRYPTOED_SYMBOLS:"BTCUSDT, ETHUSDT"});expect(c.venueSymbols).toEqual(["BTCUSDT","ETHUSDT"]);expect(c.executionMode).toBe("paper_internal");expect(()=>loadExchangeAdapterConfiguration({...base,CRYPTOED_EXECUTION_MODE:"live"})).toThrow();});
 it("builds the instrument catalogue from venue metadata",async()=>{const a=new BinanceRestAdapter("https://example",async()=>response(200,{symbols:[{symbol:"BTCUSDT",status:"TRADING",baseAsset:"BTC",quoteAsset:"USDT"}]}));expect((await a.catalogue(["BTCUSDT"]))[0]).toMatchObject({canonicalAsset:"BTC",venueSymbol:"BTCUSDT"});});
 it("handles exchange circuit responses and Retry-After",async()=>{const a=new BinanceRestAdapter("https://example",async()=>response(429,{},"3"));await expect(a.catalogue(["BTCUSDT"])).rejects.toEqual(expect.objectContaining<Partial<ExchangeRateLimitError>>({status:429,retryAfterMs:3000}));});
 it("parses native REST candles",async()=>{const a=new BinanceRestAdapter("https://example",async()=>response(200,[[0,"1","2","0.5","1.5","10",59_999,"15",3,0,0]]),()=>new Date(60_000));const c=await a.candles("BTCUSDT","1m",0,60_000);expect(c[0]).toMatchObject({closed:true,source:undefined,venueSymbol:"BTCUSDT"});});
 it("detects gaps, bounds repair work, and deduplicates events",()=>{const tracker=new CandleContinuityTracker();const base={venue:"binance" as const,venueSymbol:"BTCUSDT",interval:"1m" as const,closeTime:new Date(59_999),eventTime:new Date(),receivedAt:new Date(),open:"1",high:"1",low:"1",close:"1",baseVolume:"1",quoteVolume:"1",trades:1,closed:true,fingerprint:"a"};expect(tracker.observe({...base,openTime:new Date(0)})).toBeNull();expect(tracker.observe({...base,openTime:new Date(120_000),fingerprint:"b"})?.startTime).toBe(60_000);const q=new BackfillCoordinator();for(let i=0;i<65;i++)q.enqueue({venueSymbol:"x",interval:"1m",startTime:i,endTime:i},i);expect(q.depth).toBe(64);const d=new EventDeduplicator(1);expect(d.accept("a")).toBe(true);expect(d.accept("a")).toBe(false);expect(d.accept("b")).toBe(true);expect(d.accept("a")).toBe(true);});
 it("persists stream data and repairs gaps",async()=>{const store={saveCandle:vi.fn(),saveBook:vi.fn(),saveTicker:vi.fn(),recordStreamEvent:vi.fn()};const rest={candles:vi.fn(async()=>[])};const svc=new ExchangeIngestionService(store,rest);const base={venue:"binance" as const,venueSymbol:"BTCUSDT",interval:"1m" as const,closeTime:new Date(59_999),eventTime:new Date(),receivedAt:new Date(),open:"1",high:"1",low:"1",close:"1",baseVolume:"1",quoteVolume:"1",trades:1,closed:true};await svc.onCandle({...base,openTime:new Date(0),fingerprint:"a"});await svc.onCandle({...base,openTime:new Date(120_000),fingerprint:"b"});expect(svc.backfillDepth).toBe(1);await svc.repairNext();expect(rest.candles).toHaveBeenCalledOnce();});
 it("reconnects and performs controlled rotation",()=>{const callbacks:{cb:()=>void,delay:number}[]=[];const clock={setTimeout:(cb:()=>void,delay:number)=>{callbacks.push({cb,delay});return cb;},clearTimeout:vi.fn()};const sockets:{listeners:Map<string,(e:any)=>void>,close:ReturnType<typeof vi.fn>}[]=[];const runtime=new BinanceStreamRuntime({websocketBaseUrl:"wss://x",venueSymbols:["BTCUSDT"]},()=>{const s={listeners:new Map<string,(e:any)=>void>(),close:vi.fn()};sockets.push(s);return {addEventListener:(t,f)=>s.listeners.set(t,f),close:s.close};},{onCandle:vi.fn(),onBook:vi.fn(),onTicker:vi.fn(),onState:vi.fn()},clock,100,()=>0.5);runtime.start();sockets[0]!.listeners.get("open")!({});expect(callbacks[0]!.delay).toBe(100);callbacks[0]!.cb();expect(sockets).toHaveLength(2);runtime.stop();expect(sockets[1]!.close).toHaveBeenCalled();});
});
