'use strict';
const appScope=require('../../shared/services/appScope'),STATUSES=['present','absent','late','excused','unrecorded'];
function boot(c){c.log.info('classroom_attendance booting',{module:'classroom_attendance'})}function teardown(){}function scope(r){return appScope.fromRequest(r)}function text(v){return String(v==null?'':v).trim()}function bad(m,x,s){return{success:false,statusCode:s||400,error:{code:x||'VALIDATION_ERROR',message:m}}}function emit(c,ch,row){c.events.publish(ch,{entityId:row.id,record:row,__module:'classroom_attendance'})}
function book(c,id,s){return c.db.query('SELECT * FROM gradebook_instances WHERE id=? AND app_id=?',[id,s]).rows[0]}
async function createSession(r,c){const g=book(c,r.params.id,scope(r)),b=r.body||{};if(!g)return bad('Gradebook not found','NOT_FOUND',404);if(!text(b.session_date))return bad('Session date is required');try{const x=c.db.query('INSERT INTO class_attendance_sessions(gradebook_id,session_date,title,created_by) VALUES(?,?,?,?)',[g.id,text(b.session_date),text(b.title)||null,String(r.user.id)]),row=c.db.query('SELECT * FROM class_attendance_sessions WHERE id=?',[x.lastInsertRowid]).rows[0];emit(c,'classroom_attendance.session_created',row);return{success:true,session:row}}catch(e){if(String(e.message).includes('UNIQUE'))return bad('Session already exists','SESSION_EXISTS',409);throw e}}
function session(c,id,s){return c.db.query('SELECT cs.*,g.teaching_group_id,g.app_id FROM class_attendance_sessions cs JOIN gradebook_instances g ON g.id=cs.gradebook_id WHERE cs.id=? AND g.app_id=?',[id,s]).rows[0]}
function insert(c,sess,student,b,user,supersedes){if(!STATUSES.includes(b.attendance_status))return{error:bad('Valid attendance status is required')};if(!c.db.query('SELECT id FROM teaching_group_enrolments WHERE teaching_group_id=? AND student_id=?',[sess.teaching_group_id,student]).rows[0])return{error:bad('Student has no enrolment history in Gradebook','STUDENT_NOT_ENROLLED',409)};const x=c.db.query('INSERT INTO class_attendance_marks(session_id,student_id,attendance_status,minutes_late,notes,recorded_by,supersedes_id) VALUES(?,?,?,?,?,?,?)',[sess.id,student,b.attendance_status,Math.max(0,+b.minutes_late||0),b.notes||null,String(user),supersedes||null]);return{row:c.db.query('SELECT * FROM class_attendance_marks WHERE id=?',[x.lastInsertRowid]).rows[0]}}
async function recordMark(r,c){const sess=session(c,r.params.id,scope(r)),student=text(r.params.studentId),b=r.body||{};if(!sess)return bad('Session not found','NOT_FOUND',404);if(sess.status!=='open')return bad('Session is not open','INVALID_STATE',409);if(c.db.query("SELECT id FROM class_attendance_marks WHERE session_id=? AND student_id=? AND status='active'",[sess.id,student]).rows[0])return bad('Current mark already exists; use correction','MARK_EXISTS',409);const result=insert(c,sess,student,b,r.user.id,null);if(result.error)return result.error;emit(c,'classroom_attendance.recorded',result.row);return{success:true,mark:result.row}}
async function correctMark(r,c){const s=scope(r),old=c.db.query('SELECT m.*,cs.gradebook_id,g.teaching_group_id,g.app_id FROM class_attendance_marks m JOIN class_attendance_sessions cs ON cs.id=m.session_id JOIN gradebook_instances g ON g.id=cs.gradebook_id WHERE m.id=? AND g.app_id=?',[r.params.id,s]).rows[0],b=r.body||{};if(!old)return bad('Mark not found','NOT_FOUND',404);if(old.status!=='active')return bad('Mark already superseded','ALREADY_SUPERSEDED',409);if(!text(b.reason))return bad('Correction reason is required');c.db.query("UPDATE class_attendance_marks SET status='superseded' WHERE id=?",[old.id]);const result=insert(c,{id:old.session_id,teaching_group_id:old.teaching_group_id},old.student_id,{attendance_status:b.attendance_status||old.attendance_status,minutes_late:b.minutes_late==null?old.minutes_late:b.minutes_late,notes:'Correction: '+text(b.reason)+(b.notes?' — '+b.notes:'')},r.user.id,old.id);if(result.error){c.db.query("UPDATE class_attendance_marks SET status='active' WHERE id=?",[old.id]);return result.error}c.db.query('UPDATE class_attendance_marks SET superseded_by_id=? WHERE id=?',[result.row.id,old.id]);emit(c,'classroom_attendance.corrected',result.row);return{success:true,mark:result.row,superseded:c.db.query('SELECT * FROM class_attendance_marks WHERE id=?',[old.id]).rows[0]}}
async function summary(r,c){const g=book(c,r.params.id,scope(r)),student=text(r.params.studentId),p=[r.params.id,student];if(!g)return bad('Gradebook not found','NOT_FOUND',404);let dates='';if(r.query.reporting_period_id){const period=c.db.query('SELECT * FROM reporting_periods WHERE id=? AND app_id=? AND academic_year_id=?',[r.query.reporting_period_id,scope(r),g.academic_year_id]).rows[0];if(!period)return bad('Reporting period not found','NOT_FOUND',404);dates=' AND s.session_date BETWEEN ? AND ?';p.push(period.starts_on,period.ends_on)}const rows=c.db.query("SELECT m.*,s.session_date FROM class_attendance_marks m JOIN class_attendance_sessions s ON s.id=m.session_id WHERE s.gradebook_id=? AND m.student_id=? AND m.status='active' AND s.status!='withdrawn'"+dates+' ORDER BY s.session_date,m.id',p).rows,counts={present:0,absent:0,late:0,excused:0,unrecorded:0};rows.forEach(x=>counts[x.attendance_status]++);const recorded=rows.length-counts.unrecorded,attended=counts.present+counts.late;return{success:true,summary:{gradebook_id:g.id,student_id:student,total_sessions:rows.length,recorded_sessions:recorded,counts,attendance_rate:recorded?Math.round(attended/recorded*1000)/10:null,minutes_late:rows.reduce((n,x)=>n+x.minutes_late,0)}}}
module.exports={boot,teardown,createSession,recordMark,correctMark,summary};
const exportedCorrection=module.exports.correctMark;module.exports.correctMark=function(r,c){let promise;c.db.transaction(()=>{promise=exportedCorrection(r,c)});return promise};
